<?php

return [
    'head_title' => 'Roles and permissions', 'eyebrow' => 'Identity and access governance', 'title' => 'Roles & permissions', 'description' => 'Govern role inheritance and exceptional direct user permissions from one audited, least-privilege control plane.',
    'programme_roles' => 'Programme roles', 'permission_definitions' => 'Permission definitions', 'users_in_register' => 'Users in register', 'role_matrix' => 'Role permission matrix', 'role_matrix_description' => 'Role permissions are inherited by every user assigned to that role. Changes are audited.', 'users' => 'users', 'separator' => '·', 'permissions' => 'Permissions', 'edit' => 'Edit', 'no_inherited_permissions' => 'No inherited permissions',
    'direct_exceptions' => 'Direct permission exceptions', 'direct_exceptions_description' => 'Direct grants are explicit exceptions layered over the role. Use them sparingly and record a reason.', 'search_placeholder' => 'Search users by name or email', 'search_users' => 'Search users', 'number' => 'No.', 'user' => 'User', 'role' => 'Role', 'inherited' => 'Inherited', 'direct' => 'Direct', 'effective' => 'Effective', 'actions' => 'Actions', 'actions_for' => 'Actions for', 'manage_direct_permissions' => 'Manage direct permissions', 'no_users' => 'No users found', 'no_users_description' => 'No authorized users match the active search.', 'showing' => 'Showing', 'range_separator' => '–', 'of' => 'of',
    'edit_role' => 'Edit role', 'role_sheet_description' => 'Select the complete inherited permission set for this role.', 'direct_permissions' => 'Direct permissions', 'user_sheet_description' => 'Select only exceptional permissions. Role-inherited permissions remain unchanged.', 'inherited_by_role' => 'inherited by role', 'business_reason' => 'Business reason', 'reason_placeholder' => 'Record the approved operational reason for this access change.', 'save_changes' => 'Save permission changes',
    'grant_programme_access' => 'Grant programme access', 'grant_programme_access_description' => 'Create an administrator-approved identity and send password setup instructions.',
    'grant_access' => 'Grant access', 'name' => 'Name', 'official_email' => 'Official email', 'programme_role' => 'Programme role',
    'home_county' => 'Home county', 'assigned_county_portfolio' => 'Assigned county portfolio', 'current_user' => 'Current user', 'deactivate' => 'Deactivate',
];
