<?php

return [
    'head_title' => 'Assessment configuration', 'eyebrow' => 'Devolution performance assessment', 'title' => 'Scorecards and assessment cycles', 'description' => 'Govern reproducible digital scorecards across all fourteen devolved functions, enabler themes, standards, criteria, MCDA rules and evidence requirements.',
    'new_scorecard' => 'New scorecard', 'new_scorecard_description' => 'Create a stable scorecard definition whose released versions become immutable.', 'create_scorecard' => 'Create scorecard', 'code' => 'Code', 'name' => 'Name', 'description_label' => 'Description',
    'new_cycle' => 'New assessment cycle', 'new_cycle_description' => 'Pin a reporting period to an immutable released scorecard version.', 'create_cycle' => 'Create cycle', 'publish_before_cycle' => 'Publish a scorecard version before creating a cycle.', 'released_scorecard' => 'Released scorecard', 'period_start' => 'Period start', 'period_end' => 'Period end', 'submission_opens' => 'Submission opens', 'submission_closes' => 'Submission closes',
    'valid_json_error' => 'The scorecard configuration must be valid JSON.', 'compose_version_title' => 'Compose next scorecard version', 'compose_version_description' => 'Create a governed draft from the complete scorecard configuration before review and publication.', 'compose_version' => 'Compose version', 'baseline_notice' => 'The baseline contains all fourteen devolved functions. Replace provisional standards, norms, criteria, weights and evidence rules with approved content before publishing.', 'scorecard_json' => 'Scorecard version JSON', 'save_draft_version' => 'Save draft version',
    'pagination' => 'pagination', 'page' => 'Page', 'of' => 'of', 'separator' => '·', 'total' => 'total', 'previous' => 'Previous', 'next' => 'Next', 'search_scorecards' => 'Search scorecards', 'search' => 'Search', 'no_description' => 'No description', 'version_prefix' => 'v', 'functions' => 'functions', 'publish' => 'Publish', 'scorecards' => 'Scorecards',
    'assessment_cycles' => 'Assessment cycles', 'assessment_cycles_description' => 'Reporting periods pinned to immutable scorecard releases.', 'to' => 'to', 'no_scorecard' => 'No scorecard',
    'value_active' => 'Active', 'value_inactive' => 'Inactive', 'value_draft' => 'Draft', 'value_published' => 'Published', 'value_retired' => 'Retired', 'value_planned' => 'Planned', 'value_open' => 'Open', 'value_closed' => 'Closed',
];
