<?php

return [
    'page_title' => ':county County', 'all_counties' => 'All counties', 'county_code_region' => 'County :code · :region', 'description' => 'Complete assessment, evidence, verification and exchequer record within your authorized scope.', 'official_website' => 'Official website', 'county_record' => 'County record', 'county_summary' => 'County summary',
    'assessment_cycles' => 'Assessment cycles', 'evidence_documents' => 'Evidence documents', 'verified_evidence' => 'Verified evidence', 'grant_disbursement' => 'Grant disbursement', 'of_amount' => 'of :amount',
    'administrative_hierarchy' => 'Administrative hierarchy', 'administrative_hierarchy_description' => 'Governed sub-county and ward structure retained with source lineage.', 'sub_counties' => 'Sub-counties', 'wards' => 'Wards', 'registered_voters' => 'Registered voters (2022)', 'ward_count' => ':count wards', 'source_lineage' => 'Source: :authority · effective :date', 'no_administrative_units' => 'No administrative hierarchy available', 'no_administrative_units_description' => 'Import and approve the governed sub-county and ward register for this county.',
    'assessment_history' => 'Assessment history', 'document_management' => 'Document management', 'exchequer_grants' => 'Exchequer and grants', 'matching_records' => ':count matching records', 'no_matching_county_records' => 'No matching county records', 'no_matching_county_records_description' => 'Adjust the search or date range. Records remain limited to this county and your assigned access.',
    'column_cycle' => 'Cycle', 'column_status' => 'Status', 'column_score' => 'Score', 'column_evidence' => 'Evidence', 'column_assessor' => 'Assessor', 'column_document' => 'Document', 'column_category' => 'Category', 'column_verification' => 'Verification', 'column_uploaded_by' => 'Uploaded by', 'column_programme' => 'Programme', 'column_financial_year' => 'Financial year', 'column_allocated' => 'Allocated (KES)', 'column_disbursed' => 'Disbursed (KES)',
    'unassigned' => 'Unassigned', 'system_migration' => 'System migration', 'scanned_copy' => 'Scanned copy', 'digital_file' => 'Digital file', 'empty_value' => '—', 'separator' => '·', 'label_separator' => ':',
];
