<?php

return [
    'overview' => 'Overview', 'assessment_cycles' => 'Assessment cycles', 'action_queue' => 'Action queue', 'funds_evidence' => 'Funds & evidence',
    'dashboard_title' => ':role dashboard', 'portfolio_statistics' => 'Portfolio statistics', 'require_attention' => ':count require attention', 'no_active_exceptions' => 'No active exceptions', 'open_county_record_label' => 'Open :county county record',
    'operational_control' => 'Operational control position', 'operational_control_description' => 'Cross-module exceptions in your authorized portfolio.', 'role_brief' => 'Role operating brief', 'priority_decisions_for_role' => 'Priority decisions for :role.', 'full_stop' => '.', 'active_projects_visible' => 'active projects are currently visible in this scope.',
    'county_coverage' => 'County coverage', 'kenya_assessment_map' => 'Kenya assessment map', 'county_detail' => 'County detail', 'open_county_record' => 'Open complete county record', 'county_intervention_queue' => 'County intervention queue', 'county_intervention_description' => 'Ranked from filtered, authorized records; select a county to continue with its full evidence and delivery record.',
    'score' => 'Score', 'funding_gap' => 'Funding gap', 'no_county_flags' => 'No county intervention flags', 'no_county_flags_description' => 'No incomplete assessment, missing evidence, low score, or grant gap was found in this filtered scope.', 'exception_register' => 'Exception register', 'exception_register_description' => 'Cross-module workload requiring accountable follow-up.',
    'performance_across_cycles' => 'Performance across cycles', 'performance_across_cycles_description' => 'Average verified score and county completion for the authorized portfolio.', 'county_completion' => 'County completion', 'average_score' => 'Average score', 'evidence' => 'Evidence', 'no_assessment_cycles' => 'No assessment cycles', 'no_assessment_cycles_description' => 'Cycle analytics will appear after an assessment cycle is configured.',
    'grant_allocation_disbursement' => 'Grant allocation and disbursement', 'grant_chart_description' => 'Top counties by allocated value in the current filtered portfolio.', 'evidence_coverage' => 'Evidence coverage', 'evidence_coverage_description' => 'Counties with the largest document collections in the selected period.',
    'cycle_completion' => 'Cycle completion', 'allocated' => 'Allocated', 'disbursed' => 'Disbursed', 'evidence_documents' => 'Evidence documents', 'assessment_incomplete' => 'Assessment incomplete', 'no_evidence_indexed' => 'No evidence indexed', 'score_below_threshold' => 'Score below 60%', 'undisbursed_allocation' => 'Undisbursed allocation',
    'evidence_awaiting_review' => 'Evidence awaiting review', 'evidence_awaiting_review_detail' => 'Active records without a verification decision', 'evidence_scan_attention' => 'Evidence scan attention', 'evidence_scan_attention_detail' => 'Pending, failed, or quarantined scan outcomes', 'overdue_citizen_cases' => 'Overdue citizen cases', 'overdue_citizen_cases_detail' => 'Unresolved cases past their resolution deadline', 'delayed_exchequer_requests' => 'Delayed exchequer requests', 'delayed_exchequer_requests_detail' => 'Open requests beyond the current-stage SLA', 'overdue_evaluation_findings' => 'Overdue evaluation findings', 'overdue_evaluation_findings_detail' => 'Recommendations past due and not closed', 'open_partner_alerts' => 'Open partner alerts', 'open_partner_alerts_detail' => 'Unresolved agreement or contribution exceptions',
    'counties_in_view' => 'Counties in view', 'assessed' => 'assessed', 'pending' => 'pending', 'completed_assessments_detail' => 'Across completed assessments', 'selected_period_detail' => 'Within the selected period', 'grant_disbursement' => 'Grant disbursement', 'disbursed_lower' => 'disbursed', 'separator' => '·', 'range_separator' => '–', 'slash' => '/', 'percent' => '%',
    'profiles' => [
        'county-official' => ['role_label' => 'County official', 'eyebrow' => 'County workspace', 'title' => 'Evidence and assessment readiness', 'description' => 'Prepare county evidence, monitor completeness, and follow the latest assessment outcome.', 'focus' => ['first' => 'Complete outstanding evidence', 'second' => 'Respond to county service cases', 'third' => 'Track corrective actions']],
        'county-admin' => ['role_label' => 'County administrator', 'eyebrow' => 'County administration', 'title' => 'County performance control', 'description' => 'Coordinate officials, evidence collection, submissions, grants, and county readiness.', 'focus' => ['first' => 'Remove submission blockers', 'second' => 'Coordinate county delivery owners', 'third' => 'Escalate overdue obligations']],
        'assessor' => ['role_label' => 'Independent assessor', 'eyebrow' => 'Independent verification', 'title' => 'Assigned county assessments', 'description' => 'Review evidence and assessment progress only for counties assigned to you.', 'focus' => ['first' => 'Prioritize submitted assessments', 'second' => 'Clear evidence review queues', 'third' => 'Record independent findings']],
        'development-partner' => ['role_label' => 'Development partner', 'eyebrow' => 'Partner portfolio', 'title' => 'Programme results and grants', 'description' => 'Track assessment results, evidence, and grant delivery across your partner portfolio.', 'focus' => ['first' => 'Review grant absorption', 'second' => 'Resolve partner delivery alerts', 'third' => 'Validate programme results']],
        'top-management' => ['role_label' => 'Top management', 'eyebrow' => 'Executive oversight', 'title' => 'County performance overview', 'description' => 'Monitor the counties in your oversight portfolio and focus attention where delivery is behind.', 'focus' => ['first' => 'Intervene on overdue commitments', 'second' => 'Review low-performing counties', 'third' => 'Authorize pending decisions']],
        'devolution-admin' => ['role_label' => 'Devolution administrator', 'eyebrow' => 'National coordination', 'title' => 'All-county delivery command', 'description' => 'Coordinate assessment cycles, evidence readiness, grants, and performance across all 47 counties.', 'focus' => ['first' => 'Drive national cycle completion', 'second' => 'Resolve cross-county bottlenecks', 'third' => 'Protect evidence and reporting integrity']],
        'platform-admin' => ['role_label' => 'Platform administrator', 'eyebrow' => 'Platform operations', 'title' => 'National platform control', 'description' => 'Monitor platform coverage and administer governed access across the national service.', 'focus' => ['first' => 'Maintain service operability', 'second' => 'Govern access and integrations', 'third' => 'Review assurance exceptions']],
    ],
];
