<?php

return [
    'registered_assets' => 'Registered assets', 'processing_activities' => 'Processing activities', 'retention_schedules' => 'Retention schedules', 'privacy_requests' => 'Privacy requests', 'breach_incidents' => 'Breach incidents',
    'personal_data_breach_register' => 'Personal data breach register', 'no_privacy_incidents' => 'No privacy incidents', 'no_data_assets_registered' => 'No data assets registered', 'processing_activity_register' => 'Processing activity register', 'no_processing_activities' => 'No processing activities', 'no_privacy_requests' => 'No privacy requests',
    'decision' => 'Decision', 'independent_review_findings' => 'Independent review findings', 'workflow_transition' => 'Workflow transition', 'identity_evidence_reference' => 'Identity-evidence reference', 'decision_or_response' => 'Decision or response', 'reason_and_legal_assessment' => 'Reason and legal assessment', 'response_evidence_reference' => 'Response evidence reference',
    'register_data_asset' => 'Register data asset', 'asset_code' => 'Asset code', 'asset_name' => 'Asset name', 'accountable_data_owner' => 'Accountable data owner', 'operational_data_steward' => 'Operational data steward', 'tor_module_or_shared_service' => 'ToR module or shared service', 'authoritative_source' => 'Authoritative source', 'classification' => 'Classification', 'residency_country' => 'Residency country',
    'contains_personal_data' => 'Contains personal data', 'contains_sensitive_personal_data' => 'Contains sensitive personal data', 'dataset_scope_and_intended_use' => 'Dataset scope and intended use', 'personal_data_categories_comma_separated' => 'Personal-data categories (comma separated)', 'data_subject_categories_comma_separated' => 'Data-subject categories (comma separated)', 'approved_storage_locations_comma_separated' => 'Approved storage locations (comma separated)', 'quality_and_provenance_standard' => 'Quality and provenance standard',
    'schedule_code' => 'Schedule code', 'record_class' => 'Record class', 'retention_months' => 'Retention months', 'disposition_action' => 'Disposition action', 'next_review_date' => 'Next review date', 'retention_trigger_event' => 'Retention trigger event', 'legal_or_approved_records_authority' => 'Legal or approved records authority', 'legal_hold_suspension_rule' => 'Legal-hold suspension rule',
    'submit_processing_activity' => 'Submit processing activity', 'data_asset' => 'Data asset', 'retention_schedule' => 'Retention schedule', 'processing_reference' => 'Processing reference', 'activity_name' => 'Activity name', 'lawful_basis' => 'Lawful basis', 'controller' => 'Controller', 'dpia_status' => 'DPIA status', 'dpia_evidence_reference' => 'DPIA evidence reference',
    'uses_automated_decision_making' => 'Uses automated decision-making', 'includes_cross_border_transfer' => 'Includes cross-border transfer', 'specific_processing_purpose' => 'Specific processing purpose', 'lawful_basis_authority_and_assessment' => 'Lawful-basis authority and assessment', 'processors_comma_separated' => 'Processors (comma separated)', 'recipient_categories_comma_separated' => 'Recipient categories (comma separated)', 'processing_operations_comma_separated' => 'Processing operations (comma separated)', 'transfer_countries_comma_separated' => 'Transfer countries (comma separated)', 'transfer_safeguards' => 'Transfer safeguards', 'privacy_risk_summary' => 'Privacy risk summary', 'technical_and_organizational_measures' => 'Technical and organizational measures',
    'record_data_subject_request' => 'Record data-subject request', 'request_type' => 'Request type', 'assigned_privacy_operator' => 'Assigned privacy operator', 'requester_name' => 'Requester name', 'controlled_contact' => 'Controlled contact', 'contact_channel' => 'Contact channel', 'received_date_and_time' => 'Received date and time', 'requested_personal_data_and_service_scope' => 'Requested personal data and service scope',
    'report_personal_data_breach' => 'Report personal data breach', 'incident_title' => 'Incident title', 'incident_lead' => 'Incident lead', 'affected_data_asset' => 'Affected data asset', 'affected_county' => 'Affected county', 'sdd_role' => 'SDD role', 'breach_type' => 'Breach type', 'estimated_affected_people' => 'Estimated affected people', 'sensitive_personal_data_may_be_involved' => 'Sensitive personal data may be involved', 'occurred_date_and_time' => 'Occurred date and time', 'discovered_date_and_time' => 'Discovered date and time', 'controlled_incident_description' => 'Controlled incident description',
    'containment_actions_completed' => 'Containment actions completed', 'assessed_severity' => 'Assessed severity', 'real_risk_of_harm' => 'Real risk of harm', 'independent_risk_assessment_and_legal_reasoning' => 'Independent risk assessment and legal reasoning', 'odpc_notified_date_and_time' => 'ODPC notified date and time', 'odpc_notification_reference' => 'ODPC notification reference', 'delay_reason_when_after_72_hours' => 'Delay reason, when after 72 hours', 'affected_person_communication' => 'Affected-person communication', 'affected_people_notified_date_and_time' => 'Affected people notified date and time', 'no_notice_or_delay_rationale' => 'No-notice or delay rationale', 'verified_root_cause' => 'Verified root cause', 'completed_corrective_and_preventive_actions' => 'Completed corrective and preventive actions', 'controlled_closure_evidence_reference' => 'Controlled closure evidence reference',
];
