<?php

return ['collaboration_threads' => 'Governed collaboration threads', 'collaboration_description' => 'Working-group discussions retain attributed, checksummed contributions within authorized county scope.', 'no_collaboration_threads' => 'No collaboration threads', 'no_collaboration_description' => 'Open the first governed discussion for an authorized working group.', 'create_thread' => 'Create thread', 'new_thread' => 'New thread', 'create_thread_description' => 'Start an attributed discussion within an authorized working group.', 'working_group' => 'Working group', 'thread_title' => 'Thread title', 'opening_contribution' => 'Opening contribution', 'thread_messages' => 'Thread contributions', 'checksum' => 'Checksum:', 'post_contribution' => 'Post contribution', 'reply' => 'Reply', 'contribution' => 'Contribution', 'separator' => '·', 'thread_closed' => 'This collaboration thread is closed.',
    'action_create_unauthorized' => 'You are not authorized to assign DSWG actions.', 'accountable_member_required' => 'The accountable person must be an active member of this working group.', 'action_county_outside_portfolio' => 'The action county is outside the working group portfolio.', 'action_decision_mismatch' => 'The selected decision does not belong to this meeting.',
    'meeting_series_create_unauthorized' => 'You are not authorized to create recurring DSWG meetings.', 'recurring_invitee_member_required' => 'Every recurring invitee must be an active working-group member.', 'recurring_quorum_exceeded' => 'Quorum cannot exceed the number of recurring invitees.',
    'group_create_unauthorized' => 'You are not authorized to establish DSWG working groups.', 'group_county_outside_scope' => 'One or more selected counties are outside your authorized scope.',
    'audit_action_created' => 'DSWG action :code assigned.', 'audit_meeting_series_created' => 'Recurring DSWG meeting series :reference created.', 'audit_group_created' => 'DSWG :code created.',
    'invitee_member_required' => 'Every invitee must be a working-group member.', 'quorum_exceeded' => 'Quorum cannot exceed the number of invitees.', 'meeting_workflow_unavailable' => 'Meeting workflow is unavailable.',
    'attendance_invitees_only' => 'Attendance can include invited participants only.', 'clean_minutes_required' => 'A clean repository-linked minutes record is required before approval.', 'decision_after_outcomes' => 'Decisions may be registered only after outcomes are recorded.',
    'action_after_outcomes' => 'Actions may be assigned only after meeting outcomes are recorded.', 'action_workflow_unavailable' => 'Action workflow is unavailable.', 'workflow_outcomes_recorded' => 'Meeting outcomes and draft minutes recorded.',
    'outcome_group_created' => 'Sector working group established.', 'outcome_meeting_scheduled' => 'Meeting scheduled and invitations sent.', 'outcome_thread_created' => 'Collaboration thread created.', 'outcome_contribution_posted' => 'Contribution posted.',
    'outcome_meeting_series_created' => 'Recurring meeting series :reference created and its rolling schedule generated.', 'outcome_invitation_recorded' => 'Invitation response recorded.', 'outcome_meeting_outcomes_recorded' => 'Meeting outcomes recorded for independent minutes approval.',
    'outcome_minutes_approved' => 'Minutes approved and meeting closed.', 'outcome_decision_registered' => 'Meeting decision registered.', 'outcome_action_created' => 'Accountable action created and assignee notified.', 'outcome_action_updated' => 'Action workflow updated.',
    'notification_meeting_title' => 'DSWG meeting invitation', 'notification_meeting_message' => 'You are invited to :title on :date.', 'notification_action_title' => 'New DSWG action assigned', 'notification_action_message' => ':code: :title is due :date.',
    'audit_meeting_scheduled' => 'DSWG meeting :reference scheduled.', 'audit_thread_created' => 'DSWG collaboration thread :title created.', 'audit_contribution_posted' => 'Contribution posted to DSWG thread :title.',
    'audit_invitation_responded' => 'Meeting invitation marked :status.', 'audit_outcomes_recorded' => 'Draft minutes recorded for :reference.', 'audit_minutes_approved' => 'Minutes approved for :reference.',
    'audit_decision_adopted' => 'DSWG decision :code adopted.', 'audit_action_transitioned' => 'DSWG action :code transitioned via :transition.',
];
