<?php

return [
    'head_title' => 'DSWG coordination', 'eyebrow' => 'Sector coordination and accountability', 'title' => 'Devolution Sector Working Groups', 'description' => 'Coordinate membership, invitations, quorum, agendas, approved minutes, decisions, accountable actions, deadlines, reminders and independent closure.',
    'series_title' => 'Recurring meeting series', 'series_description' => 'Rolling, idempotent schedules generated in the selected IANA timezone with a governed workflow for every occurrence.', 'no_series' => 'No recurring series', 'no_series_description' => 'Create a series to maintain future meeting occurrences automatically.', 'every' => 'Every', 'periods' => 'period(s)', 'occurrences_generated' => 'occurrence(s) generated', 'next_occurrence' => 'Next:', 'ends_on' => 'Ends:',
    'meeting_workspace' => 'Meeting workspace', 'meeting_workspace_description' => 'Tracked invitations, attendance, quorum, minutes, decisions and actions.', 'no_meetings' => 'No meetings available', 'no_meetings_description' => 'Adjust the reporting dates or schedule the first sector working group meeting.', 'no_actions' => 'No matching accountable actions', 'no_actions_description' => 'Adjust the filters or record actions from an approved sector working group meeting.',
    'quorum' => 'quorum', 'decisions' => 'decisions', 'actions' => 'actions', 'agenda' => 'Agenda:', 'record_outcomes_title' => 'Record meeting outcomes', 'record_outcomes' => 'Record outcomes', 'record_outcomes_description' => 'Record attendance, quorum and draft minutes for', 'draft_minutes' => 'Draft minutes', 'members_present' => 'Members present', 'record_outcomes_submit' => 'Record outcomes and quorum', 'minutes' => 'Minutes',
    'approve_minutes_title' => 'Approve meeting minutes', 'approve_minutes' => 'Approve minutes', 'approve_minutes_description' => 'Independently review and approve the minutes for', 'clean_minutes_ready' => 'A clean repository-linked minutes record is ready for approval.', 'clean_minutes_required' => 'Upload a clean minutes record before approval can be completed.', 'minutes_comment' => 'Independent minutes approval comment',
    'register_decision_title' => 'Register adopted decision', 'register_decision' => 'Register decision', 'register_decision_description' => 'Record an adopted decision from', 'decision_title' => 'Decision title', 'adopted_decision' => 'Adopted decision', 'decision_datetime' => 'Decision date and time',
    'assign_action_title' => 'Assign accountable action', 'assign_action' => 'Assign action', 'assign_action_description' => 'Create a deadline-bound action from', 'using_catalogue' => 'Using governed catalogue release v', 'no_effective_catalogue' => 'No checksum-valid published reference catalogue is currently effective.', 'action_title' => 'Action title', 'deliverable_evidence' => 'Deliverable and acceptance evidence', 'due_date' => 'Due date',
    'start' => 'Start', 'submit_completion_title' => 'Submit action completion', 'submit_completion' => 'Submit completion', 'submit_completion_description' => 'Submit repository-backed completion evidence for independent verification.', 'clean_evidence_ready' => 'A clean action-evidence record is linked and ready for submission.', 'clean_evidence_required' => 'Upload a clean action-evidence record before submitting completion.', 'evidence_narrative' => 'Optional evidence narrative or repository reference', 'completion_comment' => 'Completion submission comment', 'verify' => 'Verify', 'return' => 'Return', 'accountable_action' => 'accountable action', 'transition_description' => 'this action through the governed DSWG workflow.', 'transition_comment' => 'action through the governed DSWG workflow.', 'rationale' => 'rationale', 'confirm' => 'Confirm',
    'value_active' => 'Active', 'value_open' => 'Open', 'value_closed' => 'Closed', 'value_scheduled' => 'Scheduled', 'value_minutes_pending' => 'Minutes pending', 'value_accepted' => 'Accepted', 'value_tentative' => 'Tentative', 'value_declined' => 'Declined',
];
