<?php

return [
    'separator' => '·',
    'upload_evidence' => 'Upload evidence', 'upload_evidence_description' => 'Upload a scanned copy or a born-digital file. Files are stored privately and linked to the selected assessment cycle.', 'upload_criterion_evidence' => 'Upload criterion evidence', 'upload_criterion_evidence_description' => 'Files are stored privately and count toward completeness only after independent verification.', 'assessment' => 'Assessment', 'evidence_requirement' => 'Evidence requirement', 'source_type' => 'Source type', 'category_placeholder' => 'ADP, CIDP…', 'upload' => 'Upload', 'uploading' => 'Uploading :percentage%', 'attachment_help' => 'PDF, office document, image or structured data file within the approved size limit.', 'choose_file' => 'Choose file', 'remove_file' => 'Remove selected file', 'selected_file' => 'Selected', 'attachment_security' => 'Private upload · malware scan, SHA-256 checksum and immutable version recorded after submission.',
    'errors' => ['integrity_failed' => 'Document integrity verification failed.', 'preview_unavailable' => 'Preview is not available for this file type.', 'document_quarantined' => 'This document is quarantined until its security scan passes.', 'version_quarantined' => 'This document version is quarantined until its security scan passes.', 'version_integrity_failed' => 'Document version integrity verification failed.', 'assessment_locked' => 'Evidence is locked after assessment.', 'retention_locked' => 'Retention cannot be changed while a legal hold is active.', 'archive_locked' => 'A document under legal hold cannot be archived.', 'clean_current_version_required' => 'Only a clean current document version can be processed.', 'hold_separation_required' => 'The officer who placed a legal hold cannot release it.', 'media_range_invalid_with_value' => 'The requested media range is invalid: :range.', 'media_range_invalid' => 'The requested media range is invalid.', 'media_range_outside_file' => 'The requested media range :start-:end is outside the :size-byte file.'],
    'audit' => ['previewed' => 'Document previewed: :title.', 'downloaded' => 'Document downloaded: :title.', 'version_previewed' => 'Document version :version previewed: :title.', 'version_downloaded' => 'Document version :version downloaded: :title.', 'metadata_updated' => 'Document metadata updated: :title.', 'archived' => 'Document archived: :title.', 'hold_released' => 'Legal hold :reference released.'],
    'outcomes' => ['uploaded' => 'Evidence uploaded securely.', 'verified' => 'Evidence verification recorded.', 'metadata_updated' => 'Document metadata updated.', 'archived' => 'Document archived.', 'version_uploaded' => 'A new immutable document version was uploaded.', 'extraction_queued' => 'Document text extraction queued.', 'hold_placed' => 'Legal hold placed.', 'hold_released' => 'Legal hold released.', 'disposition_submitted' => 'Controlled disposition submitted for independent review.', 'disposition_decided' => 'Disposition review decision recorded.', 'disposition_executed' => 'Controlled disposition executed and evidence retained.'],
    'disposition' => [
        'errors' => ['retention_due_required' => 'A retention due date is required before disposition can be requested.', 'legal_hold_request' => 'A document under legal hold cannot enter disposition.', 'retention_not_expired_request' => 'Disposition cannot be scheduled before the retention period expires.', 'open_request_exists' => 'This document already has an open disposition request.', 'reviewer_separation' => 'The requesting officer cannot decide the disposition request.', 'pending_required' => 'Only a pending disposition request can be decided.', 'execution_separation' => 'Disposition execution requires an officer independent of the requester and reviewer.', 'legal_hold_execute' => 'A document under legal hold cannot be disposed.', 'retention_not_expired_execute' => 'The approved retention period has not expired.', 'executable_status_required' => 'Only an approved or failed disposition can be executed.', 'retained_object_missing' => 'A retained object is missing: :path.', 'retained_object_integrity' => 'Integrity verification failed for retained object: :path.', 'secure_deletion_unconfirmed' => 'Secure object deletion could not be confirmed: :path.', 'execution_state_changed' => 'Disposition execution state changed unexpectedly.'],
        'audit' => ['requested' => 'Controlled disposition requested for :title.', 'decided' => 'Document disposition :decision.', 'executed' => 'Controlled disposition executed for :title.'],
        'statuses' => ['approved' => 'approved', 'rejected' => 'rejected'],
    ],
    'open_actions' => 'Open evidence actions', 'preview_document' => 'Preview document', 'download_original' => 'Download original', 'manage_record' => 'Manage record', 'reprocess_text' => 'Reprocess searchable text', 'verify_evidence' => 'Verify evidence', 'reject_evidence' => 'Reject evidence',
    'document_preview' => 'Document preview', 'secure_document' => 'Secure evidence document', 'scanned_copy' => 'Scanned copy', 'digital_file' => 'Digital file', 'text_extraction' => 'Text extraction: :status', 'not_requested' => 'not requested', 'searchable_unavailable' => 'Searchable text unavailable',
    'attempts_title' => 'Extraction attempt evidence', 'attempts_description' => 'Append-only processing and retry history for the current immutable version.', 'attempt' => 'Attempt', 'source' => 'Source', 'actor' => 'Actor', 'engine' => 'Engine', 'status' => 'Status', 'duration' => 'Duration', 'result' => 'Result', 'in_progress' => 'In progress', 'characters' => ':count characters',
    'preview_of' => 'Preview of :title', 'document' => 'document', 'extracted_preview' => 'Extracted text preview', 'download_original_document' => 'Download original document', 'preview_page' => 'Preview :page of :total', 'sha256_verified' => 'SHA-256 verified', 'uploaded_by_marker' => 'Uploaded by :actor', 'previous_preview' => 'Previous document preview', 'next_preview' => 'Next document preview',
    'manage_document' => 'Manage document', 'manage_description' => 'Update governed metadata, versions, retention, and legal holds.', 'title' => 'Title', 'category' => 'Category', 'document_date' => 'Document date', 'description' => 'Description', 'tags' => 'Tags', 'tags_placeholder' => 'planning, FY2025', 'retain_until' => 'Retain until', 'save_metadata' => 'Save metadata',
    'versions_title' => 'Immutable versions', 'version_integrity' => 'Version :version · SHA-256 :checksum · scan :scan · text extraction :ocr', 'completed_at' => ' · completed :date', 'replacement_reason' => 'Reason for this replacement', 'upload_version' => 'Upload new version', 'no_versions' => 'No retained version history is available for this legacy record.', 'version_number' => 'Version :number', 'current' => 'Current', 'uploaded_by' => ':name · uploaded by :actor · :date', 'preview' => 'Preview', 'download' => 'Download', 'initial_version' => 'Initial governed version', 'version_manifest' => 'SHA-256 :checksum · :bytes bytes · text :status',
    'place_hold' => 'Place legal hold', 'place_hold_description' => 'Prevent replacement, archival, and retention changes.', 'hold_reference' => 'Hold reference', 'issuing_authority' => 'Issuing authority', 'hold_reason' => 'Legal or regulatory reason', 'under_hold' => 'This record is under legal hold. Replacement, retention changes, and archival are locked.', 'hold_history' => 'Legal-hold history', 'hold_history_description' => 'Placement and release decisions remain visible after a hold is released.', 'no_holds' => 'No legal holds have been recorded.', 'hold_placed' => ':authority · placed by :actor · :date', 'released' => 'Released', 'active' => 'Active', 'hold_released' => 'Released by :actor on :date. :reason', 'unknown' => 'Unknown', 'release_reason' => 'Release reason', 'release_placeholder' => 'Authority and reason for releasing this hold', 'release_hold' => 'Release legal hold',
    'archive_document' => 'Archive document', 'request_disposition' => 'Request controlled disposition', 'disposition_description' => 'Requires independent review and a separate executing officer. Active legal holds and integrity failures stop execution.', 'retention_required' => 'Retention date required', 'retention_required_description' => 'Set an approved retain-until date before requesting secure destruction.', 'authority_reference' => 'Authority reference', 'authority_placeholder' => 'Approved schedule or disposal authority', 'scheduled_date' => 'Scheduled execution date', 'disposition_reason' => 'Disposition reason', 'disposition_placeholder' => 'Record class, retention trigger and reason destruction is authorized', 'submit_disposition' => 'Submit disposition for review',
    'disposition_history' => 'Disposition history', 'disposition_history_description' => 'Requests, independent decisions, execution failures and immutable destruction evidence.', 'no_dispositions' => 'No disposition requests have been recorded.', 'secure_destruction' => 'Secure destruction · :reference', 'requested_by' => 'Requested by :actor on :date', 'retention_schedule' => 'Retention due :due · scheduled :scheduled', 'reviewed_by' => 'Reviewed by :actor on :date. :reason', 'execution_stopped' => 'Execution stopped', 'executed_by' => 'Executed by :actor on :date. :objects objects / :bytes bytes.', 'manifest_checksum' => 'Manifest SHA-256 :checksum', 'independent_reason' => 'Independent review reason', 'approve' => 'Approve', 'reject' => 'Reject', 'execute_destruction' => 'Execute approved secure destruction',
];
