<?php

return [
    'upload_evidence' => 'Upload evidence', 'upload_evidence_description' => 'Upload a scanned copy or a born-digital file. Files are stored privately and linked to the selected assessment cycle.', 'upload_criterion_evidence' => 'Upload criterion evidence', 'upload_criterion_evidence_description' => 'Files are stored privately and count toward completeness only after independent verification.', 'assessment' => 'Assessment', 'evidence_requirement' => 'Evidence requirement', 'source_type' => 'Source type', 'category_placeholder' => 'ADP, CIDP…', 'upload' => 'Upload', 'uploading' => 'Uploading :percentage%',
    'errors' => ['integrity_failed' => 'Document integrity verification failed.', 'preview_unavailable' => 'Preview is not available for this file type.'],
    'outcomes' => ['uploaded' => 'Evidence uploaded securely.', 'verified' => 'Evidence verification recorded.', 'metadata_updated' => 'Document metadata updated.', 'archived' => 'Document archived.', 'version_uploaded' => 'A new immutable document version was uploaded.', 'extraction_queued' => 'Document text extraction queued.', 'hold_placed' => 'Legal hold placed.', 'hold_released' => 'Legal hold released.', 'disposition_submitted' => 'Controlled disposition submitted for independent review.', 'disposition_decided' => 'Disposition review decision recorded.', 'disposition_executed' => 'Controlled disposition executed and evidence retained.'],
    'open_actions' => 'Open evidence actions', 'preview_document' => 'Preview document', 'download_original' => 'Download original', 'manage_record' => 'Manage record', 'reprocess_text' => 'Reprocess searchable text', 'verify_evidence' => 'Verify evidence', 'reject_evidence' => 'Reject evidence',
    'document_preview' => 'Document preview', 'secure_document' => 'Secure evidence document', 'scanned_copy' => 'Scanned copy', 'digital_file' => 'Digital file', 'text_extraction' => 'Text extraction: :status', 'not_requested' => 'not requested', 'searchable_unavailable' => 'Searchable text unavailable',
    'attempts_title' => 'Extraction attempt evidence', 'attempts_description' => 'Append-only processing and retry history for the current immutable version.', 'attempt' => 'Attempt', 'source' => 'Source', 'actor' => 'Actor', 'engine' => 'Engine', 'status' => 'Status', 'duration' => 'Duration', 'result' => 'Result', 'in_progress' => 'In progress', 'characters' => ':count characters',
    'preview_of' => 'Preview of :title', 'document' => 'document', 'extracted_preview' => 'Extracted text preview', 'download_original_document' => 'Download original document',
    'manage_document' => 'Manage document', 'manage_description' => 'Update governed metadata, versions, retention, and legal holds.', 'title' => 'Title', 'category' => 'Category', 'document_date' => 'Document date', 'description' => 'Description', 'tags' => 'Tags', 'tags_placeholder' => 'planning, FY2025', 'retain_until' => 'Retain until', 'save_metadata' => 'Save metadata',
    'versions_title' => 'Immutable versions', 'version_integrity' => 'Version :version · SHA-256 :checksum · scan :scan · text extraction :ocr', 'completed_at' => ' · completed :date', 'replacement_reason' => 'Reason for this replacement', 'upload_version' => 'Upload new version', 'no_versions' => 'No retained version history is available for this legacy record.', 'version_number' => 'Version :number', 'current' => 'Current', 'uploaded_by' => ':name · uploaded by :actor · :date', 'preview' => 'Preview', 'download' => 'Download', 'initial_version' => 'Initial governed version', 'version_manifest' => 'SHA-256 :checksum · :bytes bytes · text :status',
    'place_hold' => 'Place legal hold', 'place_hold_description' => 'Prevent replacement, archival, and retention changes.', 'hold_reference' => 'Hold reference', 'issuing_authority' => 'Issuing authority', 'hold_reason' => 'Legal or regulatory reason', 'under_hold' => 'This record is under legal hold. Replacement, retention changes, and archival are locked.', 'hold_history' => 'Legal-hold history', 'hold_history_description' => 'Placement and release decisions remain visible after a hold is released.', 'no_holds' => 'No legal holds have been recorded.', 'hold_placed' => ':authority · placed by :actor · :date', 'released' => 'Released', 'active' => 'Active', 'hold_released' => 'Released by :actor on :date. :reason', 'unknown' => 'Unknown', 'release_reason' => 'Release reason', 'release_placeholder' => 'Authority and reason for releasing this hold', 'release_hold' => 'Release legal hold',
    'archive_document' => 'Archive document', 'request_disposition' => 'Request controlled disposition', 'disposition_description' => 'Requires independent review and a separate executing officer. Active legal holds and integrity failures stop execution.', 'retention_required' => 'Retention date required', 'retention_required_description' => 'Set an approved retain-until date before requesting secure destruction.', 'authority_reference' => 'Authority reference', 'authority_placeholder' => 'Approved schedule or disposal authority', 'scheduled_date' => 'Scheduled execution date', 'disposition_reason' => 'Disposition reason', 'disposition_placeholder' => 'Record class, retention trigger and reason destruction is authorized', 'submit_disposition' => 'Submit disposition for review',
    'disposition_history' => 'Disposition history', 'disposition_history_description' => 'Requests, independent decisions, execution failures and immutable destruction evidence.', 'no_dispositions' => 'No disposition requests have been recorded.', 'secure_destruction' => 'Secure destruction · :reference', 'requested_by' => 'Requested by :actor on :date', 'retention_schedule' => 'Retention due :due · scheduled :scheduled', 'reviewed_by' => 'Reviewed by :actor on :date. :reason', 'execution_stopped' => 'Execution stopped', 'executed_by' => 'Executed by :actor on :date. :objects objects / :bytes bytes.', 'manifest_checksum' => 'Manifest SHA-256 :checksum', 'independent_reason' => 'Independent review reason', 'approve' => 'Approve', 'reject' => 'Reject', 'execute_destruction' => 'Execute approved secure destruction',
];
