<?php

return [
    'no_dependency_paths_in_scope' => 'No dependency paths in scope', 'categories' => 'Categories', 'severities' => 'Severities', 'no_resolutions_available' => 'No resolutions available', 'no_matching_implementation_gaps' => 'No matching implementation gaps', 'no_matching_resolutions' => 'No matching resolutions',
    'establish_igr_forum' => 'Establish IGR forum', 'forum_code' => 'Forum code', 'igr_cg_summit' => 'IGR-CG-SUMMIT', 'forum_name' => 'Forum name', 'forum_type' => 'Forum type', 'mandate' => 'Mandate', 'secretariat' => 'Secretariat',
    'record_formal_igr_meeting' => 'Record formal IGR meeting', 'forum' => 'Forum', 'meeting_reference' => 'Meeting reference', 'igr_summit_2026_04' => 'IGR/SUMMIT/2026/04', 'meeting_title' => 'Meeting title', 'meeting_date' => 'Meeting date', 'venue' => 'Venue', 'chair' => 'Chair', 'minutes_reference' => 'Minutes reference', 'dms_igr_min_2026_04' => 'DMS/IGR/MIN/2026/04',
    'create_implementation_gap_category' => 'Create implementation-gap category', 'category_code' => 'Category code', 'data_quality' => 'DATA-QUALITY', 'category_name' => 'Category name', 'description_label' => 'Description', 'default_severity' => 'Default severity',
    'register_adopted_resolution' => 'Register adopted resolution', 'source_forum' => 'Source forum', 'formal_meeting_optional_for_historical_records' => 'Formal meeting (optional for historical records)', 'resolution_number' => 'Resolution number', 'igr_2026_001' => 'IGR/2026/001', 'title_label' => 'Title', 'resolution_date' => 'Resolution date', 'implementation_deadline' => 'Implementation deadline', 'resolution_text' => 'Resolution text', 'priority' => 'Priority',
    'county' => 'County', 'organization' => 'Organization', 'role' => 'Role', 'prerequisites' => 'Prerequisites', 'dependent_resolutions' => 'Dependent resolutions', 'report_implementation_gap' => 'Report implementation gap', 'gap_category' => 'Gap category', 'gap_title' => 'Gap title', 'implementation_impact' => 'Implementation impact', 'severity' => 'Severity', 'accountable_owner' => 'Accountable owner', 'affected_county' => 'Affected county', 'mitigation_due_date' => 'Mitigation due date',
    'add_resolution_dependency' => 'Add resolution dependency', 'prerequisite_resolution' => 'Prerequisite resolution', 'dependency_type' => 'Dependency type', 'dependency_rationale' => 'Dependency rationale', 'record_implementation_progress' => 'Record implementation progress', 'progress_percentage' => 'Progress percentage', 'evidence_note_or_reference_optional' => 'Evidence note or reference (optional)', 'add_context_for_the_linked_repository_evidence' => 'Add context for the linked repository evidence', 'implementation_narrative' => 'Implementation narrative',
    'start_implementation' => 'Start implementation', 'submit_for_closure' => 'Submit for closure', 'approve_closure' => 'Approve closure', 'return_for_action' => 'Return for action', 'start_mitigation' => 'Start mitigation', 'submit_resolution' => 'Submit resolution', 'accept_resolution' => 'Accept resolution', 'return_mitigation' => 'Return mitigation', 'decision_rationale' => 'Decision rationale', 'decision_comment' => 'Decision comment',
    'gap_transition_description' => 'Record the decision basis for the governed implementation-gap lifecycle.', 'transition_not_available' => 'This transition is not available.', 'transition_decision_basis' => 'Record the decision basis for :transition.',
];
