<?php

return ['outcomes' => [
    'system_registered' => 'Integration system :code registered.', 'activation_recorded' => 'Production integration activation recorded.', 'contract_submitted' => 'Interface contract v:version submitted for review.', 'contract_published' => 'Interface contract independently published.', 'exchange_recorded' => 'Exchange :correlation recorded as :status.', 'exchange_retried' => 'Exchange :correlation retry completed as :status.', 'reconciliation_resolved' => 'Reconciliation exception resolved with an auditable decision.',
], 'exchange' => [
    'oauth_client' => 'OAuth client',
    'errors' => ['fixture_sandbox_only' => 'Fixture transport is restricted to sandbox systems.', 'unsupported_transport' => 'Unsupported integration transport [:transport].', 'production_activation_required' => 'Production exchange requires recorded source-owner activation approval.', 'endpoint_credentials_required' => 'Production endpoint and credential-vault reference are required.', 'host_not_allowlisted' => 'Integration endpoint host is not allowlisted.', 'credential_unresolved' => 'Credential-vault reference is unresolved.', 'effective_inbound_contract' => 'Only an effective published interface contract can receive data.', 'inbound_not_approved' => 'This integration system is not approved for inbound exchange.', 'system_inactive' => 'The integration system is not active.', 'oauth_client_unbound' => 'The OAuth client is not bound to this integration system.', 'production_source_approval' => 'Production source-owner activation approval is required.', 'production_agreements' => 'Production contract and data-sharing approvals are required.', 'missing_headers' => 'Missing contract-required headers: :headers.', 'idempotency_conflict' => 'The idempotency key is already associated with a different exchange.', 'effective_outbound_contract' => 'Only an effective published interface contract can exchange data.'],
    'audit' => ['ingested' => 'Inbound exchange :correlation accepted from :system.'],
]];
