<?php

return [
    'create_collaboration_plan' => 'Create collaboration plan', 'partner' => 'Partner', 'starts_on' => 'Starts on', 'ends_on' => 'Ends on', 'add_accountable_action' => 'Add accountable action', 'county' => 'County', 'accountable_owner' => 'Accountable owner', 'accountable_organization' => 'Accountable organization', 'due_on' => 'Due on', 'upload_action_evidence' => 'Upload action evidence', 'source_type' => 'Source type', 'submit_action_progress' => 'Submit action progress', 'verify_action_progress' => 'Verify action progress', 'decision' => 'Decision',
    'request_agreement_change' => 'Request agreement change', 'change_type' => 'Change type', 'effective_date' => 'Effective date', 'revised_end_date' => 'Revised end date', 'upload_change_evidence' => 'Upload change evidence', 'decide_agreement_change' => 'Decide agreement change', 'upload_agreement_record' => 'Upload agreement record', 'review_agreement' => 'Review agreement', 'submit_agreement_for_approval' => 'Submit agreement for approval',
    'create_plan' => 'Create plan', 'create_plan_description' => 'Create a time-bound plan for independent approval.', 'transition_plan' => ':transition plan', 'plan_transition_description' => 'Record an attributable plan lifecycle decision.', 'add_action' => 'Add action', 'add_action_description' => 'Assign a measurable county action within the approved period.', 'upload_evidence' => 'Upload evidence', 'upload_action_evidence_description' => 'Attach a scanned or born-digital implementation record.', 'submit_progress' => 'Submit progress', 'submit_progress_description' => 'Completion requires clean evidence and independent verification.', 'verify' => 'Verify', 'verify_progress_description' => 'Record an independent immutable verification decision.',
    'preview_document' => 'Preview :title', 'request_change' => 'Request change', 'request_change_description' => 'Propose an amendment, renewal, suspension or termination without rewriting the approved agreement.', 'upload_change_evidence_description' => 'Attach the signed amendment, renewal, suspension or termination instrument.', 'record_decision' => 'Record decision', 'change_decision_description' => 'An independent approver reviews the clean evidence and records an immutable decision.', 'upload_record' => 'Upload record', 'upload_record_description' => 'Add a privately stored scanned or born-digital copy. Files are checksum-bound and security scanned.', 'agreement_decision_description' => 'Approve or reject this independently submitted agreement. The submitter cannot make this decision.', 'submit_for_approval' => 'Submit for approval', 'submit_for_approval_description' => 'Confirm the repository record is complete. Submission locks further uploads and sends the agreement for an independent decision.',
    'actions_for_record' => 'Actions for :record', 'upload_reconciliation_evidence' => 'Upload reconciliation evidence', 'upload_reconciliation_evidence_description' => 'Add a scanned or born-digital source record to the governed repository.', 'reconcile_contribution' => 'Reconcile contribution', 'reconcile_contribution_description' => 'Independent maker-checker decision using the attached clean evidence.', 'download_document' => 'Download :title',
];
