<?php

return [
    'contribution_register' => 'Contribution reconciliation register', 'contribution_register_description' => 'Reported commitments are independently reconciled against clean DMS evidence and retained as a checksum-linked decision history.', 'no_contributions' => 'No contributions registered', 'no_contributions_description' => 'Record a partner contribution to begin evidence collection and reconciliation.',
    'partner_project' => 'Partner / project', 'county' => 'County', 'reported' => 'Reported', 'decision' => 'Decision', 'actions' => 'Actions', 'of' => 'of', 'view_record' => 'View record', 'verified_commitment' => 'Verified commitment', 'verified_disbursement' => 'Verified disbursement', 'verified_in_kind' => 'Verified in-kind value', 'source_reference' => 'Source reference', 'review_note' => 'Review note',
    'contribution_chain' => 'contribution, evidence, and reconciliation chain.', 'reported_commitment' => 'Reported commitment', 'reported_disbursement' => 'Reported disbursement', 'evidence' => 'Evidence', 'ellipsis' => '…', 'decision_history' => 'Decision history', 'no_reconciliation_decision' => 'No reconciliation decision yet.',
    'collaboration_plans' => 'Collaboration plans and actions', 'collaboration_plans_description' => 'Approved partner/county plans with accountable evidence-backed actions and independent progress verification.', 'no_collaboration_plans' => 'No collaboration plans', 'no_collaboration_plans_description' => 'Create a governed plan to coordinate partner and county delivery actions.', 'no_accountable_actions' => 'No accountable actions assigned.',
    'due' => 'due', 'empty_value' => '—', 'reference' => 'Reference', 'title_label' => 'Title', 'objective' => 'Objective', 'create_draft' => 'Create draft', 'record' => 'Record', 'code' => 'Code', 'description_label' => 'Description', 'assign_action' => 'Assign action', 'progress' => 'Progress', 'narrative' => 'Narrative', 'submit_verification' => 'Submit for verification', 'verification_note' => 'Verification note',
    'open_parenthesis' => '(', 'close_parenthesis' => ')',
    'agreement_register' => 'Agreement approval register', 'agreement_register_description' => 'Document-backed MoUs and cooperation instruments move from draft submission to independent approval with immutable workflow history.', 'no_agreements' => 'No agreements registered', 'no_agreements_description' => 'Register an agreement to begin its document and approval lifecycle.',
    'separator' => '·', 'label_separator' => ':', 'to' => 'to', 'repository_records' => 'Repository records', 'no_repository_records' => 'No scanned or born-digital agreement record has been uploaded.', 'scan' => 'scan', 'ocr' => 'OCR', 'preview' => 'Preview', 'download' => 'Download',
    'change_history' => 'Post-approval change history', 'version_prefix' => 'v', 'effective' => 'Effective', 'authorized_preview' => 'Authorized preview of the private repository copy.', 'revised_title' => 'Revised title (amendments)', 'revised_summary' => 'Revised summary (amendments)', 'revised_value' => 'Revised committed value', 'reason' => 'Reason',
    'submit_governed_request' => 'Submit governed request', 'record_title' => 'Record title', 'category' => 'Category', 'document' => 'Document', 'upload_securely' => 'Upload securely', 'decision_note' => 'Decision note', 'retain_decision' => 'Retain decision', 'agreement_file' => 'Agreement file', 'uploading' => 'Uploading', 'percent' => '%', 'decision_rationale' => 'Decision rationale', 'record_decision' => 'Record decision', 'confirm_submission' => 'Confirm submission',
];
