<?php

return [
    'operational_control_alerts' => 'Operational control alerts', 'operational_control_alerts_description' => 'Idempotent monitoring of agreement expiry and overdue, exception, or rejected contribution reconciliations.', 'no_operational_alerts' => 'No partner operational alerts', 'no_operational_alerts_description' => 'The scheduled monitor has not detected expiry or reconciliation exceptions in your county scope.', 'alert' => 'Alert', 'partner_county' => 'Partner / county', 'status' => 'Status', 'detected' => 'Detected', 'alert_actions' => 'Actions for :alert', 'resolve_operational_alert' => 'Resolve operational alert', 'resolve_operational_alert_description' => 'Record remediation or a formally accepted risk decision; source evidence remains unchanged.', 'record_disposition' => 'Record disposition', 'disposition' => 'Disposition', 'resolution_evidence' => 'Resolution evidence',
    'severity_critical' => 'Critical', 'severity_warning' => 'Warning', 'status_open' => 'Open', 'status_resolved' => 'Resolved', 'status_accepted_risk' => 'Accepted risk', 'status_system_resolved' => 'System resolved', 'alert_type_agreement_expired' => 'Agreement expired', 'alert_type_agreement_expiry_due' => 'Agreement expiry due', 'alert_type_contribution_reconciliation_overdue' => 'Contribution reconciliation overdue', 'alert_type_contribution_reconciliation_exception' => 'Contribution reconciliation exception', 'alert_type_contribution_reconciliation_rejected' => 'Contribution reconciliation rejected',
    'contribution_register' => 'Contribution reconciliation register', 'contribution_register_description' => 'Reported commitments are independently reconciled against clean DMS evidence and retained as a checksum-linked decision history.', 'no_contributions' => 'No contributions registered', 'no_contributions_description' => 'Record a partner contribution to begin evidence collection and reconciliation.',
    'partner_project' => 'Partner / project', 'county' => 'County', 'reported' => 'Reported', 'decision' => 'Decision', 'actions' => 'Actions', 'of' => 'of', 'view_record' => 'View record', 'verified_commitment' => 'Verified commitment', 'verified_disbursement' => 'Verified disbursement', 'verified_in_kind' => 'Verified in-kind value', 'source_reference' => 'Source reference', 'review_note' => 'Review note',
    'contribution_chain' => 'contribution, evidence, and reconciliation chain.', 'reported_commitment' => 'Reported commitment', 'reported_disbursement' => 'Reported disbursement', 'evidence' => 'Evidence', 'ellipsis' => '…', 'decision_history' => 'Decision history', 'no_reconciliation_decision' => 'No reconciliation decision yet.',
    'collaboration_plans' => 'Collaboration plans and actions', 'collaboration_plans_description' => 'Approved partner/county plans with accountable evidence-backed actions and independent progress verification.', 'no_collaboration_plans' => 'No collaboration plans', 'no_collaboration_plans_description' => 'Create a governed plan to coordinate partner and county delivery actions.', 'no_accountable_actions' => 'No accountable actions assigned.',
    'due' => 'due', 'empty_value' => '—', 'reference' => 'Reference', 'title_label' => 'Title', 'objective' => 'Objective', 'create_draft' => 'Create draft', 'record' => 'Record', 'code' => 'Code', 'description_label' => 'Description', 'assign_action' => 'Assign action', 'progress' => 'Progress', 'narrative' => 'Narrative', 'submit_verification' => 'Submit for verification', 'verification_note' => 'Verification note',
    'open_parenthesis' => '(', 'close_parenthesis' => ')',
    'agreement_register' => 'Agreement approval register', 'agreement_register_description' => 'Document-backed MoUs and cooperation instruments move from draft submission to independent approval with immutable workflow history.', 'no_agreements' => 'No agreements registered', 'no_agreements_description' => 'Register an agreement to begin its document and approval lifecycle.',
    'separator' => '·', 'label_separator' => ':', 'to' => 'to', 'repository_records' => 'Repository records', 'no_repository_records' => 'No scanned or born-digital agreement record has been uploaded.', 'scan' => 'scan', 'ocr' => 'OCR', 'preview' => 'Preview', 'download' => 'Download',
    'change_history' => 'Post-approval change history', 'version_prefix' => 'v', 'effective' => 'Effective', 'authorized_preview' => 'Authorized preview of the private repository copy.', 'revised_title' => 'Revised title (amendments)', 'revised_summary' => 'Revised summary (amendments)', 'revised_value' => 'Revised committed value', 'reason' => 'Reason',
    'submit_governed_request' => 'Submit governed request', 'record_title' => 'Record title', 'category' => 'Category', 'document' => 'Document', 'upload_securely' => 'Upload securely', 'decision_note' => 'Decision note', 'retain_decision' => 'Retain decision', 'agreement_file' => 'Agreement file', 'uploading' => 'Uploading', 'percent' => '%', 'decision_rationale' => 'Decision rationale', 'record_decision' => 'Record decision', 'confirm_submission' => 'Confirm submission',
    'development_cooperation_intelligence' => 'Development cooperation intelligence', 'partner_coordination' => 'Partner coordination', 'partner_coordination_description' => 'A governed directory of partners, agreements, financial and in-kind contributions, geographic coverage, overlaps, and collaboration opportunities.', 'sector' => 'Sector',
    'status_draft' => 'Draft', 'status_pending_approval' => 'Pending approval', 'status_active' => 'Active', 'status_in_progress' => 'In progress', 'status_completed' => 'Completed', 'status_suspended' => 'Suspended', 'status_rejected' => 'Rejected',
    'no_matching_partner_profiles' => 'No matching partner profiles', 'no_matching_partner_profiles_description' => 'Adjust the search or reporting dates, or add an authorized development partner profile.', 'collaboration_intelligence' => 'Collaboration intelligence', 'collaboration_intelligence_description' => 'Potential overlaps and synergies detected from shared projects, counties, and sectors.', 'refresh_analysis' => 'Refresh analysis', 'no_collaboration_alerts' => 'No collaboration alerts', 'no_collaboration_alerts_description' => 'Run the portfolio analysis after partner activities and commitments have been recorded.',
    'alert_type_overlap' => 'Portfolio overlap', 'severity_low' => 'Low', 'severity_medium' => 'Medium', 'severity_high' => 'High', 'partner_pair' => ':primary × :related', 'resolution_value' => 'Resolution: :resolution', 'resolve_collaboration_alert' => 'Resolve collaboration alert', 'resolve_alert' => 'Resolve alert', 'resolve_collaboration_alert_description' => ':primary and :related: record the agreed resolution and next action.', 'resolution_and_next_action' => 'Resolution and next action', 'resolution' => 'Resolution',
    'geographic_partner_portfolio' => 'Geographic partner portfolio', 'nationwide_portfolio_description' => 'Nationwide geography with only authorized portfolio counties activated.', 'single_county_portfolio_description' => 'Your county is automatically zoomed and isolated.', 'select_active_county_description' => 'Select an active county to inspect its partner portfolio.', 'county_portfolio' => 'County portfolio', 'select_authorized_county' => 'Select an authorized county', 'partners' => 'Partners', 'active_agreements' => 'Active agreements', 'committed' => 'Committed', 'disbursed' => 'Disbursed', 'portfolio_selection_notice' => 'The selection updates this portfolio summary without leaving the partner workspace.', 'select_county_on_map' => 'Select an authorized county on the map to inspect its portfolio.',
];
