<?php

return [
    'physical_progress' => 'Physical progress', 'approved_budget' => 'Approved budget', 'expenditure' => 'Expenditure', 'scope' => 'Scope', 'delivery_scope' => 'Delivery scope', 'results_links' => 'Results links', 'control_status' => 'Control status',
    'upload_project_record' => 'Upload project record', 'document_title' => 'Document title', 'record_purpose' => 'Record purpose', 'record_category' => 'Record category',
    'add_milestone' => 'Add milestone', 'ms_01' => 'MS-01', 'milestone_title' => 'Milestone title', 'planned_start' => 'Planned start', 'planned_end' => 'Planned end', 'weight' => 'Weight %', 'dependencies' => 'Dependencies',
    'add_budget_line' => 'Add budget line', 'bl_01' => 'BL-01', 'category' => 'Category', 'description_label' => 'Description', 'approved_amount' => 'Approved amount', 'currency' => 'Currency',
    'register_risk' => 'Register risk', 'rsk_01' => 'RSK-01', 'risk_description' => 'Risk description', 'probability_1_5' => 'Probability 1–5', 'impact_1_5' => 'Impact 1–5', 'mitigation' => 'Mitigation',
    'add_procurement' => 'Add procurement', 'tender_reference' => 'Tender reference', 'procurement_title' => 'Procurement title', 'method' => 'Method', 'estimated_value' => 'Estimated value', 'planned_notice_date' => 'Planned notice date',
    'record_the_evidence_based_lifecycle_decision' => 'Record the evidence-based lifecycle decision', 'verify_progress_update' => 'Verify progress update', 'independent_verification_rationale' => 'Independent verification rationale',
    'milestones' => 'Milestones', 'budget_lines' => 'Budget lines', 'risks' => 'Risks', 'procurements' => 'Procurements', 'progress_history' => 'Progress history',
    'capture_schedule_baseline' => 'Capture schedule baseline', 'record_the_planning_evidence_and_authority_supporting_this_proposed_baseline' => 'Record the planning evidence and authority supporting this proposed baseline.',
    'approved_baseline' => 'Approved baseline', 'critical_path' => 'Critical path', 'forecast_finish' => 'Forecast finish', 'forecast_variance' => 'Forecast variance',
    'record_the_independent_schedule_review_evidence_and_decision_rationale' => 'Record the independent schedule review evidence and decision rationale.',
    'register_project_resource' => 'Register project resource', 'resource_code' => 'Resource code', 'resource_name' => 'Resource name', 'resource_type' => 'Resource type', 'capacity_unit' => 'Capacity unit', 'available_from' => 'Available from', 'available_to' => 'Available to',
    'allocate_project_resource' => 'Allocate project resource', 'resource' => 'Resource', 'milestone' => 'Milestone', 'allocation_start' => 'Allocation start', 'allocation_end' => 'Allocation end',
    'planned_value' => 'Planned value', 'earned_value' => 'Earned value', 'actual_cost' => 'Actual cost', 'estimate_at_completion' => 'Estimate at completion', 'cost_performance_index' => 'Cost performance index', 'schedule_performance_index' => 'Schedule performance index', 'variance_at_completion' => 'Variance at completion', 'to_complete_index' => 'To-complete index',
    'title_label' => 'Title', 'actual_start' => 'Actual start', 'actual_end' => 'Actual end', 'progress' => 'Progress (%)', 'funding_source' => 'Funding source', 'review_due' => 'Review due', 'contract_value' => 'Contract value', 'award_date' => 'Award date', 'supplier_name' => 'Supplier name', 'contract_reference' => 'Contract reference',
    'preview_document' => 'Preview of :title', 'review_reporting_date' => 'Review :date', 'verify_physical_progress_description' => 'Independently verify the :progress% physical-progress submission.', 'project_action_description' => 'Complete the governed project action and record it in the audit trail.', 'capture_baseline' => 'Capture baseline', 'capture_baseline_description' => 'Freeze the complete current milestone plan for independent approval and future variance measurement.', 'review_schedule_baseline' => 'Review schedule baseline v:version', 'review_pending_baseline' => 'Review pending baseline v:version', 'review_baseline_description' => 'Independently approve the checksum-bound milestone snapshot or reject it with evidence.', 'add_resource' => 'Add resource', 'resource_currency_description' => 'Capacity and rates are recorded in :currency, inherited from the project.', 'add_allocation' => 'Add allocation', 'add_allocation_description' => 'Allocate uniform daily capacity within both the resource and milestone periods.', 'actions_for_record' => 'Actions for :record',
];
