<?php

return [
    'stage_identity_lifecycle_change' => 'Stage identity lifecycle change', 'lifecycle_event' => 'Lifecycle event', 'target_identity' => 'Target identity', 'authoritative_source_system' => 'Authoritative source system', 'unique_source_event_id' => 'Unique source event ID', 'source_evidence_reference' => 'Source evidence reference', 'effective_at' => 'Effective at',
    'proposed_home_county' => 'Proposed home county', 'proposed_assigned_counties' => 'Proposed assigned counties', 'business_reason_and_source_reconciliation_note' => 'Business reason and source reconciliation note', 'independent_decision' => 'Independent decision', 'decision_rationale' => 'Decision rationale',
    'record_security_response' => 'Record security response', 'assigned_incident_lead' => 'Assigned incident lead', 'response_playbook' => 'Response playbook', 'initial_severity' => 'Initial severity', 'incident_or_exercise_title' => 'Incident or exercise title', 'controlled_incident_summary' => 'Controlled incident summary', 'affected_services_comma_separated' => 'Affected services (comma-separated)', 'observed_or_simulated_business_impact' => 'Observed or simulated business impact', 'soc_service_desk_privacy_or_legal_reference' => 'SOC, service desk, privacy or legal reference', 'exercise_objectives_comma_separated' => 'Exercise objectives (comma-separated)',
    'incident_lead' => 'Incident lead', 'summary' => 'Summary', 'affected_services' => 'Affected services', 'business_impact' => 'Business impact', 'acknowledgement_target' => 'Acknowledgement target', 'containment_target' => 'Containment target', 'external_reference' => 'External reference', 'exercise_outcome' => 'Exercise outcome', 'root_cause' => 'Root cause', 'corrective_actions' => 'Corrective actions',
    'controlled_evidence_reference' => 'Controlled evidence reference', 'verified_root_cause' => 'Verified root cause', 'completed_and_tracked_corrective_actions' => 'Completed and tracked corrective actions', 'lessons_and_playbook_improvements' => 'Lessons and playbook improvements', 'next_exercise_due' => 'Next exercise due',
    'record_title' => 'Record title', 'records_category' => 'Records category', 'source_type' => 'Source type', 'evidence_purpose' => 'Evidence purpose', 'composer_components' => 'Composer components', 'javascript_components' => 'JavaScript components', 'npm_vulnerabilities' => 'NPM vulnerabilities', 'composer_lock_sha256' => 'Composer lock SHA-256', 'artifact_sha256' => 'Artifact SHA-256', 'evidence_sha256' => 'Evidence SHA-256',
    'request_temporary_access' => 'Request temporary access', 'beneficiary_with_strong_authentication' => 'Beneficiary with strong authentication', 'access_type' => 'Access type', 'geographic_scope' => 'Geographic scope', 'least_privilege_permissions' => 'Least-privilege permissions', 'counties_in_scope' => 'Counties in scope', 'access_starts' => 'Access starts', 'access_expires' => 'Access expires', 'security_incident_reference' => 'Security incident reference', 'business_justification_and_expected_outcome' => 'Business justification and expected outcome', 'compensating_controls_and_monitoring' => 'Compensating controls and monitoring',
    'independent_evidence_based_rationale' => 'Independent evidence-based rationale', 'immediate_revocation_reason' => 'Immediate revocation reason', 'post_use_outcome' => 'Post-use outcome', 'audit_findings_and_follow_up' => 'Audit findings and follow-up',
    'review_decision' => 'Review decision', 'treatment_status' => 'Treatment status', 'residual_likelihood_1_5' => 'Residual likelihood (1–5)', 'residual_impact_1_5' => 'Residual impact (1–5)', 'risk_acceptance_reference' => 'Risk-acceptance reference', 'evidence_references_comma_separated' => 'Evidence references (comma separated)', 'independent_findings' => 'Independent findings',
    'certification_decision' => 'Certification decision', 'evidence_based_rationale' => 'Evidence-based rationale', 'required_remediation' => 'Required remediation', 'remediation_due_date' => 'Remediation due date',
    'register_threat_scenario' => 'Register threat scenario', 'threat_reference' => 'Threat reference', 'threat_title' => 'Threat title', 'threat_category' => 'Threat category', 'risk_owner' => 'Risk owner', 'affected_asset_or_service' => 'Affected asset or service', 'threat_actor' => 'Threat actor', 'likelihood_1_5' => 'Likelihood (1–5)', 'impact_1_5' => 'Impact (1–5)', 'review_due_date' => 'Review due date', 'abuse_or_failure_scenario' => 'Abuse or failure scenario', 'entry_points_comma_separated' => 'Entry points (comma separated)', 'existing_controls_comma_separated' => 'Existing controls (comma separated)', 'treatment_plan_and_accountable_outcome' => 'Treatment plan and accountable outcome',
    'launch_access_certification' => 'Launch access certification', 'campaign_reference' => 'Campaign reference', 'campaign_name' => 'Campaign name', 'independent_reviewer' => 'Independent reviewer', 'roles_in_scope' => 'Roles in scope', 'review_period_from' => 'Review period from', 'review_period_to' => 'Review period to', 'certification_due' => 'Certification due', 'scope_criteria_and_exclusions' => 'Scope, criteria and exclusions',
    'identity_lifecycle_description' => 'Capture an already verified HR or IAM source event. A different access certifier must decide it before IDMIS access changes.', 'identity_lifecycle' => 'Identity lifecycle', 'actions_for_record' => 'Actions for :record', 'security_response_description' => 'Create a live incident or an explicitly labelled exercise. Severity snapshots the acknowledgement and containment targets.', 'security_response' => 'Security response', 'transition_actions_outcome' => ':transition actions and outcome', 'actions_for_supply_chain_scan' => 'Actions for supply-chain scan :id', 'sha256_label' => ':file SHA-256',
    'temporary_access_description' => 'Request a time-bound, least-privilege grant for independent approval. Emergency grants are limited to four hours and require post-use review.', 'temporary_access' => 'Temporary access', 'view_record' => 'View :record', 'threat_description' => 'Capture the affected asset, STRIDE category, entry points, inherent risk and treatment before independent review.', 'threat' => 'Threat', 'access_review_description' => 'Create immutable access snapshots for selected programme roles and assign an independent reviewer.', 'access_review' => 'Access review',
];
