<?php

return [
    'title' => 'Profile settings', 'profile_photo' => 'Profile photo', 'profile_photo_description' => 'Upload, position and crop the photo shown in your authenticated account header.', 'account_status' => 'Account status', 'account_status_description' => 'Your governed identity and verification state.', 'role' => 'Role', 'email_verification' => 'Email verification', 'verified' => 'Verified', 'pending_verification' => 'Pending verification', 'account_created' => 'Account created', 'not_recorded' => 'Not recorded',
    'personal_information' => 'Personal information', 'personal_information_description' => 'Keep your account name and email address current.', 'edit' => 'Edit', 'edit_personal_information' => 'Edit personal information', 'email_change_notice' => 'Changing your email may require it to be verified again.', 'full_name' => 'Full name', 'email_address' => 'Email address', 'save_changes' => 'Save changes', 'email_unverified' => 'Your email address is unverified.', 'resend_verification' => 'Re-send the verification email', 'verification_sent' => 'A new verification link has been sent.',
    'access_scope' => 'Access scope', 'access_scope_description' => 'Assigned by an authorized administrator.', 'home_county' => 'Home county', 'national_portfolio' => 'National / portfolio', 'assigned_counties' => 'Assigned counties', 'none' => 'None', 'account_controls' => 'Account controls', 'account_controls_description' => 'Continue to the complete security, workspace and display controls for this account.', 'password_mfa_passkeys' => 'Password, MFA and passkeys', 'appearance_theme' => 'Appearance and theme',
    'account_lifecycle' => 'Account lifecycle', 'account_lifecycle_description' => 'Permanently end access and remove your personal profile photo.', 'delete_account' => 'Delete account', 'delete_account_warning' => 'This signs you out and removes access. This action cannot be undone without an authorized administrator.', 'confirm_account_deletion' => 'Confirm account deletion', 'confirm_account_deletion_description' => 'Once your account is deleted, all of its resources and access will be unavailable. Enter your password to confirm.', 'current_password' => 'Current password', 'cancel' => 'Cancel', 'deleting_account' => 'Deleting account…',
    'photo_type_error' => 'Choose a JPEG, PNG or WebP image.', 'photo_size_error' => 'Choose an image smaller than 10 MB.', 'photo_dimensions_error' => 'Choose an image at least 256 by 256 pixels.', 'photo_open_error' => 'The selected image could not be opened.', 'photo_crop_error' => 'The cropped image could not be prepared.', 'updated' => 'Updated', 'no_photo' => 'No profile photo uploaded', 'replace_crop' => 'Replace and crop', 'upload_crop' => 'Upload and crop', 'remove' => 'Remove', 'choose_photo' => 'Choose a profile photo', 'crop_photo' => 'Crop profile photo', 'crop_photo_description' => 'Adjust the zoom and position. The saved photo will match the square preview exactly.', 'crop_preview' => 'Cropped profile photo preview', 'zoom' => 'Zoom', 'separator' => '·', 'multiply' => '×', 'photo_zoom' => 'Photo zoom', 'horizontal_position' => 'Horizontal position', 'horizontal_photo_position' => 'Horizontal photo position', 'vertical_position' => 'Vertical position', 'vertical_photo_position' => 'Vertical photo position', 'keyboard_adjustment' => 'Use arrow keys on each control for precise keyboard adjustment.', 'uploading' => 'Uploading', 'choose_another' => 'Choose another', 'save_cropped_photo' => 'Save cropped photo',
    'processor_errors' => ['decode_failed' => 'The selected file could not be decoded as a supported image.', 'prepare_failed' => 'The profile photo could not be prepared.', 'background_failed' => 'The profile photo background could not be prepared.', 'resize_failed' => 'The profile photo could not be resized.', 'encode_failed' => 'The profile photo could not be encoded securely.'],
    'photo_errors' => ['store_failed' => 'The profile photo could not be stored.', 'integrity_failed' => 'The stored profile photo failed integrity verification.'], 'audit' => ['photo_updated' => 'Profile photo updated.', 'photo_removed' => 'Profile photo removed.'],
    'appearance_settings' => 'Appearance settings', 'appearance_settings_description' => 'Update the appearance settings for your account',
];
