<?php

return [
    'faqs_title' => 'Frequently asked questions', 'faqs_meta' => 'Answers about IDMIS access, accounts, information, security, and support.', 'guidance' => 'IDMIS guidance', 'faqs_intro' => 'Find quick answers about system access, permitted users, information handling, and support.',
    'questions' => [
        ['question' => 'What is IDMIS?', 'answer' => 'The Integrated Devolution Management Information System is a secure platform for coordinating programmes, monitoring results, managing evidence, sharing learning, and strengthening accountability across national and county governments.'],
        ['question' => 'Who can access the system?', 'answer' => 'Access is limited to authorized national, county, independent verification, programme, and support personnel. Permissions depend on your organization and assigned responsibilities.'],
        ['question' => 'How do I get an account?', 'answer' => 'Accounts are created or granted by authorized IDMIS administrators. There is no public self-registration. Contact your designated county or programme administrator if your duties require access.'],
        ['question' => 'What should I do if I cannot sign in?', 'answer' => 'Confirm that you are using the official email associated with your account. Use password reset if needed. If the problem continues, contact your designated administrator or use the Help page.'],
        ['question' => 'What information will IDMIS manage?', 'answer' => 'IDMIS manages programme and performance information, assessment evidence, reporting documents, decisions, and approved coordination records. Access is controlled by role, organization, county scope, and purpose.'],
        ['question' => 'How does the ACPA assessment workflow operate?', 'answer' => 'Authorized county users prepare criterion responses and mandatory evidence. Assigned assessors and independent verification roles review the package, record findings, and move it through controlled decisions and appeals. Published scores come only from complete, verified criteria and immutable result records.'],
        ['question' => 'Can previous ACPA assessments be uploaded?', 'answer' => 'Yes. Authorized migration officers can stage an approved historical CSV or XLSX package containing the assessment, criterion results, evidence manifest, findings, assessors, and appeals. Independent review and a separate final operator are required before the package becomes historical IDMIS data.'],
        ['question' => 'Can scanned evidence and digital files both be uploaded?', 'answer' => 'Yes. Evidence may be a scanned copy or a born-digital file. Uploads are private, malware-scanned, checksum-verified, versioned, and linked to their authorized county, cycle, criterion, or record before they can support a decision.'],
        ['question' => 'What can I do in File Manager?', 'answer' => 'Authorized users can search folders and records, use grid or list view, preview supported documents, inspect source and version metadata, upload files, and perform permitted bulk moves. Legal holds, county scope, retention, and records permissions continue to apply.'],
        ['question' => 'How do analytics filters and drill-downs work?', 'answer' => 'Cycle, county, and date filters constrain the authorized dataset and are carried into supported drill-downs. Users with permission can save named analytics views, compare charts and trends, and export CSV, XLSX, JSON, or PDF evidence from the same scope.'],
        ['question' => 'Does IDMIS include sub-counties and wards?', 'answer' => 'Yes. The governed administrative hierarchy contains Kenya’s 47 counties, their mapped sub-county or constituency parent units, and wards. These units support filtering and reference data; map boundaries remain visualization aids rather than cadastral or legal evidence.'],
        ['question' => 'Which languages are supported?', 'answer' => 'The interface supports English, Kiswahili, and French. Use the locale selector to change language; signed-in users can retain a preferred default. Official names, codes, checksums, and source references remain unchanged.'],
        ['question' => 'Are bulk actions and exports restricted?', 'answer' => 'Yes. The server rechecks permission, county scope, record state, and the full selection before a bulk action or export. A user cannot expand access by changing filters, URLs, request identifiers, or exported formats.'],
        ['question' => 'Can county users see another county’s restricted documents?', 'answer' => 'Not by default. Restricted working documents remain within their approved county and workflow while authorized national monitoring and approved publication follow explicit permissions.'],
        ['question' => 'Will IDMIS work with slow or interrupted internet?', 'answer' => 'The service is designed for bandwidth-conscious use, including clear upload progress, retry-safe operations, and governed offline learning packages. Approved rollout guidance defines assisted support.'],
        ['question' => 'Where can I learn more about devolution?', 'answer' => 'The State Department for Devolution website publishes policies, plans, guidance, news, and resources about Kenya’s devolved system of government.'],
    ],
    'still_need_help' => 'Still need help?', 'support_or_sign_in' => 'See the support channels or return to sign in.', 'help_and_support' => 'Help and support', 'sign_in' => 'Sign in', 'general_faqs' => 'Read general devolution FAQs',
];
