<?php

return [
    'eyebrow' => 'Controlled official travel', 'title' => 'Travel clearance', 'description' => 'Route official travel through management review, independent finance commitment, SLA monitoring and an immutable decision trail.',
    'clearance_status' => 'Clearance status', 'county' => 'County', 'sector' => 'Sector', 'requests' => 'Requests', 'approved' => 'Approved', 'rejected' => 'Rejected', 'average_decision_time' => 'Average decision time', 'hours' => 'hours',
    'cost_by_currency' => 'Cost by currency', 'cost_by_currency_description' => 'Estimated travel exposure remains currency-specific to avoid invalid conversions.', 'currency' => 'Currency', 'total_estimate' => 'Total estimate', 'average' => 'Average', 'frequent_destinations' => 'Frequent destinations', 'frequent_destinations_description' => 'Top destinations by request frequency within the authorized portfolio.', 'destination' => 'Destination', 'estimated_cost' => 'Estimated cost', 'decision_pipeline' => 'Decision pipeline', 'decision_pipeline_description' => 'Current request distribution across clearance states.', 'status' => 'Status',
    'clearance_register' => 'Clearance register', 'authorized_portfolio_count' => 'requests in your authorized portfolio', 'export' => 'Export', 'reference' => 'Reference', 'requester' => 'Requester', 'travel_dates' => 'Travel dates', 'estimate' => 'Estimate', 'reference_release' => 'Reference release', 'empty_title' => 'No matching travel requests', 'empty_description' => 'Adjust the dates, search, status, county or sector filters. Authorized staff can create the first clearance request from this workspace.', 'no_data_prefix' => 'No', 'data' => 'data', 'analytics_empty_description' => 'Matching travel requests will populate this analysis.',
    'new_request' => 'New travel request', 'new_request_description' => 'Capture purpose, funding, HRIS reference and the complete itinerary before submission.', 'organization' => 'Organization', 'travel_type' => 'Travel type', 'domestic' => 'Domestic', 'international' => 'International', 'purpose' => 'Purpose', 'departure_date' => 'Departure date', 'return_date' => 'Return date', 'total_estimated_cost' => 'Total estimated cost', 'funding_source' => 'Funding source', 'cost_centre' => 'Cost centre', 'hris_employee_reference' => 'HRIS employee reference', 'priority' => 'Priority', 'normal' => 'Normal', 'urgent' => 'Urgent', 'business_justification' => 'Business justification',
    'itinerary' => 'Itinerary', 'itinerary_description' => 'All segments must fall within the request travel dates.', 'add_segment' => 'Add segment', 'segment' => 'Segment', 'remove' => 'Remove', 'origin' => 'Origin', 'departs_at' => 'Departs at', 'arrives_at' => 'Arrives at', 'transport_mode' => 'Transport mode', 'carrier' => 'Carrier', 'segment_estimated_cost' => 'Segment estimated cost', 'save_draft_request' => 'Save draft request',
    'submit_manager_review' => 'Submit for manager review', 'cancel_request' => 'Cancel request', 'approve_finance_review' => 'Approve for finance review', 'reject_manager_review' => 'Reject at manager review', 'confirm_finance_clearance' => 'Confirm finance clearance', 'reject_finance_clearance' => 'Reject finance clearance', 'actions_for' => 'Actions for', 'view_complete_request' => 'View complete request', 'complete_record_description' => 'Complete travel, itinerary, integration and decision record.', 'record_decision_for' => 'Record a reasoned decision for', 'decision_rationale' => 'Decision rationale', 'approved_cost' => 'Approved cost', 'finance_commitment_reference' => 'Finance commitment reference',
    'national' => 'National', 'hris_reference' => 'HRIS reference', 'not_linked' => 'Not linked', 'reference_checksum' => 'Reference checksum', 'finance_reference' => 'Finance reference', 'pending' => 'Pending', 'supporting_documents' => 'Supporting documents', 'separator' => '·', 'file' => 'File', 'preview' => 'Preview', 'download' => 'Download', 'no_supporting_documents' => 'No supporting documents uploaded.', 'upload_supporting_record' => 'Upload supporting record', 'document_title' => 'Document title', 'record_category' => 'Record category', 'source_type' => 'Source type', 'born_digital' => 'Born-digital file', 'scanned_copy' => 'Scanned copy', 'document' => 'Document', 'uploading' => 'Uploading',
    'route_arrow' => '→', 'range_separator' => '–', 'carrier_pending' => 'Carrier pending', 'decision_history' => 'Decision history', 'no_decisions' => 'No approval decisions recorded yet.', 'integration_status' => 'Integration status', 'integration_description' => 'HRIS and finance identifiers remain visible for reconciliation and exception handling.',
    'value_draft' => 'Draft', 'value_manager_review' => 'Manager review', 'value_finance_review' => 'Finance review', 'value_approved' => 'Approved', 'value_rejected' => 'Rejected', 'value_cancelled' => 'Cancelled', 'value_submit' => 'Submit for manager review', 'value_cancel' => 'Cancel request', 'value_manager_approve' => 'Approve for finance review', 'value_manager_reject' => 'Reject at manager review', 'value_finance_clear' => 'Confirm finance clearance', 'value_finance_reject' => 'Reject finance clearance', 'value_air' => 'Air', 'value_road' => 'Road', 'value_rail' => 'Rail', 'value_water' => 'Water', 'value_other' => 'Other', 'value_digital' => 'Born-digital', 'value_scanned' => 'Scanned', 'value_clean' => 'Clean', 'value_pending_scan' => 'Pending scan', 'value_pending' => 'Pending', 'value_synced' => 'Synchronized', 'value_exception' => 'Exception',
    'legacy_unpinned' => 'Legacy unpinned',
    'outcomes' => ['created' => 'Travel request :reference created.', 'lifecycle_updated' => 'Travel clearance lifecycle updated.'],
    'errors' => ['itineraries_array' => 'Itineraries must be an array.', 'itinerary_object' => 'Every itinerary must be an object.'],
    'notifications' => [
        'updated_title' => 'Travel clearance updated', 'overdue_title' => 'Travel clearance overdue', 'due_soon_title' => 'Travel clearance due soon',
        'reminder_message' => ':reference: :purpose', 'status_manager_review' => ':reference is now under manager review.', 'status_finance_review' => ':reference is now under finance review.', 'status_approved' => ':reference is now approved.', 'status_rejected' => ':reference is now rejected.', 'status_cancelled' => ':reference is now cancelled.',
    ],
    'audit' => ['created' => 'Travel request :reference created.', 'transitioned' => 'Travel request :reference transitioned to :status.', 'overdue_escalated' => 'Overdue travel-clearance decision escalated.', 'reminder_sent' => 'Upcoming travel-clearance deadline reminder sent.'],
    'command' => ['reminders_sent' => 'Sent :count travel-clearance reminder(s).'],
];
