<?php

return [
    'head_title' => 'Rôles et autorisations', 'eyebrow' => 'Gouvernance des identités et des accès', 'title' => 'Rôles et autorisations', 'description' => 'Gérez l’héritage des rôles et les autorisations directes exceptionnelles depuis un plan de contrôle audité fondé sur le moindre privilège.',
    'programme_roles' => 'Rôles du programme', 'permission_definitions' => 'Définitions des autorisations', 'users_in_register' => 'Utilisateurs du registre', 'role_matrix' => 'Matrice des autorisations par rôle', 'role_matrix_description' => 'Les autorisations du rôle sont héritées par chaque utilisateur qui lui est affecté. Les modifications sont auditées.', 'users' => 'utilisateurs', 'separator' => '·', 'permissions' => 'Autorisations', 'edit' => 'Modifier', 'no_inherited_permissions' => 'Aucune autorisation héritée',
    'direct_exceptions' => 'Exceptions d’autorisation directe', 'direct_exceptions_description' => 'Les attributions directes sont des exceptions explicites superposées au rôle. Utilisez-les avec parcimonie et consignez un motif.', 'search_placeholder' => 'Rechercher par nom ou adresse électronique', 'search_users' => 'Rechercher des utilisateurs', 'number' => 'N°', 'user' => 'Utilisateur', 'role' => 'Rôle', 'inherited' => 'Héritées', 'direct' => 'Directes', 'effective' => 'Effectives', 'actions' => 'Actions', 'actions_for' => 'Actions pour', 'manage_direct_permissions' => 'Gérer les autorisations directes', 'no_users' => 'Aucun utilisateur trouvé', 'no_users_description' => 'Aucun utilisateur autorisé ne correspond à la recherche active.', 'showing' => 'Affichage', 'range_separator' => '–', 'of' => 'sur',
    'edit_role' => 'Modifier le rôle', 'role_sheet_description' => 'Sélectionnez l’ensemble complet des autorisations héritées pour ce rôle.', 'direct_permissions' => 'Autorisations directes', 'user_sheet_description' => 'Sélectionnez uniquement les autorisations exceptionnelles. Les autorisations héritées du rôle restent inchangées.', 'inherited_by_role' => 'héritée du rôle', 'business_reason' => 'Motif professionnel', 'reason_placeholder' => 'Consignez le motif opérationnel approuvé de cette modification d’accès.', 'save_changes' => 'Enregistrer les modifications',
    'grant_programme_access' => 'Accorder l’accès au programme', 'grant_programme_access_description' => 'Créez une identité approuvée par un administrateur et envoyez les instructions de configuration du mot de passe.',
    'grant_access' => 'Accorder l’accès', 'name' => 'Nom', 'official_email' => 'Adresse e-mail officielle', 'programme_role' => 'Rôle du programme',
    'home_county' => 'Comté de rattachement', 'assigned_county_portfolio' => 'Portefeuille de comtés attribué', 'current_user' => 'Utilisateur actuel', 'deactivate' => 'Désactiver',
    'errors' => ['self_deactivation' => 'Vous ne pouvez pas désactiver votre propre compte.'], 'audit' => ['access_deactivated' => 'Accès au programme désactivé pour :email.'],
];
