<?php

return [
    'head_title' => 'Configuration des évaluations', 'eyebrow' => 'Évaluation de la performance de la dévolution', 'title' => 'Fiches de notation et cycles d’évaluation', 'description' => 'Gérez des fiches numériques reproductibles couvrant les quatorze fonctions dévolues, les thèmes facilitateurs, les normes, les critères, les règles MCDA et les exigences de preuve.',
    'exceeds_standard' => 'Dépasse la norme', 'meets_standard' => 'Satisfait à la norme', 'needs_improvement' => 'À améliorer', 'function_assessment_description' => 'Évaluation de la capacité, de la productivité et de la prestation de services pour :name.', 'function_theme_description' => 'Facteurs de gouvernance, de capacité, de productivité et de résultats.', 'standard_description' => 'Mesure la conformité, la mise en œuvre et les résultats démontrés.', 'criterion_description' => 'Les preuves doivent démontrer à la fois la conformité institutionnelle et un résultat attribuable.', 'evidence_requirement_description' => 'Politique, plan, rapport, registre, preuve d’audit signés ou document primaire équivalent.',
    'new_scorecard' => 'Nouvelle fiche de notation', 'new_scorecard_description' => 'Créez une définition stable dont les versions publiées deviennent immuables.', 'create_scorecard' => 'Créer la fiche', 'code' => 'Code', 'name' => 'Nom', 'description_label' => 'Description',
    'new_cycle' => 'Nouveau cycle d’évaluation', 'new_cycle_description' => 'Rattachez une période de rapport à une version publiée et immuable de la fiche.', 'create_cycle' => 'Créer le cycle', 'publish_before_cycle' => 'Publiez une version de fiche avant de créer un cycle.', 'released_scorecard' => 'Fiche publiée', 'period_start' => 'Début de période', 'period_end' => 'Fin de période', 'submission_opens' => 'Ouverture des soumissions', 'submission_closes' => 'Clôture des soumissions',
    'valid_json_error' => 'La configuration de la fiche doit être un JSON valide.', 'compose_version_title' => 'Composer la prochaine version', 'compose_version_description' => 'Créez un brouillon gouverné à partir de la configuration complète avant examen et publication.', 'compose_version' => 'Composer une version', 'baseline_notice' => 'La base contient les quatorze fonctions dévolues. Remplacez les normes, critères, pondérations et règles de preuve provisoires par du contenu approuvé avant publication.', 'scorecard_json' => 'JSON de la version de fiche', 'save_draft_version' => 'Enregistrer le brouillon',
    'pagination' => 'pagination', 'page' => 'Page', 'of' => 'sur', 'separator' => '·', 'total' => 'au total', 'previous' => 'Précédent', 'next' => 'Suivant', 'search_scorecards' => 'Rechercher les fiches', 'search' => 'Rechercher', 'no_description' => 'Aucune description', 'version_prefix' => 'v', 'functions' => 'fonctions', 'publish' => 'Publier', 'scorecards' => 'Fiches de notation',
    'assessment_cycles' => 'Cycles d’évaluation', 'assessment_cycles_description' => 'Périodes de rapport rattachées à des versions de fiche immuables.', 'to' => 'au', 'no_scorecard' => 'Aucune fiche',
    'value_active' => 'Active', 'value_inactive' => 'Inactive', 'value_draft' => 'Brouillon', 'value_published' => 'Publiée', 'value_retired' => 'Retirée', 'value_planned' => 'Planifié', 'value_open' => 'Ouvert', 'value_closed' => 'Fermé',
    'errors' => ['draft_only' => 'Seules les versions provisoires des fiches de notation peuvent être publiées.', 'fourteen_functions' => 'Les fiches publiées doivent contenir exactement les quatorze fonctions dévolues.', 'mandatory_evidence' => 'Les critères obligatoires de :standard nécessitent au moins une exigence de preuve obligatoire.', 'weight_total' => 'Les pondérations de :scope doivent totaliser 100 ; le total configuré est :weight.'],
    'pagination_label' => 'Pagination de :label',
];
