<?php

return [
    'assessments' => 'Évaluations', 'governed_county_assessment' => 'Évaluation gouvernée du comté', 'separator' => '·', 'to' => 'au',
    'percent_complete' => '% terminé', 'computed_score' => 'Score calculé', 'reference_data_lineage' => 'Traçabilité des données de référence',
    'created_by' => 'Créé par', 'open_findings' => 'Constats ouverts', 'appeals' => 'Recours', 'calculate_verified_result' => 'Calculer le résultat vérifié',
    'publish_immutable_result' => 'Publier le résultat immuable', 'attestor_title' => "Titre de l'attestateur", 'attestation_statement' => "Déclaration d'attestation",
    'attest_submission' => 'Attester la soumission', 'percent_total_score_weight' => '% de pondération totale', 'governance_record' => 'Dossier de gouvernance',
    'governance_record_description' => "Attestations, constats et recours conservés avec l'évaluation.", 'attestations' => 'Attestations', 'findings' => 'Constats',
    'published_result_county_benchmark' => 'Résultat publié et référence du comté', 'immutable_checksum' => 'Somme de contrôle immuable', 'colon' => ':',
    'rank' => 'Rang', 'county' => 'Comté', 'score' => 'Score', 'band' => 'Bande', 'percentile' => 'Centile', 'response' => 'réponse',
    'respond' => 'Répondre', 'resolve' => 'Résoudre', 'appeal_adjudication' => 'Décision du recours', 'decision' => 'Décision', 'reject' => 'Rejeter',
    'uphold' => 'Accueillir', 'partially_uphold' => 'Accueillir partiellement', 'record_decision' => 'Enregistrer la décision', 'weight' => 'Pondération',
    'percent' => '%', 'maximum' => 'maximum', 'slash' => '/', 'verified' => 'vérifié', 'submitted' => 'Soumis', 'override' => 'dérogation',
    'weighted' => 'pondéré', 'submit' => 'Soumettre', 'verify' => 'Vérifier',
    'initiate_county_assessment' => 'Lancer l’évaluation du comté', 'initiate_county_assessment_description' => 'Créez une évaluation gouvernée pour un comté et un cycle publié. La grille de notation et le catalogue de référence en vigueur sont automatiquement figés.',
    'initiate_assessment' => 'Lancer l’évaluation', 'initiating_assessment' => 'Lancement de l’évaluation…', 'no_available_assessment_cycle' => 'Aucun comté autorisé et aucun cycle publié planifié ou ouvert ne sont disponibles.',
    'assessment_cycle' => 'Cycle d’évaluation', 'county_option' => ':county · Comté :code', 'assessment_creation_lineage' => 'Le comté, le cycle, l’empreinte de la grille publiée, la version du catalogue en vigueur, le créateur et l’événement d’audit sont conservés comme filiation de création.',
    'submit_assessment' => 'Soumettre', 'start_review' => 'Commencer l’examen', 'assessment_score' => 'Score de l’évaluation', 'record_legacy_score' => 'Consigner le score historique', 'approve_assessment' => 'Approuver', 'no_action' => 'Aucune action', 'open_criteria' => 'Ouvrir les critères',
    'statuses' => ['draft' => 'brouillon', 'evidence_collection' => 'collecte des preuves', 'submitted' => 'soumise', 'under_assessment' => 'en cours d’évaluation', 'assessed' => 'évaluée', 'approved' => 'approuvée', 'published' => 'publiée'],
    'outcomes' => ['assessment_initiated' => 'L’évaluation du comté a été lancée avec la filiation gouvernée du catalogue et de la grille de notation.', 'legacy_score_recorded' => 'Le score de l’évaluation historique a été consigné.', 'criterion_score_submitted' => 'Le score du critère a été soumis.', 'corrective_plan_submitted' => 'Le plan correctif a été soumis à un examen indépendant.', 'assessment_transitioned' => 'L’évaluation est passée au statut :status.'],
    'conflicts' => ['governed_score_calculation_required' => 'Les évaluations gouvernées doivent être calculées à partir des résultats de critères vérifiés.', 'assessment_not_under_review' => 'Seule une évaluation en cours d’examen peut être notée.', 'approval_readiness_required' => 'Une évaluation calculée, complète et attestée est requise pour l’approbation.', 'unresolved_findings' => 'Résolvez tous les constats avant l’approbation.', 'invalid_transition' => 'Cette évaluation n’est pas dans un état valide pour cette action.'],
    'audit' => ['assessment_transitioned' => 'L’évaluation est passée au statut :status.'],
    'notifications' => ['workflow_updated_title' => 'Flux d’évaluation mis à jour', 'workflow_updated_message' => 'L’évaluation :cycle de :county est passée à l’étape suivante de son flux gouverné.'],
    'corrective' => [
        'errors' => [
            'published_result_required' => 'Les plans correctifs nécessitent un résultat d’évaluation publié et immuable.', 'single_source_required' => 'Sélectionnez exactement un constat résolu ou un recours accepté.', 'finding_ineligible' => 'Seuls les constats majeurs ou critiques résolus peuvent lancer un suivi correctif.', 'appeal_ineligible' => 'Seuls les recours acceptés peuvent lancer un suivi correctif.', 'action_due_after_plan' => 'Une action ne peut pas arriver à échéance après le plan correctif.', 'independent_plan_reviewer' => 'L’auteur du plan ne peut pas l’examiner de manière indépendante.', 'plan_not_reviewable' => 'Seul un plan soumis ou retourné peut être examiné.', 'active_plan_required' => 'La progression ne peut être soumise que pour un plan correctif actif.', 'evidence_scope_mismatch' => 'La preuve corrective doit appartenir à la même évaluation et au même comté.', 'governed_evidence_required' => 'La progression corrective nécessite une preuve propre, vérifiée et conservée.', 'progress_monotonic' => 'La progression doit augmenter et ne peut pas dépasser 100 %.', 'pending_update_first' => 'Vérifiez ou rejetez d’abord la mise à jour de progression en attente.', 'independent_progress_verifier' => 'La preuve de progression doit être vérifiée de manière indépendante.', 'update_already_decided' => 'Cette mise à jour de progression a déjà fait l’objet d’une décision.', 'active_closure_required' => 'Seul un plan correctif actif peut demander sa clôture.', 'verified_completion_required' => 'Toutes les actions correctives nécessitent une preuve d’achèvement vérifiée indépendamment.', 'independent_closer' => 'La clôture corrective exige un décideur indépendant de l’auteur et de l’examinateur du plan.', 'closure_not_requested' => 'La clôture de ce plan n’a pas été demandée.',
        ],
        'decisions' => ['verified' => 'vérifiée', 'rejected' => 'rejetée'],
        'audit' => ['plan_submitted' => 'Plan correctif :reference soumis.', 'plan_reviewed' => 'Examen du plan correctif :reference enregistré.', 'progress_submitted' => 'Progression corrective soumise pour :code.', 'progress_decided' => 'Progression corrective :decision.', 'closure_requested' => 'Clôture demandée pour le plan correctif :reference.', 'closure_decided' => 'Décision de clôture du plan correctif :reference enregistrée.'],
    ],
];
