<?php

return [
    'assessments' => 'Évaluations', 'governed_county_assessment' => 'Évaluation gouvernée du comté', 'separator' => '·', 'to' => 'au',
    'percent_complete' => '% terminé', 'computed_score' => 'Score calculé', 'reference_data_lineage' => 'Traçabilité des données de référence',
    'created_by' => 'Créé par', 'open_findings' => 'Constats ouverts', 'appeals' => 'Recours', 'calculate_verified_result' => 'Calculer le résultat vérifié',
    'publish_immutable_result' => 'Publier le résultat immuable', 'attestor_title' => "Titre de l'attestateur", 'attestation_statement' => "Déclaration d'attestation",
    'attest_submission' => 'Attester la soumission', 'percent_total_score_weight' => '% de pondération totale', 'governance_record' => 'Dossier de gouvernance',
    'governance_record_description' => "Attestations, constats et recours conservés avec l'évaluation.", 'attestations' => 'Attestations', 'findings' => 'Constats',
    'published_result_county_benchmark' => 'Résultat publié et référence du comté', 'immutable_checksum' => 'Somme de contrôle immuable', 'colon' => ':',
    'rank' => 'Rang', 'county' => 'Comté', 'score' => 'Score', 'band' => 'Bande', 'percentile' => 'Centile', 'response' => 'réponse',
    'respond' => 'Répondre', 'resolve' => 'Résoudre', 'appeal_adjudication' => 'Décision du recours', 'decision' => 'Décision', 'reject' => 'Rejeter',
    'uphold' => 'Accueillir', 'partially_uphold' => 'Accueillir partiellement', 'record_decision' => 'Enregistrer la décision', 'weight' => 'Pondération',
    'percent' => '%', 'maximum' => 'maximum', 'slash' => '/', 'verified' => 'vérifié', 'submitted' => 'Soumis', 'override' => 'dérogation',
    'weighted' => 'pondéré', 'submit' => 'Soumettre', 'verify' => 'Vérifier', 'score_for' => 'Score pour :criterion', 'scoring_rationale_for' => 'Justification du score pour :criterion', 'verified_score_for' => 'Score vérifié pour :criterion', 'verification_rationale_for' => 'Justification de la vérification pour :criterion', 'evidence_based_rationale' => 'Justification fondée sur les preuves', 'independent_verification_rationale' => 'Justification de la vérification indépendante', 'questionnaire_progress' => ':complete réponses requises sur :total', 'draft_autosaved' => 'Les réponses provisoires sont enregistrées automatiquement sur cet appareil.', 'mandatory_evidence_ready' => 'Les preuves vérifiées obligatoires sont complètes.', 'mandatory_evidence_required' => 'Des preuves vérifiées obligatoires sont encore requises.',
    'initiate_county_assessment' => 'Lancer l’évaluation du comté', 'initiate_county_assessment_description' => 'Créez une évaluation gouvernée pour un comté et un cycle publié. La grille de notation et le catalogue de référence en vigueur sont automatiquement figés.',
    'initiate_assessment' => 'Lancer l’évaluation', 'initiating_assessment' => 'Lancement de l’évaluation…', 'no_available_assessment_cycle' => 'Aucun comté autorisé et aucun cycle publié planifié ou ouvert ne sont disponibles.',
    'assessment_cycle' => 'Cycle d’évaluation', 'county_option' => ':county · Comté :code', 'assessment_creation_lineage' => 'Le comté, le cycle, l’empreinte de la grille publiée, la version du catalogue en vigueur, le créateur et l’événement d’audit sont conservés comme filiation de création.',
    'submit_assessment' => 'Soumettre', 'start_review' => 'Commencer l’examen', 'assessment_score' => 'Score de l’évaluation', 'record_legacy_score' => 'Consigner le score historique', 'approve_assessment' => 'Approuver', 'no_action' => 'Aucune action', 'open_criteria' => 'Ouvrir les critères',
    'statuses' => ['draft' => 'brouillon', 'evidence_collection' => 'collecte des preuves', 'submitted' => 'soumise', 'under_assessment' => 'en cours d’évaluation', 'assessed' => 'évaluée', 'approved' => 'approuvée', 'published' => 'publiée'],
    'outcomes' => ['assessment_initiated' => 'L’évaluation du comté a été lancée avec la filiation gouvernée du catalogue et de la grille de notation.', 'legacy_score_recorded' => 'Le score de l’évaluation historique a été consigné.', 'criterion_score_submitted' => 'Le score du critère a été soumis.', 'corrective_plan_submitted' => 'Le plan correctif a été soumis à un examen indépendant.', 'assessment_transitioned' => 'L’évaluation est passée au statut :status.'],
    'conflicts' => ['governed_score_calculation_required' => 'Les évaluations gouvernées doivent être calculées à partir des résultats de critères vérifiés.', 'assessment_not_under_review' => 'Seule une évaluation en cours d’examen peut être notée.', 'approval_readiness_required' => 'Une évaluation calculée, complète et attestée est requise pour l’approbation.', 'unresolved_findings' => 'Résolvez tous les constats avant l’approbation.', 'invalid_transition' => 'Cette évaluation n’est pas dans un état valide pour cette action.'],
    'errors' => ['cycle_not_open' => 'Les évaluations ne peuvent être lancées que pour des cycles planifiés ou ouverts.', 'cycle_scorecard_required' => 'Le cycle d’évaluation doit figer une version publiée de la fiche de notation.', 'scorecard_not_released' => 'La fiche de notation du cycle d’évaluation n’a pas été publiée.', 'scorecard_checksum' => 'La fiche de notation du cycle d’évaluation ne possède pas d’empreinte d’intégrité valide.', 'duplicate_county_cycle' => 'Une évaluation existe déjà pour ce comté et ce cycle.', 'calculation_scorecard_required' => 'Une version gouvernée de la fiche de notation est requise avant le calcul.', 'criterion_verified_score' => 'Le critère :criterion nécessite un score vérifié.', 'mandatory_evidence_completeness' => 'Les preuves obligatoires sont complètes à :percentage %.', 'override_verified_only' => 'Seul un score vérifié indépendamment peut être remplacé.', 'override_range' => 'Le score doit être compris entre 0 et :maximum.', 'override_reason' => 'Une justification substantielle d’au moins 20 caractères est requise.', 'publication_approved_only' => 'Seule une évaluation gouvernée notée et approuvée peut être publiée.', 'publication_evidence_attestation' => 'Des preuves vérifiées complètes et une attestation active du comté sont requises.', 'publication_findings' => 'Tous les constats doivent être résolus avant la publication.', 'publication_appeals' => 'Tous les recours doivent être tranchés avant la publication.', 'publication_reproducible_results' => 'Chaque critère doit disposer d’un résultat calculé reproductible.', 'evidence_store_failed' => 'Le fichier de preuve n’a pas pu être conservé.', 'evidence_criterion_mismatch' => 'L’exigence de preuve n’appartient pas au critère sélectionné.', 'evidence_scorecard_mismatch' => 'L’exigence de preuve ne fait pas partie de la fiche de cette évaluation.', 'evidence_category' => 'La catégorie de preuve n’est pas acceptée pour cette exigence.', 'evidence_mime' => 'Le type du fichier de preuve n’est pas accepté pour cette exigence.'],
    'audit' => ['assessment_transitioned' => 'L’évaluation est passée au statut :status.', 'assessment_created' => 'Évaluation :cycle lancée pour le comté de :county.', 'score_calculated' => 'Score de l’évaluation calculé à partir de la fiche publiée.', 'criterion_overridden' => 'Score du critère :criterion remplacé.', 'result_published' => 'Résultat de l’évaluation publié sous forme d’instantané immuable.', 'evidence_uploaded' => 'Preuve téléversée : :title.'],
    'notifications' => ['workflow_updated_title' => 'Flux d’évaluation mis à jour', 'workflow_updated_message' => 'L’évaluation :cycle de :county est passée à l’étape suivante de son flux gouverné.', 'evidence_uploaded_title' => 'Nouvelle preuve téléversée', 'evidence_uploaded_message' => ':title a été ajouté à l’évaluation :cycle de :county.'],
    'corrective' => [
        'errors' => [
            'published_result_required' => 'Les plans correctifs nécessitent un résultat d’évaluation publié et immuable.', 'single_source_required' => 'Sélectionnez exactement un constat résolu ou un recours accepté.', 'finding_ineligible' => 'Seuls les constats majeurs ou critiques résolus peuvent lancer un suivi correctif.', 'appeal_ineligible' => 'Seuls les recours acceptés peuvent lancer un suivi correctif.', 'action_due_after_plan' => 'Une action ne peut pas arriver à échéance après le plan correctif.', 'independent_plan_reviewer' => 'L’auteur du plan ne peut pas l’examiner de manière indépendante.', 'plan_not_reviewable' => 'Seul un plan soumis ou retourné peut être examiné.', 'active_plan_required' => 'La progression ne peut être soumise que pour un plan correctif actif.', 'evidence_scope_mismatch' => 'La preuve corrective doit appartenir à la même évaluation et au même comté.', 'governed_evidence_required' => 'La progression corrective nécessite une preuve propre, vérifiée et conservée.', 'progress_monotonic' => 'La progression doit augmenter et ne peut pas dépasser 100 %.', 'pending_update_first' => 'Vérifiez ou rejetez d’abord la mise à jour de progression en attente.', 'independent_progress_verifier' => 'La preuve de progression doit être vérifiée de manière indépendante.', 'update_already_decided' => 'Cette mise à jour de progression a déjà fait l’objet d’une décision.', 'active_closure_required' => 'Seul un plan correctif actif peut demander sa clôture.', 'verified_completion_required' => 'Toutes les actions correctives nécessitent une preuve d’achèvement vérifiée indépendamment.', 'independent_closer' => 'La clôture corrective exige un décideur indépendant de l’auteur et de l’examinateur du plan.', 'closure_not_requested' => 'La clôture de ce plan n’a pas été demandée.',
        ],
        'decisions' => ['verified' => 'vérifiée', 'rejected' => 'rejetée'],
        'audit' => ['plan_submitted' => 'Plan correctif :reference soumis.', 'plan_reviewed' => 'Examen du plan correctif :reference enregistré.', 'progress_submitted' => 'Progression corrective soumise pour :code.', 'progress_decided' => 'Progression corrective :decision.', 'closure_requested' => 'Clôture demandée pour le plan correctif :reference.', 'closure_decided' => 'Décision de clôture du plan correctif :reference enregistrée.'],
    ],
];
