<?php

return [
    'page_title' => 'Comté de :county', 'all_counties' => 'Tous les comtés', 'county_code_region' => 'Comté :code · :region', 'description' => 'Dossier complet d’évaluation, de preuves, de vérification et de trésorerie dans votre périmètre autorisé.', 'official_website' => 'Site officiel', 'county_record' => 'Dossier du comté', 'county_summary' => 'Résumé du comté',
    'assessment_cycles' => 'Cycles d’évaluation', 'evidence_documents' => 'Documents de preuve', 'verified_evidence' => 'Preuves vérifiées', 'grant_disbursement' => 'Décaissement des subventions', 'of_amount' => 'sur :amount',
    'administrative_hierarchy' => 'Hiérarchie administrative', 'administrative_hierarchy_description' => 'Structure gouvernée des sous-comtés et quartiers conservée avec la filiation de la source.', 'sub_counties' => 'Sous-comtés', 'wards' => 'Quartiers', 'registered_voters' => 'Électeurs inscrits (2022)', 'ward_count' => ':count quartiers', 'source_lineage' => 'Source : :authority · effective :date', 'no_administrative_units' => 'Aucune hiérarchie administrative disponible', 'no_administrative_units_description' => 'Importez et approuvez le registre gouverné des sous-comtés et quartiers pour ce comté.',
    'assessment_history' => 'Historique des évaluations', 'document_management' => 'Gestion documentaire', 'exchequer_grants' => 'Trésorerie et subventions', 'matching_records' => ':count dossiers correspondants', 'no_matching_county_records' => 'Aucun dossier de comté correspondant', 'no_matching_county_records_description' => 'Ajustez la recherche ou la période. Les dossiers restent limités à ce comté et à votre accès attribué.',
    'column_cycle' => 'Cycle', 'column_status' => 'Statut', 'column_score' => 'Note', 'column_evidence' => 'Preuves', 'column_assessor' => 'Évaluateur', 'column_document' => 'Document', 'column_category' => 'Catégorie', 'column_verification' => 'Vérification', 'column_uploaded_by' => 'Téléversé par', 'column_programme' => 'Programme', 'column_financial_year' => 'Exercice financier', 'column_allocated' => 'Alloué (KES)', 'column_disbursed' => 'Décaissé (KES)',
    'unassigned' => 'Non attribué', 'system_migration' => 'Migration système', 'scanned_copy' => 'Copie numérisée', 'digital_file' => 'Fichier numérique', 'empty_value' => '—', 'separator' => '·', 'label_separator' => ':',
];
