<?php

return [
    'overview' => 'Vue d’ensemble', 'assessment_cycles' => 'Cycles d’évaluation', 'action_queue' => 'File d’actions', 'funds_evidence' => 'Fonds et preuves',
    'dashboard_title' => 'Tableau de bord — :role', 'portfolio_statistics' => 'Statistiques du portefeuille', 'require_attention' => ':count nécessitent une attention', 'no_active_exceptions' => 'Aucune exception active', 'open_county_record_label' => 'Ouvrir le dossier du comté de :county',
    'operational_control' => 'Position de contrôle opérationnel', 'operational_control_description' => 'Exceptions intermodules dans votre périmètre autorisé.', 'role_brief' => 'Synthèse opérationnelle du rôle', 'priority_decisions_for_role' => 'Décisions prioritaires pour :role.', 'full_stop' => '.', 'active_projects_visible' => 'projets actifs sont actuellement visibles dans ce périmètre.',
    'county_coverage' => 'Couverture des comtés', 'kenya_assessment_map' => 'Carte d’évaluation du Kenya', 'county_detail' => 'Détail du comté', 'open_county_record' => 'Ouvrir la fiche complète du comté', 'county_intervention_queue' => 'File d’intervention des comtés', 'county_intervention_description' => 'Classée à partir des fiches filtrées et autorisées ; sélectionnez un comté pour consulter son dossier complet de preuves et de mise en œuvre.',
    'score' => 'Score', 'funding_gap' => 'Écart de financement', 'no_county_flags' => 'Aucun signal d’intervention', 'no_county_flags_description' => 'Aucune évaluation incomplète, preuve manquante, note faible ou insuffisance de décaissement dans ce périmètre.', 'exception_register' => 'Registre des exceptions', 'exception_register_description' => 'Charge intermodules nécessitant un suivi responsable.',
    'performance_across_cycles' => 'Performance entre les cycles', 'performance_across_cycles_description' => 'Score vérifié moyen et achèvement des comtés pour le portefeuille autorisé.', 'county_completion' => 'Achèvement des comtés', 'average_score' => 'Score moyen', 'evidence' => 'Preuves', 'no_assessment_cycles' => 'Aucun cycle d’évaluation', 'no_assessment_cycles_description' => 'Les analyses apparaîtront après la configuration d’un cycle d’évaluation.',
    'grant_allocation_disbursement' => 'Allocation et décaissement des subventions', 'grant_chart_description' => 'Principaux comtés par valeur allouée dans le portefeuille filtré.', 'evidence_coverage' => 'Couverture des preuves', 'evidence_coverage_description' => 'Comtés disposant des plus grandes collections documentaires sur la période sélectionnée.',
    'cycle_completion' => 'Achèvement du cycle', 'allocated' => 'Alloué', 'disbursed' => 'Décaissé', 'evidence_documents' => 'Documents de preuve', 'assessment_incomplete' => 'Évaluation incomplète', 'no_evidence_indexed' => 'Aucune preuve indexée', 'score_below_threshold' => 'Score inférieur à 60 %', 'undisbursed_allocation' => 'Allocation non décaissée',
    'evidence_awaiting_review' => 'Preuves en attente d’examen', 'evidence_awaiting_review_detail' => 'Fiches actives sans décision de vérification', 'evidence_scan_attention' => 'Analyse des preuves à traiter', 'evidence_scan_attention_detail' => 'Résultats en attente, échoués ou mis en quarantaine', 'overdue_citizen_cases' => 'Dossiers citoyens en retard', 'overdue_citizen_cases_detail' => 'Dossiers non résolus après leur échéance', 'delayed_exchequer_requests' => 'Demandes de trésorerie retardées', 'delayed_exchequer_requests_detail' => 'Demandes ouvertes au-delà du SLA de l’étape actuelle', 'overdue_evaluation_findings' => 'Constats d’évaluation en retard', 'overdue_evaluation_findings_detail' => 'Recommandations échues et non closes', 'open_partner_alerts' => 'Alertes partenaires ouvertes', 'open_partner_alerts_detail' => 'Exceptions d’accord ou de contribution non résolues',
    'counties_in_view' => 'Comtés visibles', 'assessed' => 'évalués', 'pending' => 'en attente', 'completed_assessments_detail' => 'Sur les évaluations achevées', 'selected_period_detail' => 'Dans la période sélectionnée', 'grant_disbursement' => 'Décaissement des subventions', 'disbursed_lower' => 'décaissé', 'separator' => '·', 'range_separator' => '–', 'slash' => '/', 'percent' => '%',
    'profiles' => [
        'county-official' => ['role_label' => 'Agent du comté', 'eyebrow' => 'Espace de travail du comté', 'title' => 'Préparation des preuves et de l’évaluation', 'description' => 'Préparez les preuves du comté, suivez leur exhaustivité et consultez le dernier résultat d’évaluation.', 'focus' => ['first' => 'Compléter les preuves manquantes', 'second' => 'Répondre aux dossiers de service du comté', 'third' => 'Suivre les mesures correctives']],
        'county-admin' => ['role_label' => 'Administrateur du comté', 'eyebrow' => 'Administration du comté', 'title' => 'Pilotage de la performance du comté', 'description' => 'Coordonnez les agents, la collecte des preuves, les soumissions, les subventions et la préparation du comté.', 'focus' => ['first' => 'Lever les blocages de soumission', 'second' => 'Coordonner les responsables de la mise en œuvre', 'third' => 'Faire remonter les obligations en retard']],
        'assessor' => ['role_label' => 'Évaluateur indépendant', 'eyebrow' => 'Vérification indépendante', 'title' => 'Évaluations des comtés attribués', 'description' => 'Examinez les preuves et l’avancement des évaluations uniquement pour les comtés qui vous sont attribués.', 'focus' => ['first' => 'Prioriser les évaluations soumises', 'second' => 'Résorber les files d’examen des preuves', 'third' => 'Consigner les constatations indépendantes']],
        'development-partner' => ['role_label' => 'Partenaire de développement', 'eyebrow' => 'Portefeuille du partenaire', 'title' => 'Résultats des programmes et subventions', 'description' => 'Suivez les résultats d’évaluation, les preuves et l’exécution des subventions dans votre portefeuille.', 'focus' => ['first' => 'Examiner l’absorption des subventions', 'second' => 'Résoudre les alertes de mise en œuvre des partenaires', 'third' => 'Valider les résultats des programmes']],
        'top-management' => ['role_label' => 'Haute direction', 'eyebrow' => 'Supervision exécutive', 'title' => 'Vue d’ensemble de la performance des comtés', 'description' => 'Suivez les comtés de votre portefeuille de supervision et concentrez l’attention sur les retards de mise en œuvre.', 'focus' => ['first' => 'Intervenir sur les engagements en retard', 'second' => 'Examiner les comtés moins performants', 'third' => 'Autoriser les décisions en attente']],
        'devolution-admin' => ['role_label' => 'Administrateur de la dévolution', 'eyebrow' => 'Coordination nationale', 'title' => 'Pilotage de la mise en œuvre dans tous les comtés', 'description' => 'Coordonnez les cycles d’évaluation, la préparation des preuves, les subventions et la performance dans les 47 comtés.', 'focus' => ['first' => 'Faire progresser l’achèvement du cycle national', 'second' => 'Résoudre les blocages intercomtés', 'third' => 'Protéger l’intégrité des preuves et des rapports']],
        'platform-admin' => ['role_label' => 'Administrateur de la plateforme', 'eyebrow' => 'Opérations de la plateforme', 'title' => 'Pilotage de la plateforme nationale', 'description' => 'Suivez la couverture de la plateforme et administrez les accès gouvernés au service national.', 'focus' => ['first' => 'Maintenir l’opérabilité du service', 'second' => 'Gouverner les accès et les intégrations', 'third' => 'Examiner les exceptions d’assurance']],
    ],
];
