<?php

return [
    'overview' => 'Vue d’ensemble', 'assessment_cycles' => 'Cycles d’évaluation', 'action_queue' => 'File d’actions', 'funds_evidence' => 'Fonds et preuves',
    'operational_control' => 'Position de contrôle opérationnel', 'operational_control_description' => 'Exceptions intermodules dans votre périmètre autorisé.', 'role_brief' => 'Synthèse opérationnelle du rôle', 'priority_decisions_for' => 'Décisions prioritaires pour', 'full_stop' => '.', 'active_projects_visible' => 'projets actifs sont actuellement visibles dans ce périmètre.',
    'county_coverage' => 'Couverture des comtés', 'kenya_assessment_map' => 'Carte d’évaluation du Kenya', 'county_detail' => 'Détail du comté', 'open_county_record' => 'Ouvrir la fiche complète du comté', 'county_intervention_queue' => 'File d’intervention des comtés', 'county_intervention_description' => 'Classée à partir des fiches filtrées et autorisées ; sélectionnez un comté pour consulter son dossier complet de preuves et de mise en œuvre.',
    'score' => 'Score', 'funding_gap' => 'Écart de financement', 'no_county_flags' => 'Aucun signal d’intervention', 'no_county_flags_description' => 'Aucune évaluation incomplète, preuve manquante, note faible ou insuffisance de décaissement dans ce périmètre.', 'exception_register' => 'Registre des exceptions', 'exception_register_description' => 'Charge intermodules nécessitant un suivi responsable.',
    'performance_across_cycles' => 'Performance entre les cycles', 'performance_across_cycles_description' => 'Score vérifié moyen et achèvement des comtés pour le portefeuille autorisé.', 'county_completion' => 'Achèvement des comtés', 'average_score' => 'Score moyen', 'evidence' => 'Preuves', 'no_assessment_cycles' => 'Aucun cycle d’évaluation', 'no_assessment_cycles_description' => 'Les analyses apparaîtront après la configuration d’un cycle d’évaluation.',
    'grant_allocation_disbursement' => 'Allocation et décaissement des subventions', 'grant_chart_description' => 'Principaux comtés par valeur allouée dans le portefeuille filtré.', 'evidence_coverage' => 'Couverture des preuves', 'evidence_coverage_description' => 'Comtés disposant des plus grandes collections documentaires sur la période sélectionnée.',
    'cycle_completion' => 'Achèvement du cycle', 'allocated' => 'Alloué', 'disbursed' => 'Décaissé', 'evidence_documents' => 'Documents de preuve', 'assessment_incomplete' => 'Évaluation incomplète', 'no_evidence_indexed' => 'Aucune preuve indexée', 'score_below_threshold' => 'Score inférieur à 60 %', 'undisbursed_allocation' => 'Allocation non décaissée',
    'evidence_awaiting_review' => 'Preuves en attente d’examen', 'evidence_awaiting_review_detail' => 'Fiches actives sans décision de vérification', 'evidence_scan_attention' => 'Analyse des preuves à traiter', 'evidence_scan_attention_detail' => 'Résultats en attente, échoués ou mis en quarantaine', 'overdue_citizen_cases' => 'Dossiers citoyens en retard', 'overdue_citizen_cases_detail' => 'Dossiers non résolus après leur échéance', 'delayed_exchequer_requests' => 'Demandes de trésorerie retardées', 'delayed_exchequer_requests_detail' => 'Demandes ouvertes au-delà du SLA de l’étape actuelle', 'overdue_evaluation_findings' => 'Constats d’évaluation en retard', 'overdue_evaluation_findings_detail' => 'Recommandations échues et non closes', 'open_partner_alerts' => 'Alertes partenaires ouvertes', 'open_partner_alerts_detail' => 'Exceptions d’accord ou de contribution non résolues',
    'counties_in_view' => 'Comtés visibles', 'assessed' => 'évalués', 'pending' => 'en attente', 'completed_assessments_detail' => 'Sur les évaluations achevées', 'selected_period_detail' => 'Dans la période sélectionnée', 'grant_disbursement' => 'Décaissement des subventions', 'disbursed_lower' => 'décaissé', 'separator' => '·', 'range_separator' => '–', 'slash' => '/', 'percent' => '%',
];
