<?php

return [
    'registered_assets' => 'Actifs enregistrés', 'processing_activities' => 'Activités de traitement', 'retention_schedules' => 'Calendriers de conservation', 'privacy_requests' => 'Demandes relatives à la vie privée', 'breach_incidents' => 'Incidents de violation',
    'personal_data_breach_register' => 'Registre des violations de données à caractère personnel', 'no_privacy_incidents' => 'Aucun incident de confidentialité', 'no_data_assets_registered' => 'Aucun actif de données enregistré', 'processing_activity_register' => 'Registre des activités de traitement', 'no_processing_activities' => 'Aucune activité de traitement', 'no_privacy_requests' => 'Aucune demande relative à la vie privée',
    'decision' => 'Décision', 'independent_review_findings' => 'Constats de l’examen indépendant', 'workflow_transition' => 'Transition du flux de travail', 'identity_evidence_reference' => 'Référence de la preuve d’identité', 'decision_or_response' => 'Décision ou réponse', 'reason_and_legal_assessment' => 'Motif et évaluation juridique', 'response_evidence_reference' => 'Référence de la preuve de réponse',
    'register_data_asset' => 'Enregistrer un actif de données', 'asset_code' => 'Code de l’actif', 'asset_name' => 'Nom de l’actif', 'accountable_data_owner' => 'Responsable redevable des données', 'operational_data_steward' => 'Gestionnaire opérationnel des données', 'tor_module_or_shared_service' => 'Module du TdR ou service partagé', 'authoritative_source' => 'Source faisant autorité', 'classification' => 'Classification', 'residency_country' => 'Pays de résidence des données',
    'contains_personal_data' => 'Contient des données à caractère personnel', 'contains_sensitive_personal_data' => 'Contient des données personnelles sensibles', 'dataset_scope_and_intended_use' => 'Périmètre et utilisation prévue du jeu de données', 'personal_data_categories_comma_separated' => 'Catégories de données personnelles (séparées par des virgules)', 'data_subject_categories_comma_separated' => 'Catégories de personnes concernées (séparées par des virgules)', 'approved_storage_locations_comma_separated' => 'Emplacements de stockage approuvés (séparés par des virgules)', 'quality_and_provenance_standard' => 'Norme de qualité et de provenance',
    'schedule_code' => 'Code du calendrier', 'record_class' => 'Catégorie de dossier', 'retention_months' => 'Mois de conservation', 'disposition_action' => 'Action de disposition', 'next_review_date' => 'Date du prochain examen', 'retention_trigger_event' => 'Événement déclencheur de conservation', 'legal_or_approved_records_authority' => 'Autorité légale ou approuvée des dossiers', 'legal_hold_suspension_rule' => 'Règle de suspension pour gel juridique',
    'submit_processing_activity' => 'Soumettre une activité de traitement', 'data_asset' => 'Actif de données', 'retention_schedule' => 'Calendrier de conservation', 'processing_reference' => 'Référence du traitement', 'activity_name' => 'Nom de l’activité', 'lawful_basis' => 'Base légale', 'controller' => 'Responsable du traitement', 'dpia_status' => 'Statut de l’AIPD', 'dpia_evidence_reference' => 'Référence de la preuve de l’AIPD',
    'uses_automated_decision_making' => 'Utilise la prise de décision automatisée', 'includes_cross_border_transfer' => 'Comprend un transfert transfrontalier', 'specific_processing_purpose' => 'Finalité spécifique du traitement', 'lawful_basis_authority_and_assessment' => 'Autorité et évaluation de la base légale', 'processors_comma_separated' => 'Sous-traitants (séparés par des virgules)', 'recipient_categories_comma_separated' => 'Catégories de destinataires (séparées par des virgules)', 'processing_operations_comma_separated' => 'Opérations de traitement (séparées par des virgules)', 'transfer_countries_comma_separated' => 'Pays de transfert (séparés par des virgules)', 'transfer_safeguards' => 'Garanties de transfert', 'privacy_risk_summary' => 'Résumé des risques pour la vie privée', 'technical_and_organizational_measures' => 'Mesures techniques et organisationnelles',
    'record_data_subject_request' => 'Enregistrer une demande de personne concernée', 'request_type' => 'Type de demande', 'assigned_privacy_operator' => 'Agent de confidentialité désigné', 'requester_name' => 'Nom du demandeur', 'controlled_contact' => 'Coordonnées contrôlées', 'contact_channel' => 'Canal de contact', 'received_date_and_time' => 'Date et heure de réception', 'requested_personal_data_and_service_scope' => 'Données personnelles demandées et périmètre du service',
    'report_personal_data_breach' => 'Signaler une violation de données personnelles', 'incident_title' => 'Titre de l’incident', 'incident_lead' => 'Responsable de l’incident', 'affected_data_asset' => 'Actif de données touché', 'affected_county' => 'Comté touché', 'sdd_role' => 'Rôle SDD', 'breach_type' => 'Type de violation', 'estimated_affected_people' => 'Nombre estimé de personnes touchées', 'sensitive_personal_data_may_be_involved' => 'Des données personnelles sensibles peuvent être concernées', 'occurred_date_and_time' => 'Date et heure de l’incident', 'discovered_date_and_time' => 'Date et heure de la découverte', 'controlled_incident_description' => 'Description contrôlée de l’incident',
    'containment_actions_completed' => 'Actions de confinement achevées', 'assessed_severity' => 'Gravité évaluée', 'real_risk_of_harm' => 'Risque réel de préjudice', 'independent_risk_assessment_and_legal_reasoning' => 'Évaluation indépendante des risques et raisonnement juridique', 'odpc_notified_date_and_time' => 'Date et heure de notification à l’ODPC', 'odpc_notification_reference' => 'Référence de notification à l’ODPC', 'delay_reason_when_after_72_hours' => 'Motif du retard, au-delà de 72 heures', 'affected_person_communication' => 'Communication à la personne touchée', 'affected_people_notified_date_and_time' => 'Date et heure de notification aux personnes touchées', 'no_notice_or_delay_rationale' => 'Motif de l’absence ou du retard de notification', 'verified_root_cause' => 'Cause première vérifiée', 'completed_corrective_and_preventive_actions' => 'Actions correctives et préventives achevées', 'controlled_closure_evidence_reference' => 'Référence de preuve de clôture contrôlée',
];
