<?php

return [
    'title' => 'Référentiel documentaire',
    'description' => 'Organisez les fichiers gouvernés dans des dossiers par comté sans contourner l’analyse antimalware, les versions immuables, la conservation ou les gels juridiques.',
    'all_files' => 'Tous les fichiers', 'folders' => 'Dossiers', 'folder_tree' => 'Arborescence du référentiel', 'no_folders' => 'Aucun dossier n’a été provisionné dans votre périmètre autorisé.',
    'new_folder' => 'Nouveau dossier', 'create_folder' => 'Créer un dossier', 'edit_folder' => 'Modifier le dossier', 'delete_folder' => 'Supprimer le dossier', 'folder_name' => 'Nom du dossier', 'parent_folder' => 'Dossier parent', 'root_folder' => 'Niveau supérieur', 'county_scope' => 'Périmètre du comté', 'national_scope' => 'Référentiel national',
    'upload_file' => 'Téléverser un fichier', 'upload_description' => 'Les fichiers restent privés et sont analysés, vérifiés, versionnés et mis en file pour l’extraction de texte indexable.',
    'move_selected' => 'Déplacer la sélection', 'move_documents' => 'Déplacer :count document(s)', 'move_description' => 'Déplacez les documents sélectionnés dans le même périmètre autorisé de comté ou national.', 'destination_folder' => 'Dossier de destination', 'confirm_move' => 'Déplacer les documents', 'save_folder' => 'Enregistrer le dossier', 'confirm_delete_folder' => 'Supprimer le dossier vide', 'delete_description' => 'Seuls les dossiers vides peuvent être supprimés. Les documents et sous-dossiers doivent d’abord être déplacés.',
    'current_folder' => 'Dossier actuel', 'files_count' => ':count fichier(s)', 'storage_used' => ':size stockés dans le jeu de résultats actuel',
    'document_title' => 'Titre du document', 'category' => 'Catégorie', 'source_type' => 'Type de source', 'digital_file' => 'Fichier numérique natif', 'scanned_copy' => 'Copie numérisée', 'description_label' => 'Description', 'document_date' => 'Date du document', 'tags' => 'Étiquettes', 'tags_placeholder' => 'planification, audit, EF2026', 'file' => 'Fichier', 'uploading' => 'Téléversement :percentage %',
    'view_layout' => 'Disposition d’affichage des fichiers', 'grid_view' => 'Vue en grille', 'list_view' => 'Vue en liste', 'drag_to_folder' => 'Faites glisser ce fichier vers un dossier pour le déplacer.', 'drop_file_here' => 'Déposez un fichier ici ou utilisez le sélecteur ci-dessous', 'secure_upload_notice' => 'Le fichier sera analysé, contrôlé et versionné avant d’être disponible.',
    'errors' => ['folder_cycle' => 'Un dossier ne peut pas être déplacé dans lui-même ou dans l’un de ses descendants.', 'folder_scope_mismatch' => 'Les dossiers parent et enfant doivent avoir le même périmètre de comté ou national.', 'folder_name_taken' => 'Un dossier portant ce nom existe déjà au niveau sélectionné.', 'folder_not_empty' => 'Déplacez tous les documents et sous-dossiers avant de supprimer ce dossier.', 'document_scope_mismatch' => ':title ne peut pas être déplacé vers un dossier hors de son périmètre de comté ou national.', 'document_hold_move' => ':title ne peut pas être déplacé pendant un gel juridique.', 'store_failed' => 'Le document du référentiel n’a pas pu être stocké.'],
    'outcomes' => ['folder_created' => 'Le dossier :name a été créé.', 'folder_updated' => 'Le dossier :name a été mis à jour.', 'folder_deleted' => 'Le dossier a été supprimé.', 'document_uploaded' => ':title a été téléversé en toute sécurité.', 'documents_moved' => '{1} :count document déplacé vers :folder.|[2,*] :count documents déplacés vers :folder.'],
    'audit' => ['folder_created' => 'Dossier du référentiel créé : :name.', 'folder_updated' => 'Dossier du référentiel mis à jour : :name.', 'folder_deleted' => 'Dossier du référentiel supprimé : :name.', 'document_uploaded' => 'Document du référentiel téléversé : :title dans :folder.', 'document_moved' => 'Document du référentiel :title déplacé vers :folder.'],
    'version' => ['initial_upload' => 'Téléversement initial dans le référentiel'],
];
