<?php

return ['collaboration_threads' => 'Fils de collaboration gouvernés', 'collaboration_description' => 'Les discussions du groupe conservent des contributions attribuées et contrôlées par somme dans le périmètre de comté autorisé.', 'no_collaboration_threads' => 'Aucun fil de collaboration', 'no_collaboration_description' => 'Ouvrez la première discussion gouvernée pour un groupe autorisé.', 'create_thread' => 'Créer le fil', 'new_thread' => 'Nouveau fil', 'create_thread_description' => 'Lancez une discussion attribuée au sein d’un groupe autorisé.', 'working_group' => 'Groupe de travail', 'thread_title' => 'Titre du fil', 'opening_contribution' => 'Contribution initiale', 'thread_messages' => 'Contributions au fil', 'checksum' => 'Somme de contrôle :', 'post_contribution' => 'Publier la contribution', 'reply' => 'Répondre', 'contribution' => 'Contribution', 'separator' => '·', 'thread_closed' => 'Ce fil de collaboration est fermé.',
    'action_create_unauthorized' => 'Vous n’êtes pas autorisé à attribuer des actions DSWG.', 'accountable_member_required' => 'La personne responsable doit être un membre actif de ce groupe de travail.', 'action_county_outside_portfolio' => 'Le comté de l’action est hors du portefeuille du groupe de travail.', 'action_decision_mismatch' => 'La décision sélectionnée n’appartient pas à cette réunion.',
    'meeting_series_create_unauthorized' => 'Vous n’êtes pas autorisé à créer des réunions DSWG récurrentes.', 'recurring_invitee_member_required' => 'Chaque invité récurrent doit être un membre actif du groupe de travail.', 'recurring_quorum_exceeded' => 'Le quorum ne peut pas dépasser le nombre d’invités récurrents.',
    'group_create_unauthorized' => 'Vous n’êtes pas autorisé à établir des groupes de travail DSWG.', 'group_county_outside_scope' => 'Un ou plusieurs comtés sélectionnés sont hors de votre périmètre autorisé.',
    'audit_action_created' => 'Action DSWG :code attribuée.', 'audit_meeting_series_created' => 'Série de réunions DSWG récurrentes :reference créée.', 'audit_group_created' => 'DSWG :code créé.',
    'invitee_member_required' => 'Chaque invité doit être membre du groupe de travail.', 'quorum_exceeded' => 'Le quorum ne peut pas dépasser le nombre d’invités.', 'meeting_workflow_unavailable' => 'Le flux de travail de la réunion est indisponible.',
    'attendance_invitees_only' => 'La présence ne peut inclure que les participants invités.', 'clean_minutes_required' => 'Un procès-verbal sain lié au référentiel est requis avant l’approbation.', 'decision_after_outcomes' => 'Les décisions ne peuvent être enregistrées qu’après la consignation des résultats.',
    'action_after_outcomes' => 'Les actions ne peuvent être attribuées qu’après la consignation des résultats de la réunion.', 'action_workflow_unavailable' => 'Le flux de travail de l’action est indisponible.', 'workflow_outcomes_recorded' => 'Les résultats de la réunion et le projet de procès-verbal ont été consignés.',
    'outcome_group_created' => 'Le groupe de travail sectoriel a été établi.', 'outcome_meeting_scheduled' => 'La réunion a été planifiée et les invitations envoyées.', 'outcome_thread_created' => 'Le fil de collaboration a été créé.', 'outcome_contribution_posted' => 'La contribution a été publiée.',
    'outcome_meeting_series_created' => 'La série de réunions :reference a été créée et son calendrier glissant généré.', 'outcome_invitation_recorded' => 'La réponse à l’invitation a été enregistrée.', 'outcome_meeting_outcomes_recorded' => 'Les résultats ont été consignés pour approbation indépendante du procès-verbal.',
    'outcome_minutes_approved' => 'Le procès-verbal a été approuvé et la réunion clôturée.', 'outcome_decision_registered' => 'La décision de la réunion a été enregistrée.', 'outcome_action_created' => 'L’action responsable a été créée et le responsable notifié.', 'outcome_action_updated' => 'Le flux de l’action a été mis à jour.',
    'notification_meeting_title' => 'Invitation à une réunion DSWG', 'notification_meeting_message' => 'Vous êtes invité à :title le :date.', 'notification_action_title' => 'Nouvelle action DSWG attribuée', 'notification_action_message' => ':code : :title est attendue le :date.',
    'audit_meeting_scheduled' => 'Réunion DSWG :reference planifiée.', 'audit_thread_created' => 'Fil de collaboration DSWG :title créé.', 'audit_contribution_posted' => 'Contribution publiée dans le fil DSWG :title.',
    'audit_invitation_responded' => 'Invitation à la réunion marquée :status.', 'audit_outcomes_recorded' => 'Projet de procès-verbal enregistré pour :reference.', 'audit_minutes_approved' => 'Procès-verbal approuvé pour :reference.',
    'audit_decision_adopted' => 'Décision DSWG :code adoptée.', 'audit_action_transitioned' => 'Action DSWG :code passée par :transition.',
];
