<?php

return [
    'head_title' => 'Coordination DSWG', 'eyebrow' => 'Coordination et responsabilité sectorielles', 'title' => 'Groupes de travail du secteur de la dévolution', 'description' => 'Coordonnez les membres, invitations, quorums, ordres du jour, procès-verbaux approuvés, décisions, actions responsables, échéances, rappels et clôtures indépendantes.',
    'series_title' => 'Séries de réunions récurrentes', 'series_description' => 'Calendriers continus et idempotents générés dans le fuseau IANA sélectionné, avec un flux gouverné pour chaque occurrence.', 'no_series' => 'Aucune série récurrente', 'no_series_description' => 'Créez une série pour maintenir automatiquement les futures réunions.', 'every' => 'Tous les', 'periods' => 'période(s)', 'occurrences_generated' => 'occurrence(s) générée(s)', 'next_occurrence' => 'Prochaine :', 'ends_on' => 'Fin :',
    'meeting_workspace' => 'Espace de réunion', 'meeting_workspace_description' => 'Invitations, présence, quorum, procès-verbaux, décisions et actions suivis.', 'no_meetings' => 'Aucune réunion disponible', 'no_meetings_description' => 'Modifiez les dates de rapport ou planifiez la première réunion du groupe sectoriel.', 'no_actions' => 'Aucune action responsable correspondante', 'no_actions_description' => 'Modifiez les filtres ou consignez des actions issues d’une réunion sectorielle approuvée.',
    'quorum' => 'quorum', 'decisions' => 'décisions', 'actions' => 'actions', 'agenda' => 'Ordre du jour :', 'record_outcomes_title' => 'Consigner les résultats de la réunion', 'record_outcomes' => 'Consigner les résultats', 'record_outcomes_description' => 'Consignez la présence, le quorum et le projet de procès-verbal pour', 'draft_minutes' => 'Projet de procès-verbal', 'members_present' => 'Membres présents', 'record_outcomes_submit' => 'Consigner les résultats et le quorum', 'minutes' => 'Procès-verbal',
    'approve_minutes_title' => 'Approuver le procès-verbal', 'approve_minutes' => 'Approuver le procès-verbal', 'approve_minutes_description' => 'Examinez indépendamment et approuvez le procès-verbal de', 'clean_minutes_ready' => 'Un procès-verbal sain lié au référentiel est prêt pour approbation.', 'clean_minutes_required' => 'Téléversez un procès-verbal sain avant de terminer l’approbation.', 'minutes_comment' => 'Commentaire indépendant d’approbation',
    'register_decision_title' => 'Enregistrer la décision adoptée', 'register_decision' => 'Enregistrer la décision', 'register_decision_description' => 'Consignez une décision adoptée lors de', 'decision_title' => 'Titre de la décision', 'adopted_decision' => 'Décision adoptée', 'decision_datetime' => 'Date et heure de décision',
    'assign_action_title' => 'Attribuer une action responsable', 'assign_action' => 'Attribuer l’action', 'assign_action_description' => 'Créez une action assortie d’une échéance à partir de', 'using_catalogue' => 'Utilisation de la version gouvernée du catalogue v', 'no_effective_catalogue' => 'Aucun catalogue de référence publié avec une empreinte valide n’est actuellement en vigueur.', 'action_title' => 'Titre de l’action', 'deliverable_evidence' => 'Livrable et preuve d’acceptation', 'due_date' => 'Échéance',
    'start' => 'Démarrer', 'submit_completion_title' => 'Soumettre l’achèvement de l’action', 'submit_completion' => 'Soumettre l’achèvement', 'submit_completion_description' => 'Soumettez une preuve d’achèvement liée au référentiel pour vérification indépendante.', 'clean_evidence_ready' => 'Une preuve d’action saine est liée et prête à être soumise.', 'clean_evidence_required' => 'Téléversez une preuve d’action saine avant de soumettre l’achèvement.', 'evidence_narrative' => 'Récit de preuve facultatif ou référence du référentiel', 'completion_comment' => 'Commentaire de soumission de l’achèvement', 'verify' => 'Vérifier', 'return' => 'Renvoyer', 'accountable_action' => 'action responsable', 'transition_description' => 'cette action dans le flux DSWG gouverné.', 'transition_comment' => 'l’action dans le flux DSWG gouverné.', 'rationale' => 'motif', 'confirm' => 'Confirmer',
    'value_active' => 'Active', 'value_open' => 'Ouverte', 'value_closed' => 'Fermée', 'value_scheduled' => 'Planifiée', 'value_minutes_pending' => 'Procès-verbal en attente', 'value_accepted' => 'Acceptée', 'value_tentative' => 'Provisoire', 'value_declined' => 'Refusée',
];
