<?php

return [
    'upload_evidence' => 'Téléverser une preuve', 'upload_evidence_description' => 'Téléversez une copie numérisée ou un fichier numérique natif. Les fichiers sont conservés de manière privée et liés au cycle d’évaluation sélectionné.', 'upload_criterion_evidence' => 'Téléverser une preuve du critère', 'upload_criterion_evidence_description' => 'Les fichiers sont conservés de manière privée et ne comptent dans l’exhaustivité qu’après une vérification indépendante.', 'assessment' => 'Évaluation', 'evidence_requirement' => 'Exigence de preuve', 'source_type' => 'Type de source', 'category_placeholder' => 'ADP, CIDP…', 'upload' => 'Téléverser', 'uploading' => 'Téléversement :percentage %',
    'errors' => ['integrity_failed' => 'La vérification de l’intégrité du document a échoué.', 'preview_unavailable' => 'L’aperçu n’est pas disponible pour ce type de fichier.', 'document_quarantined' => 'Ce document est en quarantaine jusqu’à la réussite de son analyse de sécurité.', 'version_quarantined' => 'Cette version du document est en quarantaine jusqu’à la réussite de son analyse de sécurité.', 'version_integrity_failed' => 'La vérification de l’intégrité de la version du document a échoué.', 'assessment_locked' => 'Les preuves sont verrouillées après l’évaluation.', 'retention_locked' => 'La durée de conservation ne peut pas être modifiée pendant qu’un gel juridique est actif.', 'archive_locked' => 'Un document sous gel juridique ne peut pas être archivé.', 'clean_current_version_required' => 'Seule une version actuelle et saine du document peut être traitée.', 'hold_separation_required' => 'L’agent ayant placé un gel juridique ne peut pas le lever.', 'media_range_invalid_with_value' => 'La plage média demandée n’est pas valide : :range.', 'media_range_invalid' => 'La plage média demandée n’est pas valide.', 'media_range_outside_file' => 'La plage média :start-:end se trouve hors du fichier de :size octets.'],
    'audit' => ['previewed' => 'Document prévisualisé : :title.', 'downloaded' => 'Document téléchargé : :title.', 'version_previewed' => 'Version :version du document prévisualisée : :title.', 'version_downloaded' => 'Version :version du document téléchargée : :title.', 'metadata_updated' => 'Métadonnées du document mises à jour : :title.', 'archived' => 'Document archivé : :title.', 'hold_released' => 'Gel juridique :reference levé.'],
    'outcomes' => ['uploaded' => 'La preuve a été téléversée en toute sécurité.', 'verified' => 'La vérification de la preuve a été enregistrée.', 'metadata_updated' => 'Les métadonnées du document ont été mises à jour.', 'archived' => 'Le document a été archivé.', 'version_uploaded' => 'Une nouvelle version immuable du document a été téléversée.', 'extraction_queued' => 'L’extraction du texte du document a été mise en file.', 'hold_placed' => 'Le gel juridique a été placé.', 'hold_released' => 'Le gel juridique a été levé.', 'disposition_submitted' => 'Le sort final contrôlé a été soumis à une revue indépendante.', 'disposition_decided' => 'La décision de revue du sort final a été enregistrée.', 'disposition_executed' => 'Le sort final contrôlé a été exécuté et les preuves conservées.'],
    'open_actions' => 'Ouvrir les actions de preuve', 'preview_document' => 'Prévisualiser le document', 'download_original' => 'Télécharger l’original', 'manage_record' => 'Gérer le dossier', 'reprocess_text' => 'Retraiter le texte indexable', 'verify_evidence' => 'Vérifier la preuve', 'reject_evidence' => 'Rejeter la preuve',
    'document_preview' => 'Aperçu du document', 'secure_document' => 'Document de preuve sécurisé', 'scanned_copy' => 'Copie numérisée', 'digital_file' => 'Fichier numérique', 'text_extraction' => 'Extraction du texte : :status', 'not_requested' => 'non demandée', 'searchable_unavailable' => 'Texte indexable indisponible',
    'attempts_title' => 'Preuves des tentatives d’extraction', 'attempts_description' => 'Historique inaltérable des traitements et nouvelles tentatives de la version immuable actuelle.', 'attempt' => 'Tentative', 'source' => 'Source', 'actor' => 'Acteur', 'engine' => 'Moteur', 'status' => 'Statut', 'duration' => 'Durée', 'result' => 'Résultat', 'in_progress' => 'En cours', 'characters' => ':count caractères',
    'preview_of' => 'Aperçu de :title', 'document' => 'document', 'extracted_preview' => 'Aperçu du texte extrait', 'download_original_document' => 'Télécharger le document original',
    'manage_document' => 'Gérer le document', 'manage_description' => 'Mettre à jour les métadonnées gouvernées, les versions, la conservation et les gels juridiques.', 'title' => 'Titre', 'category' => 'Catégorie', 'document_date' => 'Date du document', 'description' => 'Description', 'tags' => 'Étiquettes', 'tags_placeholder' => 'planification, EF2025', 'retain_until' => 'Conserver jusqu’au', 'save_metadata' => 'Enregistrer les métadonnées',
    'versions_title' => 'Versions immuables', 'version_integrity' => 'Version :version · SHA-256 :checksum · analyse :scan · extraction du texte :ocr', 'completed_at' => ' · terminée le :date', 'replacement_reason' => 'Motif de ce remplacement', 'upload_version' => 'Téléverser une nouvelle version', 'no_versions' => 'Aucun historique de version conservé n’est disponible pour ce dossier historique.', 'version_number' => 'Version :number', 'current' => 'Actuelle', 'uploaded_by' => ':name · téléversé par :actor · :date', 'preview' => 'Aperçu', 'download' => 'Télécharger', 'initial_version' => 'Version gouvernée initiale', 'version_manifest' => 'SHA-256 :checksum · :bytes octets · texte :status',
    'place_hold' => 'Placer un gel juridique', 'place_hold_description' => 'Empêcher le remplacement, l’archivage et les modifications de conservation.', 'hold_reference' => 'Référence du gel', 'issuing_authority' => 'Autorité émettrice', 'hold_reason' => 'Motif juridique ou réglementaire', 'under_hold' => 'Ce dossier est sous gel juridique. Le remplacement, la conservation et l’archivage sont verrouillés.', 'hold_history' => 'Historique des gels juridiques', 'hold_history_description' => 'Les décisions de placement et de levée restent visibles après la levée du gel.', 'no_holds' => 'Aucun gel juridique n’a été enregistré.', 'hold_placed' => ':authority · placé par :actor · :date', 'released' => 'Levée', 'active' => 'Actif', 'hold_released' => 'Levée par :actor le :date. :reason', 'unknown' => 'Inconnu', 'release_reason' => 'Motif de la levée', 'release_placeholder' => 'Autorité et motif de la levée de ce gel', 'release_hold' => 'Lever le gel juridique',
    'archive_document' => 'Archiver le document', 'request_disposition' => 'Demander un sort final contrôlé', 'disposition_description' => 'Nécessite une revue indépendante et un agent d’exécution distinct. Les gels actifs et les défauts d’intégrité arrêtent l’exécution.', 'retention_required' => 'Date de conservation requise', 'retention_required_description' => 'Définissez une date de conservation approuvée avant de demander une destruction sécurisée.', 'authority_reference' => 'Référence de l’autorité', 'authority_placeholder' => 'Calendrier approuvé ou autorité de destruction', 'scheduled_date' => 'Date d’exécution prévue', 'disposition_reason' => 'Motif du sort final', 'disposition_placeholder' => 'Classe du dossier, déclencheur de conservation et motif autorisant la destruction', 'submit_disposition' => 'Soumettre le sort final à revue',
    'disposition_history' => 'Historique des sorts finaux', 'disposition_history_description' => 'Demandes, décisions indépendantes, échecs d’exécution et preuves immuables de destruction.', 'no_dispositions' => 'Aucune demande de sort final n’a été enregistrée.', 'secure_destruction' => 'Destruction sécurisée · :reference', 'requested_by' => 'Demandée par :actor le :date', 'retention_schedule' => 'Conservation due le :due · prévue le :scheduled', 'reviewed_by' => 'Examinée par :actor le :date. :reason', 'execution_stopped' => 'Exécution arrêtée', 'executed_by' => 'Exécutée par :actor le :date. :objects objets / :bytes octets.', 'manifest_checksum' => 'Manifeste SHA-256 :checksum', 'independent_reason' => 'Motif de la revue indépendante', 'approve' => 'Approuver', 'reject' => 'Rejeter', 'execute_destruction' => 'Exécuter la destruction sécurisée approuvée',
];
