<?php

return [
    'reported' => 'Signalées', 'accepted' => 'Acceptées', 'gap_status' => 'État de la lacune', 'gap_severity' => 'Gravité de la lacune',
    'no_dependency_paths_in_scope' => 'Aucun chemin de dépendance dans le périmètre', 'categories' => 'Catégories', 'severities' => 'Niveaux de gravité', 'no_resolutions_available' => 'Aucune résolution disponible', 'no_matching_implementation_gaps' => 'Aucun écart de mise en œuvre correspondant', 'no_matching_resolutions' => 'Aucune résolution correspondante',
    'establish_igr_forum' => 'Établir un forum IGR', 'forum_code' => 'Code du forum', 'igr_cg_summit' => 'IGR-CG-SUMMIT', 'forum_name' => 'Nom du forum', 'forum_type' => 'Type de forum', 'mandate' => 'Mandat', 'secretariat' => 'Secrétariat',
    'record_formal_igr_meeting' => 'Enregistrer une réunion IGR officielle', 'forum' => 'Forum', 'meeting_reference' => 'Référence de la réunion', 'igr_summit_2026_04' => 'IGR/SUMMIT/2026/04', 'meeting_title' => 'Titre de la réunion', 'meeting_date' => 'Date de la réunion', 'venue' => 'Lieu', 'chair' => 'Présidence', 'minutes_reference' => 'Référence du procès-verbal', 'dms_igr_min_2026_04' => 'DMS/IGR/MIN/2026/04',
    'create_implementation_gap_category' => 'Créer une catégorie d’écart de mise en œuvre', 'category_code' => 'Code de la catégorie', 'data_quality' => 'DATA-QUALITY', 'category_name' => 'Nom de la catégorie', 'description_label' => 'Description', 'default_severity' => 'Gravité par défaut',
    'register_adopted_resolution' => 'Enregistrer une résolution adoptée', 'source_forum' => 'Forum source', 'formal_meeting_optional_for_historical_records' => 'Réunion officielle (facultative pour les dossiers historiques)', 'resolution_number' => 'Numéro de résolution', 'igr_2026_001' => 'IGR/2026/001', 'title_label' => 'Titre', 'resolution_date' => 'Date de la résolution', 'implementation_deadline' => 'Échéance de mise en œuvre', 'resolution_text' => 'Texte de la résolution', 'priority' => 'Priorité',
    'county' => 'Comté', 'organization' => 'Organisation', 'role' => 'Rôle', 'prerequisites' => 'Prérequis', 'dependent_resolutions' => 'Résolutions dépendantes', 'report_implementation_gap' => 'Signaler un écart de mise en œuvre', 'gap_category' => 'Catégorie de l’écart', 'gap_title' => 'Titre de l’écart', 'implementation_impact' => 'Impact sur la mise en œuvre', 'severity' => 'Gravité', 'accountable_owner' => 'Responsable redevable', 'affected_county' => 'Comté touché', 'mitigation_due_date' => 'Échéance d’atténuation',
    'add_resolution_dependency' => 'Ajouter une dépendance de résolution', 'prerequisite_resolution' => 'Résolution préalable', 'dependency_type' => 'Type de dépendance', 'dependency_rationale' => 'Motif de la dépendance', 'record_implementation_progress' => 'Enregistrer l’avancement de la mise en œuvre', 'progress_percentage' => 'Pourcentage d’avancement', 'evidence_note_or_reference_optional' => 'Note ou référence de preuve (facultative)', 'add_context_for_the_linked_repository_evidence' => 'Ajouter du contexte à la preuve liée dans le référentiel', 'implementation_narrative' => 'Compte rendu de mise en œuvre',
    'start_implementation' => 'Démarrer la mise en œuvre', 'submit_for_closure' => 'Soumettre pour clôture', 'approve_closure' => 'Approuver la clôture', 'return_for_action' => 'Renvoyer pour action', 'start_mitigation' => 'Démarrer l’atténuation', 'submit_resolution' => 'Soumettre la résolution', 'accept_resolution' => 'Accepter la résolution', 'return_mitigation' => 'Renvoyer l’atténuation', 'decision_rationale' => 'Motif de la décision', 'decision_comment' => 'Commentaire sur la décision',
    'gap_transition_description' => 'Consignez le fondement de la décision pour le cycle de vie gouverné de l’écart de mise en œuvre.', 'transition_not_available' => 'Cette transition n’est pas disponible.', 'transition_decision_basis' => 'Consignez le fondement de la décision pour :transition.',
    'add_dependency_path_description' => 'Ajoutez un prérequis bloquant ou informatif afin d’exposer l’analyse du chemin.', 'dependency_path_label' => 'Chemin de dépendance comportant :count liens', 'active_gaps_label' => ':name : :count écarts actifs', 'record_forum_and_resolution_description' => 'Consignez un forum intergouvernemental autorisé et sa première résolution afin de commencer le suivi de la mise en œuvre.', 'no_governed_gaps_description' => 'Aucun écart gouverné ne correspond aux filtres de rapport sélectionnés.', 'no_matching_resolutions_description' => 'Ajustez la recherche ou les dates de rapport, ou consignez une résolution issue d’un forum autorisé.', 'county_gaps_label' => ':name : :count écarts',
    'establish_forum' => 'Établir un forum', 'establish_forum_description' => 'Créez le forum source faisant autorité.', 'record_meeting_description' => 'Consignez le quorum et la provenance du procès-verbal avant de relier les résolutions adoptées.', 'create_gap_category' => 'Créer une catégorie d’écart', 'create_gap_category_description' => 'Configurez une classification réutilisable et sa gravité de risque par défaut.', 'register_resolution' => 'Enregistrer une résolution', 'register_resolution_description' => 'Désignez exactement un responsable principal et toute partie d’appui responsable.', 'report_gap' => 'Signaler un écart', 'report_gap_description' => 'Classez, attribuez et fixez l’échéance d’un écart affectant :number.', 'add_dependency_description' => 'Consignez le prérequis qui régit :number. Les liens circulaires et hors périmètre sont rejetés.', 'record_progress_description' => 'Mettez à jour :number avec les preuves et tout écart de mise en œuvre.',
];
