<?php

return [
    'operational_status' => 'État opérationnel', 'county' => 'Comté',
    'no_integration_systems_registered' => 'Aucun système d’intégration enregistré', 'exchange_register' => 'Registre des échanges', 'no_matching_exchanges' => 'Aucun échange correspondant', 'no_reconciliation_exceptions' => 'Aucune exception de rapprochement',
    'owner' => 'Responsable', 'owner_organization' => 'Organisation responsable', 'reference_catalogue' => 'Catalogue de référence', 'classification' => 'Classification', 'authentication' => 'Authentification', 'health' => 'État de santé', 'endpoint' => 'Point de terminaison', 'credential_reference' => 'Référence de l’identifiant secret',
    'source_owner_approval_reference' => 'Référence d’approbation du responsable de la source', 'data_sharing_agreement_reference' => 'Référence de l’accord de partage de données', 'effective_from' => 'Prend effet le', 'effective_until' => 'En vigueur jusqu’au',
    'register_integration_system' => 'Enregistrer un système d’intégration', 'system_code' => 'Code du système', 'system_name' => 'Nom du système', 'authoritative_system_owner' => 'Responsable officiel du système',
    'environment' => 'Environnement', 'transport' => 'Transport', 'direction' => 'Direction', 'data_classification' => 'Classification des données', 'lifecycle_status' => 'État du cycle de vie', 'base_url' => 'URL de base', 'credential_vault_reference' => 'Référence du coffre d’identifiants',
    'purpose_and_authorized_data_use' => 'Finalité et utilisation autorisée des données', 'submit_interface_contract' => 'Soumettre le contrat d’interface', 'integration_system' => 'Système d’intégration', 'contract_name' => 'Nom du contrat', 'canonical_resource' => 'Ressource canonique', 'http_method' => 'Méthode HTTP',
    'resource_path' => 'Chemin de la ressource', 'idempotency_field' => 'Champ d’idempotence', 'rate_limit_per_minute' => 'Limite de requêtes par minute', 'request_json_schema' => 'Schéma JSON de la requête', 'response_json_schema' => 'Schéma JSON de la réponse',
    'canonical_field_mappings' => 'Mappages des champs canoniques', 'required_headers' => 'En-têtes requis', 'retry_policy' => 'Politique de nouvelle tentative', 'idempotency_key' => 'Clé d’idempotence', 'external_reference' => 'Référence externe', 'county_scope' => 'Périmètre du comté',
    'source_event_time' => 'Heure de l’événement source', 'contract_valid_json_payload' => 'Charge JSON conforme au contrat', 'source_owner_activation_reference' => 'Référence d’activation du responsable de la source', 'approval_date_and_time' => 'Date et heure d’approbation',
    'contract' => 'Contrat', 'payload_checksum' => 'Somme de contrôle de la charge', 'status' => 'Statut', 'next_attempt' => 'Prochaine tentative', 'accepted' => 'Accepté', 'no_retained_attempts' => 'Aucune tentative conservée',
    'description_label' => 'Description', 'references' => 'Références', 'verified_resolution_and_evidence' => 'Résolution et preuve vérifiées',
    'no_systems_description' => 'Enregistrez le premier système source et soumettez un contrat d’interface versionné pour approbation indépendante.', 'exchange_record_count' => ':count dossiers d’échange sécurisés au niveau de la charge utile', 'no_exchanges_description' => 'Envoyez une charge utile de bac à sable conforme au schéma ou ajustez les filtres.', 'no_discrepancies_description' => 'Aucun écart ne correspond au périmètre et aux filtres actuels.', 'actions_for_record' => 'Actions pour :record', 'publish_contract' => 'Publier :name v:version', 'publish_contract_description' => 'Approuvez indépendamment le contrat de schéma immuable. Les interfaces de production exigent les références du propriétaire de la source et du partage de données.', 'review_and_publish' => 'Examiner et publier', 'new_system_description' => 'Enregistrez uniquement les métadonnées du point de terminaison et une référence de coffre. Ne stockez jamais d’identifiants dans ce formulaire.', 'new_system' => 'Nouveau système', 'new_contract_description' => 'Définissez le schéma, les correspondances, l’idempotence et la politique de nouvelle tentative pour publication indépendante.', 'new_contract' => 'Nouveau contrat', 'actions_for_exchange' => 'Actions pour l’échange :id', 'legacy_exchange_description' => 'Cet échange est antérieur au registre immuable des tentatives.', 'view_reconciliation_exception' => 'Voir l’exception de rapprochement :id',
];
