<?php

return ['outcomes' => [
    'system_registered' => 'Système d’intégration :code enregistré.', 'activation_recorded' => 'L’activation de l’intégration de production a été enregistrée.', 'contract_submitted' => 'Le contrat d’interface v:version a été soumis à revue.', 'contract_published' => 'Le contrat d’interface a été publié indépendamment.', 'exchange_recorded' => 'L’échange :correlation a été enregistré avec le statut :status.', 'exchange_retried' => 'La nouvelle tentative de l’échange :correlation s’est terminée avec le statut :status.', 'reconciliation_resolved' => 'L’exception de rapprochement a été résolue par une décision auditable.',
], 'exchange' => [
    'oauth_client' => 'Client OAuth',
    'errors' => ['fixture_sandbox_only' => 'Le transport de simulation est limité aux systèmes sandbox.', 'unsupported_transport' => 'Transport d’intégration non pris en charge [:transport].', 'production_activation_required' => 'L’échange de production exige l’approbation d’activation consignée du propriétaire de la source.', 'endpoint_credentials_required' => 'Le point de terminaison de production et la référence d’identifiants du coffre sont requis.', 'host_not_allowlisted' => 'L’hôte du point de terminaison d’intégration ne figure pas dans la liste d’autorisation.', 'credential_unresolved' => 'La référence d’identifiants du coffre n’est pas résolue.', 'effective_inbound_contract' => 'Seul un contrat d’interface publié et effectif peut recevoir des données.', 'inbound_not_approved' => 'Ce système d’intégration n’est pas approuvé pour les échanges entrants.', 'system_inactive' => 'Le système d’intégration n’est pas actif.', 'oauth_client_unbound' => 'Le client OAuth n’est pas rattaché à ce système d’intégration.', 'production_source_approval' => 'L’approbation d’activation du propriétaire de la source de production est requise.', 'production_agreements' => 'Les approbations du contrat de production et du partage de données sont requises.', 'missing_headers' => 'En-têtes requis par le contrat manquants : :headers.', 'idempotency_conflict' => 'La clé d’idempotence est déjà associée à un autre échange.', 'effective_outbound_contract' => 'Seul un contrat d’interface publié et effectif peut échanger des données.'],
    'audit' => ['ingested' => 'L’échange entrant :correlation a été accepté depuis :system.'],
]];
