<?php

return [
    'publication_status' => 'État de publication', 'county' => 'Comté', 'sector' => 'Secteur', 'tag' => 'Étiquette', 'report_status' => 'État du signalement', 'search_moderation_reports' => 'Rechercher les signalements de modération',
    'curated_repository' => 'Référentiel éditorialisé', 'no_knowledge_resources_found' => 'Aucune ressource de connaissances trouvée', 'no_matching_innovations' => 'Aucune innovation correspondante', 'no_matching_community_reports' => 'Aucun rapport communautaire correspondant',
    'reported_contribution' => 'Contribution signalée', 'report' => 'Signalement', 'reporter' => 'Auteur du signalement', 'sla_due' => 'Échéance du SLA', 'decision' => 'Décision', 'decision_rationale' => 'Motif de la décision', 'contribution_action' => 'Action sur la contribution', 'resolution_and_safeguards' => 'Résolution et mesures de protection',
    'contribute_knowledge_resource' => 'Contribuer une ressource de connaissances', 'resource_title' => 'Titre de la ressource', 'resource_type' => 'Type de ressource', 'sector' => 'Secteur', 'repository_document' => 'Document du référentiel', 'linked_e_learning_course' => 'Cours en ligne associé',
    'source_organization' => 'Organisation source', 'external_source_url' => 'URL de la source externe', 'language' => 'Langue', 'tags_comma_separated' => 'Étiquettes (séparées par des virgules)', 'executive_summary' => 'Résumé exécutif', 'curated_content' => 'Contenu éditorialisé',
    'open_community_discussion' => 'Ouvrir une discussion communautaire', 'discussion_title' => 'Titre de la discussion', 'opening_prompt' => 'Question d’ouverture', 'linked_resource' => 'Ressource associée',
    'submit_devolution_innovation' => 'Soumettre une innovation de dévolution', 'innovation_title' => 'Titre de l’innovation', 'maturity_level' => 'Niveau de maturité', 'evidence_or_prototype_url' => 'URL de la preuve ou du prototype',
    'problem_statement' => 'Énoncé du problème', 'proposed_solution' => 'Solution proposée', 'expected_impact' => 'Impact attendu', 'support_requested' => 'Assistance demandée',
    'discussion_notifications' => 'Notifications de discussion', 'report_category' => 'Catégorie du signalement', 'potential_severity' => 'Gravité potentielle', 'what_should_the_moderation_team_review' => 'Que doit examiner l’équipe de modération ?',
    'moderation_rationale' => 'Motif de modération', 'contribution' => 'Contribution', 'problem' => 'Problème', 'incubation_support' => 'Soutien à l’incubation', 'recommendation' => 'Recommandation', 'independent_assessment_rationale' => 'Motif de l’évaluation indépendante',
    'amount' => 'Montant', 'currency' => 'Devise', 'funding_type' => 'Type de financement', 'decision_reference' => 'Référence de la décision', 'funding_rationale' => 'Motif du financement', 'accountable_owner' => 'Responsable redevable',
    'milestone_title' => 'Titre du jalon', 'testable_hypothesis' => 'Hypothèse vérifiable', 'success_metric' => 'Indicateur de réussite', 'baseline' => 'Valeur de référence', 'target' => 'Cible', 'due_date' => 'Échéance',
    'incubation_support_and_next_steps' => 'Soutien à l’incubation et prochaines étapes', 'pilot_evidence_reference' => 'Référence de la preuve pilote', 'result_status' => 'Statut du résultat', 'actual_value' => 'Valeur réelle', 'outcome_summary' => 'Résumé du résultat',
    'clean_repository_evidence' => 'Preuve saine du référentiel', 'verification_decision' => 'Décision de vérification', 'independent_verification_rationale' => 'Motif de la vérification indépendante',
    'authorized_resources_count' => ':count ressources autorisées', 'no_resources_description' => 'Ajustez les filtres ou ajoutez la première pratique, étude de cas, production de recherche, boîte à outils ou publication fondée sur des preuves.', 'submit_solution_description' => 'Soumettez une solution développée localement pour examen et incubation.', 'no_reports_description' => 'Les signalements relevant de votre périmètre autorisé apparaîtront ici avec leur SLA et leur état de décision.', 'actions_for_record' => 'Actions pour :record',
    'create_resource_description' => 'Créez une ressource fondée sur des preuves et reliez-la à une preuve sécurisée du référentiel ou à une formation en ligne.', 'new_resource' => 'Nouvelle ressource', 'create_discussion_description' => 'Réunissez une communauté de pratique modérée autour d’une ressource ou d’un défi de comté.', 'new_discussion' => 'Nouvelle discussion', 'submit_innovation_description' => 'Enregistrez une solution pour un examen indépendant, une incubation, un pilote et un passage à l’échelle.', 'submit_innovation' => 'Soumettre une innovation',
    'discussion_notifications_description' => 'Choisissez si les nouvelles contributions à :title apparaissent dans votre centre de notifications.', 'actions_for_contribution' => 'Actions pour la contribution de :author', 'contribute_to_discussion' => 'Contribuer à :title', 'add_contribution_description' => 'Ajoutez une contribution traçable à cette communauté de pratique.', 'add_contribution' => 'Ajouter une contribution', 'score_out_of_one_hundred' => ':label (0–100)',
];
