<?php

return [
    'lineage_proposed' => 'La décision de traçabilité des référentiels a été proposée pour examen indépendant.',
    'lineage_reviewed' => 'La décision d’examen de la traçabilité des référentiels a été enregistrée.',
    'lineage_applied' => 'La décision approuvée de traçabilité des référentiels a été appliquée.',
    'import' => [
        'csv_or_xlsx' => 'Téléversez un fichier source CSV ou XLSX.', 'one_worksheet' => 'La source XLSX doit contenir exactement une feuille de calcul.', 'formula_forbidden' => 'Les formules sont interdites (ligne :row). Remplacez-les par leurs valeurs approuvées.', 'xlsx_unreadable' => 'La source XLSX n’a pas pu être lue. Utilisez un classeur non chiffré généré depuis le modèle contrôlé.', 'invalid_archive' => 'La source XLSX n’est pas une archive de classeur valide.', 'too_many_entries' => 'La source XLSX contient trop d’entrées d’archive.', 'archive_uninspectable' => 'L’archive de la source XLSX n’a pas pu être inspectée.', 'external_content' => 'Les liens externes et le contenu exécutable des feuilles de calcul sont interdits.', 'expanded_limit' => 'La source XLSX dépasse la limite de traitement de 50 Mo après extraction.', 'unsupported_value' => 'La source XLSX contient une valeur non prise en charge à la ligne :row.', 'source_unavailable' => 'Le fichier source téléversé n’est plus disponible.', 'checksum_failed' => 'La somme de contrôle du fichier source n’a pas pu être calculée.', 'upload_checksum_failed' => 'La somme de contrôle de la source téléversée n’a pas pu être calculée.', 'private_store_failed' => 'Le fichier source n’a pas pu être conservé dans l’espace privé.', 'header_unreadable' => 'L’en-tête de la source n’a pas pu être lu.', 'required_columns' => 'Utilisez les colonnes requises dans cet ordre exact : :columns.', 'legacy_acpa_columns' => 'Utilisez les colonnes ACPA historiques requises dans cet ordre exact : :columns.', 'migration_row_limit' => 'Un lot de migration peut contenir au maximum 5 000 lignes de données.', 'bulk_row_limit' => 'Un lot d’importation peut contenir au maximum 5 000 lignes de données.', 'no_rows' => 'Le fichier source ne contient aucune ligne de données.', 'unsupported_dataset' => 'Le jeu de données d’importation sélectionné n’est pas pris en charge.',
    ],
    'ui' => [
        'inventory_title' => 'Inventaire historique et non rattaché',
        'inventory_description' => 'Enregistrements explicites sans traçabilité vers une version gouvernée. L’inventaire n’attribue jamais silencieusement un catalogue actuel aux données historiques.',
        'record_type' => 'Type d’enregistrement à rapprocher',
        'open' => 'ouverts', 'pending' => 'en attente', 'applied' => 'appliqués',
        'register_title' => 'Registre des décisions de traçabilité',
        'register_description' => 'Propositions liées à une empreinte, décisions indépendantes, liens successeurs et preuve d’application finale.',
        'empty_title' => 'Aucune décision de traçabilité enregistrée',
        'empty_description' => 'Proposez une décision contrôlée pour un enregistrement historique ou non rattaché.',
        'reconcile' => 'Rapprocher un enregistrement', 'actions_for' => 'Actions pour :reference', 'view_details' => 'Voir les détails', 'review_decision' => 'Examiner la décision', 'apply_disposition' => 'Appliquer la décision',
        'proposal_title' => 'Proposer une décision de traçabilité', 'proposal_description' => 'Enregistrez une décision étayée pour examen indépendant. Cette proposition ne modifie pas l’enregistrement sélectionné.',
        'record' => 'Enregistrement historique ou non rattaché', 'disposition_decision' => 'Décision de traitement', 'retain_legacy' => 'Conserver explicitement comme historique', 'pin_release' => 'Rattacher une version de catalogue vérifiée', 'deprecate' => 'Retirer des futurs usages opérationnels', 'published_release' => 'Version de catalogue publiée', 'version' => 'Version :version', 'successor' => 'Enregistrement successeur (facultatif)', 'source_reference' => 'Référence de source ou d’approbation', 'rationale' => 'Justification fondée sur les preuves', 'recording' => 'Enregistrement de la proposition…', 'submit_review' => 'Soumettre à un examen indépendant',
        'reference' => 'Référence', 'created_at' => 'Créé le',
        'details_title' => 'Détails de la décision de traçabilité', 'review_title' => 'Examiner la décision de traçabilité', 'apply_title' => 'Appliquer la décision de traçabilité', 'checksum_bound' => ':reference · décision liée à une empreinte', 'record_type_value' => 'Type d’enregistrement', 'decision' => 'Décision', 'status' => 'Statut', 'catalogue' => 'Catalogue', 'explicitly_unpinned' => 'Explicitement non rattaché', 'proposed_by' => 'Proposé par', 'reviewed_by' => 'Examiné par', 'applied_by' => 'Appliqué par', 'business_rationale' => 'Justification métier', 'controlled_successor' => 'Successeur contrôlé', 'source_checksum' => 'SHA-256 de l’enregistrement source', 'decision_checksum' => 'SHA-256 de la décision', 'independent_notes' => 'Notes d’examen indépendant', 'approve' => 'Approuver', 'reject' => 'Rejeter', 'record_independent_decision' => 'Enregistrer la décision indépendante', 'final_application' => 'Application finale contrôlée', 'final_application_description' => 'IDMIS revérifiera l’enregistrement source, la décision et les empreintes du catalogue. Le proposant et l’examinateur ne peuvent pas exécuter cette action.', 'not_pinned' => 'Non rattaché',
        'legacy_export' => 'Exporter le registre', 'legacy_empty_title' => 'Aucun dossier ACPA reconstitué', 'legacy_empty_description' => 'Appliquez un lot de reconstitution ACPA historique approuvé indépendamment pour alimenter ce registre immuable.', 'legacy_actions' => 'Actions pour :assessment', 'legacy_view' => 'Voir la reconstitution', 'legacy_sheet_title' => 'Reconstitution ACPA historique', 'legacy_sheet_description' => 'Critères, preuves, constats, affectations des évaluateurs et recours immuables, rapprochés des sources.', 'assessment' => 'Évaluation', 'period' => 'Période', 'overall_score' => 'Note globale', 'imported_by' => 'Importé par', 'record_checksum' => 'SHA-256 du dossier', 'components' => 'Composants reconstitués', 'component_count' => ':count composants immuables', 'assessment_level' => 'Dossier au niveau de l’évaluation', 'score' => 'Note', 'assessor_role' => 'Rôle de l’évaluateur', 'assessor' => 'Évaluateur', 'evidence_file' => 'Fichier de preuve', 'description' => 'Description', 'file_checksum' => 'SHA-256 du fichier', 'unknown_type' => 'Type inconnu',
        'legacy_register_title' => 'Registre de reconstitution ACPA historique', 'legacy_register_description' => 'En-têtes d’évaluations historiques immuables avec critères, manifestes de preuves, constats, affectations des évaluateurs et recours rapprochés.', 'county' => 'Comté', 'criteria' => 'Critères', 'evidence' => 'Preuves', 'findings' => 'Constats', 'assessors' => 'Évaluateurs', 'appeals' => 'Recours', 'source' => 'Source', 'imported_at' => 'Importé le',
    ],
];
