<?php

return [
    'create_collaboration_plan' => 'Créer un plan de collaboration', 'partner' => 'Partenaire', 'starts_on' => 'Commence le', 'ends_on' => 'Se termine le', 'add_accountable_action' => 'Ajouter une action assortie d’une responsabilité', 'county' => 'Comté', 'accountable_owner' => 'Responsable redevable', 'accountable_organization' => 'Organisation redevable', 'due_on' => 'Échéance', 'upload_action_evidence' => 'Téléverser la preuve de l’action', 'source_type' => 'Type de source', 'submit_action_progress' => 'Soumettre l’avancement de l’action', 'verify_action_progress' => 'Vérifier l’avancement de l’action', 'decision' => 'Décision',
    'request_agreement_change' => 'Demander une modification de l’accord', 'change_type' => 'Type de modification', 'effective_date' => 'Date d’effet', 'revised_end_date' => 'Date de fin révisée', 'upload_change_evidence' => 'Téléverser la preuve de la modification', 'decide_agreement_change' => 'Statuer sur la modification de l’accord', 'upload_agreement_record' => 'Téléverser un dossier d’accord', 'review_agreement' => 'Examiner l’accord', 'submit_agreement_for_approval' => 'Soumettre l’accord pour approbation',
    'create_plan' => 'Créer un plan', 'create_plan_description' => 'Créez un plan limité dans le temps en vue d’une approbation indépendante.', 'transition_plan' => 'Plan :transition', 'plan_transition_description' => 'Consignez une décision attribuable du cycle de vie du plan.', 'add_action' => 'Ajouter une action', 'add_action_description' => 'Attribuez une action de comté mesurable pendant la période approuvée.', 'upload_evidence' => 'Téléverser une preuve', 'upload_action_evidence_description' => 'Joignez un dossier de mise en œuvre numérisé ou natif numérique.', 'submit_progress' => 'Soumettre l’avancement', 'submit_progress_description' => 'L’achèvement exige une preuve saine et une vérification indépendante.', 'verify' => 'Vérifier', 'verify_progress_description' => 'Consignez une décision de vérification indépendante et immuable.',
    'preview_document' => 'Prévisualiser :title', 'request_change' => 'Demander une modification', 'request_change_description' => 'Proposez un avenant, un renouvellement, une suspension ou une résiliation sans réécrire l’accord approuvé.', 'upload_change_evidence_description' => 'Joignez l’instrument signé d’avenant, de renouvellement, de suspension ou de résiliation.', 'record_decision' => 'Consigner la décision', 'change_decision_description' => 'Un approbateur indépendant examine la preuve saine et consigne une décision immuable.', 'upload_record' => 'Téléverser le dossier', 'upload_record_description' => 'Ajoutez une copie numérisée ou native numérique conservée de manière privée. Les fichiers sont liés à une somme de contrôle et analysés pour la sécurité.', 'agreement_decision_description' => 'Approuvez ou rejetez cet accord soumis indépendamment. L’auteur de la soumission ne peut pas prendre cette décision.', 'submit_for_approval' => 'Soumettre pour approbation', 'submit_for_approval_description' => 'Confirmez que le dossier du référentiel est complet. La soumission verrouille les téléversements ultérieurs et envoie l’accord pour une décision indépendante.',
    'actions_for_record' => 'Actions pour :record', 'upload_reconciliation_evidence' => 'Téléverser la preuve de rapprochement', 'upload_reconciliation_evidence_description' => 'Ajoutez au référentiel gouverné un dossier source numérisé ou natif numérique.', 'reconcile_contribution' => 'Rapprocher la contribution', 'reconcile_contribution_description' => 'Décision indépendante selon le principe préparateur-vérificateur fondée sur la preuve saine jointe.', 'download_document' => 'Télécharger :title',
];
