<?php

return [
    'operational_control_alerts' => 'Alertes de contrôle opérationnel', 'operational_control_alerts_description' => 'Surveillance idempotente de l’expiration des accords et des rapprochements de contributions en retard, en exception ou rejetés.', 'no_operational_alerts' => 'Aucune alerte opérationnelle partenaire', 'no_operational_alerts_description' => 'Le contrôle planifié n’a détecté aucune expiration ni exception de rapprochement dans votre périmètre de comté.', 'alert' => 'Alerte', 'partner_county' => 'Partenaire / comté', 'status' => 'Statut', 'detected' => 'Détectée', 'alert_actions' => 'Actions pour :alert', 'resolve_operational_alert' => 'Résoudre l’alerte opérationnelle', 'resolve_operational_alert_description' => 'Consignez la remédiation ou une décision formelle d’acceptation du risque ; les preuves sources restent inchangées.', 'record_disposition' => 'Consigner la décision', 'disposition' => 'Décision', 'resolution_evidence' => 'Preuve de résolution',
    'severity_critical' => 'Critique', 'severity_warning' => 'Avertissement', 'status_open' => 'Ouverte', 'status_resolved' => 'Résolue', 'status_accepted_risk' => 'Risque accepté', 'status_system_resolved' => 'Résolue par le système', 'alert_type_agreement_expired' => 'Accord expiré', 'alert_type_agreement_expiry_due' => 'Échéance de l’accord proche', 'alert_type_contribution_reconciliation_overdue' => 'Rapprochement de contribution en retard', 'alert_type_contribution_reconciliation_exception' => 'Exception de rapprochement de contribution', 'alert_type_contribution_reconciliation_rejected' => 'Rapprochement de contribution rejeté',
    'contribution_register' => 'Registre de rapprochement des contributions', 'contribution_register_description' => 'Les engagements déclarés sont rapprochés indépendamment des preuves DMS saines et conservés dans un historique de décisions lié par somme de contrôle.', 'no_contributions' => 'Aucune contribution enregistrée', 'no_contributions_description' => 'Enregistrez une contribution partenaire pour démarrer la collecte des preuves et le rapprochement.',
    'partner_project' => 'Partenaire / projet', 'county' => 'Comté', 'reported' => 'Déclaré', 'decision' => 'Décision', 'actions' => 'Actions', 'of' => 'sur', 'view_record' => 'Voir la fiche', 'verified_commitment' => 'Engagement vérifié', 'verified_disbursement' => 'Décaissement vérifié', 'verified_in_kind' => 'Valeur en nature vérifiée', 'source_reference' => 'Référence source', 'review_note' => 'Note d’examen',
    'contribution_chain' => 'chaîne de contribution, de preuve et de rapprochement.', 'reported_commitment' => 'Engagement déclaré', 'reported_disbursement' => 'Décaissement déclaré', 'evidence' => 'Preuves', 'ellipsis' => '…', 'decision_history' => 'Historique des décisions', 'no_reconciliation_decision' => 'Aucune décision de rapprochement pour le moment.',
    'collaboration_plans' => 'Plans et actions de collaboration', 'collaboration_plans_description' => 'Plans partenaires/comtés approuvés, assortis d’actions responsables, de preuves et d’une vérification indépendante des progrès.', 'no_collaboration_plans' => 'Aucun plan de collaboration', 'no_collaboration_plans_description' => 'Créez un plan gouverné pour coordonner les actions du partenaire et du comté.', 'no_accountable_actions' => 'Aucune action responsable attribuée.',
    'due' => 'échéance', 'empty_value' => '—', 'reference' => 'Référence', 'title_label' => 'Titre', 'objective' => 'Objectif', 'create_draft' => 'Créer le brouillon', 'record' => 'Consigner', 'code' => 'Code', 'description_label' => 'Description', 'assign_action' => 'Attribuer l’action', 'progress' => 'Progrès', 'narrative' => 'Compte rendu', 'submit_verification' => 'Soumettre à vérification', 'verification_note' => 'Note de vérification',
    'open_parenthesis' => '(', 'close_parenthesis' => ')',
    'agreement_register' => 'Registre d’approbation des accords', 'agreement_register_description' => 'Les protocoles et instruments de coopération documentés passent du projet à l’approbation indépendante avec un historique immuable.', 'no_agreements' => 'Aucun accord enregistré', 'no_agreements_description' => 'Enregistrez un accord pour démarrer son cycle documentaire et d’approbation.',
    'separator' => '·', 'label_separator' => ':', 'to' => 'au', 'repository_records' => 'Documents du référentiel', 'no_repository_records' => 'Aucun document numérisé ou créé nativement au format numérique n’a été téléversé.', 'scan' => 'analyse', 'ocr' => 'OCR', 'preview' => 'Aperçu', 'download' => 'Télécharger',
    'change_history' => 'Historique des modifications après approbation', 'version_prefix' => 'v', 'effective' => 'En vigueur', 'authorized_preview' => 'Aperçu autorisé de la copie privée du référentiel.', 'revised_title' => 'Titre révisé', 'revised_summary' => 'Résumé révisé', 'revised_value' => 'Valeur engagée révisée', 'reason' => 'Motif',
    'submit_governed_request' => 'Soumettre la demande gouvernée', 'record_title' => 'Titre du document', 'category' => 'Catégorie', 'document' => 'Document', 'upload_securely' => 'Téléverser en sécurité', 'decision_note' => 'Note de décision', 'retain_decision' => 'Conserver la décision', 'agreement_file' => 'Fichier de l’accord', 'uploading' => 'Téléversement', 'percent' => '%', 'decision_rationale' => 'Justification de la décision', 'record_decision' => 'Consigner la décision', 'confirm_submission' => 'Confirmer la soumission',
    'development_cooperation_intelligence' => 'Renseignements sur la coopération au développement', 'partner_coordination' => 'Coordination des partenaires', 'partner_coordination_description' => 'Un répertoire gouverné des partenaires, accords, contributions financières et en nature, couverture géographique, chevauchements et possibilités de collaboration.', 'sector' => 'Secteur',
    'status_draft' => 'Brouillon', 'status_pending_approval' => 'En attente d’approbation', 'status_active' => 'Actif', 'status_in_progress' => 'En cours', 'status_completed' => 'Terminé', 'status_suspended' => 'Suspendu', 'status_rejected' => 'Rejeté',
    'no_matching_partner_profiles' => 'Aucun profil de partenaire correspondant', 'no_matching_partner_profiles_description' => 'Ajustez la recherche ou les dates de rapport, ou ajoutez un profil de partenaire de développement autorisé.', 'collaboration_intelligence' => 'Renseignements sur la collaboration', 'collaboration_intelligence_description' => 'Chevauchements et synergies potentiels détectés à partir des projets, comtés et secteurs partagés.', 'refresh_analysis' => 'Actualiser l’analyse', 'no_collaboration_alerts' => 'Aucune alerte de collaboration', 'no_collaboration_alerts_description' => 'Exécutez l’analyse du portefeuille après l’enregistrement des activités et engagements des partenaires.',
    'alert_type_overlap' => 'Chevauchement de portefeuille', 'severity_low' => 'Faible', 'severity_medium' => 'Moyenne', 'severity_high' => 'Élevée', 'partner_pair' => ':primary × :related', 'resolution_value' => 'Résolution : :resolution', 'resolve_collaboration_alert' => 'Résoudre l’alerte de collaboration', 'resolve_alert' => 'Résoudre l’alerte', 'resolve_collaboration_alert_description' => ':primary et :related : consignez la résolution convenue et la prochaine action.', 'resolution_and_next_action' => 'Résolution et prochaine action', 'resolution' => 'Résolution',
    'geographic_partner_portfolio' => 'Portefeuille géographique des partenaires', 'nationwide_portfolio_description' => 'Géographie nationale avec uniquement les comtés autorisés du portefeuille activés.', 'single_county_portfolio_description' => 'Votre comté est automatiquement agrandi et isolé.', 'select_active_county_description' => 'Sélectionnez un comté actif pour examiner son portefeuille de partenaires.', 'county_portfolio' => 'Portefeuille du comté', 'select_authorized_county' => 'Sélectionnez un comté autorisé', 'partners' => 'Partenaires', 'active_agreements' => 'Accords actifs', 'committed' => 'Engagé', 'disbursed' => 'Décaissé', 'portfolio_selection_notice' => 'La sélection met à jour ce résumé sans quitter l’espace de travail des partenaires.', 'select_county_on_map' => 'Sélectionnez un comté autorisé sur la carte pour examiner son portefeuille.',
    'form_register_partner' => 'Enregistrer un partenaire', 'form_register_partner_description' => 'Définissez l’organisation, les représentants autorisés, les comtés, les secteurs et les modalités de mise en œuvre.', 'form_organization' => 'Organisation', 'form_partner_type' => 'Type de partenaire', 'form_country' => 'Pays', 'form_focal_point' => 'Point focal', 'form_focal_email' => 'Adresse du point focal', 'form_website' => 'Site web', 'form_county_portfolio' => 'Portefeuille de comtés', 'form_sector_portfolio' => 'Portefeuille sectoriel', 'form_authorized_partner_users' => 'Utilisateurs partenaires autorisés', 'form_strategic_priorities' => 'Priorités stratégiques', 'form_create_partner_profile' => 'Créer le profil du partenaire',
    'form_register_agreement' => 'Enregistrer un accord', 'form_register_agreement_description' => 'Cataloguez les protocoles d’accord, instruments de financement et cadres de coopération.', 'form_partner' => 'Partenaire', 'form_reference' => 'Référence', 'form_agreement_type' => 'Type d’accord', 'form_title' => 'Titre', 'form_starts_on' => 'Date de début', 'form_ends_on' => 'Date de fin', 'form_committed_value' => 'Valeur engagée', 'form_currency' => 'Devise', 'form_document_reference' => 'Référence du document', 'form_document_reference_placeholder' => 'Dossier du référentiel ou URL sécurisée', 'form_summary' => 'Résumé',
    'form_report_contribution' => 'Déclarer une contribution', 'form_report_contribution_description' => 'Consignez qui finance quoi, où et comment avec une provenance traçable.', 'form_project' => 'Projet', 'form_financial_year' => 'Exercice financier', 'form_contribution_type' => 'Type de contribution', 'form_committed' => 'Engagé', 'form_disbursed' => 'Décaissé', 'form_in_kind_value' => 'Valeur en nature', 'form_source_system' => 'Système source', 'form_partner_portal' => 'Portail partenaire', 'form_description' => 'Description', 'form_record_contribution' => 'Enregistrer la contribution',
];
