<?php

return [
    'operational_control_alerts' => 'Alertes de contrôle opérationnel', 'operational_control_alerts_description' => 'Surveillance idempotente de l’expiration des accords et des rapprochements de contributions en retard, en exception ou rejetés.', 'no_operational_alerts' => 'Aucune alerte opérationnelle partenaire', 'no_operational_alerts_description' => 'Le contrôle planifié n’a détecté aucune expiration ni exception de rapprochement dans votre périmètre de comté.', 'alert' => 'Alerte', 'partner_county' => 'Partenaire / comté', 'status' => 'Statut', 'detected' => 'Détectée', 'alert_actions' => 'Actions pour :alert', 'resolve_operational_alert' => 'Résoudre l’alerte opérationnelle', 'resolve_operational_alert_description' => 'Consignez la remédiation ou une décision formelle d’acceptation du risque ; les preuves sources restent inchangées.', 'record_disposition' => 'Consigner la décision', 'disposition' => 'Décision', 'resolution_evidence' => 'Preuve de résolution',
    'severity_critical' => 'Critique', 'severity_warning' => 'Avertissement', 'status_open' => 'Ouverte', 'status_resolved' => 'Résolue', 'status_accepted_risk' => 'Risque accepté', 'status_system_resolved' => 'Résolue par le système', 'alert_type_agreement_expired' => 'Accord expiré', 'alert_type_agreement_expiry_due' => 'Échéance de l’accord proche', 'alert_type_contribution_reconciliation_overdue' => 'Rapprochement de contribution en retard', 'alert_type_contribution_reconciliation_exception' => 'Exception de rapprochement de contribution', 'alert_type_contribution_reconciliation_rejected' => 'Rapprochement de contribution rejeté',
    'contribution_register' => 'Registre de rapprochement des contributions', 'contribution_register_description' => 'Les engagements déclarés sont rapprochés indépendamment des preuves DMS saines et conservés dans un historique de décisions lié par somme de contrôle.', 'no_contributions' => 'Aucune contribution enregistrée', 'no_contributions_description' => 'Enregistrez une contribution partenaire pour démarrer la collecte des preuves et le rapprochement.',
    'partner_project' => 'Partenaire / projet', 'county' => 'Comté', 'reported' => 'Déclaré', 'decision' => 'Décision', 'actions' => 'Actions', 'of' => 'sur', 'view_record' => 'Voir la fiche', 'verified_commitment' => 'Engagement vérifié', 'verified_disbursement' => 'Décaissement vérifié', 'verified_in_kind' => 'Valeur en nature vérifiée', 'source_reference' => 'Référence source', 'review_note' => 'Note d’examen',
    'contribution_chain' => 'chaîne de contribution, de preuve et de rapprochement.', 'reported_commitment' => 'Engagement déclaré', 'reported_disbursement' => 'Décaissement déclaré', 'evidence' => 'Preuves', 'ellipsis' => '…', 'decision_history' => 'Historique des décisions', 'no_reconciliation_decision' => 'Aucune décision de rapprochement pour le moment.',
    'collaboration_plans' => 'Plans et actions de collaboration', 'collaboration_plans_description' => 'Plans partenaires/comtés approuvés, assortis d’actions responsables, de preuves et d’une vérification indépendante des progrès.', 'no_collaboration_plans' => 'Aucun plan de collaboration', 'no_collaboration_plans_description' => 'Créez un plan gouverné pour coordonner les actions du partenaire et du comté.', 'no_accountable_actions' => 'Aucune action responsable attribuée.',
    'due' => 'échéance', 'empty_value' => '—', 'reference' => 'Référence', 'title_label' => 'Titre', 'objective' => 'Objectif', 'create_draft' => 'Créer le brouillon', 'record' => 'Consigner', 'code' => 'Code', 'description_label' => 'Description', 'assign_action' => 'Attribuer l’action', 'progress' => 'Progrès', 'narrative' => 'Compte rendu', 'submit_verification' => 'Soumettre à vérification', 'verification_note' => 'Note de vérification',
    'open_parenthesis' => '(', 'close_parenthesis' => ')',
    'agreement_register' => 'Registre d’approbation des accords', 'agreement_register_description' => 'Les protocoles et instruments de coopération documentés passent du projet à l’approbation indépendante avec un historique immuable.', 'no_agreements' => 'Aucun accord enregistré', 'no_agreements_description' => 'Enregistrez un accord pour démarrer son cycle documentaire et d’approbation.',
    'separator' => '·', 'label_separator' => ':', 'to' => 'au', 'repository_records' => 'Documents du référentiel', 'no_repository_records' => 'Aucun document numérisé ou créé nativement au format numérique n’a été téléversé.', 'scan' => 'analyse', 'ocr' => 'OCR', 'preview' => 'Aperçu', 'download' => 'Télécharger',
    'change_history' => 'Historique des modifications après approbation', 'version_prefix' => 'v', 'effective' => 'En vigueur', 'authorized_preview' => 'Aperçu autorisé de la copie privée du référentiel.', 'revised_title' => 'Titre révisé', 'revised_summary' => 'Résumé révisé', 'revised_value' => 'Valeur engagée révisée', 'reason' => 'Motif',
    'submit_governed_request' => 'Soumettre la demande gouvernée', 'record_title' => 'Titre du document', 'category' => 'Catégorie', 'document' => 'Document', 'upload_securely' => 'Téléverser en sécurité', 'decision_note' => 'Note de décision', 'retain_decision' => 'Conserver la décision', 'agreement_file' => 'Fichier de l’accord', 'uploading' => 'Téléversement', 'percent' => '%', 'decision_rationale' => 'Justification de la décision', 'record_decision' => 'Consigner la décision', 'confirm_submission' => 'Confirmer la soumission',
];
