<?php

return [
    'physical_progress' => 'Avancement physique', 'approved_budget' => 'Budget approuvé', 'expenditure' => 'Dépenses', 'scope' => 'Périmètre', 'delivery_scope' => 'Périmètre de réalisation', 'results_links' => 'Liens vers les résultats', 'control_status' => 'État des contrôles',
    'upload_project_record' => 'Téléverser un dossier de projet', 'document_title' => 'Titre du document', 'record_purpose' => 'Objet du dossier', 'record_category' => 'Catégorie du dossier',
    'add_milestone' => 'Ajouter un jalon', 'ms_01' => 'MS-01', 'milestone_title' => 'Titre du jalon', 'planned_start' => 'Début prévu', 'planned_end' => 'Fin prévue', 'weight' => 'Pondération %', 'dependencies' => 'Dépendances',
    'add_budget_line' => 'Ajouter une ligne budgétaire', 'bl_01' => 'BL-01', 'category' => 'Catégorie', 'description_label' => 'Description', 'approved_amount' => 'Montant approuvé', 'currency' => 'Devise',
    'register_risk' => 'Enregistrer un risque', 'rsk_01' => 'RSK-01', 'risk_description' => 'Description du risque', 'probability_1_5' => 'Probabilité 1–5', 'impact_1_5' => 'Impact 1–5', 'mitigation' => 'Mesure d’atténuation',
    'add_procurement' => 'Ajouter un marché', 'tender_reference' => 'Référence de l’appel d’offres', 'procurement_title' => 'Titre du marché', 'method' => 'Méthode', 'estimated_value' => 'Valeur estimée', 'planned_notice_date' => 'Date prévue de l’avis',
    'record_the_evidence_based_lifecycle_decision' => 'Consignez la décision de cycle de vie fondée sur des preuves', 'verify_progress_update' => 'Vérifier la mise à jour de l’avancement', 'independent_verification_rationale' => 'Motif de la vérification indépendante',
    'milestones' => 'Jalons', 'budget_lines' => 'Lignes budgétaires', 'risks' => 'Risques', 'procurements' => 'Marchés', 'progress_history' => 'Historique de l’avancement',
    'capture_schedule_baseline' => 'Enregistrer la référence du calendrier', 'record_the_planning_evidence_and_authority_supporting_this_proposed_baseline' => 'Consignez la preuve de planification et l’autorité appuyant cette référence proposée.',
    'approved_baseline' => 'Référence approuvée', 'critical_path' => 'Chemin critique', 'forecast_finish' => 'Fin prévisionnelle', 'forecast_variance' => 'Écart prévisionnel',
    'record_the_independent_schedule_review_evidence_and_decision_rationale' => 'Consignez la preuve de l’examen indépendant du calendrier et le motif de la décision.',
    'register_project_resource' => 'Enregistrer une ressource du projet', 'resource_code' => 'Code de la ressource', 'resource_name' => 'Nom de la ressource', 'resource_type' => 'Type de ressource', 'capacity_unit' => 'Unité de capacité', 'available_from' => 'Disponible à partir du', 'available_to' => 'Disponible jusqu’au',
    'allocate_project_resource' => 'Affecter une ressource au projet', 'resource' => 'Ressource', 'milestone' => 'Jalon', 'allocation_start' => 'Début de l’affectation', 'allocation_end' => 'Fin de l’affectation',
    'planned_value' => 'Valeur planifiée', 'earned_value' => 'Valeur acquise', 'actual_cost' => 'Coût réel', 'estimate_at_completion' => 'Estimation à l’achèvement', 'cost_performance_index' => 'Indice de performance des coûts', 'schedule_performance_index' => 'Indice de performance du calendrier', 'variance_at_completion' => 'Écart à l’achèvement', 'to_complete_index' => 'Indice de performance à achever',
    'title_label' => 'Titre', 'actual_start' => 'Début réel', 'actual_end' => 'Fin réelle', 'progress' => 'Avancement (%)', 'funding_source' => 'Source de financement', 'review_due' => 'Échéance de l’examen', 'contract_value' => 'Valeur du contrat', 'award_date' => 'Date d’attribution', 'supplier_name' => 'Nom du fournisseur', 'contract_reference' => 'Référence du contrat',
    'preview_document' => 'Aperçu de :title', 'review_reporting_date' => 'Examiner :date', 'verify_physical_progress_description' => 'Vérifiez indépendamment la soumission d’avancement physique de :progress %.', 'project_action_description' => 'Terminez l’action de projet gouvernée et consignez-la dans la piste d’audit.', 'capture_baseline' => 'Capturer la référence', 'capture_baseline_description' => 'Figez le plan actuel complet des jalons pour approbation indépendante et mesure ultérieure des écarts.', 'review_schedule_baseline' => 'Examiner la référence du calendrier v:version', 'review_pending_baseline' => 'Examiner la référence en attente v:version', 'review_baseline_description' => 'Approuvez indépendamment l’instantané des jalons lié à la somme de contrôle ou rejetez-le avec des preuves.', 'add_resource' => 'Ajouter une ressource', 'resource_currency_description' => 'La capacité et les tarifs sont enregistrés en :currency, héritée du projet.', 'add_allocation' => 'Ajouter une allocation', 'add_allocation_description' => 'Allouez une capacité quotidienne uniforme dans les périodes de la ressource et du jalon.', 'actions_for_record' => 'Actions pour :record',
];
