<?php

return [
    'stage_identity_lifecycle_change' => 'Préparer une modification du cycle de vie de l’identité', 'lifecycle_event' => 'Événement du cycle de vie', 'target_identity' => 'Identité cible', 'authoritative_source_system' => 'Système source faisant autorité', 'unique_source_event_id' => 'Identifiant unique de l’événement source', 'source_evidence_reference' => 'Référence de la preuve source', 'effective_at' => 'Prend effet le',
    'proposed_home_county' => 'Comté d’origine proposé', 'proposed_assigned_counties' => 'Comtés d’affectation proposés', 'business_reason_and_source_reconciliation_note' => 'Motif opérationnel et note de rapprochement de la source', 'independent_decision' => 'Décision indépendante', 'decision_rationale' => 'Motif de la décision',
    'record_security_response' => 'Enregistrer la réponse de sécurité', 'assigned_incident_lead' => 'Responsable d’incident désigné', 'response_playbook' => 'Guide de réponse', 'initial_severity' => 'Gravité initiale', 'incident_or_exercise_title' => 'Titre de l’incident ou de l’exercice', 'controlled_incident_summary' => 'Résumé contrôlé de l’incident', 'affected_services_comma_separated' => 'Services touchés (séparés par des virgules)', 'observed_or_simulated_business_impact' => 'Impact opérationnel observé ou simulé', 'soc_service_desk_privacy_or_legal_reference' => 'Référence SOC, centre de services, confidentialité ou juridique', 'exercise_objectives_comma_separated' => 'Objectifs de l’exercice (séparés par des virgules)',
    'incident_lead' => 'Responsable de l’incident', 'summary' => 'Résumé', 'affected_services' => 'Services touchés', 'business_impact' => 'Impact opérationnel', 'acknowledgement_target' => 'Objectif d’accusé de réception', 'containment_target' => 'Objectif de confinement', 'external_reference' => 'Référence externe', 'exercise_outcome' => 'Résultat de l’exercice', 'root_cause' => 'Cause première', 'corrective_actions' => 'Actions correctives',
    'controlled_evidence_reference' => 'Référence de preuve contrôlée', 'verified_root_cause' => 'Cause première vérifiée', 'completed_and_tracked_corrective_actions' => 'Actions correctives achevées et suivies', 'lessons_and_playbook_improvements' => 'Enseignements et améliorations du guide', 'next_exercise_due' => 'Échéance du prochain exercice',
    'record_title' => 'Titre du dossier', 'records_category' => 'Catégorie de dossiers', 'source_type' => 'Type de source', 'evidence_purpose' => 'Objet de la preuve', 'composer_components' => 'Composants Composer', 'javascript_components' => 'Composants JavaScript', 'npm_vulnerabilities' => 'Vulnérabilités NPM', 'composer_lock_sha256' => 'SHA-256 du verrou Composer', 'artifact_sha256' => 'SHA-256 de l’artefact', 'evidence_sha256' => 'SHA-256 de la preuve',
    'request_temporary_access' => 'Demander un accès temporaire', 'beneficiary_with_strong_authentication' => 'Bénéficiaire avec authentification forte', 'access_type' => 'Type d’accès', 'geographic_scope' => 'Périmètre géographique', 'least_privilege_permissions' => 'Autorisations de moindre privilège', 'counties_in_scope' => 'Comtés concernés', 'access_starts' => 'Début de l’accès', 'access_expires' => 'Expiration de l’accès', 'security_incident_reference' => 'Référence de l’incident de sécurité', 'business_justification_and_expected_outcome' => 'Justification opérationnelle et résultat attendu', 'compensating_controls_and_monitoring' => 'Contrôles compensatoires et surveillance',
    'independent_evidence_based_rationale' => 'Motif indépendant fondé sur des preuves', 'immediate_revocation_reason' => 'Motif de révocation immédiate', 'post_use_outcome' => 'Résultat après utilisation', 'audit_findings_and_follow_up' => 'Constats d’audit et suivi',
    'review_decision' => 'Décision de réexamen', 'treatment_status' => 'État du traitement', 'residual_likelihood_1_5' => 'Probabilité résiduelle (1–5)', 'residual_impact_1_5' => 'Impact résiduel (1–5)', 'risk_acceptance_reference' => 'Référence d’acceptation du risque', 'evidence_references_comma_separated' => 'Références des preuves (séparées par des virgules)', 'independent_findings' => 'Constats indépendants',
    'certification_decision' => 'Décision de certification', 'evidence_based_rationale' => 'Motif fondé sur des preuves', 'required_remediation' => 'Mesure corrective requise', 'remediation_due_date' => 'Échéance de la mesure corrective',
    'register_threat_scenario' => 'Enregistrer un scénario de menace', 'threat_reference' => 'Référence de la menace', 'threat_title' => 'Titre de la menace', 'threat_category' => 'Catégorie de menace', 'risk_owner' => 'Responsable du risque', 'affected_asset_or_service' => 'Actif ou service touché', 'threat_actor' => 'Acteur de la menace', 'likelihood_1_5' => 'Probabilité (1–5)', 'impact_1_5' => 'Impact (1–5)', 'review_due_date' => 'Échéance du réexamen', 'abuse_or_failure_scenario' => 'Scénario d’abus ou de défaillance', 'entry_points_comma_separated' => 'Points d’entrée (séparés par des virgules)', 'existing_controls_comma_separated' => 'Contrôles existants (séparés par des virgules)', 'treatment_plan_and_accountable_outcome' => 'Plan de traitement et résultat assorti d’une responsabilité',
    'launch_access_certification' => 'Lancer la certification des accès', 'campaign_reference' => 'Référence de la campagne', 'campaign_name' => 'Nom de la campagne', 'independent_reviewer' => 'Examinateur indépendant', 'roles_in_scope' => 'Rôles concernés', 'review_period_from' => 'Période de réexamen du', 'review_period_to' => 'Période de réexamen au', 'certification_due' => 'Échéance de la certification', 'scope_criteria_and_exclusions' => 'Périmètre, critères et exclusions',
];
