<?php

return [
    'title' => 'Paramètres du profil', 'profile_photo' => 'Photo de profil', 'profile_photo_description' => 'Téléversez, positionnez et recadrez la photo affichée dans l’en-tête de votre compte authentifié.', 'account_status' => 'Statut du compte', 'account_status_description' => 'Votre identité gouvernée et son état de vérification.', 'role' => 'Rôle', 'email_verification' => 'Vérification de l’adresse électronique', 'verified' => 'Vérifiée', 'pending_verification' => 'Vérification en attente', 'account_created' => 'Compte créé', 'not_recorded' => 'Non enregistré',
    'personal_information' => 'Informations personnelles', 'personal_information_description' => 'Maintenez à jour le nom et l’adresse électronique de votre compte.', 'edit' => 'Modifier', 'edit_personal_information' => 'Modifier les informations personnelles', 'email_change_notice' => 'La modification de votre adresse peut nécessiter une nouvelle vérification.', 'full_name' => 'Nom complet', 'email_address' => 'Adresse électronique', 'save_changes' => 'Enregistrer les modifications', 'email_unverified' => 'Votre adresse électronique n’est pas vérifiée.', 'resend_verification' => 'Renvoyer le courriel de vérification', 'verification_sent' => 'Un nouveau lien de vérification a été envoyé.',
    'access_scope' => 'Périmètre d’accès', 'access_scope_description' => 'Attribué par un administrateur autorisé.', 'home_county' => 'Comté principal', 'national_portfolio' => 'National / portefeuille', 'assigned_counties' => 'Comtés attribués', 'none' => 'Aucun', 'account_controls' => 'Contrôles du compte', 'account_controls_description' => 'Accédez aux contrôles complets de sécurité, d’espace de travail et d’affichage de ce compte.', 'password_mfa_passkeys' => 'Mot de passe, MFA et clés d’accès', 'appearance_theme' => 'Apparence et thème',
    'account_lifecycle' => 'Cycle de vie du compte', 'account_lifecycle_description' => 'Mettez fin définitivement à l’accès et supprimez votre photo de profil personnelle.', 'delete_account' => 'Supprimer le compte', 'delete_account_warning' => 'Cette action vous déconnecte et supprime votre accès. Elle ne peut pas être annulée sans un administrateur autorisé.', 'confirm_account_deletion' => 'Confirmer la suppression du compte', 'confirm_account_deletion_description' => 'Une fois votre compte supprimé, ses ressources et son accès seront indisponibles. Saisissez votre mot de passe pour confirmer.', 'current_password' => 'Mot de passe actuel', 'cancel' => 'Annuler', 'deleting_account' => 'Suppression du compte…',
    'photo_type_error' => 'Choisissez une image JPEG, PNG ou WebP.', 'photo_size_error' => 'Choisissez une image de moins de 10 Mo.', 'photo_dimensions_error' => 'Choisissez une image d’au moins 256 × 256 pixels.', 'photo_open_error' => 'L’image sélectionnée n’a pas pu être ouverte.', 'photo_crop_error' => 'L’image recadrée n’a pas pu être préparée.', 'updated' => 'Mise à jour', 'no_photo' => 'Aucune photo de profil téléversée', 'replace_crop' => 'Remplacer et recadrer', 'upload_crop' => 'Téléverser et recadrer', 'remove' => 'Supprimer', 'choose_photo' => 'Choisir une photo de profil', 'crop_photo' => 'Recadrer la photo de profil', 'crop_photo_description' => 'Réglez le zoom et la position. La photo enregistrée correspondra exactement à l’aperçu carré.', 'crop_preview' => 'Aperçu de la photo recadrée', 'zoom' => 'Zoom', 'separator' => '·', 'multiply' => '×', 'photo_zoom' => 'Zoom de la photo', 'horizontal_position' => 'Position horizontale', 'horizontal_photo_position' => 'Position horizontale de la photo', 'vertical_position' => 'Position verticale', 'vertical_photo_position' => 'Position verticale de la photo', 'keyboard_adjustment' => 'Utilisez les flèches de chaque contrôle pour un réglage précis au clavier.', 'uploading' => 'Téléversement', 'choose_another' => 'Choisir une autre', 'save_cropped_photo' => 'Enregistrer la photo recadrée',
    'processor_errors' => ['decode_failed' => 'Le fichier sélectionné n’a pas pu être décodé comme une image prise en charge.', 'prepare_failed' => 'La photo de profil n’a pas pu être préparée.', 'background_failed' => 'L’arrière-plan de la photo de profil n’a pas pu être préparé.', 'resize_failed' => 'La photo de profil n’a pas pu être redimensionnée.', 'encode_failed' => 'La photo de profil n’a pas pu être encodée de manière sécurisée.'],
    'photo_errors' => ['store_failed' => 'La photo de profil n’a pas pu être enregistrée.', 'integrity_failed' => 'La photo de profil enregistrée a échoué au contrôle d’intégrité.'], 'audit' => ['photo_updated' => 'Photo de profil mise à jour.', 'photo_removed' => 'Photo de profil supprimée.'],
    'appearance_settings' => 'Paramètres d’apparence', 'appearance_settings_description' => 'Mettez à jour les paramètres d’apparence de votre compte',
];
