<?php

return [
    'faqs_title' => 'Questions fréquemment posées', 'faqs_meta' => 'Réponses sur l’accès, les comptes, les informations, la sécurité et l’assistance IDMIS.', 'guidance' => 'Guide IDMIS', 'faqs_intro' => 'Trouvez des réponses rapides sur l’accès au système, les utilisateurs autorisés, le traitement des informations et l’assistance.',
    'questions' => [
        ['question' => 'Qu’est-ce qu’IDMIS ?', 'answer' => 'Le Système intégré d’information de gestion de la dévolution est une plateforme sécurisée qui coordonne les programmes, suit les résultats, gère les preuves, partage les connaissances et renforce la responsabilité des gouvernements national et de comté.'],
        ['question' => 'Qui peut accéder au système ?', 'answer' => 'L’accès est limité au personnel national, des comtés, de vérification indépendante, des programmes et d’assistance dûment autorisé. Les permissions dépendent de l’organisation et des responsabilités attribuées.'],
        ['question' => 'Comment obtenir un compte ?', 'answer' => 'Les comptes sont créés ou accordés par les administrateurs IDMIS autorisés. Il n’existe aucune inscription publique. Contactez l’administrateur désigné de votre comté ou programme si vos fonctions exigent un accès.'],
        ['question' => 'Que faire si je ne peux pas me connecter ?', 'answer' => 'Vérifiez que vous utilisez l’adresse professionnelle officielle de votre compte. Réinitialisez le mot de passe si nécessaire. Si le problème persiste, contactez votre administrateur ou consultez la page d’assistance.'],
        ['question' => 'Quelles informations IDMIS gère-t-il ?', 'answer' => 'IDMIS gère les informations de programme et de performance, les preuves d’évaluation, les rapports, les décisions et les dossiers de coordination approuvés. L’accès dépend du rôle, de l’organisation, du périmètre territorial et de la finalité.'],
        ['question' => 'Comment fonctionne le processus d’évaluation ACPA ?', 'answer' => 'Les utilisateurs autorisés des comtés préparent les réponses aux critères et les preuves obligatoires. Les évaluateurs désignés et les rôles de vérification indépendante examinent le dossier, consignent les constatations et le font progresser dans les décisions et recours contrôlés. Les scores publiés proviennent uniquement de critères complets et vérifiés et de résultats immuables.'],
        ['question' => 'Peut-on importer des évaluations ACPA antérieures ?', 'answer' => 'Oui. Les agents de migration autorisés peuvent préparer un dossier historique CSV ou XLSX approuvé comprenant l’évaluation, les résultats par critère, le manifeste des preuves, les constatations, les évaluateurs et les recours. Une vérification indépendante et un opérateur final distinct sont requis avant son intégration aux données historiques IDMIS.'],
        ['question' => 'Peut-on téléverser des preuves numérisées et des fichiers numériques ?', 'answer' => 'Oui. Une preuve peut être une copie numérisée ou un fichier numérique natif. Les téléversements sont privés, analysés contre les logiciels malveillants, vérifiés par somme de contrôle, versionnés et liés au comté, cycle, critère ou dossier autorisé avant de pouvoir appuyer une décision.'],
        ['question' => 'Que permet le Gestionnaire de fichiers ?', 'answer' => 'Les utilisateurs autorisés peuvent rechercher des dossiers et fichiers, utiliser la grille ou la liste, prévisualiser les documents pris en charge, examiner leur provenance et leurs versions, téléverser des fichiers et effectuer les déplacements groupés permis. Les gels juridiques, le périmètre territorial, la conservation et les permissions documentaires restent applicables.'],
        ['question' => 'Comment fonctionnent les filtres et analyses détaillées ?', 'answer' => 'Les filtres de cycle, comté et date limitent les données autorisées et sont conservés dans les analyses détaillées prises en charge. Les utilisateurs habilités peuvent enregistrer des vues nommées, comparer graphiques et tendances et exporter les mêmes données en CSV, XLSX, JSON ou PDF.'],
        ['question' => 'IDMIS comprend-il les sous-comtés et les quartiers ?', 'answer' => 'Oui. La hiérarchie administrative gouvernée contient les 47 comtés du Kenya, leurs unités parentes de sous-comté ou circonscription et leurs quartiers. Ces unités servent au filtrage et aux références ; les limites cartographiques restent des aides visuelles et non des preuves cadastrales ou juridiques.'],
        ['question' => 'Quelles langues sont prises en charge ?', 'answer' => 'L’interface prend en charge l’anglais, le kiswahili et le français. Le sélecteur de langue permet de changer de langue et les utilisateurs connectés peuvent conserver leur préférence. Les noms officiels, codes, sommes de contrôle et références de sources restent inchangés.'],
        ['question' => 'Les actions groupées et les exports sont-ils limités ?', 'answer' => 'Oui. Le serveur revérifie la permission, le périmètre territorial, l’état des dossiers et toute la sélection avant une action groupée ou un export. Modifier les filtres, URL, identifiants de requête ou formats d’export ne permet pas d’élargir l’accès.'],
        ['question' => 'Les utilisateurs d’un comté peuvent-ils voir les documents restreints d’un autre comté ?', 'answer' => 'Pas par défaut. Les documents de travail restreints restent dans le comté et le processus approuvés ; le suivi national et la publication exigent des permissions explicites.'],
        ['question' => 'IDMIS fonctionne-t-il avec une connexion lente ou interrompue ?', 'answer' => 'Le service privilégie une faible consommation de bande passante, une progression claire des téléversements, des opérations relançables et des modules d’apprentissage hors ligne contrôlés.'],
        ['question' => 'Où en apprendre davantage sur la dévolution ?', 'answer' => 'Le site du Département d’État chargé de la Dévolution publie politiques, plans, guides, actualités et ressources sur le système décentralisé du Kenya.'],
    ],
    'still_need_help' => 'Besoin d’aide supplémentaire ?', 'support_or_sign_in' => 'Consultez les canaux d’assistance ou revenez à la connexion.', 'help_and_support' => 'Aide et assistance', 'sign_in' => 'Se connecter', 'general_faqs' => 'Lire les FAQ générales sur la dévolution',
];
