<?php

return [
    'eyebrow' => 'Déplacements officiels contrôlés', 'title' => 'Autorisation de déplacement', 'description' => 'Faites passer les déplacements officiels par l’examen hiérarchique, l’engagement financier indépendant, le suivi des SLA et une piste de décision immuable.',
    'clearance_status' => 'Statut de l’autorisation', 'county' => 'Comté', 'sector' => 'Secteur', 'requests' => 'Demandes', 'approved' => 'Approuvées', 'rejected' => 'Rejetées', 'average_decision_time' => 'Délai moyen de décision', 'hours' => 'heures',
    'cost_by_currency' => 'Coût par devise', 'cost_by_currency_description' => 'L’exposition estimée reste propre à chaque devise afin d’éviter les conversions incorrectes.', 'currency' => 'Devise', 'total_estimate' => 'Estimation totale', 'average' => 'Moyenne', 'frequent_destinations' => 'Destinations fréquentes', 'frequent_destinations_description' => 'Principales destinations par fréquence de demande dans le portefeuille autorisé.', 'destination' => 'Destination', 'estimated_cost' => 'Coût estimé', 'decision_pipeline' => 'Circuit de décision', 'decision_pipeline_description' => 'Répartition actuelle des demandes entre les statuts d’autorisation.', 'status' => 'Statut',
    'clearance_register' => 'Registre des autorisations', 'authorized_portfolio_count' => 'demandes dans votre portefeuille autorisé', 'export' => 'Exporter', 'reference' => 'Référence', 'requester' => 'Demandeur', 'travel_dates' => 'Dates du déplacement', 'estimate' => 'Estimation', 'reference_release' => 'Version de référence', 'empty_title' => 'Aucune demande correspondante', 'empty_description' => 'Modifiez les dates, la recherche, le statut, le comté ou le secteur. Le personnel autorisé peut créer la première demande depuis cet espace.', 'no_data_prefix' => 'Aucune donnée pour', 'data' => '', 'analytics_empty_description' => 'Les demandes correspondantes alimenteront cette analyse.',
    'new_request' => 'Nouvelle demande de déplacement', 'new_request_description' => 'Saisissez l’objet, le financement, la référence HRIS et l’itinéraire complet avant la soumission.', 'organization' => 'Organisation', 'travel_type' => 'Type de déplacement', 'domestic' => 'National', 'international' => 'International', 'purpose' => 'Objet', 'departure_date' => 'Date de départ', 'return_date' => 'Date de retour', 'total_estimated_cost' => 'Coût total estimé', 'funding_source' => 'Source de financement', 'cost_centre' => 'Centre de coûts', 'hris_employee_reference' => 'Référence employé HRIS', 'priority' => 'Priorité', 'normal' => 'Normale', 'urgent' => 'Urgente', 'business_justification' => 'Justification professionnelle',
    'itinerary' => 'Itinéraire', 'itinerary_description' => 'Tous les segments doivent se situer dans les dates de la demande.', 'add_segment' => 'Ajouter un segment', 'segment' => 'Segment', 'remove' => 'Supprimer', 'origin' => 'Origine', 'departs_at' => 'Départ', 'arrives_at' => 'Arrivée', 'transport_mode' => 'Mode de transport', 'carrier' => 'Transporteur', 'segment_estimated_cost' => 'Coût estimé du segment', 'save_draft_request' => 'Enregistrer le brouillon',
    'submit_manager_review' => 'Soumettre à l’examen hiérarchique', 'cancel_request' => 'Annuler la demande', 'approve_finance_review' => 'Approuver pour examen financier', 'reject_manager_review' => 'Rejeter lors de l’examen hiérarchique', 'confirm_finance_clearance' => 'Confirmer l’autorisation financière', 'reject_finance_clearance' => 'Rejeter l’autorisation financière', 'actions_for' => 'Actions pour', 'view_complete_request' => 'Voir la demande complète', 'complete_record_description' => 'Dossier complet du déplacement, de l’itinéraire, des intégrations et des décisions.', 'record_decision_for' => 'Enregistrer une décision motivée pour', 'decision_rationale' => 'Motif de la décision', 'approved_cost' => 'Coût approuvé', 'finance_commitment_reference' => 'Référence de l’engagement financier',
    'national' => 'National', 'hris_reference' => 'Référence HRIS', 'not_linked' => 'Non lié', 'reference_checksum' => 'Empreinte de référence', 'finance_reference' => 'Référence financière', 'pending' => 'En attente', 'supporting_documents' => 'Pièces justificatives', 'separator' => '·', 'file' => 'Fichier', 'preview' => 'Aperçu', 'download' => 'Télécharger', 'no_supporting_documents' => 'Aucune pièce justificative téléversée.', 'upload_supporting_record' => 'Téléverser une pièce justificative', 'document_title' => 'Titre du document', 'record_category' => 'Catégorie du dossier', 'source_type' => 'Type de source', 'born_digital' => 'Fichier numérique natif', 'scanned_copy' => 'Copie numérisée', 'document' => 'Document', 'uploading' => 'Téléversement',
    'route_arrow' => '→', 'range_separator' => '–', 'carrier_pending' => 'Transporteur en attente', 'decision_history' => 'Historique des décisions', 'no_decisions' => 'Aucune décision d’approbation enregistrée.', 'integration_status' => 'Statut d’intégration', 'integration_description' => 'Les identifiants HRIS et financiers restent visibles pour le rapprochement et le traitement des exceptions.',
    'value_draft' => 'Brouillon', 'value_manager_review' => 'Examen hiérarchique', 'value_finance_review' => 'Examen financier', 'value_approved' => 'Approuvée', 'value_rejected' => 'Rejetée', 'value_cancelled' => 'Annulée', 'value_submit' => 'Soumettre à l’examen hiérarchique', 'value_cancel' => 'Annuler la demande', 'value_manager_approve' => 'Approuver pour examen financier', 'value_manager_reject' => 'Rejeter lors de l’examen hiérarchique', 'value_finance_clear' => 'Confirmer l’autorisation financière', 'value_finance_reject' => 'Rejeter l’autorisation financière', 'value_air' => 'Aérien', 'value_road' => 'Routier', 'value_rail' => 'Ferroviaire', 'value_water' => 'Maritime', 'value_other' => 'Autre', 'value_digital' => 'Numérique', 'value_scanned' => 'Numérisé', 'value_clean' => 'Sain', 'value_pending_scan' => 'Analyse en attente', 'value_pending' => 'En attente', 'value_synced' => 'Synchronisé', 'value_exception' => 'Exception',
    'legacy_unpinned' => 'Ancien enregistrement non rattaché',
    'outcomes' => ['created' => 'Demande de voyage :reference créée.', 'lifecycle_updated' => 'Cycle de validation du voyage mis à jour.'],
    'errors' => ['itineraries_array' => 'Les itinéraires doivent être un tableau.', 'itinerary_object' => 'Chaque itinéraire doit être un objet de données.'],
    'notifications' => [
        'updated_title' => 'Autorisation de voyage mise à jour', 'overdue_title' => 'Autorisation de voyage en retard', 'due_soon_title' => 'Échéance prochaine de l’autorisation de voyage',
        'reminder_message' => ':reference : :purpose', 'status_manager_review' => ':reference est désormais en examen hiérarchique.', 'status_finance_review' => ':reference est désormais en examen financier.', 'status_approved' => ':reference est désormais approuvée.', 'status_rejected' => ':reference est désormais rejetée.', 'status_cancelled' => ':reference est désormais annulée.',
    ],
    'audit' => ['created' => 'Demande de voyage :reference créée.', 'transitioned' => 'Demande de voyage :reference passée au statut :status.', 'overdue_escalated' => 'La décision d’autorisation de voyage en retard a été transmise au niveau supérieur.', 'reminder_sent' => 'Le rappel d’échéance de l’autorisation de voyage a été envoyé.'],
    'command' => ['reminders_sent' => ':count rappel(s) d’autorisation de voyage envoyé(s).'],
];
