<?php

return [
    'head_title' => 'Registre des workflows', 'eyebrow' => 'Plan de contrôle partagé de la plateforme', 'title' => 'Registre des workflows et des règles', 'description' => 'Définissez, validez, signez et publiez des règles de cycle de vie réutilisables pour chaque module IDMIS.',
    'business_calendars' => 'Calendriers ouvrés', 'business_calendars_description' => 'Les horaires publiés et les exceptions officielles déterminent des échéances SLA reproductibles.', 'workflow_definitions' => 'Définitions des workflows', 'workflow_definitions_description' => 'Contrôles de cycle de vie versionnés et testables, partagés entre les modules IDMIS.',
    'edit' => 'Modifier', 'version' => 'version', 'version_prefix' => 'v', 'workflow' => 'Workflow', 'configuration' => 'configuration', 'edit_description' => 'Mettez à jour les états, permissions, règles, contrôles de séparation et le calendrier SLA avant publication.', 'edit_draft' => 'Modifier le brouillon', 'published_sla_calendar' => 'Calendrier ouvré SLA publié', 'save_draft' => 'Enregistrer le brouillon', 'publish_version' => 'Publier la version',
    'correct_configuration_json' => 'Corrigez le JSON de configuration avant de sélectionner un calendrier.', 'configuration_valid_json' => 'La configuration doit être un JSON valide.', 'create_workflow_definition' => 'Créer une définition de workflow', 'create_workflow_description' => 'Créez une définition gouvernée avant de préparer et simuler ses parcours de contrôle versionnés.', 'new_workflow' => 'Nouveau workflow',
    'code' => 'Code', 'name' => 'Nom', 'module' => 'Module', 'description_label' => 'Description', 'create_workflow' => 'Créer le workflow', 'create_calendar_version' => 'Créer une version du calendrier ouvré', 'create_calendar_description' => 'Définissez les jours, horaires et période d’effet. Ajoutez les jours fériés sourcés avant la publication par un acteur indépendant.', 'new_calendar' => 'Nouveau calendrier',
    'timezone' => 'Fuseau horaire', 'working_days' => 'Jours ouvrés', 'workday_starts' => 'Début de journée', 'workday_ends' => 'Fin de journée', 'effective_from' => 'En vigueur à partir du', 'effective_to' => 'En vigueur jusqu’au', 'create_draft' => 'Créer le brouillon', 'separator' => '·', 'range_separator' => '–', 'view_calendar' => 'Voir le calendrier', 'add_exception' => 'Ajouter une exception', 'publish_independently' => 'Publier indépendamment', 'exceptions' => 'exceptions',
    'monday' => 'Lundi', 'tuesday' => 'Mardi', 'wednesday' => 'Mercredi', 'thursday' => 'Jeudi', 'friday' => 'Vendredi', 'saturday' => 'Samedi', 'sunday' => 'Dimanche',
    'effective' => 'En vigueur', 'to' => 'au', 'no_end_date' => 'sans date de fin enregistrée', 'add_calendar_exception' => 'Ajouter une exception au calendrier', 'exception_description' => 'Consignez le jour férié officiel ou la source responsable de la fermeture administrative.', 'exception_date' => 'Date de l’exception', 'category' => 'Catégorie', 'authority_reference' => 'Référence au journal officiel ou à l’autorité', 'recorded_by' => 'Consigné par', 'sha256' => 'SHA-256',
    'no_calendar_exceptions' => 'Aucune exception au calendrier', 'no_calendar_exceptions_description' => 'Cette version ne comporte aucun jour férié ni aucune fermeture enregistrée.',
    'no_business_calendars' => 'Aucun calendrier ouvré', 'no_business_calendars_description' => 'Créez un calendrier gouvernemental versionné avant d’attribuer des SLA en heures ouvrées.', 'search_workflows' => 'Rechercher des workflows', 'search' => 'Rechercher', 'no_description' => 'Aucune description', 'active' => 'actifs', 'overdue' => 'en retard', 'create_next_draft' => 'Créer le prochain brouillon', 'no_matching_workflows' => 'Aucun workflow correspondant', 'no_matching_workflows_description' => 'Effacez la recherche ou créez une définition de workflow gouvernée.', 'definitions' => 'définitions', 'page' => 'page', 'of' => 'sur', 'previous' => 'Précédent', 'next' => 'Suivant',
];
