<?php

return [
    'calendar_code_placeholder' => 'KENYA-GOVERNMENT',
    'errors' => ['released_version_archive' => 'Les versions de workflow publiées ou retirées ne peuvent pas être archivées.', 'draft_publish_required' => 'Seules les versions de workflow à l’état de brouillon peuvent être publiées.'],
    'head_title' => 'Registre des workflows', 'eyebrow' => 'Plan de contrôle partagé de la plateforme', 'title' => 'Registre des workflows et des règles', 'description' => 'Définissez, validez, signez et publiez des règles de cycle de vie réutilisables pour chaque module IDMIS.',
    'business_calendars' => 'Calendriers ouvrés', 'business_calendars_description' => 'Les horaires publiés et les exceptions officielles déterminent des échéances SLA reproductibles.', 'workflow_definitions' => 'Définitions des workflows', 'workflow_definitions_description' => 'Contrôles de cycle de vie versionnés et testables, partagés entre les modules IDMIS.',
    'edit' => 'Modifier', 'version' => 'version', 'version_prefix' => 'v', 'workflow' => 'Workflow', 'configuration' => 'configuration', 'edit_description' => 'Mettez à jour les états, permissions, règles, contrôles de séparation et le calendrier SLA avant publication.', 'edit_draft' => 'Modifier le brouillon', 'published_sla_calendar' => 'Calendrier ouvré SLA publié', 'save_draft' => 'Enregistrer le brouillon', 'publish_version' => 'Publier la version',
    'correct_configuration_json' => 'Corrigez le JSON de configuration avant de sélectionner un calendrier.', 'configuration_valid_json' => 'La configuration doit être un JSON valide.', 'create_workflow_definition' => 'Créer une définition de workflow', 'create_workflow_description' => 'Créez une définition gouvernée avant de préparer et simuler ses parcours de contrôle versionnés.', 'new_workflow' => 'Nouveau workflow',
    'code' => 'Code', 'name' => 'Nom', 'module' => 'Module', 'description_label' => 'Description', 'create_workflow' => 'Créer le workflow', 'create_calendar_version' => 'Créer une version du calendrier ouvré', 'create_calendar_description' => 'Définissez les jours, horaires et période d’effet. Ajoutez les jours fériés sourcés avant la publication par un acteur indépendant.', 'new_calendar' => 'Nouveau calendrier',
    'timezone' => 'Fuseau horaire', 'working_days' => 'Jours ouvrés', 'workday_starts' => 'Début de journée', 'workday_ends' => 'Fin de journée', 'effective_from' => 'En vigueur à partir du', 'effective_to' => 'En vigueur jusqu’au', 'create_draft' => 'Créer le brouillon', 'separator' => '·', 'range_separator' => '–', 'view_calendar' => 'Voir le calendrier', 'add_exception' => 'Ajouter une exception', 'publish_independently' => 'Publier indépendamment', 'exceptions' => 'exceptions',
    'monday' => 'Lundi', 'tuesday' => 'Mardi', 'wednesday' => 'Mercredi', 'thursday' => 'Jeudi', 'friday' => 'Vendredi', 'saturday' => 'Samedi', 'sunday' => 'Dimanche',
    'effective' => 'En vigueur', 'to' => 'au', 'no_end_date' => 'sans date de fin enregistrée', 'add_calendar_exception' => 'Ajouter une exception au calendrier', 'exception_description' => 'Consignez le jour férié officiel ou la source responsable de la fermeture administrative.', 'exception_date' => 'Date de l’exception', 'category' => 'Catégorie', 'authority_reference' => 'Référence au journal officiel ou à l’autorité', 'recorded_by' => 'Consigné par', 'sha256' => 'SHA-256',
    'no_calendar_exceptions' => 'Aucune exception au calendrier', 'no_calendar_exceptions_description' => 'Cette version ne comporte aucun jour férié ni aucune fermeture enregistrée.',
    'no_business_calendars' => 'Aucun calendrier ouvré', 'no_business_calendars_description' => 'Créez un calendrier gouvernemental versionné avant d’attribuer des SLA en heures ouvrées.', 'search_workflows' => 'Rechercher des workflows', 'search' => 'Rechercher', 'no_description' => 'Aucune description', 'active' => 'actifs', 'overdue' => 'en retard', 'create_next_draft' => 'Créer le prochain brouillon', 'no_matching_workflows' => 'Aucun workflow correspondant', 'no_matching_workflows_description' => 'Effacez la recherche ou créez une définition de workflow gouvernée.', 'definitions' => 'définitions', 'page' => 'page', 'of' => 'sur', 'previous' => 'Précédent', 'next' => 'Suivant',
    'calendar' => [
        'errors' => ['draft_required' => 'Seuls les calendriers à l’état de brouillon peuvent être publiés.', 'independent_publisher' => 'La publication du calendrier exige un acteur indépendant de son auteur.', 'overlapping_versions' => 'Les versions publiées d’un même calendrier ne peuvent pas avoir de périodes d’effet qui se chevauchent.', 'new_version_for_holidays' => 'Les calendriers publiés sont immuables. Créez une nouvelle version pour modifier les jours fériés.', 'published_immutable' => 'Les calendriers publiés sont immuables.', 'sla_calendar_published' => 'Les calendriers SLA de workflow doivent être publiés.', 'positive_sla_hours' => 'Les heures SLA de workflow doivent être positives.', 'planning_horizon_exceeded' => 'L’échéance du calendrier ouvré dépasse l’horizon de planification pris en charge.'],
        'outcomes' => ['created' => 'Le brouillon du calendrier ouvré a été créé.', 'holiday_added' => 'L’exception du calendrier a été ajoutée.', 'holiday_removed' => 'L’exception du brouillon du calendrier a été supprimée.', 'published' => 'Le calendrier ouvré a été publié indépendamment.'],
        'audit' => ['created' => 'Le calendrier ouvré :code v:version a été préparé.', 'holiday_added' => ':holiday a été ajouté à :code v:version.', 'holiday_removed' => ':holiday a été supprimé du brouillon du calendrier.', 'published' => 'Le calendrier ouvré :code v:version a été publié.'],
    ],
    'engine' => [
        'errors' => ['unsupported_operator' => 'L’opérateur de règle de flux [:operator] n’est pas pris en charge.', 'rule_string_required' => 'La règle de flux [:key] doit être une chaîne non vide.', 'initial_state_required' => 'Le flux publié ne possède pas d’état initial valide.', 'start_unauthorized' => 'Vous n’êtes pas autorisé à démarrer ce flux.', 'effective_version_required' => 'Le flux [:workflow] ne possède aucune version publiée en vigueur.', 'calendar_ineffective' => 'Le calendrier ouvré configuré n’est pas publié ou en vigueur.', 'active_only' => 'Seules les instances de flux actives peuvent effectuer une transition.', 'rules_failed' => 'Les règles de transition du flux ne sont pas satisfaites.', 'transition_unavailable' => 'La transition [:transition] n’est pas disponible depuis l’état [:state].', 'transition_unauthorized' => 'Vous n’êtes pas autorisé à effectuer cette transition de flux.', 'separation_failed' => 'La séparation des tâches empêche le même acteur d’effectuer cette transition.'],
        'simulation' => ['start_permission_denied' => 'L’initiateur sélectionné ne possède pas l’autorisation de démarrage configurée.', 'terminal_state_reached' => 'Aucune transition ne peut être exécutée après un état terminal.', 'scenario_stopped' => 'Le scénario s’est arrêté après un échec de contrôle antérieur.', 'transition_permission_denied' => 'L’acteur sélectionné ne possède pas l’autorisation de transition.', 'separation_failed' => 'L’acteur sélectionné enfreint la règle configurée de séparation des tâches.', 'rules_failed' => 'Une ou plusieurs règles de flux ne sont pas satisfaites.', 'controls_passed' => 'Tous les contrôles de transition sont satisfaits.', 'completed' => 'Le scénario a atteint un état terminal.', 'active' => 'Toutes les étapes fournies sont satisfaites ; le flux reste actif.'],
        'audit' => ['started' => 'Flux :workflow démarré.', 'transitioned' => 'Flux passé de :from à :to.'],
    ],
    'edit_workflow_version' => 'Modifier :workflow version :version', 'edit_draft_version' => 'Modifier le brouillon v:version', 'workflow_configuration_label' => 'Configuration du workflow :workflow', 'actions_for_calendar_version' => 'Actions pour :code version :version', 'remove_record' => 'Supprimer :record',
];
