<?php

use App\Http\Controllers\AnalyticsReportingController;
use App\Http\Controllers\AssessmentAnalyticsController;
use App\Http\Controllers\AssessmentConfigurationController;
use App\Http\Controllers\AssessmentWorkflowController;
use App\Http\Controllers\AuditAssuranceController;
use App\Http\Controllers\BulkAssessmentTransitionController;
use App\Http\Controllers\BulkCitizenCaseTriageController;
use App\Http\Controllers\BulkEvidenceVerificationController;
use App\Http\Controllers\BulkProgrammeUserController;
use App\Http\Controllers\BusinessCalendarController;
use App\Http\Controllers\ChangeReadinessController;
use App\Http\Controllers\CitizenCaseController;
use App\Http\Controllers\CountyController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DataGovernanceController;
use App\Http\Controllers\DepartmentalPerformanceController;
use App\Http\Controllers\DswgCoordinationController;
use App\Http\Controllers\EvidenceController;
use App\Http\Controllers\ExchequerTrackingController;
use App\Http\Controllers\GlobalSearchController;
use App\Http\Controllers\GrantController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HistoricalDataMigrationController;
use App\Http\Controllers\IdentityLifecycleController;
use App\Http\Controllers\IgrResolutionController;
use App\Http\Controllers\InnovationReplicationController;
use App\Http\Controllers\IntegrationManagementController;
use App\Http\Controllers\KnowledgeCommunityAnalyticsController;
use App\Http\Controllers\KnowledgeManagementController;
use App\Http\Controllers\LearningAnalyticsController;
use App\Http\Controllers\LearningController;
use App\Http\Controllers\LinkedDocumentController;
use App\Http\Controllers\MonitoringEvaluationController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\PartnerCoordinationController;
use App\Http\Controllers\PlatformSettingController;
use App\Http\Controllers\ProgrammeUserController;
use App\Http\Controllers\ProgrammeWorkspaceController;
use App\Http\Controllers\ProjectManagementController;
use App\Http\Controllers\PublicCitizenCaseController;
use App\Http\Controllers\PublicLearningCertificateController;
use App\Http\Controllers\ReferenceDataController;
use App\Http\Controllers\SecurityGovernanceController;
use App\Http\Controllers\Teams\TeamInvitationController;
use App\Http\Controllers\TravelClearanceController;
use App\Http\Controllers\UniqueValueController;
use App\Http\Controllers\WorkflowDefinitionController;
use App\Http\Controllers\WorkspaceExportController;
use App\Http\Middleware\EnsureTeamMembership;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'welcome')->name('home');
Route::inertia('faqs', 'faqs')->name('faqs');
Route::inertia('help', 'help')->name('help');
Route::get('health/ready', HealthController::class)->name('health.ready');
Route::get('learning/certificates/verify', PublicLearningCertificateController::class)->middleware('throttle:certificate-verification')->name('learning.certificates.verify');
Route::get('citizen-engagement', [PublicCitizenCaseController::class, 'index'])->name('citizen-engagement.index');
Route::post('citizen-engagement/cases', [PublicCitizenCaseController::class, 'store'])->middleware('throttle:citizen-intake')->name('citizen-engagement.store');
Route::get('citizen-engagement/receipt', [PublicCitizenCaseController::class, 'receipt'])->name('citizen-engagement.receipt');
Route::post('citizen-engagement/track', [PublicCitizenCaseController::class, 'track'])->middleware('throttle:citizen-tracking')->name('citizen-engagement.track');
Route::get('citizen-engagement/tracking', [PublicCitizenCaseController::class, 'tracking'])->name('citizen-engagement.tracking');
Route::post('citizen-engagement/rate', [PublicCitizenCaseController::class, 'rate'])->middleware('throttle:citizen-tracking')->name('citizen-engagement.rate');

Route::prefix('{current_team}')
    ->middleware(['auth', 'verified', EnsureTeamMembership::class])
    ->group(function () {
        Route::get('dashboard', DashboardController::class)->name('dashboard');
        Route::get('search', GlobalSearchController::class)->middleware('throttle:global-search')->name('search.global');
        Route::get('notifications', [NotificationController::class, 'index'])->name('notifications.index');
        Route::patch('assessments/bulk-transition', BulkAssessmentTransitionController::class)->name('assessments.bulk-transition');
        Route::patch('evidence/bulk-verification', BulkEvidenceVerificationController::class)->name('evidence.bulk-verification');
        Route::patch('citizen-cases/bulk-triage', BulkCitizenCaseTriageController::class)->name('citizen-cases.bulk-triage');
        Route::delete('users/bulk', BulkProgrammeUserController::class)->name('programme-users.bulk-destroy');
        Route::patch('notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
        Route::patch('notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
        Route::controller(ProgrammeWorkspaceController::class)->group(function () {
            Route::get('counties', 'counties')->name('counties.index');
            Route::get('assessments', 'assessments')->name('assessments.index');
            Route::get('evidence', 'evidence')->name('evidence.index');
            Route::get('grants', 'grants')->name('grants.index');
            Route::get('reports', 'reports')->name('reports.index');
            Route::get('users', 'users')->name('programme-users.index');
            Route::get('audit', 'audit')->name('audit.index');
            Route::get('platform', 'platform')->name('platform.index');
        });
        Route::get('counties/{county}', CountyController::class)->name('counties.show');
        Route::get('exchequer', [ExchequerTrackingController::class, 'index'])->name('exchequer.index');
        Route::post('exchequer', [ExchequerTrackingController::class, 'store'])->name('exchequer.store');
        Route::post('exchequer/{exchequerRequest}/events', [ExchequerTrackingController::class, 'recordEvent'])->name('exchequer.events.store');
        Route::get('projects', [ProjectManagementController::class, 'index'])->name('projects.index');
        Route::post('projects', [ProjectManagementController::class, 'store'])->name('projects.store');
        Route::get('projects/{project}', [ProjectManagementController::class, 'show'])->name('projects.show');
        Route::post('projects/{project}/documents', [LinkedDocumentController::class, 'storeProject'])->name('projects.documents.store');
        Route::post('projects/{project}/milestones', [ProjectManagementController::class, 'storeMilestone'])->name('projects.milestones.store');
        Route::patch('projects/{project}/milestones/{milestone}', [ProjectManagementController::class, 'updateMilestone'])->name('projects.milestones.update');
        Route::post('projects/{project}/schedule-baselines', [ProjectManagementController::class, 'storeScheduleBaseline'])->name('projects.schedule-baselines.store');
        Route::patch('projects/{project}/schedule-baselines/{scheduleBaseline}', [ProjectManagementController::class, 'decideScheduleBaseline'])->name('projects.schedule-baselines.decide');
        Route::post('projects/{project}/budget-lines', [ProjectManagementController::class, 'storeBudgetLine'])->name('projects.budget-lines.store');
        Route::post('projects/{project}/resources', [ProjectManagementController::class, 'storeResource'])->name('projects.resources.store');
        Route::post('projects/{project}/resource-allocations', [ProjectManagementController::class, 'storeResourceAllocation'])->name('projects.resource-allocations.store');
        Route::patch('projects/{project}/budget-lines/{budgetLine}', [ProjectManagementController::class, 'updateBudgetLine'])->name('projects.budget-lines.update');
        Route::post('projects/{project}/risks', [ProjectManagementController::class, 'storeRisk'])->name('projects.risks.store');
        Route::patch('projects/{project}/risks/{risk}', [ProjectManagementController::class, 'updateRisk'])->name('projects.risks.update');
        Route::post('projects/{project}/procurements', [ProjectManagementController::class, 'storeProcurement'])->name('projects.procurements.store');
        Route::patch('projects/{project}/procurements/{procurement}', [ProjectManagementController::class, 'updateProcurement'])->name('projects.procurements.update');
        Route::post('projects/{project}/progress-updates', [ProjectManagementController::class, 'storeProgress'])->name('projects.progress-updates.store');
        Route::patch('projects/{project}/progress-updates/{progressUpdate}/verify', [ProjectManagementController::class, 'verifyProgress'])->name('projects.progress-updates.verify');
        Route::patch('projects/{project}/transition', [ProjectManagementController::class, 'transition'])->name('projects.transition');
        Route::get('partners', [PartnerCoordinationController::class, 'index'])->name('partners.index');
        Route::post('partners/profiles', [PartnerCoordinationController::class, 'storeProfile'])->name('partners.profiles.store');
        Route::post('partners/agreements', [PartnerCoordinationController::class, 'storeAgreement'])->name('partners.agreements.store');
        Route::post('partners/collaboration-plans', [PartnerCoordinationController::class, 'storeCollaborationPlan'])->name('partners.collaboration-plans.store');
        Route::patch('partners/collaboration-plans/{plan}/transition', [PartnerCoordinationController::class, 'transitionCollaborationPlan'])->name('partners.collaboration-plans.transition');
        Route::post('partners/collaboration-plans/{plan}/actions', [PartnerCoordinationController::class, 'storeCollaborationAction'])->name('partners.collaboration-actions.store');
        Route::post('partners/collaboration-actions/{action}/documents', [LinkedDocumentController::class, 'storePartnerCollaborationAction'])->name('partners.collaboration-actions.documents.store');
        Route::post('partners/collaboration-actions/{action}/updates', [PartnerCoordinationController::class, 'storeCollaborationActionUpdate'])->name('partners.collaboration-action-updates.store');
        Route::post('partners/collaboration-action-updates/{update}/decision', [PartnerCoordinationController::class, 'verifyCollaborationActionUpdate'])->name('partners.collaboration-action-updates.decision.store');
        Route::post('partners/agreements/{agreement}/documents', [LinkedDocumentController::class, 'storePartnerAgreement'])->name('partners.agreements.documents.store');
        Route::patch('partners/agreements/{agreement}/transition', [PartnerCoordinationController::class, 'transitionAgreement'])->name('partners.agreements.transition');
        Route::post('partners/agreements/{agreement}/changes', [PartnerCoordinationController::class, 'storeAgreementChange'])->name('partners.agreement-changes.store');
        Route::post('partners/agreement-changes/{changeRequest}/documents', [LinkedDocumentController::class, 'storePartnerAgreementChange'])->name('partners.agreement-changes.documents.store');
        Route::post('partners/agreement-changes/{changeRequest}/decision', [PartnerCoordinationController::class, 'decideAgreementChange'])->name('partners.agreement-changes.decision.store');
        Route::post('partners/contributions', [PartnerCoordinationController::class, 'storeContribution'])->name('partners.contributions.store');
        Route::post('partners/contributions/{contribution}/documents', [LinkedDocumentController::class, 'storePartnerContribution'])->name('partners.contributions.documents.store');
        Route::post('partners/contributions/{contribution}/reconciliations', [PartnerCoordinationController::class, 'reconcileContribution'])->name('partners.contributions.reconciliations.store');
        Route::post('partners/analyze', [PartnerCoordinationController::class, 'analyze'])->name('partners.analyze');
        Route::patch('partners/alerts/{alert}', [PartnerCoordinationController::class, 'resolveAlert'])->name('partners.alerts.resolve');
        Route::patch('partners/operational-alerts/{alert}', [PartnerCoordinationController::class, 'resolveOperationalAlert'])->name('partners.operational-alerts.resolve');
        Route::get('dswg', [DswgCoordinationController::class, 'index'])->name('dswg.index');
        Route::post('dswg/groups', [DswgCoordinationController::class, 'storeWorkingGroup'])->name('dswg.groups.store');
        Route::post('dswg/meetings', [DswgCoordinationController::class, 'storeMeeting'])->name('dswg.meetings.store');
        Route::post('dswg/meeting-series', [DswgCoordinationController::class, 'storeMeetingSeries'])->name('dswg.meeting-series.store');
        Route::post('dswg/meetings/{meeting}/documents', [LinkedDocumentController::class, 'storeDswgMeeting'])->name('dswg.meetings.documents.store');
        Route::patch('dswg/meetings/{meeting}/invitation', [DswgCoordinationController::class, 'respondInvitation'])->name('dswg.meetings.invitation.respond');
        Route::patch('dswg/meetings/{meeting}/outcomes', [DswgCoordinationController::class, 'recordOutcomes'])->name('dswg.meetings.outcomes.record');
        Route::patch('dswg/meetings/{meeting}/minutes/approve', [DswgCoordinationController::class, 'approveMinutes'])->name('dswg.meetings.minutes.approve');
        Route::post('dswg/meetings/{meeting}/decisions', [DswgCoordinationController::class, 'storeDecision'])->name('dswg.decisions.store');
        Route::post('dswg/meetings/{meeting}/actions', [DswgCoordinationController::class, 'storeAction'])->name('dswg.actions.store');
        Route::patch('dswg/actions/{action}/transition', [DswgCoordinationController::class, 'transitionAction'])->name('dswg.actions.transition');
        Route::post('dswg/actions/{action}/documents', [LinkedDocumentController::class, 'storeDswgAction'])->name('dswg.actions.documents.store');
        Route::get('igr-resolutions', [IgrResolutionController::class, 'index'])->name('igr-resolutions.index');
        Route::post('igr-resolutions/forums', [IgrResolutionController::class, 'storeForum'])->name('igr-resolutions.forums.store');
        Route::post('igr-resolutions/meetings', [IgrResolutionController::class, 'storeMeeting'])->name('igr-resolutions.meetings.store');
        Route::post('igr-resolutions/gap-categories', [IgrResolutionController::class, 'storeGapCategory'])->name('igr-resolutions.gap-categories.store');
        Route::post('igr-resolutions', [IgrResolutionController::class, 'storeResolution'])->name('igr-resolutions.store');
        Route::post('igr-resolutions/{resolution}/dependencies', [IgrResolutionController::class, 'storeDependency'])->name('igr-resolutions.dependencies.store');
        Route::post('igr-resolutions/{resolution}/gaps', [IgrResolutionController::class, 'storeGap'])->name('igr-resolutions.gaps.store');
        Route::patch('igr-resolutions/{resolution}/gaps/{gap}/transition', [IgrResolutionController::class, 'transitionGap'])->name('igr-resolutions.gaps.transition');
        Route::post('igr-resolutions/{resolution}/updates', [IgrResolutionController::class, 'storeUpdate'])->name('igr-resolutions.updates.store');
        Route::post('igr-resolutions/{resolution}/documents', [LinkedDocumentController::class, 'storeIgrResolution'])->name('igr-resolutions.documents.store');
        Route::patch('igr-resolutions/{resolution}/transition', [IgrResolutionController::class, 'transition'])->name('igr-resolutions.transition');
        Route::get('citizen-cases', [CitizenCaseController::class, 'index'])->name('citizen-cases.index');
        Route::patch('citizen-cases/{case}/triage', [CitizenCaseController::class, 'triage'])->name('citizen-cases.triage');
        Route::post('citizen-cases/{case}/messages', [CitizenCaseController::class, 'message'])->name('citizen-cases.messages.store');
        Route::patch('citizen-cases/{case}/transition', [CitizenCaseController::class, 'transition'])->name('citizen-cases.transition');
        Route::get('travel-clearance', [TravelClearanceController::class, 'index'])->name('travel-clearance.index');
        Route::post('travel-clearance', [TravelClearanceController::class, 'store'])->name('travel-clearance.store');
        Route::patch('travel-clearance/{travelRequest}/transition', [TravelClearanceController::class, 'transition'])->name('travel-clearance.transition');
        Route::post('travel-clearance/{travelRequest}/documents', [LinkedDocumentController::class, 'storeTravel'])->name('travel-clearance.documents.store');
        Route::get('departmental-performance', [DepartmentalPerformanceController::class, 'index'])->name('departmental-performance.index');
        Route::post('departmental-performance/cycles', [DepartmentalPerformanceController::class, 'storeCycle'])->name('departmental-performance.cycles.store');
        Route::post('departmental-performance/plans', [DepartmentalPerformanceController::class, 'store'])->name('departmental-performance.plans.store');
        Route::post('departmental-performance/plans/{performancePlan}/documents', [LinkedDocumentController::class, 'storePerformancePlan'])->name('departmental-performance.plans.documents.store');
        Route::patch('departmental-performance/plans/{performancePlan}/transition', [DepartmentalPerformanceController::class, 'transition'])->name('departmental-performance.plans.transition');
        Route::post('departmental-performance/plans/{performancePlan}/goals/{performanceGoal}/amendments', [DepartmentalPerformanceController::class, 'requestGoalAmendment'])->name('departmental-performance.plans.goals.amendments.store');
        Route::post('departmental-performance/plans/{performancePlan}/goal-amendments/{performanceGoalAmendment}/decisions', [DepartmentalPerformanceController::class, 'decideGoalAmendment'])->name('departmental-performance.plans.goal-amendments.decisions.store');
        Route::get('learning', [LearningController::class, 'index'])->name('learning.index');
        Route::get('learning/analytics', [LearningAnalyticsController::class, 'index'])->name('learning.analytics.index');
        Route::get('learning/analytics/export/{format}', [LearningAnalyticsController::class, 'export'])->name('learning.analytics.export');
        Route::post('learning/courses', [LearningController::class, 'store'])->name('learning.courses.store');
        Route::post('learning/cohorts', [LearningController::class, 'storeCohort'])->name('learning.cohorts.store');
        Route::post('learning/cohorts/{cohort}/members', [LearningController::class, 'addCohortMember'])->name('learning.cohorts.members.store');
        Route::patch('learning/cohorts/{cohort}/transition', [LearningController::class, 'transitionCohort'])->name('learning.cohorts.transition');
        Route::patch('learning/courses/{course}/transition', [LearningController::class, 'transition'])->name('learning.courses.transition');
        Route::post('learning/courses/{course}/offline-packages', [LearningController::class, 'generateOfflinePackage'])->name('learning.courses.offline-packages.store');
        Route::get('learning/offline-packages/{offlinePackage}', [LearningController::class, 'downloadOfflinePackage'])->name('learning.offline-packages.download');
        Route::post('learning/enrollments/{enrollment}/offline-syncs', [LearningController::class, 'submitOfflineSync'])->name('learning.enrollments.offline-syncs.store');
        Route::post('learning/offline-syncs/{offlineSync}/decision', [LearningController::class, 'decideOfflineSync'])->name('learning.offline-syncs.decision.store');
        Route::post('learning/courses/{course}/lessons/{lesson}/assets', [LearningController::class, 'storeAsset'])->name('learning.lessons.assets.store');
        Route::post('learning/enrollments', [LearningController::class, 'enroll'])->name('learning.enrollments.store');
        Route::patch('learning/enrollments/{enrollment}/lessons/{lesson}', [LearningController::class, 'completeLesson'])->name('learning.lessons.complete');
        Route::post('learning/enrollments/{enrollment}/assessment', [LearningController::class, 'assess'])->name('learning.assessments.store');
        Route::post('learning/classrooms', [LearningController::class, 'storeClassroom'])->name('learning.classrooms.store');
        Route::get('learning/classrooms/{classroom}', [LearningController::class, 'showClassroom'])->name('learning.classrooms.show');
        Route::post('learning/classrooms/{classroom}/attendance', [LearningController::class, 'recordClassroomAttendance'])->name('learning.classrooms.attendance.store');
        Route::get('learning/certificates/{certificate}', [LearningController::class, 'certificate'])->name('learning.certificates.show');
        Route::get('knowledge', [KnowledgeManagementController::class, 'index'])->name('knowledge.index');
        Route::get('knowledge/community-analytics', [KnowledgeCommunityAnalyticsController::class, 'index'])->name('knowledge.community-analytics.index');
        Route::get('knowledge/community-analytics/export/{format}', [KnowledgeCommunityAnalyticsController::class, 'export'])->name('knowledge.community-analytics.export');
        Route::get('knowledge/innovation-replications', [InnovationReplicationController::class, 'index'])->name('knowledge.innovation-replications.index');
        Route::get('knowledge/innovation-replications/export/{format}', [InnovationReplicationController::class, 'export'])->name('knowledge.innovation-replications.export');
        Route::post('knowledge/innovation-replications', [InnovationReplicationController::class, 'store'])->name('knowledge.innovation-replications.store');
        Route::patch('knowledge/innovation-replications/{replication}', [InnovationReplicationController::class, 'update'])->name('knowledge.innovation-replications.update');
        Route::patch('knowledge/innovation-replications/{replication}/verify', [InnovationReplicationController::class, 'verify'])->name('knowledge.innovation-replications.verify');
        Route::post('knowledge/innovation-replications/{replication}/documents', [LinkedDocumentController::class, 'storeInnovationReplication'])->name('knowledge.innovation-replications.documents.store');
        Route::post('knowledge/items', [KnowledgeManagementController::class, 'store'])->name('knowledge.items.store');
        Route::patch('knowledge/items/{item}/transition', [KnowledgeManagementController::class, 'transition'])->name('knowledge.items.transition');
        Route::post('knowledge/discussions', [KnowledgeManagementController::class, 'storeDiscussion'])->name('knowledge.discussions.store');
        Route::patch('knowledge/discussions/{discussion}/subscription', [KnowledgeManagementController::class, 'updateDiscussionSubscription'])->name('knowledge.discussions.subscription');
        Route::post('knowledge/discussions/{discussion}/posts', [KnowledgeManagementController::class, 'storePost'])->name('knowledge.posts.store');
        Route::patch('knowledge/posts/{post}/moderation', [KnowledgeManagementController::class, 'moderatePost'])->name('knowledge.posts.moderate');
        Route::post('knowledge/posts/{post}/reports', [KnowledgeManagementController::class, 'storeCommunityReport'])->name('knowledge.posts.reports.store');
        Route::patch('knowledge/community-reports/{report}/transition', [KnowledgeManagementController::class, 'transitionCommunityReport'])->name('knowledge.community-reports.transition');
        Route::post('knowledge/innovations', [KnowledgeManagementController::class, 'storeInnovation'])->name('knowledge.innovations.store');
        Route::patch('knowledge/innovations/{innovation}/transition', [KnowledgeManagementController::class, 'transitionInnovation'])->name('knowledge.innovations.transition');
        Route::post('knowledge/innovations/{innovation}/panel-reviews', [KnowledgeManagementController::class, 'storeInnovationPanelReview'])->name('knowledge.innovations.panel-reviews.store');
        Route::post('knowledge/innovations/{innovation}/funding-decisions', [KnowledgeManagementController::class, 'storeInnovationFundingDecision'])->name('knowledge.innovations.funding-decisions.store');
        Route::post('knowledge/innovations/{innovation}/milestones', [KnowledgeManagementController::class, 'storeInnovationMilestone'])->name('knowledge.innovations.milestones.store');
        Route::patch('knowledge/innovations/{innovation}/milestones/{milestone}', [KnowledgeManagementController::class, 'updateInnovationMilestone'])->name('knowledge.innovations.milestones.update');
        Route::patch('knowledge/innovations/{innovation}/milestones/{milestone}/verify', [KnowledgeManagementController::class, 'verifyInnovationMilestone'])->name('knowledge.innovations.milestones.verify');
        Route::get('integrations', [IntegrationManagementController::class, 'index'])->name('integrations.index');
        Route::post('integrations/systems', [IntegrationManagementController::class, 'storeSystem'])->name('integrations.systems.store');
        Route::patch('integrations/systems/{system}/activate', [IntegrationManagementController::class, 'activate'])->name('integrations.systems.activate');
        Route::post('integrations/contracts', [IntegrationManagementController::class, 'storeContract'])->name('integrations.contracts.store');
        Route::patch('integrations/contracts/{contract}/publish', [IntegrationManagementController::class, 'publish'])->name('integrations.contracts.publish');
        Route::post('integrations/contracts/{contract}/dispatch', [IntegrationManagementController::class, 'dispatch'])->name('integrations.exchanges.dispatch');
        Route::post('integrations/exchanges/{exchange}/retry', [IntegrationManagementController::class, 'retry'])->name('integrations.exchanges.retry');
        Route::patch('integrations/exceptions/{exception}/resolve', [IntegrationManagementController::class, 'resolve'])->name('integrations.exceptions.resolve');
        Route::get('operations', [OperationsController::class, 'index'])->name('operations.index');
        Route::get('audit-assurance', [AuditAssuranceController::class, 'index'])->name('audit-assurance.index');
        Route::post('audit-assurance', [AuditAssuranceController::class, 'store'])->name('audit-assurance.store');
        Route::get('audit-assurance/{auditAssuranceRun}/download', [AuditAssuranceController::class, 'download'])->name('audit-assurance.download');
        Route::post('operations/backups', [OperationsController::class, 'createBackup'])->name('operations.backups.store');
        Route::post('operations/backups/{backup}/verify', [OperationsController::class, 'verifyBackup'])->name('operations.backups.verify');
        Route::post('operations/failed-jobs/{failedJobUuid}/retry', [OperationsController::class, 'retryFailedJob'])->name('operations.failed-jobs.retry');
        Route::post('operations/releases', [OperationsController::class, 'storeRelease'])->name('operations.releases.store');
        Route::patch('operations/releases/{release}/validate', [OperationsController::class, 'validateRelease'])->name('operations.releases.validate');
        Route::patch('operations/releases/{release}/rollback', [OperationsController::class, 'rollbackRelease'])->name('operations.releases.rollback');
        Route::get('data-governance', [DataGovernanceController::class, 'index'])->name('data-governance.index');
        Route::post('data-governance/assets', [DataGovernanceController::class, 'storeAsset'])->name('data-governance.assets.store');
        Route::post('data-governance/retention-schedules', [DataGovernanceController::class, 'storeRetentionSchedule'])->name('data-governance.retention-schedules.store');
        Route::post('data-governance/processing-activities', [DataGovernanceController::class, 'storeProcessingActivity'])->name('data-governance.processing-activities.store');
        Route::patch('data-governance/processing-activities/{processingActivity}/review', [DataGovernanceController::class, 'reviewProcessingActivity'])->name('data-governance.processing-activities.review');
        Route::post('data-governance/data-subject-requests', [DataGovernanceController::class, 'storeDataSubjectRequest'])->name('data-governance.data-subject-requests.store');
        Route::patch('data-governance/data-subject-requests/{dataSubjectRequest}/advance', [DataGovernanceController::class, 'advanceDataSubjectRequest'])->name('data-governance.data-subject-requests.advance');
        Route::post('data-governance/privacy-incidents', [DataGovernanceController::class, 'storePrivacyIncident'])->name('data-governance.privacy-incidents.store');
        Route::patch('data-governance/privacy-incidents/{privacyIncident}/advance', [DataGovernanceController::class, 'advancePrivacyIncident'])->name('data-governance.privacy-incidents.advance');
        Route::post('data-governance/privacy-incidents/{privacyIncident}/documents', [LinkedDocumentController::class, 'storePrivacyIncident'])->name('data-governance.privacy-incidents.documents.store');
        Route::get('security-governance', [SecurityGovernanceController::class, 'index'])->name('security-governance.index');
        Route::post('security-governance/incidents', [SecurityGovernanceController::class, 'storeIncident'])->name('security-governance.incidents.store');
        Route::patch('security-governance/incidents/{securityIncident}/transition', [SecurityGovernanceController::class, 'transitionIncident'])->name('security-governance.incidents.transition');
        Route::post('security-governance/incidents/{securityIncident}/documents', [LinkedDocumentController::class, 'storeSecurityIncident'])->name('security-governance.incidents.documents.store');
        Route::get('security-governance/supply-chain-scans/{supplyChainScan}/download', [SecurityGovernanceController::class, 'downloadSupplyChainArtifact'])->name('security-governance.supply-chain-scans.download');
        Route::post('security-governance/threats', [SecurityGovernanceController::class, 'storeThreat'])->name('security-governance.threats.store');
        Route::patch('security-governance/threats/{securityThreat}/review', [SecurityGovernanceController::class, 'reviewThreat'])->name('security-governance.threats.review');
        Route::post('security-governance/access-reviews', [SecurityGovernanceController::class, 'launchAccessReview'])->name('security-governance.access-reviews.store');
        Route::patch('security-governance/access-review-items/{accessReviewItem}/decide', [SecurityGovernanceController::class, 'decideAccess'])->name('security-governance.access-review-items.decide');
        Route::patch('security-governance/access-review-items/{accessReviewItem}/reinstate', [SecurityGovernanceController::class, 'reinstateAccess'])->name('security-governance.access-review-items.reinstate');
        Route::post('security-governance/access-delegations', [SecurityGovernanceController::class, 'storeDelegation'])->name('security-governance.access-delegations.store');
        Route::patch('security-governance/access-delegations/{accessDelegation}/decide', [SecurityGovernanceController::class, 'decideDelegation'])->name('security-governance.access-delegations.decide');
        Route::patch('security-governance/access-delegations/{accessDelegation}/revoke', [SecurityGovernanceController::class, 'revokeDelegation'])->name('security-governance.access-delegations.revoke');
        Route::patch('security-governance/access-delegations/{accessDelegation}/review', [SecurityGovernanceController::class, 'reviewEmergencyAccess'])->name('security-governance.access-delegations.review');
        Route::post('security-governance/identity-lifecycle', [IdentityLifecycleController::class, 'store'])->name('security-governance.identity-lifecycle.store');
        Route::patch('security-governance/identity-lifecycle/{identityLifecycleRequest}/decide', [IdentityLifecycleController::class, 'decide'])->name('security-governance.identity-lifecycle.decide');
        Route::get('change-readiness', [ChangeReadinessController::class, 'index'])->name('change-readiness.index');
        Route::post('change-readiness/waves', [ChangeReadinessController::class, 'storeWave'])->name('change-readiness.waves.store');
        Route::post('change-readiness/cohorts', [ChangeReadinessController::class, 'storeCohort'])->name('change-readiness.cohorts.store');
        Route::post('change-readiness/participants', [ChangeReadinessController::class, 'enroll'])->name('change-readiness.participants.store');
        Route::post('change-readiness/participants/{participant}/assessments', [ChangeReadinessController::class, 'assess'])->name('change-readiness.assessments.store');
        Route::patch('change-readiness/waves/{wave}/approve', [ChangeReadinessController::class, 'approve'])->name('change-readiness.waves.approve');
        Route::get('analytics', [AnalyticsReportingController::class, 'index'])->name('analytics.index');
        Route::post('analytics/dashboards', [AnalyticsReportingController::class, 'storeDashboard'])->name('analytics.dashboards.store');
        Route::post('analytics/dashboards/{dashboard}/widgets', [AnalyticsReportingController::class, 'storeWidget'])->name('analytics.widgets.store');
        Route::patch('analytics/dashboards/{dashboard}/publish', [AnalyticsReportingController::class, 'publish'])->name('analytics.dashboards.publish');
        Route::post('analytics/report-schedules', [AnalyticsReportingController::class, 'storeSchedule'])->name('analytics.schedules.store');
        Route::patch('analytics/report-schedules/{schedule}/activate', [AnalyticsReportingController::class, 'activate'])->name('analytics.schedules.activate');
        Route::post('analytics/report-schedules/{schedule}/run', [AnalyticsReportingController::class, 'runNow'])->name('analytics.schedules.run');
        Route::get('analytics/report-runs/{run}/download', [AnalyticsReportingController::class, 'download'])->name('analytics.runs.download');
        Route::get('citizen-case-attachments/{attachment}', [CitizenCaseController::class, 'attachment'])->name('citizen-cases.attachments.download');
        Route::get('assessments/analytics', [AssessmentAnalyticsController::class, 'index'])->name('assessments.analytics.index');
        Route::get('assessments/analytics/export/{format}', [AssessmentAnalyticsController::class, 'export'])->whereIn('format', ['csv', 'xlsx', 'json', 'pdf'])->name('assessments.analytics.export');
        Route::post('assessments', [AssessmentWorkflowController::class, 'store'])->name('assessments.store');
        Route::get('assessments/{assessment}', [AssessmentWorkflowController::class, 'show'])->name('assessments.show');
        Route::get('reference-data', [ReferenceDataController::class, 'index'])->name('reference-data.index');
        Route::post('reference-data/unique-value', UniqueValueController::class)->middleware('throttle:unique-value')->name('reference-data.unique-value');
        Route::get('data-migrations', [HistoricalDataMigrationController::class, 'index'])->name('data-migrations.index');
        Route::post('data-migrations', [HistoricalDataMigrationController::class, 'store'])->name('data-migrations.store');
        Route::post('data-migrations/reference-data', [HistoricalDataMigrationController::class, 'storeReferenceData'])->name('data-migrations.reference-data.store');
        Route::get('data-migrations/templates/{datasetType}', [HistoricalDataMigrationController::class, 'template'])->name('data-migrations.templates.show');
        Route::patch('data-migrations/{dataMigrationBatch}/review', [HistoricalDataMigrationController::class, 'review'])->name('data-migrations.review');
        Route::post('data-migrations/{dataMigrationBatch}/apply', [HistoricalDataMigrationController::class, 'apply'])->name('data-migrations.apply');
        Route::get('data-migrations/{dataMigrationBatch}/download', [HistoricalDataMigrationController::class, 'download'])->name('data-migrations.download');
        Route::post('reference-data/organizations', [ReferenceDataController::class, 'storeOrganization'])->name('reference-data.organizations.store');
        Route::patch('reference-data/organizations/{organization}', [ReferenceDataController::class, 'updateOrganization'])->name('reference-data.organizations.update');
        Route::delete('reference-data/organizations/{organization}', [ReferenceDataController::class, 'destroyOrganization'])->name('reference-data.organizations.destroy');
        Route::post('reference-data/sectors', [ReferenceDataController::class, 'storeSector'])->name('reference-data.sectors.store');
        Route::patch('reference-data/sectors/{sector}', [ReferenceDataController::class, 'updateSector'])->name('reference-data.sectors.update');
        Route::delete('reference-data/sectors/{sector}', [ReferenceDataController::class, 'destroySector'])->name('reference-data.sectors.destroy');
        Route::post('reference-data/programmes', [ReferenceDataController::class, 'storeProgramme'])->name('reference-data.programmes.store');
        Route::patch('reference-data/programmes/{programme}', [ReferenceDataController::class, 'updateProgramme'])->name('reference-data.programmes.update');
        Route::delete('reference-data/programmes/{programme}', [ReferenceDataController::class, 'destroyProgramme'])->name('reference-data.programmes.destroy');
        Route::post('reference-data/programme-coverages', [ReferenceDataController::class, 'storeProgrammeCountyCoverage'])->name('reference-data.programme-coverages.store');
        Route::delete('reference-data/programme-coverages/{programmeCountyCoverage}', [ReferenceDataController::class, 'destroyProgrammeCountyCoverage'])->name('reference-data.programme-coverages.destroy');
        Route::post('reference-data/releases', [ReferenceDataController::class, 'storeRelease'])->name('reference-data.releases.store');
        Route::patch('reference-data/releases/{release}/publish', [ReferenceDataController::class, 'publishRelease'])->name('reference-data.releases.publish');
        Route::get('assessment-configuration', [AssessmentConfigurationController::class, 'index'])->name('assessment-configuration.index');
        Route::get('monitoring-evaluation', [MonitoringEvaluationController::class, 'index'])->name('monitoring-evaluation.index');
        Route::post('monitoring-evaluation/indicators', [MonitoringEvaluationController::class, 'storeIndicator'])->name('monitoring-evaluation.indicators.store');
        Route::post('monitoring-evaluation/indicators/{indicator}/supersede', [MonitoringEvaluationController::class, 'supersedeIndicator'])->name('monitoring-evaluation.indicators.supersede');
        Route::patch('monitoring-evaluation/indicators/{indicator}/approve', [MonitoringEvaluationController::class, 'approveIndicator'])->name('monitoring-evaluation.indicators.approve');
        Route::post('monitoring-evaluation/observations', [MonitoringEvaluationController::class, 'storeObservation'])->name('monitoring-evaluation.observations.store');
        Route::patch('monitoring-evaluation/observations/{observation}/verify', [MonitoringEvaluationController::class, 'verifyObservation'])->name('monitoring-evaluation.observations.verify');
        Route::post('monitoring-evaluation/evaluations', [MonitoringEvaluationController::class, 'storeEvaluation'])->name('monitoring-evaluation.evaluations.store');
        Route::post('monitoring-evaluation/evaluations/{evaluation}/documents', [LinkedDocumentController::class, 'storeProgrammeEvaluation'])->name('monitoring-evaluation.evaluations.documents.store');
        Route::patch('monitoring-evaluation/evaluations/{evaluation}/transition', [MonitoringEvaluationController::class, 'transitionEvaluation'])->name('monitoring-evaluation.evaluations.transition');
        Route::post('monitoring-evaluation/evaluations/{evaluation}/findings', [MonitoringEvaluationController::class, 'storeFinding'])->name('monitoring-evaluation.evaluations.findings.store');
        Route::post('monitoring-evaluation/findings/{finding}/documents', [LinkedDocumentController::class, 'storeEvaluationFinding'])->name('monitoring-evaluation.findings.documents.store');
        Route::post('monitoring-evaluation/findings/{finding}/actions', [MonitoringEvaluationController::class, 'storeFindingAction'])->name('monitoring-evaluation.findings.actions.store');
        Route::post('monitoring-evaluation/finding-actions/{action}/documents', [LinkedDocumentController::class, 'storeEvaluationFindingAction'])->name('monitoring-evaluation.finding-actions.documents.store');
        Route::post('monitoring-evaluation/finding-actions/{action}/updates', [MonitoringEvaluationController::class, 'storeFindingActionUpdate'])->name('monitoring-evaluation.finding-actions.updates.store');
        Route::patch('monitoring-evaluation/finding-action-updates/{update}/verify', [MonitoringEvaluationController::class, 'verifyFindingActionUpdate'])->name('monitoring-evaluation.finding-action-updates.verify');
        Route::post('monitoring-evaluation/findings/{finding}/updates', [MonitoringEvaluationController::class, 'storeFindingUpdate'])->name('monitoring-evaluation.findings.updates.store');
        Route::patch('monitoring-evaluation/finding-updates/{update}/verify', [MonitoringEvaluationController::class, 'verifyFindingUpdate'])->name('monitoring-evaluation.finding-updates.verify');
        Route::patch('monitoring-evaluation/findings/{finding}/close', [MonitoringEvaluationController::class, 'closeFinding'])->name('monitoring-evaluation.findings.close');
        Route::post('assessment-configuration/scorecards', [AssessmentConfigurationController::class, 'storeScorecard'])->name('assessment-configuration.scorecards.store');
        Route::post('assessment-configuration/scorecards/{assessmentScorecard}/versions', [AssessmentConfigurationController::class, 'storeVersion'])->name('assessment-configuration.scorecards.versions.store');
        Route::patch('assessment-configuration/scorecards/{assessmentScorecard}/versions/{scorecardVersion}/publish', [AssessmentConfigurationController::class, 'publishVersion'])->name('assessment-configuration.scorecards.versions.publish');
        Route::post('assessment-configuration/cycles', [AssessmentConfigurationController::class, 'storeCycle'])->name('assessment-configuration.cycles.store');
        Route::get('workflows', [WorkflowDefinitionController::class, 'index'])->name('workflows.index');
        Route::post('workflows', [WorkflowDefinitionController::class, 'store'])->name('workflows.store');
        Route::post('workflows/{workflowDefinition}/versions', [WorkflowDefinitionController::class, 'storeVersion'])->name('workflows.versions.store');
        Route::patch('workflows/{workflowDefinition}/versions/{workflowVersion}', [WorkflowDefinitionController::class, 'updateVersion'])->name('workflows.versions.update');
        Route::patch('workflows/{workflowDefinition}/versions/{workflowVersion}/publish', [WorkflowDefinitionController::class, 'publish'])->name('workflows.versions.publish');
        Route::post('workflows/{workflowDefinition}/versions/{workflowVersion}/simulate', [WorkflowDefinitionController::class, 'simulate'])->name('workflows.versions.simulate');
        Route::delete('workflows/{workflowDefinition}/versions/{workflowVersion}', [WorkflowDefinitionController::class, 'destroyVersion'])->name('workflows.versions.destroy');
        Route::post('business-calendars', [BusinessCalendarController::class, 'store'])->name('business-calendars.store');
        Route::post('business-calendars/{businessCalendar}/holidays', [BusinessCalendarController::class, 'storeHoliday'])->name('business-calendars.holidays.store');
        Route::delete('business-calendars/{businessCalendar}/holidays/{businessCalendarHoliday}', [BusinessCalendarController::class, 'destroyHoliday'])->name('business-calendars.holidays.destroy');
        Route::patch('business-calendars/{businessCalendar}/publish', [BusinessCalendarController::class, 'publish'])->name('business-calendars.publish');
        Route::get('{workspace}/export/{format}', WorkspaceExportController::class)
            ->whereIn('workspace', ['counties', 'assessments', 'evidence', 'grants', 'exchequer', 'reports', 'users', 'audit', 'audit-assurance', 'platform', 'monitoring-evaluation', 'monitoring-performance', 'programme-evaluations', 'projects', 'partners', 'partner-actions', 'dswg', 'igr-resolutions', 'igr-gaps', 'citizen-cases', 'travel-clearance', 'departmental-performance', 'learning', 'learning-cohorts', 'learning-attendance', 'learning-offline-syncs', 'knowledge', 'knowledge-innovations', 'knowledge-moderation', 'integrations', 'integration-systems', 'operations', 'data-governance', 'privacy-incidents', 'security-governance', 'security-incidents', 'access-delegations', 'identity-lifecycle', 'business-calendars', 'change-readiness', 'programme-coverage'])
            ->whereIn('format', ['csv', 'json', 'xlsx', 'pdf'])
            ->name('workspace.export');
        Route::prefix('assessments/{assessment}')->controller(AssessmentWorkflowController::class)->group(function () {
            Route::patch('submit', 'submit')->name('assessments.submit');
            Route::patch('review', 'review')->name('assessments.review');
            Route::patch('score', 'score')->name('assessments.score');
            Route::patch('approve', 'approve')->name('assessments.approve');
            Route::post('criteria/{criterion}/scores', 'submitCriterionScore')->name('assessments.criteria.scores.store');
            Route::patch('criterion-results/{result}/verify', 'verifyCriterionScore')->name('assessments.criteria.scores.verify');
            Route::patch('criterion-results/{result}/override', 'overrideCriterionScore')->name('assessments.criteria.scores.override');
            Route::post('calculate', 'calculate')->name('assessments.calculate');
            Route::post('attest', 'attest')->name('assessments.attest');
            Route::post('findings', 'storeFinding')->name('assessments.findings.store');
            Route::post('appeals', 'storeAppeal')->name('assessments.appeals.store');
            Route::patch('findings/{finding}/respond', 'respondToFinding')->name('assessments.findings.respond');
            Route::patch('findings/{finding}/resolve', 'resolveFinding')->name('assessments.findings.resolve');
            Route::patch('appeals/{appeal}/decide', 'decideAppeal')->name('assessments.appeals.decide');
            Route::post('publish', 'publish')->name('assessments.publish');
            Route::post('corrective-plans', 'storeCorrectivePlan')->name('assessments.corrective-plans.store');
            Route::patch('corrective-plans/{plan}/review', 'reviewCorrectivePlan')->name('assessments.corrective-plans.review');
            Route::post('corrective-plans/{plan}/actions/{correctiveAction}/updates', 'storeCorrectiveUpdate')->name('assessments.corrective-plans.actions.updates.store');
            Route::patch('corrective-plans/{plan}/actions/{correctiveAction}/updates/{update}/verify', 'verifyCorrectiveUpdate')->name('assessments.corrective-plans.actions.updates.verify');
            Route::post('corrective-plans/{plan}/closure', 'requestCorrectiveClosure')->name('assessments.corrective-plans.closure.store');
            Route::patch('corrective-plans/{plan}/closure', 'decideCorrectiveClosure')->name('assessments.corrective-plans.closure.decide');
        });
        Route::post('assessments/{assessment}/evidence', [EvidenceController::class, 'store'])->name('evidence.store');
        Route::get('evidence/{document}/download', [EvidenceController::class, 'download'])->name('evidence.download');
        Route::get('evidence/{document}/preview', [EvidenceController::class, 'preview'])->name('evidence.preview');
        Route::patch('evidence/{document}', [EvidenceController::class, 'update'])->name('evidence.update');
        Route::delete('evidence/{document}', [EvidenceController::class, 'destroy'])->name('evidence.destroy');
        Route::patch('evidence/{document}/verify', [EvidenceController::class, 'verify'])->name('evidence.verify');
        Route::post('evidence/{document}/versions', [EvidenceController::class, 'replace'])->name('evidence.versions.store');
        Route::get('evidence/{document}/versions/{version}/download', [EvidenceController::class, 'downloadVersion'])->name('evidence.versions.download');
        Route::get('evidence/{document}/versions/{version}/preview', [EvidenceController::class, 'previewVersion'])->name('evidence.versions.preview');
        Route::post('evidence/{document}/extract', [EvidenceController::class, 'extract'])->name('evidence.extract');
        Route::post('evidence/{document}/legal-holds', [EvidenceController::class, 'placeLegalHold'])->name('evidence.legal-holds.store');
        Route::patch('evidence/{document}/legal-holds/{legalHold}/release', [EvidenceController::class, 'releaseLegalHold'])->name('evidence.legal-holds.release');
        Route::post('evidence/{document}/dispositions', [EvidenceController::class, 'requestDisposition'])->name('evidence.dispositions.store');
        Route::patch('evidence/{document}/dispositions/{disposition}/decide', [EvidenceController::class, 'decideDisposition'])->name('evidence.dispositions.decide');
        Route::post('evidence/{document}/dispositions/{disposition}/execute', [EvidenceController::class, 'executeDisposition'])->name('evidence.dispositions.execute');
        Route::patch('grants/{grant}', [GrantController::class, 'update'])->name('grants.update');
        Route::post('users', [ProgrammeUserController::class, 'store'])->name('programme-users.store');
        Route::delete('users/{programmeUser}', [ProgrammeUserController::class, 'destroy'])->name('programme-users.destroy');
        Route::patch('platform/settings/{setting}', [PlatformSettingController::class, 'update'])->name('platform-settings.update');
    });

Route::middleware(['auth'])->group(function () {
    Route::post('invitations/{invitation}/accept', [TeamInvitationController::class, 'accept'])->name('invitations.accept');
    Route::delete('invitations/{invitation}', [TeamInvitationController::class, 'decline'])->name('invitations.decline');
});

require __DIR__.'/settings.php';
