<?php

return [
    'head_title' => 'Usanidi wa tathmini', 'eyebrow' => 'Tathmini ya utendaji wa ugatuzi', 'title' => 'Kadi za alama na mizunguko ya tathmini', 'description' => 'Simamia kadi za alama za kidijitali zinazoweza kurudiwa katika majukumu yote kumi na manne yaliyogatuliwa, mada wezeshi, viwango, vigezo, kanuni za MCDA na mahitaji ya ushahidi.',
    'new_scorecard' => 'Kadi mpya ya alama', 'new_scorecard_description' => 'Unda ufafanuzi thabiti wa kadi ya alama ambao matoleo yake yaliyochapishwa hayabadiliki.', 'create_scorecard' => 'Unda kadi ya alama', 'code' => 'Msimbo', 'name' => 'Jina', 'description_label' => 'Maelezo',
    'new_cycle' => 'Mzunguko mpya wa tathmini', 'new_cycle_description' => 'Fungamanisha kipindi cha kuripoti na toleo la kadi ya alama lisilobadilika.', 'create_cycle' => 'Unda mzunguko', 'publish_before_cycle' => 'Chapisha toleo la kadi ya alama kabla ya kuunda mzunguko.', 'released_scorecard' => 'Kadi ya alama iliyochapishwa', 'period_start' => 'Mwanzo wa kipindi', 'period_end' => 'Mwisho wa kipindi', 'submission_opens' => 'Uwasilishaji unafunguliwa', 'submission_closes' => 'Uwasilishaji unafungwa',
    'valid_json_error' => 'Usanidi wa kadi ya alama lazima uwe JSON halali.', 'compose_version_title' => 'Tunga toleo linalofuata la kadi ya alama', 'compose_version_description' => 'Unda rasimu inayodhibitiwa kutoka usanidi kamili kabla ya ukaguzi na uchapishaji.', 'compose_version' => 'Tunga toleo', 'baseline_notice' => 'Msingi una majukumu yote kumi na manne yaliyogatuliwa. Badilisha viwango, kanuni, vigezo, uzito na masharti ya ushahidi ya muda kwa maudhui yaliyoidhinishwa kabla ya kuchapisha.', 'scorecard_json' => 'JSON ya toleo la kadi ya alama', 'save_draft_version' => 'Hifadhi rasimu ya toleo',
    'pagination' => 'kurasa', 'page' => 'Ukurasa', 'of' => 'wa', 'separator' => '·', 'total' => 'jumla', 'previous' => 'Iliyotangulia', 'next' => 'Inayofuata', 'search_scorecards' => 'Tafuta kadi za alama', 'search' => 'Tafuta', 'no_description' => 'Hakuna maelezo', 'version_prefix' => 't', 'functions' => 'majukumu', 'publish' => 'Chapisha', 'scorecards' => 'Kadi za alama',
    'assessment_cycles' => 'Mizunguko ya tathmini', 'assessment_cycles_description' => 'Vipindi vya kuripoti vilivyofungamanishwa na matoleo ya kadi za alama yasiyobadilika.', 'to' => 'hadi', 'no_scorecard' => 'Hakuna kadi ya alama',
    'value_active' => 'Inatumika', 'value_inactive' => 'Haitumiki', 'value_draft' => 'Rasimu', 'value_published' => 'Imechapishwa', 'value_retired' => 'Imestaafishwa', 'value_planned' => 'Imepangwa', 'value_open' => 'Wazi', 'value_closed' => 'Imefungwa',
];
