<?php

return [
    'page_title' => 'Kaunti ya :county', 'all_counties' => 'Kaunti zote', 'county_code_region' => 'Kaunti :code · :region', 'description' => 'Rekodi kamili ya tathmini, ushahidi, uthibitishaji na hazina katika wigo wako ulioidhinishwa.', 'official_website' => 'Tovuti rasmi', 'county_record' => 'Rekodi ya kaunti', 'county_summary' => 'Muhtasari wa kaunti',
    'assessment_cycles' => 'Mizunguko ya tathmini', 'evidence_documents' => 'Hati za ushahidi', 'verified_evidence' => 'Ushahidi uliothibitishwa', 'grant_disbursement' => 'Malipo ya ruzuku', 'of_amount' => 'kati ya :amount',
    'administrative_hierarchy' => 'Mpangilio wa kiutawala', 'administrative_hierarchy_description' => 'Muundo unaodhibitiwa wa kaunti ndogo na wadi wenye historia ya chanzo.', 'sub_counties' => 'Kaunti ndogo', 'wards' => 'Wadi', 'registered_voters' => 'Wapiga kura waliosajiliwa (2022)', 'ward_count' => 'Wadi :count', 'source_lineage' => 'Chanzo: :authority · kinaanza :date', 'no_administrative_units' => 'Hakuna mpangilio wa kiutawala', 'no_administrative_units_description' => 'Ingiza na uidhinishe rejista inayodhibitiwa ya kaunti ndogo na wadi kwa kaunti hii.',
    'assessment_history' => 'Historia ya tathmini', 'document_management' => 'Usimamizi wa hati', 'exchequer_grants' => 'Hazina na ruzuku', 'matching_records' => 'Rekodi :count zinazolingana', 'no_matching_county_records' => 'Hakuna rekodi za kaunti zinazolingana', 'no_matching_county_records_description' => 'Rekebisha utafutaji au kipindi cha tarehe. Rekodi zinasalia katika kaunti hii na ufikiaji uliokabidhiwa.',
    'column_cycle' => 'Mzunguko', 'column_status' => 'Hali', 'column_score' => 'Alama', 'column_evidence' => 'Ushahidi', 'column_assessor' => 'Mtathmini', 'column_document' => 'Hati', 'column_category' => 'Aina', 'column_verification' => 'Uthibitishaji', 'column_uploaded_by' => 'Imepakiwa na', 'column_programme' => 'Programu', 'column_financial_year' => 'Mwaka wa fedha', 'column_allocated' => 'Imetengwa (KES)', 'column_disbursed' => 'Imelipwa (KES)',
    'unassigned' => 'Hajapangiwa', 'system_migration' => 'Uhamishaji wa mfumo', 'scanned_copy' => 'Nakala iliyochanganuliwa', 'digital_file' => 'Faili la kidijitali', 'empty_value' => '—', 'separator' => '·', 'label_separator' => ':',
];
