<?php

return [
    'overview' => 'Muhtasari', 'assessment_cycles' => 'Mizunguko ya tathmini', 'action_queue' => 'Foleni ya hatua', 'funds_evidence' => 'Fedha na ushahidi',
    'operational_control' => 'Hali ya udhibiti wa utendaji', 'operational_control_description' => 'Vighairi vya moduli mbalimbali katika wigo ulioidhinishwa.', 'role_brief' => 'Muhtasari wa jukumu', 'priority_decisions_for' => 'Maamuzi ya kipaumbele kwa', 'full_stop' => '.', 'active_projects_visible' => 'miradi hai inaonekana katika wigo huu.',
    'county_coverage' => 'Ueneaji wa kaunti', 'kenya_assessment_map' => 'Ramani ya tathmini ya Kenya', 'county_detail' => 'Maelezo ya kaunti', 'open_county_record' => 'Fungua rekodi kamili ya kaunti', 'county_intervention_queue' => 'Foleni ya hatua za kaunti', 'county_intervention_description' => 'Imepangwa kutoka rekodi zilizochujwa na kuidhinishwa; chagua kaunti kuendelea na ushahidi na rekodi kamili ya utekelezaji.',
    'score' => 'Alama', 'funding_gap' => 'Pengo la ufadhili', 'no_county_flags' => 'Hakuna tahadhari za kaunti', 'no_county_flags_description' => 'Hakuna tathmini isiyokamilika, ushahidi unaokosekana, alama ya chini au pengo la ruzuku katika wigo huu.', 'exception_register' => 'Rejista ya vighairi', 'exception_register_description' => 'Mzigo wa moduli mbalimbali unaohitaji ufuatiliaji wenye uwajibikaji.',
    'performance_across_cycles' => 'Utendaji katika mizunguko', 'performance_across_cycles_description' => 'Wastani wa alama zilizothibitishwa na ukamilishaji wa kaunti kwa wigo ulioidhinishwa.', 'county_completion' => 'Ukamilishaji wa kaunti', 'average_score' => 'Wastani wa alama', 'evidence' => 'Ushahidi', 'no_assessment_cycles' => 'Hakuna mizunguko ya tathmini', 'no_assessment_cycles_description' => 'Takwimu za mzunguko zitaonekana baada ya mzunguko wa tathmini kusanidiwa.',
    'grant_allocation_disbursement' => 'Ugawaji na utoaji wa ruzuku', 'grant_chart_description' => 'Kaunti zinazoongoza kwa thamani iliyotengwa katika wigo wa sasa.', 'evidence_coverage' => 'Ueneaji wa ushahidi', 'evidence_coverage_description' => 'Kaunti zenye makusanyo makubwa zaidi ya nyaraka katika kipindi kilichochaguliwa.',
    'cycle_completion' => 'Ukamilishaji wa mzunguko', 'allocated' => 'Imetengwa', 'disbursed' => 'Imetolewa', 'evidence_documents' => 'Nyaraka za ushahidi', 'assessment_incomplete' => 'Tathmini haijakamilika', 'no_evidence_indexed' => 'Hakuna ushahidi uliowekwa faharasa', 'score_below_threshold' => 'Alama chini ya 60%', 'undisbursed_allocation' => 'Mgao ambao haujatolewa',
    'evidence_awaiting_review' => 'Ushahidi unasubiri ukaguzi', 'evidence_awaiting_review_detail' => 'Rekodi hai bila uamuzi wa uthibitishaji', 'evidence_scan_attention' => 'Uchanganuzi wa ushahidi unahitaji umakini', 'evidence_scan_attention_detail' => 'Matokeo yanayosubiri, yaliyoshindwa au yaliyotengwa', 'overdue_citizen_cases' => 'Kesi za wananchi zilizochelewa', 'overdue_citizen_cases_detail' => 'Kesi ambazo hazijatatuliwa baada ya makataa', 'delayed_exchequer_requests' => 'Maombi ya hazina yaliyochelewa', 'delayed_exchequer_requests_detail' => 'Maombi wazi zaidi ya SLA ya hatua ya sasa', 'overdue_evaluation_findings' => 'Matokeo ya tathmini yaliyochelewa', 'overdue_evaluation_findings_detail' => 'Mapendekezo yaliyopita muda na hayajafungwa', 'open_partner_alerts' => 'Tahadhari wazi za washirika', 'open_partner_alerts_detail' => 'Vighairi vya makubaliano au michango ambavyo havijatatuliwa',
    'counties_in_view' => 'Kaunti zinazoonekana', 'assessed' => 'zimetathminiwa', 'pending' => 'zinasubiri', 'completed_assessments_detail' => 'Katika tathmini zilizokamilika', 'selected_period_detail' => 'Ndani ya kipindi kilichochaguliwa', 'grant_disbursement' => 'Utoaji wa ruzuku', 'disbursed_lower' => 'imetolewa', 'separator' => '·', 'range_separator' => '–', 'slash' => '/', 'percent' => '%',
];
