<?php

return [
    'overview' => 'Muhtasari', 'assessment_cycles' => 'Mizunguko ya tathmini', 'action_queue' => 'Foleni ya hatua', 'funds_evidence' => 'Fedha na ushahidi',
    'dashboard_title' => 'Dashibodi ya :role', 'portfolio_statistics' => 'Takwimu za wigo', 'require_attention' => ':count zinahitaji umakini', 'no_active_exceptions' => 'Hakuna vighairi hai', 'open_county_record_label' => 'Fungua rekodi ya kaunti ya :county',
    'operational_control' => 'Hali ya udhibiti wa utendaji', 'operational_control_description' => 'Vighairi vya moduli mbalimbali katika wigo ulioidhinishwa.', 'role_brief' => 'Muhtasari wa jukumu', 'priority_decisions_for_role' => 'Maamuzi ya kipaumbele kwa :role.', 'full_stop' => '.', 'active_projects_visible' => 'miradi hai inaonekana katika wigo huu.',
    'county_coverage' => 'Ueneaji wa kaunti', 'kenya_assessment_map' => 'Ramani ya tathmini ya Kenya', 'county_detail' => 'Maelezo ya kaunti', 'open_county_record' => 'Fungua rekodi kamili ya kaunti', 'county_intervention_queue' => 'Foleni ya hatua za kaunti', 'county_intervention_description' => 'Imepangwa kutoka rekodi zilizochujwa na kuidhinishwa; chagua kaunti kuendelea na ushahidi na rekodi kamili ya utekelezaji.',
    'score' => 'Alama', 'funding_gap' => 'Pengo la ufadhili', 'no_county_flags' => 'Hakuna tahadhari za kaunti', 'no_county_flags_description' => 'Hakuna tathmini isiyokamilika, ushahidi unaokosekana, alama ya chini au pengo la ruzuku katika wigo huu.', 'exception_register' => 'Rejista ya vighairi', 'exception_register_description' => 'Mzigo wa moduli mbalimbali unaohitaji ufuatiliaji wenye uwajibikaji.',
    'performance_across_cycles' => 'Utendaji katika mizunguko', 'performance_across_cycles_description' => 'Wastani wa alama zilizothibitishwa na ukamilishaji wa kaunti kwa wigo ulioidhinishwa.', 'county_completion' => 'Ukamilishaji wa kaunti', 'average_score' => 'Wastani wa alama', 'evidence' => 'Ushahidi', 'no_assessment_cycles' => 'Hakuna mizunguko ya tathmini', 'no_assessment_cycles_description' => 'Takwimu za mzunguko zitaonekana baada ya mzunguko wa tathmini kusanidiwa.',
    'grant_allocation_disbursement' => 'Ugawaji na utoaji wa ruzuku', 'grant_chart_description' => 'Kaunti zinazoongoza kwa thamani iliyotengwa katika wigo wa sasa.', 'evidence_coverage' => 'Ueneaji wa ushahidi', 'evidence_coverage_description' => 'Kaunti zenye makusanyo makubwa zaidi ya nyaraka katika kipindi kilichochaguliwa.',
    'cycle_completion' => 'Ukamilishaji wa mzunguko', 'allocated' => 'Imetengwa', 'disbursed' => 'Imetolewa', 'evidence_documents' => 'Nyaraka za ushahidi', 'assessment_incomplete' => 'Tathmini haijakamilika', 'no_evidence_indexed' => 'Hakuna ushahidi uliowekwa faharasa', 'score_below_threshold' => 'Alama chini ya 60%', 'undisbursed_allocation' => 'Mgao ambao haujatolewa',
    'evidence_awaiting_review' => 'Ushahidi unasubiri ukaguzi', 'evidence_awaiting_review_detail' => 'Rekodi hai bila uamuzi wa uthibitishaji', 'evidence_scan_attention' => 'Uchanganuzi wa ushahidi unahitaji umakini', 'evidence_scan_attention_detail' => 'Matokeo yanayosubiri, yaliyoshindwa au yaliyotengwa', 'overdue_citizen_cases' => 'Kesi za wananchi zilizochelewa', 'overdue_citizen_cases_detail' => 'Kesi ambazo hazijatatuliwa baada ya makataa', 'delayed_exchequer_requests' => 'Maombi ya hazina yaliyochelewa', 'delayed_exchequer_requests_detail' => 'Maombi wazi zaidi ya SLA ya hatua ya sasa', 'overdue_evaluation_findings' => 'Matokeo ya tathmini yaliyochelewa', 'overdue_evaluation_findings_detail' => 'Mapendekezo yaliyopita muda na hayajafungwa', 'open_partner_alerts' => 'Tahadhari wazi za washirika', 'open_partner_alerts_detail' => 'Vighairi vya makubaliano au michango ambavyo havijatatuliwa',
    'counties_in_view' => 'Kaunti zinazoonekana', 'assessed' => 'zimetathminiwa', 'pending' => 'zinasubiri', 'completed_assessments_detail' => 'Katika tathmini zilizokamilika', 'selected_period_detail' => 'Ndani ya kipindi kilichochaguliwa', 'grant_disbursement' => 'Utoaji wa ruzuku', 'disbursed_lower' => 'imetolewa', 'separator' => '·', 'range_separator' => '–', 'slash' => '/', 'percent' => '%',
    'profiles' => [
        'county-official' => ['role_label' => 'Afisa wa kaunti', 'eyebrow' => 'Eneo la kazi la kaunti', 'title' => 'Utayari wa ushahidi na tathmini', 'description' => 'Andaa ushahidi wa kaunti, fuatilia ukamilifu na ufuate matokeo ya hivi karibuni ya tathmini.', 'focus' => ['first' => 'Kamilisha ushahidi uliosalia', 'second' => 'Jibu kesi za huduma za kaunti', 'third' => 'Fuatilia hatua za marekebisho']],
        'county-admin' => ['role_label' => 'Msimamizi wa kaunti', 'eyebrow' => 'Usimamizi wa kaunti', 'title' => 'Udhibiti wa utendaji wa kaunti', 'description' => 'Ratibu maafisa, ukusanyaji wa ushahidi, uwasilishaji, ruzuku na utayari wa kaunti.', 'focus' => ['first' => 'Ondoa vizuizi vya uwasilishaji', 'second' => 'Ratibu wahusika wa utekelezaji wa kaunti', 'third' => 'Pandisha wajibu uliochelewa']],
        'assessor' => ['role_label' => 'Mkadiriaji huru', 'eyebrow' => 'Uthibitishaji huru', 'title' => 'Tathmini za kaunti ulizopangiwa', 'description' => 'Kagua ushahidi na maendeleo ya tathmini kwa kaunti ulizopangiwa pekee.', 'focus' => ['first' => 'Tanguliza tathmini zilizowasilishwa', 'second' => 'Kamilisha foleni za ukaguzi wa ushahidi', 'third' => 'Rekodi matokeo huru']],
        'development-partner' => ['role_label' => 'Mshirika wa maendeleo', 'eyebrow' => 'Wigo wa mshirika', 'title' => 'Matokeo ya programu na ruzuku', 'description' => 'Fuatilia matokeo ya tathmini, ushahidi na utoaji wa ruzuku katika wigo wako wa ushirikiano.', 'focus' => ['first' => 'Kagua matumizi ya ruzuku', 'second' => 'Tatua tahadhari za utekelezaji wa washirika', 'third' => 'Thibitisha matokeo ya programu']],
        'top-management' => ['role_label' => 'Uongozi wa juu', 'eyebrow' => 'Usimamizi wa kiutendaji', 'title' => 'Muhtasari wa utendaji wa kaunti', 'description' => 'Fuatilia kaunti katika wigo wako wa usimamizi na elekeza umakini pale utekelezaji unapochelewa.', 'focus' => ['first' => 'Chukua hatua kwa ahadi zilizochelewa', 'second' => 'Kagua kaunti zenye utendaji wa chini', 'third' => 'Idhinisha maamuzi yanayosubiri']],
        'devolution-admin' => ['role_label' => 'Msimamizi wa ugatuzi', 'eyebrow' => 'Uratibu wa kitaifa', 'title' => 'Udhibiti wa utekelezaji wa kaunti zote', 'description' => 'Ratibu mizunguko ya tathmini, utayari wa ushahidi, ruzuku na utendaji katika kaunti zote 47.', 'focus' => ['first' => 'Endesha ukamilishaji wa mzunguko wa kitaifa', 'second' => 'Tatua vizuizi vya kaunti mbalimbali', 'third' => 'Linda uadilifu wa ushahidi na taarifa']],
        'platform-admin' => ['role_label' => 'Msimamizi wa jukwaa', 'eyebrow' => 'Uendeshaji wa jukwaa', 'title' => 'Udhibiti wa jukwaa la kitaifa', 'description' => 'Fuatilia ueneaji wa jukwaa na simamia ufikiaji unaodhibitiwa katika huduma ya kitaifa.', 'focus' => ['first' => 'Dumisha uendeshaji wa huduma', 'second' => 'Simamia ufikiaji na miunganisho', 'third' => 'Kagua vighairi vya uhakikisho']],
    ],
];
