<?php

return [
    'registered_assets' => 'Rasilimali zilizosajiliwa', 'processing_activities' => 'Shughuli za uchakataji', 'retention_schedules' => 'Ratiba za uhifadhi', 'privacy_requests' => 'Maombi ya faragha', 'breach_incidents' => 'Matukio ya ukiukaji',
    'personal_data_breach_register' => 'Rejesta ya ukiukaji wa data binafsi', 'no_privacy_incidents' => 'Hakuna matukio ya faragha', 'no_data_assets_registered' => 'Hakuna rasilimali za data zilizosajiliwa', 'processing_activity_register' => 'Rejesta ya shughuli za uchakataji', 'no_processing_activities' => 'Hakuna shughuli za uchakataji', 'no_privacy_requests' => 'Hakuna maombi ya faragha',
    'decision' => 'Uamuzi', 'independent_review_findings' => 'Matokeo ya mapitio huru', 'workflow_transition' => 'Hamisho la mtiririko wa kazi', 'identity_evidence_reference' => 'Rejea ya ushahidi wa utambulisho', 'decision_or_response' => 'Uamuzi au jibu', 'reason_and_legal_assessment' => 'Sababu na tathmini ya kisheria', 'response_evidence_reference' => 'Rejea ya ushahidi wa jibu',
    'register_data_asset' => 'Sajili rasilimali ya data', 'asset_code' => 'Msimbo wa rasilimali', 'asset_name' => 'Jina la rasilimali', 'accountable_data_owner' => 'Mmiliki wa data mwenye uwajibikaji', 'operational_data_steward' => 'Msimamizi wa data wa uendeshaji', 'tor_module_or_shared_service' => 'Moduli ya ToR au huduma ya pamoja', 'authoritative_source' => 'Chanzo rasmi', 'classification' => 'Uainishaji', 'residency_country' => 'Nchi data inapohifadhiwa',
    'contains_personal_data' => 'Ina data binafsi', 'contains_sensitive_personal_data' => 'Ina data nyeti binafsi', 'dataset_scope_and_intended_use' => 'Wigo na matumizi yaliyokusudiwa ya mkusanyiko wa data', 'personal_data_categories_comma_separated' => 'Kategoria za data binafsi (tenganisha kwa koma)', 'data_subject_categories_comma_separated' => 'Kategoria za wahusika wa data (tenganisha kwa koma)', 'approved_storage_locations_comma_separated' => 'Maeneo ya hifadhi yaliyoidhinishwa (tenganisha kwa koma)', 'quality_and_provenance_standard' => 'Kiwango cha ubora na asili',
    'schedule_code' => 'Msimbo wa ratiba', 'record_class' => 'Daraja la rekodi', 'retention_months' => 'Miezi ya uhifadhi', 'disposition_action' => 'Hatua ya mwisho ya rekodi', 'next_review_date' => 'Tarehe ya mapitio yanayofuata', 'retention_trigger_event' => 'Tukio linaloanzisha uhifadhi', 'legal_or_approved_records_authority' => 'Mamlaka ya kisheria au iliyoidhinishwa ya rekodi', 'legal_hold_suspension_rule' => 'Kanuni ya kusimamisha kwa amri ya kisheria',
    'submit_processing_activity' => 'Wasilisha shughuli ya uchakataji', 'data_asset' => 'Rasilimali ya data', 'retention_schedule' => 'Ratiba ya uhifadhi', 'processing_reference' => 'Rejea ya uchakataji', 'activity_name' => 'Jina la shughuli', 'lawful_basis' => 'Msingi wa kisheria', 'controller' => 'Mdhibiti', 'dpia_status' => 'Hali ya DPIA', 'dpia_evidence_reference' => 'Rejea ya ushahidi wa DPIA',
    'uses_automated_decision_making' => 'Inatumia ufanyaji maamuzi otomatiki', 'includes_cross_border_transfer' => 'Inajumuisha uhamisho wa kuvuka mipaka', 'specific_processing_purpose' => 'Madhumuni mahsusi ya uchakataji', 'lawful_basis_authority_and_assessment' => 'Mamlaka na tathmini ya msingi wa kisheria', 'processors_comma_separated' => 'Wachakataji (tenganisha kwa koma)', 'recipient_categories_comma_separated' => 'Kategoria za wapokeaji (tenganisha kwa koma)', 'processing_operations_comma_separated' => 'Shughuli za uchakataji (tenganisha kwa koma)', 'transfer_countries_comma_separated' => 'Nchi za uhamisho (tenganisha kwa koma)', 'transfer_safeguards' => 'Hatua za ulinzi wa uhamisho', 'privacy_risk_summary' => 'Muhtasari wa hatari ya faragha', 'technical_and_organizational_measures' => 'Hatua za kiufundi na kishirika',
    'record_data_subject_request' => 'Rekodi ombi la mhusika wa data', 'request_type' => 'Aina ya ombi', 'assigned_privacy_operator' => 'Mhudumu wa faragha aliyeteuliwa', 'requester_name' => 'Jina la mwombaji', 'controlled_contact' => 'Mawasiliano yanayodhibitiwa', 'contact_channel' => 'Njia ya mawasiliano', 'received_date_and_time' => 'Tarehe na saa ya kupokelewa', 'requested_personal_data_and_service_scope' => 'Data binafsi iliyoombwa na wigo wa huduma',
    'report_personal_data_breach' => 'Ripoti ukiukaji wa data binafsi', 'incident_title' => 'Kichwa cha tukio', 'incident_lead' => 'Kiongozi wa tukio', 'affected_data_asset' => 'Rasilimali ya data iliyoathiriwa', 'affected_county' => 'Kaunti iliyoathiriwa', 'sdd_role' => 'Jukumu la SDD', 'breach_type' => 'Aina ya ukiukaji', 'estimated_affected_people' => 'Makadirio ya watu walioathiriwa', 'sensitive_personal_data_may_be_involved' => 'Data nyeti binafsi huenda imehusika', 'occurred_date_and_time' => 'Tarehe na saa ya tukio', 'discovered_date_and_time' => 'Tarehe na saa ya kugunduliwa', 'controlled_incident_description' => 'Maelezo ya tukio yanayodhibitiwa',
    'containment_actions_completed' => 'Hatua za kudhibiti zilizokamilishwa', 'assessed_severity' => 'Ukali uliotathminiwa', 'real_risk_of_harm' => 'Hatari halisi ya madhara', 'independent_risk_assessment_and_legal_reasoning' => 'Tathmini huru ya hatari na sababu za kisheria', 'odpc_notified_date_and_time' => 'Tarehe na saa ODPC ilipoarifiwa', 'odpc_notification_reference' => 'Rejea ya taarifa kwa ODPC', 'delay_reason_when_after_72_hours' => 'Sababu ya kuchelewa, ikiwa ni baada ya saa 72', 'affected_person_communication' => 'Mawasiliano kwa mtu aliyeathiriwa', 'affected_people_notified_date_and_time' => 'Tarehe na saa watu walioathiriwa walipoarifiwa', 'no_notice_or_delay_rationale' => 'Sababu ya kutotoa taarifa au kuchelewa', 'verified_root_cause' => 'Chanzo kikuu kilichothibitishwa', 'completed_corrective_and_preventive_actions' => 'Hatua za kurekebisha na kuzuia zilizokamilishwa', 'controlled_closure_evidence_reference' => 'Rejea ya ushahidi wa kufungwa unaodhibitiwa',
];
