<?php

return ['collaboration_threads' => 'Majadiliano ya ushirikiano yanayosimamiwa', 'collaboration_description' => 'Majadiliano ya kikundi huhifadhi michango yenye wahusika na alama za ukaguzi ndani ya wigo wa kaunti ulioidhinishwa.', 'no_collaboration_threads' => 'Hakuna majadiliano ya ushirikiano', 'no_collaboration_description' => 'Fungua mjadala wa kwanza unaosimamiwa kwa kikundi kilichoidhinishwa.', 'create_thread' => 'Unda mjadala', 'new_thread' => 'Mjadala mpya', 'create_thread_description' => 'Anzisha mjadala wenye mhusika ndani ya kikundi kilichoidhinishwa.', 'working_group' => 'Kikundi kazi', 'thread_title' => 'Kichwa cha mjadala', 'opening_contribution' => 'Mchango wa ufunguzi', 'thread_messages' => 'Michango ya mjadala', 'checksum' => 'Alama ya ukaguzi:', 'post_contribution' => 'Chapisha mchango', 'reply' => 'Jibu', 'contribution' => 'Mchango', 'separator' => '·', 'thread_closed' => 'Mjadala huu wa ushirikiano umefungwa.',
    'action_create_unauthorized' => 'Hujaidhinishwa kugawa vitendo vya DSWG.', 'accountable_member_required' => 'Mhusika mwenye wajibu lazima awe mwanachama hai wa kikundi hiki.', 'action_county_outside_portfolio' => 'Kaunti ya kitendo iko nje ya wigo wa kikundi kazi.', 'action_decision_mismatch' => 'Uamuzi uliochaguliwa si wa mkutano huu.',
    'meeting_series_create_unauthorized' => 'Hujaidhinishwa kuunda mikutano ya DSWG inayojirudia.', 'recurring_invitee_member_required' => 'Kila mwalikwa wa kudumu lazima awe mwanachama hai wa kikundi kazi.', 'recurring_quorum_exceeded' => 'Akidi haiwezi kuzidi idadi ya waalikwa wa kudumu.',
    'group_create_unauthorized' => 'Hujaidhinishwa kuanzisha vikundi kazi vya DSWG.', 'group_county_outside_scope' => 'Kaunti moja au zaidi zilizochaguliwa ziko nje ya wigo wako ulioidhinishwa.',
    'audit_action_created' => 'Kitendo cha DSWG :code kimegawiwa.', 'audit_meeting_series_created' => 'Mfululizo wa mikutano ya DSWG :reference umeundwa.', 'audit_group_created' => 'DSWG :code imeundwa.',
    'invitee_member_required' => 'Kila mwalikwa lazima awe mwanachama wa kikundi kazi.', 'quorum_exceeded' => 'Akidi haiwezi kuzidi idadi ya waalikwa.', 'meeting_workflow_unavailable' => 'Mtiririko wa kazi wa mkutano haupatikani.',
    'attendance_invitees_only' => 'Mahudhurio yanaweza kujumuisha washiriki walioalikwa pekee.', 'clean_minutes_required' => 'Kumbukumbu safi iliyounganishwa na hazina inahitajika kabla ya idhini.', 'decision_after_outcomes' => 'Maamuzi yanaweza kusajiliwa tu baada ya matokeo kurekodiwa.',
    'action_after_outcomes' => 'Vitendo vinaweza kugawiwa tu baada ya matokeo ya mkutano kurekodiwa.', 'action_workflow_unavailable' => 'Mtiririko wa kazi wa kitendo haupatikani.', 'workflow_outcomes_recorded' => 'Matokeo ya mkutano na rasimu ya kumbukumbu vimerekodiwa.',
    'outcome_group_created' => 'Kikundi kazi cha sekta kimeanzishwa.', 'outcome_meeting_scheduled' => 'Mkutano umepangwa na mialiko imetumwa.', 'outcome_thread_created' => 'Mjadala wa ushirikiano umeundwa.', 'outcome_contribution_posted' => 'Mchango umechapishwa.',
    'outcome_meeting_series_created' => 'Mfululizo wa mikutano :reference umeundwa na ratiba yake inayoendelea imetengenezwa.', 'outcome_invitation_recorded' => 'Jibu la mwaliko limerekodiwa.', 'outcome_meeting_outcomes_recorded' => 'Matokeo ya mkutano yamerekodiwa kwa idhini huru ya kumbukumbu.',
    'outcome_minutes_approved' => 'Kumbukumbu zimeidhinishwa na mkutano umefungwa.', 'outcome_decision_registered' => 'Uamuzi wa mkutano umesajiliwa.', 'outcome_action_created' => 'Kitendo chenye uwajibikaji kimeundwa na mhusika amearifiwa.', 'outcome_action_updated' => 'Mtiririko wa kazi wa kitendo umesasishwa.',
    'notification_meeting_title' => 'Mwaliko wa mkutano wa DSWG', 'notification_meeting_message' => 'Umealikwa kwenye :title tarehe :date.', 'notification_action_title' => 'Kitendo kipya cha DSWG kimegawiwa', 'notification_action_message' => ':code: :title kinapaswa kukamilika :date.',
    'audit_meeting_scheduled' => 'Mkutano wa DSWG :reference umepangwa.', 'audit_thread_created' => 'Mjadala wa ushirikiano wa DSWG :title umeundwa.', 'audit_contribution_posted' => 'Mchango umechapishwa kwenye mjadala wa DSWG :title.',
    'audit_invitation_responded' => 'Mwaliko wa mkutano umewekwa :status.', 'audit_outcomes_recorded' => 'Rasimu ya kumbukumbu imerekodiwa kwa :reference.', 'audit_minutes_approved' => 'Kumbukumbu zimeidhinishwa kwa :reference.',
    'audit_decision_adopted' => 'Uamuzi wa DSWG :code umepitishwa.', 'audit_action_transitioned' => 'Kitendo cha DSWG :code kimehamishwa kupitia :transition.',
];
