<?php

return [
    'separator' => '·',
    'upload_evidence' => 'Pakia ushahidi', 'upload_evidence_description' => 'Pakia nakala iliyochanganuliwa au faili lililozaliwa kidijitali. Faili huhifadhiwa kwa faragha na kuunganishwa na mzunguko wa tathmini uliochaguliwa.', 'upload_criterion_evidence' => 'Pakia ushahidi wa kigezo', 'upload_criterion_evidence_description' => 'Faili huhifadhiwa kwa faragha na huhesabiwa katika ukamilifu baada tu ya uthibitishaji huru.', 'assessment' => 'Tathmini', 'evidence_requirement' => 'Hitaji la ushahidi', 'source_type' => 'Aina ya chanzo', 'category_placeholder' => 'ADP, CIDP…', 'upload' => 'Pakia', 'uploading' => 'Inapakia :percentage%', 'attachment_help' => 'PDF, waraka wa ofisi, picha au faili ya data yenye muundo ndani ya kikomo cha ukubwa kilichoidhinishwa.', 'choose_file' => 'Chagua faili', 'remove_file' => 'Ondoa faili iliyochaguliwa', 'selected_file' => 'Imechaguliwa', 'attachment_security' => 'Upakiaji wa faragha · ukaguzi wa programu hasidi, checksum ya SHA-256 na toleo lisilobadilika hurekodiwa baada ya kuwasilisha.',
    'errors' => ['integrity_failed' => 'Uthibitishaji wa uadilifu wa hati umeshindwa.', 'preview_unavailable' => 'Hakiki haipatikani kwa aina hii ya faili.', 'document_quarantined' => 'Hati hii imetengwa hadi ukaguzi wake wa usalama ufaulu.', 'version_quarantined' => 'Toleo hili la hati limetengwa hadi ukaguzi wake wa usalama ufaulu.', 'version_integrity_failed' => 'Uthibitishaji wa uadilifu wa toleo la hati umeshindwa.', 'assessment_locked' => 'Ushahidi umefungwa baada ya tathmini.', 'retention_locked' => 'Muda wa kuhifadhi hauwezi kubadilishwa wakati zuio la kisheria linatumika.', 'archive_locked' => 'Hati iliyo chini ya zuio la kisheria haiwezi kuwekwa kwenye kumbukumbu.', 'clean_current_version_required' => 'Toleo la sasa lililo safi pekee ndilo linaweza kuchakatwa.', 'hold_separation_required' => 'Afisa aliyeweka zuio la kisheria hawezi kuliondoa.', 'media_range_invalid_with_value' => 'Sehemu ya media iliyoombwa si sahihi: :range.', 'media_range_invalid' => 'Sehemu ya media iliyoombwa si sahihi.', 'media_range_outside_file' => 'Sehemu ya media :start-:end iko nje ya faili ya baiti :size.'],
    'audit' => ['previewed' => 'Hati imehakikiwa: :title.', 'downloaded' => 'Hati imepakuliwa: :title.', 'version_previewed' => 'Toleo la hati :version limehakikiwa: :title.', 'version_downloaded' => 'Toleo la hati :version limepakuliwa: :title.', 'metadata_updated' => 'Metadata ya hati imesasishwa: :title.', 'archived' => 'Hati imewekwa kwenye kumbukumbu: :title.', 'hold_released' => 'Zuio la kisheria :reference limeondolewa.'],
    'outcomes' => ['uploaded' => 'Ushahidi umepakiwa kwa usalama.', 'verified' => 'Uthibitishaji wa ushahidi umerekodiwa.', 'metadata_updated' => 'Metadata ya hati imesasishwa.', 'archived' => 'Hati imewekwa kwenye kumbukumbu.', 'version_uploaded' => 'Toleo jipya la hati lisilobadilika limepakiwa.', 'extraction_queued' => 'Utoaji wa maandishi ya hati umewekwa kwenye foleni.', 'hold_placed' => 'Zuio la kisheria limewekwa.', 'hold_released' => 'Zuio la kisheria limeondolewa.', 'disposition_submitted' => 'Uondoaji unaodhibitiwa umewasilishwa kwa ukaguzi huru.', 'disposition_decided' => 'Uamuzi wa ukaguzi wa uondoaji umerekodiwa.', 'disposition_executed' => 'Uondoaji unaodhibitiwa umetekelezwa na ushahidi umehifadhiwa.'],
    'disposition' => [
        'errors' => ['retention_due_required' => 'Tarehe ya mwisho ya uhifadhi inahitajika kabla ya kuomba uondoaji.', 'legal_hold_request' => 'Hati iliyo chini ya zuio la kisheria haiwezi kuingia kwenye mchakato wa uondoaji.', 'retention_not_expired_request' => 'Uondoaji hauwezi kupangwa kabla ya muda wa uhifadhi kuisha.', 'open_request_exists' => 'Hati hii tayari ina ombi la uondoaji lililo wazi.', 'reviewer_separation' => 'Afisa aliyeomba hawezi kuamua ombi la uondoaji.', 'pending_required' => 'Ombi la uondoaji linalosubiri pekee ndilo linaweza kuamuliwa.', 'execution_separation' => 'Utekelezaji wa uondoaji unahitaji afisa tofauti na mwombaji na mkaguzi.', 'legal_hold_execute' => 'Hati iliyo chini ya zuio la kisheria haiwezi kuondolewa.', 'retention_not_expired_execute' => 'Muda wa uhifadhi ulioidhinishwa bado haujaisha.', 'executable_status_required' => 'Uondoaji ulioidhinishwa au ulioshindwa pekee ndio unaweza kutekelezwa.', 'retained_object_missing' => 'Kitu kilichohifadhiwa hakipo: :path.', 'retained_object_integrity' => 'Uthibitishaji wa uadilifu umeshindwa kwa kitu kilichohifadhiwa: :path.', 'secure_deletion_unconfirmed' => 'Ufutaji salama wa kitu haukuweza kuthibitishwa: :path.', 'execution_state_changed' => 'Hali ya utekelezaji wa uondoaji ilibadilika bila kutarajiwa.'],
        'audit' => ['requested' => 'Uondoaji unaodhibitiwa umeombwa kwa :title.', 'decided' => 'Uondoaji wa hati :decision.', 'executed' => 'Uondoaji unaodhibitiwa umetekelezwa kwa :title.'],
        'statuses' => ['approved' => 'umeidhinishwa', 'rejected' => 'umekataliwa'],
    ],
    'open_actions' => 'Fungua vitendo vya ushahidi', 'preview_document' => 'Hakiki hati', 'download_original' => 'Pakua asili', 'manage_record' => 'Simamia rekodi', 'reprocess_text' => 'Chakata tena maandishi yanayotafutika', 'verify_evidence' => 'Thibitisha ushahidi', 'reject_evidence' => 'Kataa ushahidi',
    'document_preview' => 'Hakiki ya hati', 'secure_document' => 'Hati salama ya ushahidi', 'scanned_copy' => 'Nakala iliyochanganuliwa', 'digital_file' => 'Faili la kidijitali', 'text_extraction' => 'Utoaji wa maandishi: :status', 'not_requested' => 'haijaombwa', 'searchable_unavailable' => 'Maandishi yanayotafutika hayapatikani',
    'attempts_title' => 'Ushahidi wa majaribio ya utoaji', 'attempts_description' => 'Historia isiyofutika ya uchakataji na majaribio kwa toleo la sasa lisilobadilika.', 'attempt' => 'Jaribio', 'source' => 'Chanzo', 'actor' => 'Mhusika', 'engine' => 'Injini', 'status' => 'Hali', 'duration' => 'Muda', 'result' => 'Matokeo', 'in_progress' => 'Inaendelea', 'characters' => 'Herufi :count',
    'preview_of' => 'Hakiki ya :title', 'document' => 'hati', 'extracted_preview' => 'Hakiki ya maandishi yaliyotolewa', 'download_original_document' => 'Pakua hati asili', 'preview_page' => 'Hakiki :page kati ya :total', 'sha256_verified' => 'SHA-256 imethibitishwa', 'uploaded_by_marker' => 'Imepakiwa na :actor', 'previous_preview' => 'Hakiki iliyotangulia ya hati', 'next_preview' => 'Hakiki inayofuata ya hati',
    'manage_document' => 'Simamia hati', 'manage_description' => 'Sasisha metadata inayodhibitiwa, matoleo, uhifadhi na vizuizi vya kisheria.', 'title' => 'Kichwa', 'category' => 'Aina', 'document_date' => 'Tarehe ya hati', 'description' => 'Maelezo', 'tags' => 'Lebo', 'tags_placeholder' => 'mipango, MW2025', 'retain_until' => 'Hifadhi hadi', 'save_metadata' => 'Hifadhi metadata',
    'versions_title' => 'Matoleo yasiyobadilika', 'version_integrity' => 'Toleo :version · SHA-256 :checksum · ukaguzi :scan · utoaji wa maandishi :ocr', 'completed_at' => ' · imekamilika :date', 'replacement_reason' => 'Sababu ya ubadilishaji huu', 'upload_version' => 'Pakia toleo jipya', 'no_versions' => 'Hakuna historia ya matoleo iliyohifadhiwa kwa rekodi hii ya zamani.', 'version_number' => 'Toleo :number', 'current' => 'La sasa', 'uploaded_by' => ':name · limepakiwa na :actor · :date', 'preview' => 'Hakiki', 'download' => 'Pakua', 'initial_version' => 'Toleo la awali linalodhibitiwa', 'version_manifest' => 'SHA-256 :checksum · baiti :bytes · maandishi :status',
    'place_hold' => 'Weka zuio la kisheria', 'place_hold_description' => 'Zuia ubadilishaji, uhifadhi wa nyaraka na mabadiliko ya muda wa kuhifadhi.', 'hold_reference' => 'Rejea ya zuio', 'issuing_authority' => 'Mamlaka inayotoa', 'hold_reason' => 'Sababu ya kisheria au kanuni', 'under_hold' => 'Rekodi hii iko chini ya zuio la kisheria. Ubadilishaji, mabadiliko ya uhifadhi na uwekaji kwenye kumbukumbu vimefungwa.', 'hold_history' => 'Historia ya vizuizi vya kisheria', 'hold_history_description' => 'Maamuzi ya kuweka na kuondoa zuio yanaendelea kuonekana baada ya zuio kuondolewa.', 'no_holds' => 'Hakuna vizuizi vya kisheria vilivyorekodiwa.', 'hold_placed' => ':authority · limewekwa na :actor · :date', 'released' => 'Limeondolewa', 'active' => 'Linatumika', 'hold_released' => 'Limeondolewa na :actor tarehe :date. :reason', 'unknown' => 'Haijulikani', 'release_reason' => 'Sababu ya kuondoa', 'release_placeholder' => 'Mamlaka na sababu ya kuondoa zuio hili', 'release_hold' => 'Ondoa zuio la kisheria',
    'archive_document' => 'Weka hati kwenye kumbukumbu', 'request_disposition' => 'Omba uondoaji unaodhibitiwa', 'disposition_description' => 'Inahitaji ukaguzi huru na afisa tofauti wa utekelezaji. Vizuizi vya kisheria na hitilafu za uadilifu huzuia utekelezaji.', 'retention_required' => 'Tarehe ya uhifadhi inahitajika', 'retention_required_description' => 'Weka tarehe iliyoidhinishwa ya kuhifadhi hadi kabla ya kuomba uharibifu salama.', 'authority_reference' => 'Rejea ya mamlaka', 'authority_placeholder' => 'Ratiba iliyoidhinishwa au mamlaka ya uondoaji', 'scheduled_date' => 'Tarehe ya utekelezaji iliyopangwa', 'disposition_reason' => 'Sababu ya uondoaji', 'disposition_placeholder' => 'Aina ya rekodi, kichocheo cha uhifadhi na sababu ya kuidhinisha uharibifu', 'submit_disposition' => 'Wasilisha uondoaji kwa ukaguzi',
    'disposition_history' => 'Historia ya uondoaji', 'disposition_history_description' => 'Maombi, maamuzi huru, hitilafu za utekelezaji na ushahidi usiobadilika wa uharibifu.', 'no_dispositions' => 'Hakuna maombi ya uondoaji yaliyorekodiwa.', 'secure_destruction' => 'Uharibifu salama · :reference', 'requested_by' => 'Imeombwa na :actor tarehe :date', 'retention_schedule' => 'Uhifadhi unafikia :due · umepangwa :scheduled', 'reviewed_by' => 'Imekaguliwa na :actor tarehe :date. :reason', 'execution_stopped' => 'Utekelezaji umesimamishwa', 'executed_by' => 'Imetekelezwa na :actor tarehe :date. Vitu :objects / baiti :bytes.', 'manifest_checksum' => 'Cheksamu ya manifesti SHA-256 :checksum', 'independent_reason' => 'Sababu ya ukaguzi huru', 'approve' => 'Idhinisha', 'reject' => 'Kataa', 'execute_destruction' => 'Tekeleza uharibifu salama ulioidhinishwa',
];
