<?php

return [
    'no_dependency_paths_in_scope' => 'Hakuna njia za utegemezi ndani ya wigo', 'categories' => 'Kategoria', 'severities' => 'Viwango vya ukali', 'no_resolutions_available' => 'Hakuna maazimio yanayopatikana', 'no_matching_implementation_gaps' => 'Hakuna mapengo ya utekelezaji yanayolingana', 'no_matching_resolutions' => 'Hakuna maazimio yanayolingana',
    'establish_igr_forum' => 'Anzisha jukwaa la IGR', 'forum_code' => 'Msimbo wa jukwaa', 'igr_cg_summit' => 'IGR-CG-SUMMIT', 'forum_name' => 'Jina la jukwaa', 'forum_type' => 'Aina ya jukwaa', 'mandate' => 'Mamlaka', 'secretariat' => 'Sekretarieti',
    'record_formal_igr_meeting' => 'Rekodi mkutano rasmi wa IGR', 'forum' => 'Jukwaa', 'meeting_reference' => 'Rejea ya mkutano', 'igr_summit_2026_04' => 'IGR/SUMMIT/2026/04', 'meeting_title' => 'Kichwa cha mkutano', 'meeting_date' => 'Tarehe ya mkutano', 'venue' => 'Mahali', 'chair' => 'Mwenyekiti', 'minutes_reference' => 'Rejea ya kumbukumbu', 'dms_igr_min_2026_04' => 'DMS/IGR/MIN/2026/04',
    'create_implementation_gap_category' => 'Unda kategoria ya pengo la utekelezaji', 'category_code' => 'Msimbo wa kategoria', 'data_quality' => 'DATA-QUALITY', 'category_name' => 'Jina la kategoria', 'description_label' => 'Maelezo', 'default_severity' => 'Ukali chaguomsingi',
    'register_adopted_resolution' => 'Sajili azimio lililopitishwa', 'source_forum' => 'Jukwaa chanzo', 'formal_meeting_optional_for_historical_records' => 'Mkutano rasmi (hiari kwa rekodi za kihistoria)', 'resolution_number' => 'Nambari ya azimio', 'igr_2026_001' => 'IGR/2026/001', 'title_label' => 'Kichwa', 'resolution_date' => 'Tarehe ya azimio', 'implementation_deadline' => 'Tarehe ya mwisho ya utekelezaji', 'resolution_text' => 'Maandishi ya azimio', 'priority' => 'Kipaumbele',
    'county' => 'Kaunti', 'organization' => 'Shirika', 'role' => 'Jukumu', 'prerequisites' => 'Masharti tangulizi', 'dependent_resolutions' => 'Maazimio tegemezi', 'report_implementation_gap' => 'Ripoti pengo la utekelezaji', 'gap_category' => 'Kategoria ya pengo', 'gap_title' => 'Kichwa cha pengo', 'implementation_impact' => 'Athari ya utekelezaji', 'severity' => 'Ukali', 'accountable_owner' => 'Mmiliki mwenye uwajibikaji', 'affected_county' => 'Kaunti iliyoathiriwa', 'mitigation_due_date' => 'Tarehe ya mwisho ya kupunguza athari',
    'add_resolution_dependency' => 'Ongeza utegemezi wa azimio', 'prerequisite_resolution' => 'Azimio tangulizi', 'dependency_type' => 'Aina ya utegemezi', 'dependency_rationale' => 'Sababu ya utegemezi', 'record_implementation_progress' => 'Rekodi maendeleo ya utekelezaji', 'progress_percentage' => 'Asilimia ya maendeleo', 'evidence_note_or_reference_optional' => 'Dokezo au rejea ya ushahidi (hiari)', 'add_context_for_the_linked_repository_evidence' => 'Ongeza muktadha wa ushahidi uliounganishwa kwenye hazina', 'implementation_narrative' => 'Maelezo ya utekelezaji',
    'start_implementation' => 'Anza utekelezaji', 'submit_for_closure' => 'Wasilisha ili kufungwa', 'approve_closure' => 'Idhinisha kufungwa', 'return_for_action' => 'Rudisha kwa hatua zaidi', 'start_mitigation' => 'Anza kupunguza athari', 'submit_resolution' => 'Wasilisha utatuzi', 'accept_resolution' => 'Kubali utatuzi', 'return_mitigation' => 'Rudisha hatua za kupunguza athari', 'decision_rationale' => 'Sababu za uamuzi', 'decision_comment' => 'Maoni ya uamuzi',
    'gap_transition_description' => 'Rekodi msingi wa uamuzi wa mzunguko unaosimamiwa wa pengo la utekelezaji.', 'transition_not_available' => 'Hamisho hili halipatikani.', 'transition_decision_basis' => 'Rekodi msingi wa uamuzi wa :transition.',
];
