<?php

return [
    'operational_status' => 'Hali ya uendeshaji', 'county' => 'Kaunti',
    'no_integration_systems_registered' => 'Hakuna mifumo ya ujumuishaji iliyosajiliwa', 'exchange_register' => 'Rejesta ya ubadilishanaji', 'no_matching_exchanges' => 'Hakuna ubadilishanaji unaolingana', 'no_reconciliation_exceptions' => 'Hakuna tofauti za upatanisho',
    'owner' => 'Mmiliki', 'owner_organization' => 'Shirika mmiliki', 'reference_catalogue' => 'Katalogi ya marejeo', 'classification' => 'Uainishaji', 'authentication' => 'Uthibitishaji', 'health' => 'Afya ya mfumo', 'endpoint' => 'Ncha ya huduma', 'credential_reference' => 'Rejea ya kitambulisho cha siri',
    'source_owner_approval_reference' => 'Rejea ya idhini ya mmiliki wa chanzo', 'data_sharing_agreement_reference' => 'Rejea ya makubaliano ya kushiriki data', 'effective_from' => 'Inaanza kutumika', 'effective_until' => 'Inatumika hadi',
    'register_integration_system' => 'Sajili mfumo wa ujumuishaji', 'system_code' => 'Msimbo wa mfumo', 'system_name' => 'Jina la mfumo', 'authoritative_system_owner' => 'Mmiliki rasmi wa mfumo',
    'environment' => 'Mazingira', 'transport' => 'Usafirishaji', 'direction' => 'Mwelekeo', 'data_classification' => 'Uainishaji wa data', 'lifecycle_status' => 'Hali ya mzunguko wa maisha', 'base_url' => 'URL ya msingi', 'credential_vault_reference' => 'Rejea ya hifadhi ya vitambulisho vya siri',
    'purpose_and_authorized_data_use' => 'Madhumuni na matumizi ya data yaliyoidhinishwa', 'submit_interface_contract' => 'Wasilisha mkataba wa kiolesura', 'integration_system' => 'Mfumo wa ujumuishaji', 'contract_name' => 'Jina la mkataba', 'canonical_resource' => 'Rasilimali sanifu', 'http_method' => 'Mbinu ya HTTP',
    'resource_path' => 'Njia ya rasilimali', 'idempotency_field' => 'Sehemu ya kutorudia matokeo', 'rate_limit_per_minute' => 'Kikomo cha maombi kwa dakika', 'request_json_schema' => 'Skima ya JSON ya ombi', 'response_json_schema' => 'Skima ya JSON ya jibu',
    'canonical_field_mappings' => 'Ulinganishaji wa sehemu sanifu', 'required_headers' => 'Vichwa vinavyohitajika', 'retry_policy' => 'Sera ya kujaribu tena', 'idempotency_key' => 'Ufunguo wa kutorudia matokeo', 'external_reference' => 'Rejea ya nje', 'county_scope' => 'Wigo wa kaunti',
    'source_event_time' => 'Muda wa tukio la chanzo', 'contract_valid_json_payload' => 'Mzigo wa JSON unaokubaliana na mkataba', 'source_owner_activation_reference' => 'Rejea ya uanzishaji ya mmiliki wa chanzo', 'approval_date_and_time' => 'Tarehe na saa ya idhini',
    'contract' => 'Mkataba', 'payload_checksum' => 'Jumla hakiki ya mzigo', 'status' => 'Hali', 'next_attempt' => 'Jaribio linalofuata', 'accepted' => 'Imekubaliwa', 'no_retained_attempts' => 'Hakuna majaribio yaliyohifadhiwa',
    'description_label' => 'Maelezo', 'references' => 'Marejeo', 'verified_resolution_and_evidence' => 'Utatuzi na ushahidi uliothibitishwa',
    'no_systems_description' => 'Sajili mfumo wa kwanza wa chanzo na uwasilishe mkataba wa kiolesura wenye toleo kwa idhini huru.', 'exchange_record_count' => 'Rekodi :count za ubadilishanaji salama wa payload', 'no_exchanges_description' => 'Tuma payload ya sandbox inayokidhi schema au rekebisha vichujio.', 'no_discrepancies_description' => 'Hakuna tofauti zinazolingana na wigo na vichujio vya sasa.', 'actions_for_record' => 'Vitendo vya :record', 'publish_contract' => 'Chapisha :name v:version', 'publish_contract_description' => 'Idhinisha kwa uhuru mkataba wa schema usiobadilika. Violesura vya uzalishaji vinahitaji marejeo ya mmiliki wa chanzo na ushiriki wa data.', 'review_and_publish' => 'Kagua na uchapishe', 'new_system_description' => 'Sajili metadata ya endpoint na rejea ya vault pekee. Kamwe usihifadhi vitambulisho katika fomu hii.', 'new_system' => 'Mfumo mpya', 'new_contract_description' => 'Fafanua schema, ulinganishaji, idempotency na sera ya kujaribu tena kwa uchapishaji huru.', 'new_contract' => 'Mkataba mpya', 'actions_for_exchange' => 'Vitendo vya ubadilishanaji :id', 'legacy_exchange_description' => 'Ubadilishanaji huu ulitangulia daftari la majaribio lisilobadilika.', 'view_reconciliation_exception' => 'Tazama hitilafu ya upatanisho :id',
];
