<?php

return ['outcomes' => [
    'system_registered' => 'Mfumo wa muunganisho :code umesajiliwa.', 'activation_recorded' => 'Uanzishaji wa muunganisho wa uzalishaji umerekodiwa.', 'contract_submitted' => 'Mkataba wa kiolesura v:version umewasilishwa kwa tathmini.', 'contract_published' => 'Mkataba wa kiolesura umechapishwa kwa uhuru.', 'exchange_recorded' => 'Ubadilishanaji :correlation umerekodiwa kwa hali :status.', 'exchange_retried' => 'Jaribio jingine la ubadilishanaji :correlation limekamilika kwa hali :status.', 'reconciliation_resolved' => 'Hitilafu ya upatanisho imetatuliwa kwa uamuzi unaoweza kukaguliwa.',
], 'exchange' => [
    'oauth_client' => 'Mteja wa OAuth',
    'errors' => ['fixture_sandbox_only' => 'Usafirishaji wa data ya majaribio unaruhusiwa kwenye mifumo ya sandbox pekee.', 'unsupported_transport' => 'Usafirishaji wa muunganisho [:transport] hautumiki.', 'production_activation_required' => 'Ubadilishanaji wa uzalishaji unahitaji idhini ya uanzishaji ya mmiliki wa chanzo iliyorekodiwa.', 'endpoint_credentials_required' => 'Anwani ya uzalishaji na rejeleo la sifa za hifadhi zinahitajika.', 'host_not_allowlisted' => 'Seva ya muunganisho haipo kwenye orodha ya ruhusa.', 'credential_unresolved' => 'Rejeleo la sifa za hifadhi halijatatuliwa.', 'effective_inbound_contract' => 'Mkataba wa kiolesura uliochapishwa na unaotumika pekee ndio unaweza kupokea data.', 'inbound_not_approved' => 'Mfumo huu wa muunganisho haujaidhinishwa kwa ubadilishanaji unaoingia.', 'system_inactive' => 'Mfumo wa muunganisho haufanyi kazi.', 'oauth_client_unbound' => 'Mteja wa OAuth hajafungamanishwa na mfumo huu wa muunganisho.', 'production_source_approval' => 'Idhini ya uanzishaji ya mmiliki wa chanzo cha uzalishaji inahitajika.', 'production_agreements' => 'Idhini za mkataba wa uzalishaji na ushirikishaji data zinahitajika.', 'missing_headers' => 'Vichwa vinavyohitajika na mkataba havipo: :headers.', 'idempotency_conflict' => 'Ufunguo wa kutorudia tayari umehusishwa na ubadilishanaji mwingine.', 'effective_outbound_contract' => 'Mkataba wa kiolesura uliochapishwa na unaotumika pekee ndio unaweza kubadilishana data.'],
    'audit' => ['ingested' => 'Ubadilishanaji unaoingia :correlation umekubaliwa kutoka :system.'],
]];
