<?php

return ['valid_oauth_client_required' => 'Mteja halali wa OAuth anahitajika.', 'outcomes' => [
    'system_registered' => 'Mfumo wa muunganisho :code umesajiliwa.', 'activation_recorded' => 'Uanzishaji wa muunganisho wa uzalishaji umerekodiwa.', 'contract_submitted' => 'Mkataba wa kiolesura v:version umewasilishwa kwa tathmini.', 'contract_published' => 'Mkataba wa kiolesura umechapishwa kwa uhuru.', 'exchange_recorded' => 'Ubadilishanaji :correlation umerekodiwa kwa hali :status.', 'exchange_retried' => 'Jaribio jingine la ubadilishanaji :correlation limekamilika kwa hali :status.', 'reconciliation_resolved' => 'Hitilafu ya upatanisho imetatuliwa kwa uamuzi unaoweza kukaguliwa.',
], 'exchange' => [
    'oauth_client' => 'Mteja wa OAuth',
    'errors' => ['fixture_sandbox_only' => 'Usafirishaji wa data ya majaribio unaruhusiwa kwenye mifumo ya sandbox pekee.', 'unsupported_transport' => 'Usafirishaji wa muunganisho [:transport] hautumiki.', 'production_activation_required' => 'Ubadilishanaji wa uzalishaji unahitaji idhini ya uanzishaji ya mmiliki wa chanzo iliyorekodiwa.', 'endpoint_credentials_required' => 'Anwani ya uzalishaji na rejeleo la sifa za hifadhi zinahitajika.', 'host_not_allowlisted' => 'Seva ya muunganisho haipo kwenye orodha ya ruhusa.', 'credential_unresolved' => 'Rejeleo la sifa za hifadhi halijatatuliwa.', 'effective_inbound_contract' => 'Mkataba wa kiolesura uliochapishwa na unaotumika pekee ndio unaweza kupokea data.', 'inbound_not_approved' => 'Mfumo huu wa muunganisho haujaidhinishwa kwa ubadilishanaji unaoingia.', 'system_inactive' => 'Mfumo wa muunganisho haufanyi kazi.', 'oauth_client_unbound' => 'Mteja wa OAuth hajafungamanishwa na mfumo huu wa muunganisho.', 'production_source_approval' => 'Idhini ya uanzishaji ya mmiliki wa chanzo cha uzalishaji inahitajika.', 'production_agreements' => 'Idhini za mkataba wa uzalishaji na ushirikishaji data zinahitajika.', 'missing_headers' => 'Vichwa vinavyohitajika na mkataba havipo: :headers.', 'idempotency_conflict' => 'Ufunguo wa kutorudia tayari umehusishwa na ubadilishanaji mwingine.', 'effective_outbound_contract' => 'Mkataba wa kiolesura uliochapishwa na unaotumika pekee ndio unaweza kubadilishana data.', 'delivery_unauthorized' => 'Huna ruhusa ya kuwasilisha mabadilishano ya miunganisho.', 'unsupported_retry_trigger' => 'Kichocheo cha kujaribu tena muunganisho hakitumiki.', 'outbound_delivery_only' => 'Mabadilishano yanayotoka pekee ndiyo yanaweza kuwasilishwa.', 'delivery_ineligible' => 'Ubadilishanaji haustahiki kitendo hiki cha uwasilishaji.', 'retry_not_due' => 'Wakati wa jaribio lililopangwa bado haujafika.', 'remote_http_status' => 'Seva ya mbali imerudisha HTTP :status.', 'delivery_claim_changed' => 'Dai la uwasilishaji wa ubadilishanaji lilibadilika kabla ya kukamilika.', 'contract_publish_unauthorized' => 'Huna ruhusa ya kuchapisha mikataba ya miunganisho.', 'contract_review_required' => 'Mikataba iliyo katika mapitio pekee ndiyo inaweza kuchapishwa.', 'contract_submitter_separation' => 'Mgawanyo wa majukumu unamzuia mwasilishaji kuchapisha mkataba wa kiolesura.', 'production_contract_approvals_required' => 'Mikataba ya uzalishaji inahitaji marejeleo ya idhini ya mmiliki wa chanzo na makubaliano ya kushiriki data.', 'system_activation_unauthorized' => 'Huna ruhusa ya kuanzisha mifumo ya miunganisho.', 'system_registrar_separation' => 'Mgawanyo wa majukumu unamzuia msajili kuanzisha muunganisho wa uzalishaji.', 'production_https_configuration_required' => 'Muunganisho wa uzalishaji wa HTTPS uliosanidiwa kikamilifu pekee ndio unaweza kuanzishwa.', 'published_contract_required' => 'Angalau mkataba mmoja uliochapishwa kwa uhuru unahitajika kabla ya uanzishaji.'],
    'audit' => ['ingested' => 'Ubadilishanaji unaoingia :correlation umekubaliwa kutoka :system.', 'delivery_attempted' => 'Jaribio la :attempt la ubadilishanaji :correlation limekamilika kwa hali :outcome.', 'contract_published' => 'Mkataba wa kiolesura :name t:version umechapishwa.', 'system_activated' => 'Muunganisho wa uzalishaji :code umeanzishwa dhidi ya idhini iliyorekodiwa ya mmiliki wa chanzo.'],
], 'reconciliation' => ['errors' => ['resolve_unauthorized' => 'Hujaruhusiwa kutatua hitilafu za upatanisho wa miunganisho.', 'county_scope' => 'Huwezi kutatua hitilafu za upatanisho nje ya wigo wa kaunti ulioidhinishwa.', 'open_required' => 'Hitilafu zilizo wazi pekee ndizo zinaweza kutatuliwa.'], 'audit' => ['resolved' => 'Hitilafu ya upatanisho imetatuliwa.']]];
