<?php

return [
    'publication_status' => 'Hali ya uchapishaji', 'county' => 'Kaunti', 'sector' => 'Sekta', 'tag' => 'Lebo', 'report_status' => 'Hali ya ripoti', 'search_moderation_reports' => 'Tafuta ripoti za usimamizi',
    'curated_repository' => 'Hazina iliyohaririwa', 'no_knowledge_resources_found' => 'Hakuna rasilimali za maarifa zilizopatikana', 'no_matching_innovations' => 'Hakuna ubunifu unaolingana', 'no_matching_community_reports' => 'Hakuna ripoti za jamii zinazolingana',
    'reported_contribution' => 'Mchango ulioripotiwa', 'report' => 'Ripoti', 'reporter' => 'Mtoa ripoti', 'sla_due' => 'Tarehe ya SLA', 'decision' => 'Uamuzi', 'decision_rationale' => 'Sababu za uamuzi', 'contribution_action' => 'Hatua kuhusu mchango', 'resolution_and_safeguards' => 'Utatuzi na hatua za ulinzi',
    'contribute_knowledge_resource' => 'Changia rasilimali ya maarifa', 'resource_title' => 'Kichwa cha rasilimali', 'resource_type' => 'Aina ya rasilimali', 'sector' => 'Sekta', 'repository_document' => 'Hati ya hazina', 'linked_e_learning_course' => 'Kozi ya mtandaoni iliyounganishwa',
    'source_organization' => 'Shirika chanzo', 'external_source_url' => 'URL ya chanzo cha nje', 'language' => 'Lugha', 'tags_comma_separated' => 'Lebo (tenganisha kwa koma)', 'executive_summary' => 'Muhtasari wa kiutendaji', 'curated_content' => 'Maudhui yaliyohaririwa',
    'open_community_discussion' => 'Fungua mjadala wa jamii', 'discussion_title' => 'Kichwa cha mjadala', 'opening_prompt' => 'Swali la kuanzisha', 'linked_resource' => 'Rasilimali iliyounganishwa',
    'submit_devolution_innovation' => 'Wasilisha ubunifu wa ugatuzi', 'innovation_title' => 'Kichwa cha ubunifu', 'maturity_level' => 'Kiwango cha ukomavu', 'evidence_or_prototype_url' => 'URL ya ushahidi au mfano',
    'problem_statement' => 'Maelezo ya tatizo', 'proposed_solution' => 'Suluhisho lililopendekezwa', 'expected_impact' => 'Athari inayotarajiwa', 'support_requested' => 'Usaidizi unaoombwa',
    'discussion_notifications' => 'Arifa za mjadala', 'report_category' => 'Kategoria ya ripoti', 'potential_severity' => 'Ukali unaowezekana', 'what_should_the_moderation_team_review' => 'Timu ya usimamizi ipitie nini?',
    'moderation_rationale' => 'Sababu za usimamizi', 'contribution' => 'Mchango', 'problem' => 'Tatizo', 'incubation_support' => 'Usaidizi wa kukuza ubunifu', 'recommendation' => 'Pendekezo', 'independent_assessment_rationale' => 'Sababu za tathmini huru',
    'amount' => 'Kiasi', 'currency' => 'Sarafu', 'funding_type' => 'Aina ya ufadhili', 'decision_reference' => 'Rejea ya uamuzi', 'funding_rationale' => 'Sababu za ufadhili', 'accountable_owner' => 'Mmiliki mwenye uwajibikaji',
    'milestone_title' => 'Kichwa cha hatua muhimu', 'testable_hypothesis' => 'Dhana inayoweza kujaribiwa', 'success_metric' => 'Kipimo cha mafanikio', 'baseline' => 'Kiwango cha msingi', 'target' => 'Lengo', 'due_date' => 'Tarehe ya mwisho',
    'incubation_support_and_next_steps' => 'Usaidizi wa kukuza ubunifu na hatua zinazofuata', 'pilot_evidence_reference' => 'Rejea ya ushahidi wa majaribio', 'result_status' => 'Hali ya matokeo', 'actual_value' => 'Thamani halisi', 'outcome_summary' => 'Muhtasari wa matokeo',
    'clean_repository_evidence' => 'Ushahidi safi wa hazina', 'verification_decision' => 'Uamuzi wa uthibitishaji', 'independent_verification_rationale' => 'Sababu za uthibitishaji huru',
    'authorized_resources_count' => 'Nyenzo :count zilizoidhinishwa', 'no_resources_description' => 'Rekebisha vichujio au changia desturi, kifani, matokeo ya utafiti, zana au makala ya kwanza yenye ushahidi.', 'submit_solution_description' => 'Wasilisha suluhisho lililotengenezwa nchini ili lichunguzwe na kukuzwa.', 'no_reports_description' => 'Ripoti zilizo ndani ya wigo wako ulioidhinishwa zitaonekana hapa pamoja na SLA na hali ya uamuzi.', 'actions_for_record' => 'Vitendo vya :record',
    'create_resource_description' => 'Unda nyenzo yenye ushahidi na uiunganishe na ushahidi salama wa hazina au mafunzo mtandaoni.', 'new_resource' => 'Nyenzo mpya', 'create_discussion_description' => 'Itisha jumuiya ya utendaji inayosimamiwa kuhusu nyenzo au changamoto ya kaunti.', 'new_discussion' => 'Mjadala mpya', 'submit_innovation_description' => 'Sajili suluhisho kwa uchunguzi huru, ukuzaji, majaribio na upanuzi.', 'submit_innovation' => 'Wasilisha ubunifu',
    'discussion_notifications_description' => 'Chagua kama michango mipya ya :title ionekane katika kituo chako cha arifa.', 'actions_for_contribution' => 'Vitendo vya mchango wa :author', 'contribute_to_discussion' => 'Changia katika :title', 'add_contribution_description' => 'Ongeza mchango unaoweza kufuatiliwa katika jumuiya hii ya utendaji.', 'add_contribution' => 'Ongeza mchango', 'score_out_of_one_hundred' => ':label (0–100)',
];
