<?php

return [
    'lineage_proposed' => 'Uamuzi wa nasaba ya marejeleo umependekezwa kwa ukaguzi huru.',
    'lineage_reviewed' => 'Uamuzi wa ukaguzi wa nasaba ya marejeleo umerekodiwa.',
    'lineage_applied' => 'Uamuzi ulioidhinishwa wa nasaba ya marejeleo umetumika.',
    'import' => [
        'csv_or_xlsx' => 'Pakia faili chanzo la CSV au XLSX.', 'one_worksheet' => 'Chanzo cha XLSX lazima kiwe na laha moja tu.', 'formula_forbidden' => 'Fomula za lahajedwali haziruhusiwi (safu :row). Badilisha fomula kwa thamani zilizoidhinishwa.', 'xlsx_unreadable' => 'Chanzo cha XLSX hakikuweza kusomwa. Tumia kitabu kisichosimbwa kilichoundwa kutoka kiolezo kinachodhibitiwa.', 'invalid_archive' => 'Chanzo cha XLSX si jalada halali la kitabu.', 'too_many_entries' => 'Chanzo cha XLSX kina vipengele vingi mno vya jalada.', 'archive_uninspectable' => 'Jalada la chanzo cha XLSX halikuweza kukaguliwa.', 'external_content' => 'Viungo vya nje vya kitabu na maudhui tekelezi ya lahajedwali hayaruhusiwi.', 'expanded_limit' => 'Chanzo cha XLSX kinazidi kikomo cha uchakataji cha MB 50 baada ya kufunguliwa.', 'unsupported_value' => 'Chanzo cha XLSX kina thamani isiyotumika katika safu :row.', 'source_unavailable' => 'Faili chanzo lililopakiwa halipatikani tena.', 'checksum_failed' => 'Cheksamu ya faili chanzo haikuweza kuhesabiwa.', 'upload_checksum_failed' => 'Cheksamu ya chanzo kilichopakiwa haikuweza kuhesabiwa.', 'private_store_failed' => 'Faili chanzo halikuweza kuhifadhiwa kwa faragha.', 'header_unreadable' => 'Kichwa cha chanzo hakikuweza kusomwa.', 'required_columns' => 'Tumia safu zinazohitajika kwa mpangilio huu kamili: :columns.', 'legacy_acpa_columns' => 'Tumia safu za ACPA ya zamani kwa mpangilio huu kamili: :columns.', 'migration_row_limit' => 'Kundi la uhamishaji linaweza kuwa na safu za data zisizozidi 5,000.', 'bulk_row_limit' => 'Kundi la uingizaji wa pamoja linaweza kuwa na safu za data zisizozidi 5,000.', 'no_rows' => 'Faili chanzo halina safu za data.', 'unsupported_dataset' => 'Seti ya data ya uingizaji wa pamoja iliyochaguliwa haitumiki.',
    ],
    'ui' => [
        'inventory_title' => 'Orodha ya rekodi za urithi zisizofungamanishwa',
        'inventory_description' => 'Rekodi bayana zisizo na nasaba ya toleo la marejeleo linalodhibitiwa. Orodha hii haihusishi kimya kimya katalogi ya sasa na rekodi za kihistoria.',
        'record_type' => 'Aina ya rekodi ya kusawazisha',
        'open' => 'wazi', 'pending' => 'inasubiri', 'applied' => 'imetumika',
        'register_title' => 'Rejesta ya maamuzi ya nasaba',
        'register_description' => 'Mapendekezo yenye hundi, maamuzi huru, viungo vya warithi na ushahidi wa utekelezaji wa mwisho.',
        'empty_title' => 'Hakuna maamuzi ya nasaba yaliyorekodiwa',
        'empty_description' => 'Pendekeza uamuzi unaodhibitiwa kwa rekodi ya urithi au isiyofungamanishwa.',
        'reconcile' => 'Sawazisha rekodi', 'actions_for' => 'Vitendo vya :reference', 'view_details' => 'Tazama maelezo', 'review_decision' => 'Kagua uamuzi', 'apply_disposition' => 'Tekeleza uamuzi',
        'proposal_title' => 'Pendekeza uamuzi wa nasaba', 'proposal_description' => 'Rekodi uamuzi wenye ushahidi kwa ukaguzi huru. Pendekezo hili halibadilishi rekodi iliyochaguliwa.',
        'record' => 'Rekodi ya urithi au isiyofungamanishwa', 'disposition_decision' => 'Uamuzi wa kushughulikia', 'retain_legacy' => 'Hifadhi bayana kama urithi', 'pin_release' => 'Fungamanisha toleo la katalogi lililothibitishwa', 'deprecate' => 'Ondoa katika matumizi ya baadaye', 'published_release' => 'Toleo la katalogi lililochapishwa', 'version' => 'Toleo :version', 'successor' => 'Rekodi mrithi (si lazima)', 'source_reference' => 'Rejeleo la chanzo au idhini', 'rationale' => 'Sababu yenye ushahidi', 'recording' => 'Inarekodi pendekezo…', 'submit_review' => 'Wasilisha kwa ukaguzi huru',
        'reference' => 'Rejeleo', 'created_at' => 'Imeundwa',
        'details_title' => 'Maelezo ya uamuzi wa nasaba', 'review_title' => 'Kagua uamuzi wa nasaba', 'apply_title' => 'Tekeleza uamuzi wa nasaba', 'checksum_bound' => ':reference · uamuzi wenye hundi', 'record_type_value' => 'Aina ya rekodi', 'decision' => 'Uamuzi', 'status' => 'Hali', 'catalogue' => 'Katalogi', 'explicitly_unpinned' => 'Haijafungamanishwa bayana', 'proposed_by' => 'Imependekezwa na', 'reviewed_by' => 'Imekaguliwa na', 'applied_by' => 'Imetekelezwa na', 'business_rationale' => 'Sababu ya biashara', 'controlled_successor' => 'Mrithi anayedhibitiwa', 'source_checksum' => 'SHA-256 ya rekodi chanzo', 'decision_checksum' => 'SHA-256 ya uamuzi', 'independent_notes' => 'Maelezo ya ukaguzi huru', 'approve' => 'Idhinisha', 'reject' => 'Kataa', 'record_independent_decision' => 'Rekodi uamuzi huru', 'final_application' => 'Utekelezaji wa mwisho unaodhibitiwa', 'final_application_description' => 'IDMIS itakagua tena rekodi chanzo, uamuzi na hundi za katalogi. Mpendekezaji na mkaguzi hawawezi kutekeleza hatua hii.', 'not_pinned' => 'Haijafungamanishwa',
        'legacy_export' => 'Hamisha rejista', 'legacy_empty_title' => 'Hakuna rekodi za ACPA zilizoundwa upya', 'legacy_empty_description' => 'Tekeleza kundi la uundaji upya wa ACPA ya zamani lililoidhinishwa kwa uhuru ili kujaza rejista hii isiyobadilika.', 'legacy_actions' => 'Vitendo vya :assessment', 'legacy_view' => 'Tazama uundaji upya', 'legacy_sheet_title' => 'Uundaji upya wa ACPA ya zamani', 'legacy_sheet_description' => 'Vigezo, ushahidi, matokeo, uteuzi wa watathmini na rufaa zilizopatanishwa na chanzo na zisizobadilika.', 'assessment' => 'Tathmini', 'period' => 'Kipindi', 'overall_score' => 'Alama ya jumla', 'imported_by' => 'Imeingizwa na', 'record_checksum' => 'SHA-256 ya rekodi', 'components' => 'Vipengele vilivyoundwa upya', 'component_count' => 'Rekodi :count za vipengele zisizobadilika', 'assessment_level' => 'Rekodi ya kiwango cha tathmini', 'score' => 'Alama', 'assessor_role' => 'Jukumu la mtathmini', 'assessor' => 'Mtathmini', 'evidence_file' => 'Faili la ushahidi', 'description' => 'Maelezo', 'file_checksum' => 'SHA-256 ya faili', 'unknown_type' => 'Aina isiyojulikana',
        'legacy_register_title' => 'Rejista ya uundaji upya wa ACPA ya zamani', 'legacy_register_description' => 'Vichwa vya tathmini za kihistoria visivyobadilika vyenye vigezo, orodha za ushahidi, matokeo, uteuzi wa watathmini na rufaa zilizopatanishwa.', 'county' => 'Kaunti', 'criteria' => 'Vigezo', 'evidence' => 'Ushahidi', 'findings' => 'Matokeo', 'assessors' => 'Watathmini', 'appeals' => 'Rufaa', 'source' => 'Chanzo', 'imported_at' => 'Imeingizwa tarehe',
    ],
];
