<?php

return [
    'create_collaboration_plan' => 'Unda mpango wa ushirikiano', 'partner' => 'Mshirika', 'starts_on' => 'Inaanza tarehe', 'ends_on' => 'Inaisha tarehe', 'add_accountable_action' => 'Ongeza hatua yenye uwajibikaji', 'county' => 'Kaunti', 'accountable_owner' => 'Mmiliki mwenye uwajibikaji', 'accountable_organization' => 'Shirika lenye uwajibikaji', 'due_on' => 'Tarehe ya mwisho', 'upload_action_evidence' => 'Pakia ushahidi wa hatua', 'source_type' => 'Aina ya chanzo', 'submit_action_progress' => 'Wasilisha maendeleo ya hatua', 'verify_action_progress' => 'Thibitisha maendeleo ya hatua', 'decision' => 'Uamuzi',
    'request_agreement_change' => 'Omba mabadiliko ya makubaliano', 'change_type' => 'Aina ya mabadiliko', 'effective_date' => 'Tarehe ya kuanza kutumika', 'revised_end_date' => 'Tarehe ya mwisho iliyorekebishwa', 'upload_change_evidence' => 'Pakia ushahidi wa mabadiliko', 'decide_agreement_change' => 'Amua kuhusu mabadiliko ya makubaliano', 'upload_agreement_record' => 'Pakia rekodi ya makubaliano', 'review_agreement' => 'Pitia makubaliano', 'submit_agreement_for_approval' => 'Wasilisha makubaliano ili yaidhinishwe',
    'create_plan' => 'Unda mpango', 'create_plan_description' => 'Unda mpango wenye muda maalum kwa idhini huru.', 'transition_plan' => 'Mpango wa :transition', 'plan_transition_description' => 'Rekodi uamuzi unaoweza kuhusishwa wa mzunguko wa maisha wa mpango.', 'add_action' => 'Ongeza hatua', 'add_action_description' => 'Weka hatua ya kaunti inayopimika ndani ya kipindi kilichoidhinishwa.', 'upload_evidence' => 'Pakia ushahidi', 'upload_action_evidence_description' => 'Ambatisha rekodi ya utekelezaji iliyochanganuliwa au ya kidijitali.', 'submit_progress' => 'Wasilisha maendeleo', 'submit_progress_description' => 'Kukamilisha kunahitaji ushahidi safi na uthibitishaji huru.', 'verify' => 'Thibitisha', 'verify_progress_description' => 'Rekodi uamuzi huru wa uthibitishaji usiobadilika.',
    'preview_document' => 'Hakiki :title', 'request_change' => 'Omba mabadiliko', 'request_change_description' => 'Pendekeza marekebisho, uhuishaji, usitishaji au ukomeshaji bila kuandika upya makubaliano yaliyoidhinishwa.', 'upload_change_evidence_description' => 'Ambatisha hati iliyotiwa saini ya marekebisho, uhuishaji, usitishaji au ukomeshaji.', 'record_decision' => 'Rekodi uamuzi', 'change_decision_description' => 'Midhinishaji huru anakagua ushahidi safi na kurekodi uamuzi usiobadilika.', 'upload_record' => 'Pakia rekodi', 'upload_record_description' => 'Ongeza nakala iliyochanganuliwa au ya kidijitali iliyohifadhiwa kwa faragha. Faili zinafungwa kwa checksum na kuchanganuliwa kiusalama.', 'agreement_decision_description' => 'Idhinisha au kataa makubaliano haya yaliyowasilishwa kwa uhuru. Mwasilishaji hawezi kufanya uamuzi huu.', 'submit_for_approval' => 'Wasilisha ili kuidhinishwa', 'submit_for_approval_description' => 'Thibitisha kuwa rekodi ya hazina imekamilika. Uwasilishaji unazuia upakiaji zaidi na kutuma makubaliano kwa uamuzi huru.',
    'actions_for_record' => 'Vitendo vya :record', 'upload_reconciliation_evidence' => 'Pakia ushahidi wa upatanisho', 'upload_reconciliation_evidence_description' => 'Ongeza rekodi ya chanzo iliyochanganuliwa au ya kidijitali kwenye hazina inayosimamiwa.', 'reconcile_contribution' => 'Patanisha mchango', 'reconcile_contribution_description' => 'Uamuzi huru wa mtayarishaji-mhakiki kwa kutumia ushahidi safi ulioambatishwa.', 'download_document' => 'Pakua :title',
];
