<?php

return [
    'operational_control_alerts' => 'Tahadhari za udhibiti wa uendeshaji', 'operational_control_alerts_description' => 'Ufuatiliaji unaoweza kurudiwa kwa kuisha kwa makubaliano na upatanisho wa michango uliochelewa, wenye hitilafu au uliokataliwa.', 'no_operational_alerts' => 'Hakuna tahadhari za uendeshaji za washirika', 'no_operational_alerts_description' => 'Kifuatiliaji kilichoratibiwa hakijagundua kuisha kwa muda au hitilafu za upatanisho katika wigo wako wa kaunti.', 'alert' => 'Tahadhari', 'partner_county' => 'Mshirika / kaunti', 'status' => 'Hali', 'detected' => 'Iligunduliwa', 'alert_actions' => 'Vitendo vya :alert', 'resolve_operational_alert' => 'Tatua tahadhari ya uendeshaji', 'resolve_operational_alert_description' => 'Rekodi hatua ya marekebisho au uamuzi rasmi wa kukubali hatari; ushahidi wa chanzo haubadilishwi.', 'record_disposition' => 'Rekodi uamuzi', 'disposition' => 'Uamuzi', 'resolution_evidence' => 'Ushahidi wa utatuzi',
    'severity_critical' => 'Hatari sana', 'severity_warning' => 'Onyo', 'status_open' => 'Wazi', 'status_resolved' => 'Imetatuliwa', 'status_accepted_risk' => 'Hatari imekubaliwa', 'status_system_resolved' => 'Imetatuliwa na mfumo', 'alert_type_agreement_expired' => 'Makubaliano yameisha', 'alert_type_agreement_expiry_due' => 'Makubaliano yanakaribia kuisha', 'alert_type_contribution_reconciliation_overdue' => 'Upatanisho wa mchango umechelewa', 'alert_type_contribution_reconciliation_exception' => 'Hitilafu ya upatanisho wa mchango', 'alert_type_contribution_reconciliation_rejected' => 'Upatanisho wa mchango umekataliwa',
    'contribution_register' => 'Rejista ya upatanisho wa michango', 'contribution_register_description' => 'Ahadi zilizoripotiwa hupatanishwa kwa uhuru dhidi ya ushahidi safi wa DMS na kuhifadhiwa kama historia ya maamuzi iliyounganishwa na alama-tambulishi.', 'no_contributions' => 'Hakuna michango iliyosajiliwa', 'no_contributions_description' => 'Rekodi mchango wa mshirika ili kuanza ukusanyaji na upatanisho wa ushahidi.',
    'partner_project' => 'Mshirika / mradi', 'county' => 'Kaunti', 'reported' => 'Imeripotiwa', 'decision' => 'Uamuzi', 'actions' => 'Vitendo', 'of' => 'kati ya', 'view_record' => 'Tazama rekodi', 'verified_commitment' => 'Ahadi iliyothibitishwa', 'verified_disbursement' => 'Malipo yaliyothibitishwa', 'verified_in_kind' => 'Thamani ya bidhaa iliyothibitishwa', 'source_reference' => 'Rejea ya chanzo', 'review_note' => 'Maelezo ya ukaguzi',
    'contribution_chain' => 'mnyororo wa mchango, ushahidi na upatanisho.', 'reported_commitment' => 'Ahadi iliyoripotiwa', 'reported_disbursement' => 'Malipo yaliyoripotiwa', 'evidence' => 'Ushahidi', 'ellipsis' => '…', 'decision_history' => 'Historia ya maamuzi', 'no_reconciliation_decision' => 'Bado hakuna uamuzi wa upatanisho.',
    'collaboration_plans' => 'Mipango na hatua za ushirikiano', 'collaboration_plans_description' => 'Mipango iliyoidhinishwa ya washirika na kaunti yenye hatua zenye uwajibikaji, ushahidi na uthibitishaji huru wa maendeleo.', 'no_collaboration_plans' => 'Hakuna mipango ya ushirikiano', 'no_collaboration_plans_description' => 'Unda mpango unaodhibitiwa wa kuratibu hatua za utekelezaji za mshirika na kaunti.', 'no_accountable_actions' => 'Hakuna hatua zenye uwajibikaji zilizotolewa.',
    'due' => 'inatarajiwa', 'empty_value' => '—', 'reference' => 'Rejea', 'title_label' => 'Kichwa', 'objective' => 'Lengo', 'create_draft' => 'Unda rasimu', 'record' => 'Rekodi', 'code' => 'Msimbo', 'description_label' => 'Maelezo', 'assign_action' => 'Toa hatua', 'progress' => 'Maendeleo', 'narrative' => 'Maelezo ya maendeleo', 'submit_verification' => 'Wasilisha kwa uthibitishaji', 'verification_note' => 'Maelezo ya uthibitishaji',
    'open_parenthesis' => '(', 'close_parenthesis' => ')',
    'agreement_register' => 'Rejista ya uidhinishaji wa makubaliano', 'agreement_register_description' => 'Hati za maelewano na ushirikiano zenye nyaraka hupitia uwasilishaji wa rasimu hadi uidhinishaji huru wenye historia isiyobadilika.', 'no_agreements' => 'Hakuna makubaliano yaliyosajiliwa', 'no_agreements_description' => 'Sajili makubaliano ili kuanza mzunguko wa nyaraka na uidhinishaji.',
    'separator' => '·', 'label_separator' => ':', 'to' => 'hadi', 'repository_records' => 'Rekodi za hazina', 'no_repository_records' => 'Hakuna rekodi iliyochanganuliwa au ya kidijitali iliyopakiwa.', 'scan' => 'uchanganuzi', 'ocr' => 'OCR', 'preview' => 'Hakiki', 'download' => 'Pakua',
    'change_history' => 'Historia ya mabadiliko baada ya uidhinishaji', 'version_prefix' => 't', 'effective' => 'Inatumika', 'authorized_preview' => 'Hakiki iliyoidhinishwa ya nakala binafsi ya hazina.', 'revised_title' => 'Kichwa kilichorekebishwa', 'revised_summary' => 'Muhtasari uliorekebishwa', 'revised_value' => 'Thamani iliyorekebishwa', 'reason' => 'Sababu',
    'submit_governed_request' => 'Wasilisha ombi linalodhibitiwa', 'record_title' => 'Kichwa cha rekodi', 'category' => 'Aina', 'document' => 'Hati', 'upload_securely' => 'Pakia kwa usalama', 'decision_note' => 'Maelezo ya uamuzi', 'retain_decision' => 'Hifadhi uamuzi', 'agreement_file' => 'Faili ya makubaliano', 'uploading' => 'Inapakiwa', 'percent' => '%', 'decision_rationale' => 'Sababu za uamuzi', 'record_decision' => 'Rekodi uamuzi', 'confirm_submission' => 'Thibitisha uwasilishaji',
];
