<?php

return [
    'physical_progress' => 'Maendeleo ya kazi', 'approved_budget' => 'Bajeti iliyoidhinishwa', 'expenditure' => 'Matumizi', 'scope' => 'Wigo', 'delivery_scope' => 'Wigo wa utekelezaji', 'results_links' => 'Viungo vya matokeo', 'control_status' => 'Hali ya vidhibiti',
    'upload_project_record' => 'Pakia rekodi ya mradi', 'document_title' => 'Kichwa cha hati', 'record_purpose' => 'Madhumuni ya rekodi', 'record_category' => 'Kategoria ya rekodi',
    'add_milestone' => 'Ongeza hatua muhimu', 'ms_01' => 'MS-01', 'milestone_title' => 'Kichwa cha hatua muhimu', 'planned_start' => 'Mwanzo uliopangwa', 'planned_end' => 'Mwisho uliopangwa', 'weight' => 'Uzito %', 'dependencies' => 'Vitegemezi',
    'add_budget_line' => 'Ongeza kipengele cha bajeti', 'bl_01' => 'BL-01', 'category' => 'Kategoria', 'description_label' => 'Maelezo', 'approved_amount' => 'Kiasi kilichoidhinishwa', 'currency' => 'Sarafu',
    'register_risk' => 'Sajili hatari', 'rsk_01' => 'RSK-01', 'risk_description' => 'Maelezo ya hatari', 'probability_1_5' => 'Uwezekano 1–5', 'impact_1_5' => 'Athari 1–5', 'mitigation' => 'Hatua za kupunguza athari',
    'add_procurement' => 'Ongeza ununuzi', 'tender_reference' => 'Rejea ya zabuni', 'procurement_title' => 'Kichwa cha ununuzi', 'method' => 'Mbinu', 'estimated_value' => 'Thamani inayokadiriwa', 'planned_notice_date' => 'Tarehe iliyopangwa ya tangazo',
    'record_the_evidence_based_lifecycle_decision' => 'Rekodi uamuzi wa mzunguko wenye msingi wa ushahidi', 'verify_progress_update' => 'Thibitisha taarifa ya maendeleo', 'independent_verification_rationale' => 'Sababu za uthibitishaji huru',
    'milestones' => 'Hatua muhimu', 'budget_lines' => 'Vipengele vya bajeti', 'risks' => 'Hatari', 'procurements' => 'Ununuzi', 'progress_history' => 'Historia ya maendeleo',
    'capture_schedule_baseline' => 'Rekodi msingi wa ratiba', 'record_the_planning_evidence_and_authority_supporting_this_proposed_baseline' => 'Rekodi ushahidi wa upangaji na mamlaka inayounga mkono msingi huu uliopendekezwa.',
    'approved_baseline' => 'Msingi ulioidhinishwa', 'critical_path' => 'Njia muhimu', 'forecast_finish' => 'Mwisho unaotabiriwa', 'forecast_variance' => 'Tofauti ya utabiri',
    'record_the_independent_schedule_review_evidence_and_decision_rationale' => 'Rekodi ushahidi wa mapitio huru ya ratiba na sababu za uamuzi.',
    'register_project_resource' => 'Sajili rasilimali ya mradi', 'resource_code' => 'Msimbo wa rasilimali', 'resource_name' => 'Jina la rasilimali', 'resource_type' => 'Aina ya rasilimali', 'capacity_unit' => 'Kipimo cha uwezo', 'available_from' => 'Inapatikana kuanzia', 'available_to' => 'Inapatikana hadi',
    'allocate_project_resource' => 'Gawa rasilimali ya mradi', 'resource' => 'Rasilimali', 'milestone' => 'Hatua muhimu', 'allocation_start' => 'Mwanzo wa mgao', 'allocation_end' => 'Mwisho wa mgao',
    'planned_value' => 'Thamani iliyopangwa', 'earned_value' => 'Thamani iliyopatikana', 'actual_cost' => 'Gharama halisi', 'estimate_at_completion' => 'Makadirio wakati wa kukamilika', 'cost_performance_index' => 'Fahirisi ya utendaji wa gharama', 'schedule_performance_index' => 'Fahirisi ya utendaji wa ratiba', 'variance_at_completion' => 'Tofauti wakati wa kukamilika', 'to_complete_index' => 'Fahirisi ya kukamilisha',
    'title_label' => 'Kichwa', 'actual_start' => 'Mwanzo halisi', 'actual_end' => 'Mwisho halisi', 'progress' => 'Maendeleo (%)', 'funding_source' => 'Chanzo cha fedha', 'review_due' => 'Tarehe ya mapitio', 'contract_value' => 'Thamani ya mkataba', 'award_date' => 'Tarehe ya tuzo', 'supplier_name' => 'Jina la msambazaji', 'contract_reference' => 'Rejea ya mkataba',
    'preview_document' => 'Hakiki ya :title', 'review_reporting_date' => 'Kagua :date', 'verify_physical_progress_description' => 'Thibitisha kwa uhuru uwasilishaji wa maendeleo ya kimwili wa :progress%.', 'project_action_description' => 'Kamilisha hatua ya mradi inayosimamiwa na uirekodi kwenye mkondo wa ukaguzi.', 'capture_baseline' => 'Rekodi msingi', 'capture_baseline_description' => 'Funga mpango kamili wa sasa wa hatua muhimu kwa idhini huru na upimaji wa tofauti za baadaye.', 'review_schedule_baseline' => 'Kagua msingi wa ratiba v:version', 'review_pending_baseline' => 'Kagua msingi unaosubiri v:version', 'review_baseline_description' => 'Idhinisha kwa uhuru picha ya hatua muhimu iliyofungwa kwa checksum au ikatae kwa ushahidi.', 'add_resource' => 'Ongeza rasilimali', 'resource_currency_description' => 'Uwezo na viwango vinarekodiwa kwa :currency, iliyorithiwa kutoka mradi.', 'add_allocation' => 'Ongeza mgao', 'add_allocation_description' => 'Gawa uwezo sawa wa kila siku ndani ya vipindi vya rasilimali na hatua muhimu.', 'actions_for_record' => 'Vitendo vya :record',
];
