<?php

return [
    'stage_identity_lifecycle_change' => 'Andaa mabadiliko ya mzunguko wa utambulisho', 'lifecycle_event' => 'Tukio la mzunguko wa utambulisho', 'target_identity' => 'Utambulisho unaolengwa', 'authoritative_source_system' => 'Mfumo rasmi wa chanzo', 'unique_source_event_id' => 'Kitambulisho cha kipekee cha tukio la chanzo', 'source_evidence_reference' => 'Rejea ya ushahidi wa chanzo', 'effective_at' => 'Inaanza kutumika',
    'proposed_home_county' => 'Kaunti ya nyumbani iliyopendekezwa', 'proposed_assigned_counties' => 'Kaunti za kazi zilizopendekezwa', 'business_reason_and_source_reconciliation_note' => 'Sababu ya kiutendaji na dokezo la upatanisho wa chanzo', 'independent_decision' => 'Uamuzi huru', 'decision_rationale' => 'Sababu za uamuzi',
    'record_security_response' => 'Rekodi mwitikio wa usalama', 'assigned_incident_lead' => 'Kiongozi wa tukio aliyeteuliwa', 'response_playbook' => 'Mwongozo wa mwitikio', 'initial_severity' => 'Ukali wa awali', 'incident_or_exercise_title' => 'Kichwa cha tukio au zoezi', 'controlled_incident_summary' => 'Muhtasari wa tukio unaodhibitiwa', 'affected_services_comma_separated' => 'Huduma zilizoathiriwa (tenganisha kwa koma)', 'observed_or_simulated_business_impact' => 'Athari ya kiutendaji iliyoonekana au kuigwa', 'soc_service_desk_privacy_or_legal_reference' => 'Rejea ya SOC, dawati la huduma, faragha au sheria', 'exercise_objectives_comma_separated' => 'Malengo ya zoezi (tenganisha kwa koma)',
    'incident_lead' => 'Kiongozi wa tukio', 'summary' => 'Muhtasari', 'affected_services' => 'Huduma zilizoathiriwa', 'business_impact' => 'Athari ya kiutendaji', 'acknowledgement_target' => 'Lengo la kuthibitisha kupokea', 'containment_target' => 'Lengo la kudhibiti', 'external_reference' => 'Rejea ya nje', 'exercise_outcome' => 'Matokeo ya zoezi', 'root_cause' => 'Chanzo kikuu', 'corrective_actions' => 'Hatua za kurekebisha',
    'controlled_evidence_reference' => 'Rejea ya ushahidi unaodhibitiwa', 'verified_root_cause' => 'Chanzo kikuu kilichothibitishwa', 'completed_and_tracked_corrective_actions' => 'Hatua za kurekebisha zilizokamilishwa na kufuatiliwa', 'lessons_and_playbook_improvements' => 'Mafunzo na maboresho ya mwongozo', 'next_exercise_due' => 'Tarehe ya zoezi linalofuata',
    'record_title' => 'Kichwa cha rekodi', 'records_category' => 'Kategoria ya rekodi', 'source_type' => 'Aina ya chanzo', 'evidence_purpose' => 'Madhumuni ya ushahidi', 'composer_components' => 'Vipengele vya Composer', 'javascript_components' => 'Vipengele vya JavaScript', 'npm_vulnerabilities' => 'Udhaifu wa NPM', 'composer_lock_sha256' => 'SHA-256 ya kufuli ya Composer', 'artifact_sha256' => 'SHA-256 ya zao', 'evidence_sha256' => 'SHA-256 ya ushahidi',
    'request_temporary_access' => 'Omba ufikiaji wa muda', 'beneficiary_with_strong_authentication' => 'Mnufaika mwenye uthibitishaji thabiti', 'access_type' => 'Aina ya ufikiaji', 'geographic_scope' => 'Wigo wa kijiografia', 'least_privilege_permissions' => 'Ruhusa za kiwango cha chini kinachohitajika', 'counties_in_scope' => 'Kaunti ndani ya wigo', 'access_starts' => 'Ufikiaji unaanza', 'access_expires' => 'Ufikiaji unaisha', 'security_incident_reference' => 'Rejea ya tukio la usalama', 'business_justification_and_expected_outcome' => 'Uhalali wa kiutendaji na matokeo yanayotarajiwa', 'compensating_controls_and_monitoring' => 'Vidhibiti mbadala na ufuatiliaji',
    'independent_evidence_based_rationale' => 'Sababu huru zenye msingi wa ushahidi', 'immediate_revocation_reason' => 'Sababu ya kufuta ufikiaji mara moja', 'post_use_outcome' => 'Matokeo baada ya matumizi', 'audit_findings_and_follow_up' => 'Matokeo ya ukaguzi na ufuatiliaji',
    'review_decision' => 'Uamuzi wa mapitio', 'treatment_status' => 'Hali ya kushughulikia hatari', 'residual_likelihood_1_5' => 'Uwezekano uliobaki (1–5)', 'residual_impact_1_5' => 'Athari iliyobaki (1–5)', 'risk_acceptance_reference' => 'Rejea ya kukubali hatari', 'evidence_references_comma_separated' => 'Marejeo ya ushahidi (tenganisha kwa koma)', 'independent_findings' => 'Matokeo huru',
    'certification_decision' => 'Uamuzi wa uthibitishaji', 'evidence_based_rationale' => 'Sababu zenye msingi wa ushahidi', 'required_remediation' => 'Marekebisho yanayohitajika', 'remediation_due_date' => 'Tarehe ya mwisho ya marekebisho',
    'register_threat_scenario' => 'Sajili hali ya tishio', 'threat_reference' => 'Rejea ya tishio', 'threat_title' => 'Kichwa cha tishio', 'threat_category' => 'Kategoria ya tishio', 'risk_owner' => 'Mmiliki wa hatari', 'affected_asset_or_service' => 'Rasilimali au huduma iliyoathiriwa', 'threat_actor' => 'Mhusika wa tishio', 'likelihood_1_5' => 'Uwezekano (1–5)', 'impact_1_5' => 'Athari (1–5)', 'review_due_date' => 'Tarehe ya mwisho ya mapitio', 'abuse_or_failure_scenario' => 'Hali ya matumizi mabaya au kushindwa', 'entry_points_comma_separated' => 'Njia za kuingia (tenganisha kwa koma)', 'existing_controls_comma_separated' => 'Vidhibiti vilivyopo (tenganisha kwa koma)', 'treatment_plan_and_accountable_outcome' => 'Mpango wa kushughulikia na matokeo yenye uwajibikaji',
    'launch_access_certification' => 'Anzisha uthibitishaji wa ufikiaji', 'campaign_reference' => 'Rejea ya kampeni', 'campaign_name' => 'Jina la kampeni', 'independent_reviewer' => 'Mhakiki huru', 'roles_in_scope' => 'Majukumu ndani ya wigo', 'review_period_from' => 'Kipindi cha mapitio kuanzia', 'review_period_to' => 'Kipindi cha mapitio hadi', 'certification_due' => 'Tarehe ya mwisho ya uthibitishaji', 'scope_criteria_and_exclusions' => 'Wigo, vigezo na vizuizi',
    'identity_lifecycle_description' => 'Rekodi tukio la chanzo cha HR au IAM ambalo tayari limethibitishwa. Mthibitishaji tofauti wa ufikiaji lazima aliamue kabla ya ufikiaji wa IDMIS kubadilika.', 'identity_lifecycle' => 'Mzunguko wa utambulisho', 'actions_for_record' => 'Vitendo vya :record', 'security_response_description' => 'Unda tukio halisi au zoezi lililotambulishwa wazi. Ukali huhifadhi malengo ya uthibitisho wa kupokea na udhibiti.', 'security_response' => 'Mwitikio wa usalama', 'transition_actions_outcome' => 'Vitendo na matokeo ya :transition', 'actions_for_supply_chain_scan' => 'Vitendo vya uchanganuzi wa msururu wa ugavi :id', 'sha256_label' => 'SHA-256 ya :file',
    'temporary_access_description' => 'Omba ruhusa ya muda yenye upendeleo mdogo kwa idhini huru. Ruhusa za dharura zina kikomo cha saa nne na zinahitaji ukaguzi baada ya matumizi.', 'temporary_access' => 'Ufikiaji wa muda', 'view_record' => 'Tazama :record', 'threat_description' => 'Rekodi mali iliyoathiriwa, kategoria ya STRIDE, njia za kuingia, hatari asilia na matibabu kabla ya ukaguzi huru.', 'threat' => 'Tishio', 'access_review_description' => 'Unda picha zisizobadilika za ufikiaji kwa majukumu yaliyochaguliwa ya programu na uteue mkaguzi huru.', 'access_review' => 'Ukaguzi wa ufikiaji',
];
