<?php

return [
    'title' => 'Mipangilio ya wasifu', 'profile_photo' => 'Picha ya wasifu', 'profile_photo_description' => 'Pakia, panga na punguza picha inayoonyeshwa kwenye kichwa cha akaunti yako.', 'account_status' => 'Hali ya akaunti', 'account_status_description' => 'Utambulisho wako unaodhibitiwa na hali ya uthibitishaji.', 'role' => 'Jukumu', 'email_verification' => 'Uthibitishaji wa barua pepe', 'verified' => 'Imethibitishwa', 'pending_verification' => 'Inasubiri uthibitishaji', 'account_created' => 'Akaunti iliundwa', 'not_recorded' => 'Haijarekodiwa',
    'personal_information' => 'Taarifa binafsi', 'personal_information_description' => 'Weka jina na anwani ya barua pepe ya akaunti yako zikiwa sahihi.', 'edit' => 'Hariri', 'edit_personal_information' => 'Hariri taarifa binafsi', 'email_change_notice' => 'Kubadilisha barua pepe kunaweza kuhitaji uthibitishaji tena.', 'full_name' => 'Jina kamili', 'email_address' => 'Anwani ya barua pepe', 'save_changes' => 'Hifadhi mabadiliko', 'email_unverified' => 'Anwani yako ya barua pepe haijathibitishwa.', 'resend_verification' => 'Tuma tena barua pepe ya uthibitishaji', 'verification_sent' => 'Kiungo kipya cha uthibitishaji kimetumwa.',
    'access_scope' => 'Wigo wa ufikiaji', 'access_scope_description' => 'Umetolewa na msimamizi aliyeidhinishwa.', 'home_county' => 'Kaunti ya nyumbani', 'national_portfolio' => 'Kitaifa / jalada', 'assigned_counties' => 'Kaunti ulizopewa', 'none' => 'Hakuna', 'account_controls' => 'Vidhibiti vya akaunti', 'account_controls_description' => 'Endelea kwenye vidhibiti kamili vya usalama, eneo la kazi na mwonekano wa akaunti hii.', 'password_mfa_passkeys' => 'Nenosiri, MFA na funguo za kuingia', 'appearance_theme' => 'Mwonekano na mandhari',
    'account_lifecycle' => 'Mzunguko wa maisha ya akaunti', 'account_lifecycle_description' => 'Sitisha ufikiaji kabisa na uondoe picha yako binafsi ya wasifu.', 'delete_account' => 'Futa akaunti', 'delete_account_warning' => 'Hatua hii itakuondoa kwenye mfumo na kuondoa ufikiaji. Haiwezi kutenduliwa bila msimamizi aliyeidhinishwa.', 'confirm_account_deletion' => 'Thibitisha kufutwa kwa akaunti', 'confirm_account_deletion_description' => 'Baada ya akaunti yako kufutwa, rasilimali na ufikiaji wake hautapatikana. Weka nenosiri lako ili kuthibitisha.', 'current_password' => 'Nenosiri la sasa', 'cancel' => 'Ghairi', 'deleting_account' => 'Akaunti inafutwa…',
    'photo_type_error' => 'Chagua picha ya JPEG, PNG au WebP.', 'photo_size_error' => 'Chagua picha ndogo kuliko MB 10.', 'photo_dimensions_error' => 'Chagua picha ya angalau pikseli 256 kwa 256.', 'photo_open_error' => 'Picha iliyochaguliwa haikuweza kufunguliwa.', 'photo_crop_error' => 'Picha iliyopunguzwa haikuweza kutayarishwa.', 'updated' => 'Ilisasishwa', 'no_photo' => 'Hakuna picha ya wasifu iliyopakiwa', 'replace_crop' => 'Badilisha na upunguze', 'upload_crop' => 'Pakia na upunguze', 'remove' => 'Ondoa', 'choose_photo' => 'Chagua picha ya wasifu', 'crop_photo' => 'Punguza picha ya wasifu', 'crop_photo_description' => 'Rekebisha ukubwa na nafasi. Picha itakayohifadhiwa italingana kabisa na hakikisho la mraba.', 'crop_preview' => 'Hakikisho la picha ya wasifu iliyopunguzwa', 'zoom' => 'Ukubwa', 'separator' => '·', 'multiply' => '×', 'photo_zoom' => 'Ukubwa wa picha', 'horizontal_position' => 'Nafasi ya mlalo', 'horizontal_photo_position' => 'Nafasi ya mlalo ya picha', 'vertical_position' => 'Nafasi ya wima', 'vertical_photo_position' => 'Nafasi ya wima ya picha', 'keyboard_adjustment' => 'Tumia vitufe vya mishale kwenye kila kidhibiti kwa marekebisho sahihi ya kibodi.', 'uploading' => 'Inapakia', 'choose_another' => 'Chagua nyingine', 'save_cropped_photo' => 'Hifadhi picha iliyopunguzwa',
    'appearance_settings' => 'Mipangilio ya mwonekano', 'appearance_settings_description' => 'Sasisha mipangilio ya mwonekano wa akaunti yako',
];
