<?php

return [
    'faqs_title' => 'Maswali yanayoulizwa mara kwa mara', 'faqs_meta' => 'Majibu kuhusu ufikiaji, akaunti, taarifa, usalama na msaada wa IDMIS.', 'guidance' => 'Mwongozo wa IDMIS', 'faqs_intro' => 'Pata majibu ya haraka kuhusu ufikiaji wa mfumo, watumiaji walioidhinishwa, usimamizi wa taarifa na msaada.',
    'questions' => [
        ['question' => 'IDMIS ni nini?', 'answer' => 'Mfumo Jumuishi wa Taarifa za Usimamizi wa Ugatuzi ni jukwaa salama la kuratibu programu, kufuatilia matokeo, kusimamia ushahidi, kushiriki maarifa na kuimarisha uwajibikaji katika serikali ya kitaifa na kaunti.'],
        ['question' => 'Nani anaweza kufikia mfumo?', 'answer' => 'Ufikiaji ni wa wafanyakazi walioidhinishwa wa kitaifa, kaunti, uthibitishaji huru, programu na msaada. Ruhusa hutegemea shirika na majukumu uliyopangiwa.'],
        ['question' => 'Ninapataje akaunti?', 'answer' => 'Akaunti huundwa au kutolewa na wasimamizi walioidhinishwa wa IDMIS. Hakuna usajili wa umma. Wasiliana na msimamizi wa kaunti au programu ikiwa kazi zako zinahitaji ufikiaji.'],
        ['question' => 'Nifanye nini nisipoweza kuingia?', 'answer' => 'Thibitisha kuwa unatumia barua pepe rasmi ya akaunti yako. Tumia uwekaji upya wa nenosiri inapohitajika. Tatizo likiendelea, wasiliana na msimamizi wako au tumia ukurasa wa Msaada.'],
        ['question' => 'IDMIS itasimamia taarifa gani?', 'answer' => 'IDMIS inasimamia taarifa za programu na utendaji, ushahidi wa tathmini, nyaraka za ripoti, maamuzi na rekodi za uratibu zilizoidhinishwa. Ufikiaji hudhibitiwa kwa jukumu, shirika, upeo wa kaunti na madhumuni.'],
        ['question' => 'Mtiririko wa tathmini ya ACPA hufanyaje kazi?', 'answer' => 'Watumiaji wa kaunti walioidhinishwa huandaa majibu ya vigezo na ushahidi wa lazima. Wakadiriaji waliopangiwa na majukumu ya uthibitishaji huru hukagua kifurushi, kurekodi matokeo na kukipitisha katika maamuzi na rufaa zinazodhibitiwa. Alama zilizochapishwa hutokana tu na vigezo kamili vilivyothibitishwa na rekodi za matokeo zisizobadilika.'],
        ['question' => 'Tathmini za awali za ACPA zinaweza kupakiwa?', 'answer' => 'Ndiyo. Maafisa wa uhamishaji walioidhinishwa wanaweza kuandaa kifurushi cha kihistoria cha CSV au XLSX chenye tathmini, matokeo ya vigezo, orodha ya ushahidi, matokeo, wakadiriaji na rufaa. Ukaguzi huru na mtendaji tofauti wa mwisho vinahitajika kabla kifurushi kuwa data ya kihistoria ya IDMIS.'],
        ['question' => 'Ushahidi uliochanganuliwa na faili za kidijitali vinaweza kupakiwa?', 'answer' => 'Ndiyo. Ushahidi unaweza kuwa nakala iliyochanganuliwa au faili lililozaliwa kidijitali. Upakiaji huhifadhiwa kwa faragha, hukaguliwa programu hasidi, huthibitishwa checksum, hupewa toleo na kuunganishwa na kaunti, mzunguko, kigezo au rekodi iliyoidhinishwa kabla ya kutumika katika uamuzi.'],
        ['question' => 'Ninaweza kufanya nini kwenye Kidhibiti Faili?', 'answer' => 'Watumiaji walioidhinishwa wanaweza kutafuta folda na rekodi, kutumia mwonekano wa gridi au orodha, kuhakiki nyaraka zinazokubalika, kukagua chanzo na matoleo, kupakia faili na kutekeleza uhamishaji wa pamoja unaoruhusiwa. Zuio la kisheria, upeo wa kaunti, uhifadhi na ruhusa za rekodi huendelea kutumika.'],
        ['question' => 'Vichujio vya uchambuzi na uchimbaji wa kina hufanyaje kazi?', 'answer' => 'Vichujio vya mzunguko, kaunti na tarehe huweka upeo wa data iliyoidhinishwa na hubebwa kwenye uchimbaji unaokubalika. Watumiaji wenye ruhusa wanaweza kuhifadhi mionekano ya uchambuzi yenye majina, kulinganisha chati na mienendo, na kuhamisha ushahidi wa CSV, XLSX, JSON au PDF kutoka upeo huo huo.'],
        ['question' => 'IDMIS ina kaunti ndogo na wadi?', 'answer' => 'Ndiyo. Ngazi ya kiutawala inayodhibitiwa ina kaunti 47 za Kenya, vitengo vyake vya kaunti ndogo au maeneo bunge na wadi. Vitengo hivi hutumika kwa uchujaji na data rejea; mipaka ya ramani ni vielelezo na si ushahidi wa kadastri au kisheria.'],
        ['question' => 'Ni lugha zipi zinazotumika?', 'answer' => 'Kiolesura kinatumia Kiingereza, Kiswahili na Kifaransa. Tumia kichaguzi cha lugha kubadilisha; watumiaji walioingia wanaweza kuhifadhi lugha chaguo-msingi. Majina rasmi, misimbo, checksum na marejeo ya vyanzo hayabadilishwi.'],
        ['question' => 'Vitendo vya pamoja na uhamishaji vinadhibitiwa?', 'answer' => 'Ndiyo. Seva hukagua tena ruhusa, upeo wa kaunti, hali ya rekodi na chaguo lote kabla ya kitendo cha pamoja au uhamishaji. Mtumiaji hawezi kupanua ufikiaji kwa kubadilisha vichujio, URL, vitambulisho vya ombi au muundo wa faili.'],
        ['question' => 'Watumiaji wa kaunti wanaweza kuona nyaraka zilizozuiliwa za kaunti nyingine?', 'answer' => 'Si kwa chaguo-msingi. Nyaraka zilizozuiliwa hubaki ndani ya kaunti na mtiririko wa kazi ulioidhinishwa; ufuatiliaji wa kitaifa na uchapishaji huhitaji ruhusa wazi.'],
        ['question' => 'IDMIS itafanya kazi kwenye intaneti hafifu au inayokatika?', 'answer' => 'Huduma imeundwa kutumia data kwa uangalifu, kuonyesha maendeleo ya upakiaji, kurudia shughuli kwa usalama na kutoa vifurushi vya mafunzo nje ya mtandao vinavyosimamiwa.'],
        ['question' => 'Ninaweza kujifunza zaidi wapi kuhusu ugatuzi?', 'answer' => 'Tovuti ya Idara ya Serikali ya Ugatuzi huchapisha sera, mipango, mwongozo, habari na rasilimali kuhusu mfumo wa ugatuzi wa Kenya.'],
    ],
    'still_need_help' => 'Bado unahitaji msaada?', 'support_or_sign_in' => 'Angalia njia za msaada au rudi kuingia.', 'help_and_support' => 'Msaada', 'sign_in' => 'Ingia', 'general_faqs' => 'Soma maswali ya jumla kuhusu ugatuzi',
];
