<?php

return [
    'eyebrow' => 'Safari rasmi inayodhibitiwa', 'title' => 'Idhini ya safari', 'description' => 'Pitisha safari rasmi kwenye ukaguzi wa usimamizi, uthibitisho huru wa fedha, ufuatiliaji wa SLA na historia ya maamuzi isiyobadilika.',
    'clearance_status' => 'Hali ya idhini', 'county' => 'Kaunti', 'sector' => 'Sekta', 'requests' => 'Maombi', 'approved' => 'Yameidhinishwa', 'rejected' => 'Yamekataliwa', 'average_decision_time' => 'Wastani wa muda wa uamuzi', 'hours' => 'saa',
    'cost_by_currency' => 'Gharama kwa sarafu', 'cost_by_currency_description' => 'Makadirio ya safari huwekwa kwa kila sarafu ili kuzuia ubadilishaji usio sahihi.', 'currency' => 'Sarafu', 'total_estimate' => 'Jumla ya makadirio', 'average' => 'Wastani', 'frequent_destinations' => 'Maeneo yanayotembelewa mara nyingi', 'frequent_destinations_description' => 'Maeneo ya juu kwa idadi ya maombi ndani ya jalada lililoidhinishwa.', 'destination' => 'Mahali pa kwenda', 'estimated_cost' => 'Gharama iliyokadiriwa', 'decision_pipeline' => 'Mtiririko wa maamuzi', 'decision_pipeline_description' => 'Mgawanyo wa sasa wa maombi katika hali za idhini.', 'status' => 'Hali',
    'clearance_register' => 'Sajili ya idhini', 'authorized_portfolio_count' => 'maombi katika jalada lako lililoidhinishwa', 'export' => 'Hamisha', 'reference' => 'Rejea', 'requester' => 'Mwombaji', 'travel_dates' => 'Tarehe za safari', 'estimate' => 'Makadirio', 'reference_release' => 'Toleo la rejea', 'empty_title' => 'Hakuna maombi ya safari yanayolingana', 'empty_description' => 'Rekebisha tarehe, utafutaji, hali, kaunti au sekta. Watumishi walioidhinishwa wanaweza kuunda ombi la kwanza hapa.', 'no_data_prefix' => 'Hakuna data ya', 'data' => '', 'analytics_empty_description' => 'Maombi yanayolingana yataonyesha uchambuzi huu.',
    'new_request' => 'Ombi jipya la safari', 'new_request_description' => 'Weka madhumuni, ufadhili, rejea ya HRIS na ratiba kamili kabla ya kuwasilisha.', 'organization' => 'Shirika', 'travel_type' => 'Aina ya safari', 'domestic' => 'Ndani ya nchi', 'international' => 'Kimataifa', 'purpose' => 'Madhumuni', 'departure_date' => 'Tarehe ya kuondoka', 'return_date' => 'Tarehe ya kurudi', 'total_estimated_cost' => 'Jumla ya gharama iliyokadiriwa', 'funding_source' => 'Chanzo cha fedha', 'cost_centre' => 'Kituo cha gharama', 'hris_employee_reference' => 'Rejea ya mfanyakazi ya HRIS', 'priority' => 'Kipaumbele', 'normal' => 'Kawaida', 'urgent' => 'Dharura', 'business_justification' => 'Sababu ya kikazi',
    'itinerary' => 'Ratiba ya safari', 'itinerary_description' => 'Vipande vyote lazima viwe ndani ya tarehe za ombi la safari.', 'add_segment' => 'Ongeza kipande', 'segment' => 'Kipande', 'remove' => 'Ondoa', 'origin' => 'Mahali pa kuanzia', 'departs_at' => 'Inaondoka', 'arrives_at' => 'Inawasili', 'transport_mode' => 'Njia ya usafiri', 'carrier' => 'Mtoa huduma', 'segment_estimated_cost' => 'Makadirio ya gharama ya kipande', 'save_draft_request' => 'Hifadhi rasimu ya ombi',
    'submit_manager_review' => 'Wasilisha kwa ukaguzi wa meneja', 'cancel_request' => 'Ghairi ombi', 'approve_finance_review' => 'Idhinisha kwa ukaguzi wa fedha', 'reject_manager_review' => 'Kataa kwenye ukaguzi wa meneja', 'confirm_finance_clearance' => 'Thibitisha idhini ya fedha', 'reject_finance_clearance' => 'Kataa idhini ya fedha', 'actions_for' => 'Vitendo vya', 'view_complete_request' => 'Tazama ombi kamili', 'complete_record_description' => 'Rekodi kamili ya safari, ratiba, miunganisho na maamuzi.', 'record_decision_for' => 'Rekodi uamuzi wenye sababu kwa', 'decision_rationale' => 'Sababu ya uamuzi', 'approved_cost' => 'Gharama iliyoidhinishwa', 'finance_commitment_reference' => 'Rejea ya ahadi ya fedha',
    'national' => 'Kitaifa', 'hris_reference' => 'Rejea ya HRIS', 'not_linked' => 'Haijaunganishwa', 'reference_checksum' => 'Alama-hundi ya rejea', 'finance_reference' => 'Rejea ya fedha', 'pending' => 'Inasubiri', 'supporting_documents' => 'Nyaraka za kuunga mkono', 'separator' => '·', 'file' => 'Faili', 'preview' => 'Hakiki', 'download' => 'Pakua', 'no_supporting_documents' => 'Hakuna nyaraka za kuunga mkono zilizopakiwa.', 'upload_supporting_record' => 'Pakia rekodi ya kuunga mkono', 'document_title' => 'Kichwa cha waraka', 'record_category' => 'Kategoria ya rekodi', 'source_type' => 'Aina ya chanzo', 'born_digital' => 'Faili asilia ya kidijitali', 'scanned_copy' => 'Nakala iliyochanganuliwa', 'document' => 'Waraka', 'uploading' => 'Inapakia',
    'route_arrow' => '→', 'range_separator' => '–', 'carrier_pending' => 'Mtoa huduma anasubiri', 'decision_history' => 'Historia ya maamuzi', 'no_decisions' => 'Hakuna maamuzi ya idhini yaliyorekodiwa bado.', 'integration_status' => 'Hali ya muunganisho', 'integration_description' => 'Vitambulisho vya HRIS na fedha hubaki kuonekana kwa upatanisho na ushughulikiaji wa hitilafu.',
    'value_draft' => 'Rasimu', 'value_manager_review' => 'Ukaguzi wa meneja', 'value_finance_review' => 'Ukaguzi wa fedha', 'value_approved' => 'Imeidhinishwa', 'value_rejected' => 'Imekataliwa', 'value_cancelled' => 'Imeghairiwa', 'value_submit' => 'Wasilisha kwa ukaguzi wa meneja', 'value_cancel' => 'Ghairi ombi', 'value_manager_approve' => 'Idhinisha kwa ukaguzi wa fedha', 'value_manager_reject' => 'Kataa kwenye ukaguzi wa meneja', 'value_finance_clear' => 'Thibitisha idhini ya fedha', 'value_finance_reject' => 'Kataa idhini ya fedha', 'value_air' => 'Ndege', 'value_road' => 'Barabara', 'value_rail' => 'Reli', 'value_water' => 'Maji', 'value_other' => 'Nyingine', 'value_digital' => 'Kidijitali', 'value_scanned' => 'Imechanganuliwa', 'value_clean' => 'Safi', 'value_pending_scan' => 'Inasubiri uchanganuzi', 'value_pending' => 'Inasubiri', 'value_synced' => 'Imesawazishwa', 'value_exception' => 'Hitilafu',
    'legacy_unpinned' => 'Rekodi ya zamani isiyounganishwa',
    'outcomes' => ['created' => 'Ombi la safari :reference limeundwa.', 'lifecycle_updated' => 'Mzunguko wa idhini ya safari umesasishwa.'],
    'errors' => ['itineraries_array' => 'Ratiba za safari lazima ziwe orodha.', 'itinerary_object' => 'Kila ratiba ya safari lazima iwe kitu cha data.'],
    'notifications' => [
        'updated_title' => 'Idhini ya safari imesasishwa', 'overdue_title' => 'Idhini ya safari imechelewa', 'due_soon_title' => 'Idhini ya safari inakaribia muda wake',
        'reminder_message' => ':reference: :purpose', 'status_manager_review' => ':reference sasa inakaguliwa na meneja.', 'status_finance_review' => ':reference sasa inakaguliwa na fedha.', 'status_approved' => ':reference sasa imeidhinishwa.', 'status_rejected' => ':reference sasa imekataliwa.', 'status_cancelled' => ':reference sasa imeghairiwa.',
    ],
    'audit' => ['created' => 'Ombi la safari :reference limeundwa.', 'transitioned' => 'Ombi la safari :reference limehamishwa hadi :status.', 'overdue_escalated' => 'Uamuzi wa idhini ya safari uliochelewa umepelekwa ngazi ya juu.', 'reminder_sent' => 'Kikumbusho cha tarehe ya mwisho ya idhini ya safari kimetumwa.'],
    'command' => ['reminders_sent' => 'Vikumbusho :count vya idhini ya safari vimetumwa.'],
    'no_data_title' => 'Hakuna data ya :title', 'actions_for_request' => 'Vitendo vya :reference',
];
