<?php

return [
    'head_title' => 'Rejista ya mtiririko wa kazi', 'eyebrow' => 'Kitovu cha pamoja cha udhibiti wa jukwaa', 'title' => 'Rejista ya mitiririko na kanuni', 'description' => 'Fafanua, thibitisha, weka alama-tambulishi na uchapishe kanuni za mzunguko wa maisha zinazotumika tena kwa kila moduli ya IDMIS.',
    'business_calendars' => 'Kalenda za kazi', 'business_calendars_description' => 'Saa za kazi zilizochapishwa na vighairi vilivyotangazwa huwezesha makataa ya SLA yanayoweza kuthibitishwa.', 'workflow_definitions' => 'Ufafanuzi wa mitiririko ya kazi', 'workflow_definitions_description' => 'Udhibiti wa mzunguko wa maisha wenye matoleo na majaribio unaoshirikiwa na moduli za IDMIS.',
    'edit' => 'Hariri', 'version' => 'toleo', 'version_prefix' => 't', 'workflow' => 'Mtiririko', 'configuration' => 'usanidi', 'edit_description' => 'Sasisha hali, ruhusa, kanuni, utenganishaji wa majukumu na kalenda ya SLA kabla ya uchapishaji.', 'edit_draft' => 'Hariri rasimu', 'published_sla_calendar' => 'Kalenda ya kazi ya SLA iliyochapishwa', 'save_draft' => 'Hifadhi rasimu', 'publish_version' => 'Chapisha toleo',
    'correct_configuration_json' => 'Sahihisha JSON ya usanidi kabla ya kuchagua kalenda.', 'configuration_valid_json' => 'Usanidi lazima uwe JSON halali.', 'create_workflow_definition' => 'Unda ufafanuzi wa mtiririko', 'create_workflow_description' => 'Unda ufafanuzi unaodhibitiwa kabla ya kutayarisha na kujaribu njia zake zenye matoleo.', 'new_workflow' => 'Mtiririko mpya',
    'code' => 'Msimbo', 'name' => 'Jina', 'module' => 'Moduli', 'description_label' => 'Maelezo', 'create_workflow' => 'Unda mtiririko', 'create_calendar_version' => 'Unda toleo la kalenda ya kazi', 'create_calendar_description' => 'Fafanua siku na saa za kazi pamoja na kipindi cha utekelezaji. Ongeza likizo zenye rejea kabla ya mhusika huru kuchapisha toleo.', 'new_calendar' => 'Kalenda mpya',
    'timezone' => 'Saa za eneo', 'working_days' => 'Siku za kazi', 'workday_starts' => 'Kazi huanza', 'workday_ends' => 'Kazi huisha', 'effective_from' => 'Inaanza kutumika', 'effective_to' => 'Inatumika hadi', 'create_draft' => 'Unda rasimu', 'separator' => '·', 'range_separator' => '–', 'view_calendar' => 'Tazama kalenda', 'add_exception' => 'Ongeza kighairi', 'publish_independently' => 'Chapisha kwa uhuru', 'exceptions' => 'vighairi',
    'monday' => 'Jumatatu', 'tuesday' => 'Jumanne', 'wednesday' => 'Jumatano', 'thursday' => 'Alhamisi', 'friday' => 'Ijumaa', 'saturday' => 'Jumamosi', 'sunday' => 'Jumapili',
    'effective' => 'Inatumika', 'to' => 'hadi', 'no_end_date' => 'bila tarehe ya mwisho iliyorekodiwa', 'add_calendar_exception' => 'Ongeza kighairi cha kalenda', 'exception_description' => 'Rekodi likizo iliyotangazwa au chanzo cha kufungwa kwa ofisi za serikali.', 'exception_date' => 'Tarehe ya kighairi', 'category' => 'Aina', 'authority_reference' => 'Rejea ya gazeti rasmi au mamlaka', 'recorded_by' => 'Imerekodiwa na', 'sha256' => 'SHA-256',
    'no_calendar_exceptions' => 'Hakuna vighairi vya kalenda', 'no_calendar_exceptions_description' => 'Toleo hili halina likizo au vighairi vya kufungwa vilivyorekodiwa.',
    'no_business_calendars' => 'Hakuna kalenda za kazi', 'no_business_calendars_description' => 'Unda kalenda ya kazi ya serikali yenye matoleo kabla ya kuunganisha SLA za saa za kazi.', 'search_workflows' => 'Tafuta mitiririko', 'search' => 'Tafuta', 'no_description' => 'Hakuna maelezo', 'active' => 'inayotumika', 'overdue' => 'iliyochelewa', 'create_next_draft' => 'Unda rasimu inayofuata', 'no_matching_workflows' => 'Hakuna mitiririko inayolingana', 'no_matching_workflows_description' => 'Futa utafutaji au unda ufafanuzi wa mtiririko unaodhibitiwa.', 'definitions' => 'ufafanuzi', 'page' => 'ukurasa', 'of' => 'kati ya', 'previous' => 'Iliyotangulia', 'next' => 'Inayofuata',
];
