<?php

namespace App\Enums;

enum ProgrammePermission: string
{
    case ViewDashboard = 'dashboard:view';
    case ViewCountyData = 'county-data:view';
    case UploadEvidence = 'evidence:upload';
    case SubmitAssessment = 'assessment:submit';
    case ReviewAssessment = 'assessment:review';
    case ScoreAssessment = 'assessment:score';
    case ApproveAssessment = 'assessment:approve';
    case ManageCountyUsers = 'county-users:manage';
    case ViewGrants = 'grants:view';
    case ManageGrants = 'grants:manage';
    case ViewNationalReports = 'national-reports:view';
    case ManageUserAccess = 'user-access:manage';
    case ConfigurePlatform = 'platform:configure';
    case ManageReferenceData = 'reference-data:manage';
    case ApproveReferenceData = 'reference-data:approve';
    case ManageWorkflows = 'workflows:manage';
    case ManageAssessmentConfiguration = 'assessment-configuration:manage';
    case ViewMonitoringEvaluation = 'monitoring-evaluation:view';
    case ManageIndicators = 'indicators:manage';
    case SubmitIndicatorData = 'indicator-data:submit';
    case VerifyIndicatorData = 'indicator-data:verify';
    case ManageRecords = 'records:manage';
    case ViewProjects = 'projects:view';
    case ManageProjects = 'projects:manage';
    case SubmitProjectUpdates = 'project-updates:submit';
    case VerifyProjectUpdates = 'project-updates:verify';
    case ViewPartnerCoordination = 'partner-coordination:view';
    case ManagePartners = 'partners:manage';
    case SubmitPartnerData = 'partner-data:submit';
    case ApprovePartnerAgreements = 'partner-agreements:approve';
    case ResolveCollaborationAlerts = 'partner-alerts:resolve';
    case ViewDswg = 'dswg:view';
    case ManageDswg = 'dswg:manage';
    case ParticipateDswg = 'dswg:participate';
    case ManageDswgActions = 'dswg-actions:manage';
    case VerifyDswgActions = 'dswg-actions:verify';
    case ViewIgrResolutions = 'igr-resolutions:view';
    case ManageIgrResolutions = 'igr-resolutions:manage';
    case UpdateIgrResolutions = 'igr-resolutions:update';
    case CloseIgrResolutions = 'igr-resolutions:close';
    case ViewCitizenCases = 'citizen-cases:view';
    case ManageCitizenCases = 'citizen-cases:manage';
    case RespondCitizenCases = 'citizen-cases:respond';
    case ResolveCitizenCases = 'citizen-cases:resolve';
    case ViewTravelClearance = 'travel-clearance:view';
    case SubmitTravelRequests = 'travel-clearance:submit';
    case ApproveTravelRequests = 'travel-clearance:approve';
    case FinanceClearTravel = 'travel-clearance:finance-clear';
    case ViewDepartmentalPerformance = 'departmental-performance:view';
    case ManagePerformanceCycles = 'departmental-performance:manage-cycles';
    case SubmitPerformancePlans = 'departmental-performance:submit';
    case ReviewPerformancePlans = 'departmental-performance:review';
    case ViewLearning = 'learning:view';
    case ManageLearning = 'learning:manage';
    case ReviewLearning = 'learning:review';
    case EnrollLearning = 'learning:enroll';
    case ViewKnowledge = 'knowledge:view';
    case ViewKnowledgeAnalytics = 'knowledge-analytics:view';
    case ContributeKnowledge = 'knowledge:contribute';
    case CurateKnowledge = 'knowledge:curate';
    case ManageKnowledge = 'knowledge:manage';
    case ViewIntegrations = 'integrations:view';
    case ManageIntegrations = 'integrations:manage';
    case ResolveIntegrationExceptions = 'integration-exceptions:resolve';
    case ViewOperations = 'operations:view';
    case ManageOperations = 'operations:manage';
    case ViewDataGovernance = 'data-governance:view';
    case ManageDataGovernance = 'data-governance:manage';
    case ViewSecurityGovernance = 'security-governance:view';
    case ManageSecurityGovernance = 'security-governance:manage';
    case CertifyAccess = 'access-certification:decide';
    case ViewChangeReadiness = 'change-readiness:view';
    case ManageChangeReadiness = 'change-readiness:manage';
    case RecordTrainingEvidence = 'training-evidence:record';
    case ApproveRolloutReadiness = 'rollout-readiness:approve';
    case ViewAnalytics = 'analytics:view';
    case ManageAnalytics = 'analytics:manage';
    case ApproveAnalytics = 'analytics:approve';
    case ApproveReportSchedules = 'report-schedules:approve';
    case ViewAuditTrail = 'audit-trail:view';
    case ViewUserActivity = 'user-activity:view';
    case ViewSupportDesk = 'support-desk:view';
    case SubmitSupportTickets = 'support-desk:submit';
    case ManageSupportTickets = 'support-desk:manage';
    case ResolveSupportTickets = 'support-desk:resolve';
    case ConfigureSupportDesk = 'support-desk:configure';
    case PublishSupportDeskPolicy = 'support-desk:publish-policy';

    public function label(): string
    {
        return match ($this) {
            self::ViewDashboard => 'View dashboard',
            self::ViewCountyData => 'View authorized county data',
            self::UploadEvidence => 'Upload assessment evidence',
            self::SubmitAssessment => 'Submit county assessment',
            self::ReviewAssessment => 'Review assessment evidence',
            self::ScoreAssessment => 'Record assessment scores',
            self::ApproveAssessment => 'Approve assessment results',
            self::ManageCountyUsers => 'Manage county users',
            self::ViewGrants => 'View grant information',
            self::ManageGrants => 'Manage grant information',
            self::ViewNationalReports => 'View national reports',
            self::ManageUserAccess => 'Manage platform access',
            self::ConfigurePlatform => 'Configure platform',
            self::ManageReferenceData => 'Manage reference data',
            self::ApproveReferenceData => 'Independently publish reference data',
            self::ManageWorkflows => 'Manage workflow definitions',
            self::ManageAssessmentConfiguration => 'Manage assessment configuration',
            self::ViewMonitoringEvaluation => 'View monitoring and evaluation',
            self::ManageIndicators => 'Manage indicator definitions',
            self::SubmitIndicatorData => 'Submit indicator observations',
            self::VerifyIndicatorData => 'Verify indicator observations',
            self::ManageRecords => 'Manage records retention and legal holds',
            self::ViewProjects => 'View authorized projects',
            self::ManageProjects => 'Manage projects',
            self::SubmitProjectUpdates => 'Submit project progress updates',
            self::VerifyProjectUpdates => 'Verify project progress updates',
            self::ViewPartnerCoordination => 'View partner coordination',
            self::ManagePartners => 'Manage partner profiles and agreements',
            self::SubmitPartnerData => 'Submit partner contributions',
            self::ApprovePartnerAgreements => 'Independently approve partner agreements',
            self::ResolveCollaborationAlerts => 'Resolve partner collaboration alerts',
            self::ViewDswg => 'View DSWG coordination',
            self::ManageDswg => 'Manage DSWG groups and meetings',
            self::ParticipateDswg => 'Participate in DSWG meetings',
            self::ManageDswgActions => 'Manage DSWG actions',
            self::VerifyDswgActions => 'Verify DSWG action completion',
            self::ViewIgrResolutions => 'View IGR resolutions',
            self::ManageIgrResolutions => 'Manage IGR forums and resolutions',
            self::UpdateIgrResolutions => 'Report IGR resolution implementation',
            self::CloseIgrResolutions => 'Independently close IGR resolutions',
            self::ViewCitizenCases => 'View citizen feedback and grievances',
            self::ManageCitizenCases => 'Triage and assign citizen cases',
            self::RespondCitizenCases => 'Respond to assigned citizen cases',
            self::ResolveCitizenCases => 'Independently approve citizen case resolutions',
            self::ViewTravelClearance => 'View authorized travel clearance',
            self::SubmitTravelRequests => 'Submit travel clearance requests',
            self::ApproveTravelRequests => 'Approve travel clearance requests',
            self::FinanceClearTravel => 'Confirm travel funding clearance',
            self::ViewDepartmentalPerformance => 'View departmental performance',
            self::ManagePerformanceCycles => 'Manage performance cycles',
            self::SubmitPerformancePlans => 'Submit performance plans and reviews',
            self::ReviewPerformancePlans => 'Review and finalize performance plans',
            self::ViewLearning => 'View learning catalogue and progress',
            self::ManageLearning => 'Manage learning courses and classrooms',
            self::ReviewLearning => 'Independently review learning courses',
            self::EnrollLearning => 'Enroll in and complete learning courses',
            self::ViewKnowledge => 'View knowledge repository and communities',
            self::ViewKnowledgeAnalytics => 'View authorized knowledge community analytics',
            self::ContributeKnowledge => 'Contribute knowledge and innovations',
            self::CurateKnowledge => 'Independently curate knowledge and innovations',
            self::ManageKnowledge => 'Manage knowledge repository and communities',
            self::ViewIntegrations => 'View integration operations',
            self::ManageIntegrations => 'Manage integration systems and contracts',
            self::ResolveIntegrationExceptions => 'Resolve integration reconciliation exceptions',
            self::ViewOperations => 'View operational readiness evidence',
            self::ManageOperations => 'Manage releases, recovery evidence and operational controls',
            self::ViewDataGovernance => 'View data governance and privacy records',
            self::ManageDataGovernance => 'Manage data governance and privacy workflows',
            self::ViewSecurityGovernance => 'View security authorization evidence',
            self::ManageSecurityGovernance => 'Manage threats and access review campaigns',
            self::CertifyAccess => 'Independently certify or revoke programme access',
            self::ViewChangeReadiness => 'View rollout and capacity-building readiness',
            self::ManageChangeReadiness => 'Manage rollout waves and training cohorts',
            self::RecordTrainingEvidence => 'Record attendance and competency evidence',
            self::ApproveRolloutReadiness => 'Independently approve rollout readiness',
            self::ViewAnalytics => 'View authorized analytics and report artifacts',
            self::ManageAnalytics => 'Configure dashboards and report schedules',
            self::ApproveAnalytics => 'Independently publish analytics dashboards',
            self::ApproveReportSchedules => 'Independently approve scheduled reports',
            self::ViewAuditTrail => 'View audit trail',
            self::ViewUserActivity => 'View user sessions and live activity',
            self::ViewSupportDesk => 'View authorized service-desk tickets',
            self::SubmitSupportTickets => 'Submit service-desk tickets',
            self::ManageSupportTickets => 'Triage and assign service-desk tickets',
            self::ResolveSupportTickets => 'Investigate and resolve assigned support tickets',
            self::ConfigureSupportDesk => 'Configure service-desk policies and rosters',
            self::PublishSupportDeskPolicy => 'Independently publish service-desk policies',
        };
    }
}
